centreon/centreon-documentation

i18n/fr/docusaurus-plugin-content-docs/version-20.10/graph-views/update.md
i18n/fr/docusaurus-plugin-content-docs/version-20.10/graph-views/upgrade.md
i18n/fr/docusaurus-plugin-content-docs/version-21.04/graph-views/update.md
i18n/fr/docusaurus-plugin-content-docs/version-21.04/graph-views/upgrade.md
i18n/fr/docusaurus-plugin-content-docs/version-21.10/graph-views/update.md
i18n/fr/docusaurus-plugin-content-docs/version-21.10/graph-views/upgrade.md
versioned_docs/version-20.10/graph-views/update.md
versioned_docs/version-20.10/graph-views/upgrade.md
versioned_docs/version-21.04/graph-views/update.md
versioned_docs/version-21.04/graph-views/upgrade.md
versioned_docs/version-21.10/graph-views/update.md
versioned_docs/version-21.10/graph-views/upgrade.md

Add info about customized centreon-map.conf file

Add info about customized centreon-map.conf file

---

Jenkinsfile

Fix pb install curl

---

i18n/fr/docusaurus-plugin-content-docs/version-21.10/releases/centreon-core.md
versioned_docs/version-21.10/releases/centreon-core.md

enh(release): Add Centreon Web 21.10.6 RN

---

i18n/fr/docusaurus-plugin-content-docs/version-21.04/releases/centreon-core.md
versioned_docs/version-21.04/releases/centreon-core.md

enh(release): Add Centreon Web 21.04.14 RN

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-monitoring-ntopng-restapi.md
pp/integrations/plugin-packs/procedures/applications-monitoring-ntopng-restapi.md
pp/sidebarsPp.js

add(epp): ntopng rest api

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04.json
i18n/fr/docusaurus-plugin-content-docs/version-22.04/monitoring/monitoring-servers/add-a-poller-to-configuration.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/monitoring/monitoring-servers/add-a-remote-server-to-configuration.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/monitoring/monitoring-servers/move-poller.md
versioned_docs/version-22.04/monitoring/monitoring-servers/add-a-poller-to-configuration.md
versioned_docs/version-22.04/monitoring/monitoring-servers/add-a-remote-server-to-configuration.md
versioned_docs/version-22.04/monitoring/monitoring-servers/move-poller.md
versioned_sidebars/version-22.04-sidebars.json

Add info about attaching a poller to a remote (next)

Add info about attaching a poller to a remote (next)

---

i18n/fr/docusaurus-plugin-content-docs/version-21.10/monitoring/monitoring-servers/add-a-poller-to-configuration.md
versioned_docs/version-21.10/monitoring/monitoring-servers/add-a-poller-to-configuration.md
versioned_docs/version-21.10/monitoring/monitoring-servers/move-poller.md

Add info about attaching a poller to a remote (staging)

Add info about attaching a poller to a remote (staging)

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/administration/secure-platform.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/upgrade/upgrade-from-18-10.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/upgrade/upgrade-from-19-04.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/upgrade/upgrade-from-19-10.md
versioned_docs/version-22.04/administration/secure-platform.md
versioned_docs/version-22.04/upgrade/upgrade-from-18-10.md
versioned_docs/version-22.04/upgrade/upgrade-from-19-04.md
versioned_docs/version-22.04/upgrade/upgrade-from-19-10.md
versioned_docs/version-22.04/upgrade/upgrade-from-3-4.md

fix(apache): manage custom uri

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-backupexec-nscp-restapi.md
pp/integrations/plugin-packs/procedures/applications-backupexec-nscp-restapi.md
pp/sidebarsPp.js

add(epp): backup exec nscp api

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-monitoring-kadiska-restapi.md
pp/integrations/plugin-packs/procedures/applications-monitoring-kadiska-restapi.md
pp/sidebarsPp.js

Adding procedure for Kadiska Plugin Pack.

add(epp): add procedure for Kadiska Plugin Pack

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-sftp.md
pp/integrations/plugin-packs/procedures/applications-protocol-sftp.md
pp/sidebarsPp.js

add(epp): protocol sftp

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-servers-hp-snmp.md
pp/integrations/plugin-packs/procedures/hardware-servers-hp-snmp.md

Update of existing HP proliant Plugin Pack monitoring procedure and format body according to new recommendations.

enh(epp): hardware hp snmp proliant - updating prerequisites and format body

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/api/clapi.md
versioned_docs/version-22.04/api/clapi.md

Add single quotes around password (next)

Add single quotes around password (next)

---

i18n/fr/docusaurus-plugin-content-docs/version-21.04/api/clapi.md
i18n/fr/docusaurus-plugin-content-docs/version-21.10/api/clapi.md
versioned_docs/version-21.04/api/clapi.md
versioned_docs/version-21.10/api/clapi.md

Add quotes around password (staging)

Add quotes around password (staging)

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-cifs.md
pp/integrations/plugin-packs/procedures/applications-protocol-cifs.md
pp/sidebarsPp.js

add(epp): protocol cifs

---

docusaurus.config.js

enh(config): Add 'edit this page' link to unversioned sections FR/EN

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/graph-views/install.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/graph-views/upgrade.md
versioned_docs/version-22.04/graph-views/install.md
versioned_docs/version-22.04/graph-views/upgrade.md

Add info about bbdo v3 and MAP

Add info about bbdo v3 and MAP

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/developer/developer-broker-stream-connector.md
versioned_docs/version-22.04/developer/developer-broker-stream-connector.md

Description of new stream connector functions.

enh(developer/sc): broker functions updated

---

i18n/fr/docusaurus-plugin-content-docs/version-21.10/alerts-notifications/resources-status.md

Fix broken GIF on Resources status page / Search bar

Fix broken GIF on Resources status page

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/installation/introduction.md
versioned_docs/version-22.04/installation/introduction.md

Add update step before running unattended script

Add update step before running unattended script

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/resources/known-issues.md
versioned_docs/version-22.04/resources/known-issues.md

Add known issue about MBI and custom database names

Add known issue about MBI and custom database names (next)

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/alerts-notifications/notif-configuration.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/alerts-notifications/resources-status.md
versioned_docs/version-22.04/alerts-notifications/notif-configuration.md
versioned_docs/version-22.04/alerts-notifications/resources-status.md

Update text on Notification EN/FR and Fix Gif on Resources status page FR

Update on Notification and Fix Gif on Resources status page

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-cifs.md
pp/integrations/plugin-packs/procedures/applications-protocol-cifs.md

enh(epp): protocol cifs - add files-size service

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-switchs-brocade-snmp.md
pp/integrations/plugin-packs/procedures/network-switchs-brocade-snmp.md

- update template
- include a link to Broadcom / Brocade docs

update(doc) use new template

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/graph-views/install.md
versioned_docs/version-22.04/graph-views/install.md

Add info about restarting centreon-map service

Add info about restarting centreon-map service

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/developer/developer-broker-bbdo.md
versioned_docs/version-22.04/developer/developer-broker-bbdo.md

Add info about switching versions of BBDO

Add info about switching versions of BBDO

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/upgrade/upgrade-from-20-04.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/upgrade/upgrade-from-20-10.md
versioned_docs/version-22.04/upgrade/upgrade-from-20-04.md
versioned_docs/version-22.04/upgrade/upgrade-from-20-10.md

Move section on upgrading MariaDB

Move section on upgrading MariaDB

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/mobile/introduction.md
versioned_docs/version-22.04/mobile/introduction.md

Remove mentions of the app as it is no longer supported

Remove mentions of the app

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/developer/developer-broker-mapping.md
versioned_docs/version-22.04/developer/developer-broker-mapping.md

Protobuf files have been update to keep a continuity in fields names. The doc describing these files had to be updated.

fix(bbdo/protobuf): messages have changed and the doc needed an update

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/metrology/chart_virtual_metrics.md
versioned_docs/version-22.04/metrology/char_virtual_metrics.md

Fix URL in Virtual metrics EN/FR - Next version

Fix URL in Virtual metrics topic EN/FR - Next version

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-databases-elasticsearch.md
i18n/fr/docusaurus-plugin-content-docs/version-20.04/metrology/chart_virtual_metrics.md
i18n/fr/docusaurus-plugin-content-docs/version-20.10/metrology/chart_virtual_metrics.md
i18n/fr/docusaurus-plugin-content-docs/version-21.04/metrology/chart_virtual_metrics.md
i18n/fr/docusaurus-plugin-content-docs/version-21.10/metrology/chart_virtual_metrics.md
pp/integrations/plugin-packs/procedures/applications-databases-elasticsearch.md
versioned_docs/version-20.04/metrology/char_virtual_metrics.md
versioned_docs/version-20.10/metrology/char_virtual_metrics.md
versioned_docs/version-21.04/metrology/char_virtual_metrics.md
versioned_docs/version-21.10/metrology/char_virtual_metrics.md

Fix URL in Elasticsearch (PP) and Virtual metrics topics
Related to: https://github.com/centreon/centreon-documentation/pull/1405

Fix URLs in Elasticsearch (PP) and Virtual metrics topics

---

i18n/fr/docusaurus-plugin-content-docs/version-20.04.json
i18n/fr/docusaurus-plugin-content-docs/version-20.04/mobile/introduction.md
i18n/fr/docusaurus-plugin-content-docs/version-20.10.json
i18n/fr/docusaurus-plugin-content-docs/version-20.10/mobile/introduction.md
i18n/fr/docusaurus-plugin-content-docs/version-21.04.json
i18n/fr/docusaurus-plugin-content-docs/version-21.04/mobile/introduction.md
i18n/fr/docusaurus-plugin-content-docs/version-21.10.json
i18n/fr/docusaurus-plugin-content-docs/version-21.10/mobile/introduction.md
versioned_docs/version-20.04/mobile/introduction.md
versioned_docs/version-20.10/mobile/introduction.md
versioned_docs/version-21.04/mobile/introduction.md
versioned_docs/version-21.10/mobile/introduction.md
versioned_sidebars/version-20.04-sidebars.json
versioned_sidebars/version-20.10-sidebars.json
versioned_sidebars/version-21.04-sidebars.json
versioned_sidebars/version-21.10-sidebars.json

Remove mentions of the app (staging), as it is no longer maintained

Remove mentions of the app (staging)

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/upgrade/upgrade-from-18-10.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/upgrade/upgrade-from-19-04.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/upgrade/upgrade-from-19-10.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/upgrade/upgrade-from-20-04.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/upgrade/upgrade-from-20-10.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/upgrade/upgrade-from-21-04.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/upgrade/upgrade-from-21-10.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/upgrade/upgrade-from-3-4.md
versioned_docs/version-22.04/upgrade/upgrade-from-18-10.md
versioned_docs/version-22.04/upgrade/upgrade-from-19-04.md
versioned_docs/version-22.04/upgrade/upgrade-from-19-10.md
versioned_docs/version-22.04/upgrade/upgrade-from-20-04.md
versioned_docs/version-22.04/upgrade/upgrade-from-20-10.md
versioned_docs/version-22.04/upgrade/upgrade-from-21-04.md
versioned_docs/version-22.04/upgrade/upgrade-from-21-10.md
versioned_docs/version-22.04/upgrade/upgrade-from-3-4.md

Warning about upgrading all servers

Warning about upgrading all servers

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/releases/release-notes.md
pp/integrations/plugin-packs/releases/release-notes.md
pp/sidebarsPp.js

Rework release note and add may content
Replace / Close https://github.com/centreon/centreon-documentation/pull/1461

(connectors) may release note

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/installation/installation-of-a-central-server/using-virtual-machines.md
versioned_docs/version-22.04/installation/installation-of-a-central-server/using-virtual-machines.md

Update password for OVA

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/installation/installation-of-a-central-server/using-virtual-machines.md
versioned_docs/version-22.04/installation/installation-of-a-central-server/using-virtual-machines.md

Add info about OVAs

---

.github/PULL_REQUEST_TEMPLATE.md

Update PR template (next becomes 22.10)

Update PR template (next becomes 22.10)

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/installation/installation-of-a-central-server/using-packages.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/installation/installation-of-a-remote-server/using-packages.md
versioned_docs/version-22.04/installation/installation-of-a-central-server/using-packages.md
versioned_docs/version-22.04/installation/installation-of-a-remote-server/using-packages.md

Langpack for el8

---

i18n/fr/docusaurus-plugin-content-docs/version-21.04/api/clapi.md
i18n/fr/docusaurus-plugin-content-docs/version-21.10/api/clapi.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/api/clapi.md
versioned_docs/version-21.04/api/clapi.md
versioned_docs/version-21.10/api/clapi.md
versioned_docs/version-22.04/api/clapi.md

Add clapi to topic title so that it is easier to find through the search

Add clapi to topic title

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-commercial-extensions.md
versioned_docs/version-22.04/releases/centreon-commercial-extensions.md

enh(release): Add Centreon BAM 22.04.1 RN

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/monitoring/discovery/hosts-discovery.md

Fix broken image

---

i18n/fr/docusaurus-plugin-content-docs/version-21.04/developer/developer-translate-centreon.md
i18n/fr/docusaurus-plugin-content-docs/version-21.10/developer/developer-translate-centreon.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/developer/developer-translate-centreon.md
versioned_docs/version-21.04/developer/developer-translate-centreon.md
versioned_docs/version-21.10/developer/developer-translate-centreon.md
versioned_docs/version-22.04/developer/developer-translate-centreon.md

Fix dead link

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/upgrade/upgrade-from-18-10.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/upgrade/upgrade-from-19-04.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/upgrade/upgrade-from-19-10.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/upgrade/upgrade-from-20-04.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/upgrade/upgrade-from-20-10.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/upgrade/upgrade-from-21-04.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/upgrade/upgrade-from-21-10.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/upgrade/upgrade-from-3-4.md
versioned_docs/version-22.04/upgrade/upgrade-from-18-10.md
versioned_docs/version-22.04/upgrade/upgrade-from-19-04.md
versioned_docs/version-22.04/upgrade/upgrade-from-19-10.md
versioned_docs/version-22.04/upgrade/upgrade-from-20-04.md
versioned_docs/version-22.04/upgrade/upgrade-from-20-10.md
versioned_docs/version-22.04/upgrade/upgrade-from-21-04.md
versioned_docs/version-22.04/upgrade/upgrade-from-21-10.md
versioned_docs/version-22.04/upgrade/upgrade-from-3-4.md

Add warning about OpenID/Web SSO configuration steps

Add warning about OpenID/Web SSO configuration steps

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-hp-storeonce-restapi.md
i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-hp-storeonce3-restapi.md
i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-hp-storeonce4-restapi.md
pp/integrations/plugin-packs/procedures/hardware-storage-hp-storeonce-restapi.md
pp/integrations/plugin-packs/procedures/hardware-storage-hp-storeonce3-restapi.md
pp/integrations/plugin-packs/procedures/hardware-storage-hp-storeonce4-restapi.md
pp/sidebarsPp.js

 add(epp): hp storeonce refactoring

---

i18n/fr/docusaurus-plugin-content-docs/version-21.04/integrations/data-analytics/sc-logstash-events.md
i18n/fr/docusaurus-plugin-content-docs/version-21.10/integrations/data-analytics/sc-logstash-events.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/integrations/data-analytics/sc-logstash-events.md
versioned_docs/version-21.04/integrations/data-analytics/sc-logstash-events.md
versioned_docs/version-21.10/integrations/data-analytics/sc-logstash-events.md
versioned_docs/version-22.04/integrations/data-analytics/sc-logstash-events.md
versioned_sidebars/version-21.04-sidebars.json
versioned_sidebars/version-21.10-sidebars.json
versioned_sidebars/version-22.04-sidebars.json

add doc for logstash stream connector

(doc/sc) add logstash sc doc

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-dell-n4000.md
i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-dell-nseries-snmp.md
pp/integrations/plugin-packs/procedures/network-dell-n4000.md
pp/integrations/plugin-packs/procedures/network-dell-nseries-snmp.md
pp/sidebarsPp.js

add(epp): dell n4000 refactoring

---

i18n/fr/docusaurus-plugin-content-docs/version-21.04/graph-views/troubleshooter.md
i18n/fr/docusaurus-plugin-content-docs/version-21.10/graph-views/troubleshooter.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/graph-views/troubleshooter.md
versioned_docs/version-21.04/graph-views/troubleshooter.md
versioned_docs/version-21.10/graph-views/troubleshooter.md
versioned_docs/version-22.04/graph-views/troubleshooter.md

Add info to MAP troubleshooting topic

Add info to MAP troubleshooting topic

---

i18n/fr/docusaurus-plugin-content-docs/version-20.10/graph-views/install.md
i18n/fr/docusaurus-plugin-content-docs/version-21.04/graph-views/install.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/graph-views/install.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/graph-views/upgrade.md
versioned_docs/version-20.10/graph-views/install.md
versioned_docs/version-21.04/graph-views/install.md
versioned_docs/version-22.04/graph-views/install.md
versioned_docs/version-22.04/graph-views/upgrade.md

Fix path to config files

---

i18n/fr/docusaurus-plugin-content-docs/version-22.10/graph-views/troubleshooter.md
versioned_docs/version-22.10/graph-views/troubleshooter.md

MON-11592 Add info to MAP troubleshooting topic (next)

MON-11592 Add info to MAP troubleshooting topic (next)

---

i18n/fr/docusaurus-plugin-content-docs/version-22.10/graph-views/upgrade.md
versioned_docs/version-22.10/graph-views/upgrade.md

MON-13831 Fix path to config files (next)

MON-13831 Fix path to config files (next)

---

versioned_docs/version-22.10/service-mapping/ba-management.md

Fix typo (next)

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-iis-wsman.md
pp/integrations/plugin-packs/procedures/applications-iis-wsman.md
pp/sidebarsPp.js

add(epp): iis wsman

---

pp/sidebarsPp.js

fix(epp): remove duplicate Amazon SES section in sidebars

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-monitoring-speedtest.md
pp/integrations/plugin-packs/procedures/applications-monitoring-speedtest.md
pp/sidebarsPp.js

add(epp): speedtest

---

i18n/fr/docusaurus-plugin-content-docs/version-21.10/releases/centreon-core.md
versioned_docs/version-21.10/releases/centreon-core.md

enh(release): add Centreon Web 21.10.7 RN

---

i18n/fr/docusaurus-plugin-content-docs/version-21.04/releases/centreon-core.md
versioned_docs/version-21.04/releases/centreon-core.md

doc(release): add release note for centreon-connector-ssh-21.04.4

---

i18n/fr/docusaurus-plugin-content-docs/version-21.04/releases/centreon-core.md
versioned_docs/version-21.04/releases/centreon-core.md

doc(release): add release note for centreon-connector-perl-21.04.4

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/administration/secure-platform.md
versioned_docs/version-22.04/administration/secure-platform.md

Improve section on Enabling HTTPS.

Improve section on Enabling HTTPS

---

i18n/fr/docusaurus-plugin-content-docs/version-22.10/monitoring/web-import-export.md

Translate Import/Export topic into FR for Next version

Translate Import/Export topic into FR for Next version

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/monitoring/web-import-export.md

Translate Import/Export topic into FR.
NOTE that the UI translation is not planned in FR (no screenshots in FR)

Translate Import/Export topic into FR

---

pp/integrations/plugin-packs/procedures/applications-monitoring-speedtest.md

fix(epp): speedtest EN fix macro typo

---

i18n/fr/docusaurus-plugin-content-docs/version-21.10/releases/centreon-core.md
versioned_docs/version-21.10/releases/centreon-core.md

doc(release): add release note for centreon-collect-21.10.2

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-monitoring-dynatrace-restapi.md
pp/integrations/plugin-packs/procedures/applications-monitoring-dynatrace-restapi.md

Enhancement of the Dynatrace Plugin Pack documentation following the plugin enhancements.

enh(doc) dynatace restapi v2 pack

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/upgrade/upgrade-from-18-10.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/upgrade/upgrade-from-19-04.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/upgrade/upgrade-from-19-10.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/upgrade/upgrade-from-20-04.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/upgrade/upgrade-from-20-10.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/upgrade/upgrade-from-21-04.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/upgrade/upgrade-from-21-10.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/upgrade/upgrade-from-3-4.md
versioned_docs/version-22.04/upgrade/upgrade-from-18-10.md
versioned_docs/version-22.04/upgrade/upgrade-from-19-04.md
versioned_docs/version-22.04/upgrade/upgrade-from-19-10.md
versioned_docs/version-22.04/upgrade/upgrade-from-20-04.md
versioned_docs/version-22.04/upgrade/upgrade-from-20-10.md
versioned_docs/version-22.04/upgrade/upgrade-from-21-04.md
versioned_docs/version-22.04/upgrade/upgrade-from-21-10.md
versioned_docs/version-22.04/upgrade/upgrade-from-3-4.md

Apply PR #1613 to all upgrade files

Apply PR #1613 to all upgrade files

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/api/rest-api-v2.md
versioned_docs/version-21.04/api/rest-api-v2.md
versioned_docs/version-22.04/api/rest-api-v2.md

Fix wrong links

---

i18n/fr/docusaurus-plugin-content-docs/version-20.04/monitoring/pluginpacks.md
i18n/fr/docusaurus-plugin-content-docs/version-20.10/monitoring/pluginpacks.md
i18n/fr/docusaurus-plugin-content-docs/version-21.04/monitoring/pluginpacks.md
i18n/fr/docusaurus-plugin-content-docs/version-21.10/monitoring/pluginpacks.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/monitoring/pluginpacks.md
versioned_docs/version-20.04/monitoring/pluginpacks.md
versioned_docs/version-20.10/monitoring/pluginpacks.md
versioned_docs/version-21.04/monitoring/pluginpacks.md
versioned_docs/version-21.10/monitoring/pluginpacks.md
versioned_docs/version-22.04/monitoring/pluginpacks.md

doc(fix) update command

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-commercial-extensions.md
versioned_docs/version-22.04/releases/centreon-commercial-extensions.md

enh(doc): added MBI 22.04.1 release notes

---

i18n/fr/docusaurus-plugin-content-docs/version-22.10/installation/installation-of-a-remote-server/using-packages.md
versioned_docs/version-22.10/installation/installation-of-a-remote-server/using-packages.md

Add mysql command (next)

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/installation/installation-of-a-remote-server/using-packages.md
versioned_docs/version-22.04/installation/installation-of-a-remote-server/using-packages.md

Add mysql command

---

i18n/fr/docusaurus-plugin-content-docs/version-22.10/getting-started/monitor-linux-server-with-snmp.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/graph-views/install.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/installation/installation-of-a-central-server/using-packages.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/installation/installation-of-a-poller/using-packages.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/installation/installation-of-a-remote-server/using-packages.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/installation/prerequisites.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/reporting/installation.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/service-mapping/install.md
versioned_docs/version-22.10/getting-started/monitor-linux-server-with-snmp.md
versioned_docs/version-22.10/graph-views/install.md
versioned_docs/version-22.10/installation/installation-of-a-central-server/using-packages.md
versioned_docs/version-22.10/installation/installation-of-a-poller/using-packages.md
versioned_docs/version-22.10/installation/installation-of-a-remote-server/using-packages.md
versioned_docs/version-22.10/installation/prerequisites.md
versioned_docs/version-22.10/reporting/installation.md
versioned_docs/version-22.10/service-mapping/install.md

Debian 11 installation (next)

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-commercial-extensions.md
versioned_docs/version-22.04/releases/centreon-commercial-extensions.md

Prepare release note for map 22.04.1 release

enh(doc): add release note for MAP 22.04.1

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-databases-postgresql.md
pp/integrations/plugin-packs/procedures/applications-databases-postgresql.md

enh(epp): postgresql proc v2

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-classic-storage-storageaccount.md
pp/integrations/plugin-packs/procedures/cloud-azure-classic-storage-storageaccount.md
pp/sidebarsPp.js

Adding documentation for Azure Classic Storage plugin pack.

add(pp) - Adding PP documentation for Azure Classic Storage

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-classicstorage-storageaccount.md
pp/integrations/plugin-packs/procedures/cloud-azure-classicstorage-storageaccount.md
pp/sidebarsPp.js

Align procedure name with Pack's one.

Fix name issue with Azure Storages MP

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-classicstorage-storageaccount.md
i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/releases/release-notes.md
pp/integrations/plugin-packs/procedures/cloud-azure-classicstorage-storageaccount.md
pp/integrations/plugin-packs/releases/release-notes.md
pp/sidebarsPp.js

Packs release note for this month

Add Monitoring Packs release note 

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-fujitsu-eternus-dx-ssh.md
pp/integrations/plugin-packs/procedures/hardware-storage-fujitsu-eternus-dx-ssh.md

need to indicate rsa as type as it might not be default

update(doc) hardware.storage.fujitsu.eternus.dx.ssh

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-snmp.md
i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-ats-apc.md
i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-pdu-clever-snmp.md
i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-pdu-emerson-snmp.md
i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-pdu-raritan-snmp.md
i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-sensors-akcp-snmp.md
i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-sensors-hwgste-snmp.md
i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-sensors-jacarta-snmp.md
i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-sensors-netbotz-snmp.md
i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-sensors-sensorip-snmp.md
pp/integrations/plugin-packs/procedures/applications-protocol-snmp.md
pp/integrations/plugin-packs/procedures/hardware-ats-apc.md
pp/integrations/plugin-packs/procedures/hardware-pdu-clever-snmp.md
pp/integrations/plugin-packs/procedures/hardware-pdu-emerson-snmp.md
pp/integrations/plugin-packs/procedures/hardware-pdu-raritan-snmp.md
pp/integrations/plugin-packs/procedures/hardware-sensors-akcp-snmp.md
pp/integrations/plugin-packs/procedures/hardware-sensors-hwgste-snmp.md
pp/integrations/plugin-packs/procedures/hardware-sensors-jacarta-snmp.md
pp/integrations/plugin-packs/procedures/hardware-sensors-netbotz-snmp.md
pp/integrations/plugin-packs/procedures/hardware-sensors-sensorip-snmp.md

use doc generator to address pages that had "PDU Raritan host" and update template

fix(doc) update template

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-cisco-wlc-snmp.md
pp/integrations/plugin-packs/procedures/network-cisco-wlc-snmp.md

- use template
- update content
- select "Ap-Status-Global"

update(doc) Network CISCO WLC SNMP

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-switchs-alcatel-omniswitch-snmp.md
pp/integrations/plugin-packs/procedures/network-switchs-alcatel-omniswitch-snmp.md

- use template
- update content
- select Traffic-Global

update(doc) Alcatel Omniswitch SNMP

---

i18n/fr/docusaurus-plugin-content-docs/version-21.10/releases/centreon-os-extensions.md
versioned_docs/version-21.10/releases/centreon-os-extensions.md

enh(release): Add Centreon Open Tickets 21.10.1 RN

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-snmp.md
i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-compute-vmscalesets.md
i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-ats-apc.md
i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-pdu-raritan-snmp.md
i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-sensors-akcp-snmp.md
i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-sensors-hwgste-snmp.md
i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-sensors-jacarta-snmp.md
i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-sensors-netbotz-snmp.md
i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-sensors-sensorip-snmp.md
i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-cisco-wlc-snmp.md
i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-switchs-alcatel-omniswitch-snmp.md
i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-switchs-brocade-snmp.md
pp/integrations/plugin-packs/procedures/applications-protocol-snmp.md
pp/integrations/plugin-packs/procedures/cloud-azure-compute-vmscalesets.md
pp/integrations/plugin-packs/procedures/hardware-ats-apc.md
pp/integrations/plugin-packs/procedures/hardware-pdu-raritan-snmp.md
pp/integrations/plugin-packs/procedures/hardware-sensors-akcp-snmp.md
pp/integrations/plugin-packs/procedures/hardware-sensors-hwgste-snmp.md
pp/integrations/plugin-packs/procedures/hardware-sensors-jacarta-snmp.md
pp/integrations/plugin-packs/procedures/hardware-sensors-netbotz-snmp.md
pp/integrations/plugin-packs/procedures/hardware-sensors-sensorip-snmp.md
pp/integrations/plugin-packs/procedures/network-cisco-wlc-snmp.md
pp/integrations/plugin-packs/procedures/network-switchs-alcatel-omniswitch-snmp.md
pp/integrations/plugin-packs/procedures/network-switchs-brocade-snmp.md

Fix uncatched typos introduced in recent PR

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-http.md
pp/integrations/plugin-packs/procedures/applications-protocol-http.md

- use template
- update content

update(doc) protocol http

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
versioned_docs/version-22.04/releases/centreon-core.md

enh(release): Add Centreon Web 22.04.1 RN

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/update/update-centreon-platform.md
versioned_docs/version-22.04/update/update-centreon-platform.md

Add clear cache Apache command on Update topic.

Add clear cache Apache command

---

i18n/fr/docusaurus-plugin-content-docs/version-22.10/installation/installation-of-a-central-server/using-packages.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/installation/installation-of-a-remote-server/using-packages.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/upgrade/upgrade-from-18-10.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/upgrade/upgrade-from-19-04.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/upgrade/upgrade-from-19-10.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/upgrade/upgrade-from-20-04.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/upgrade/upgrade-from-20-10.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/upgrade/upgrade-from-21-04.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/upgrade/upgrade-from-21-10.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/upgrade/upgrade-from-3-4.md
versioned_docs/version-22.10/installation/installation-of-a-central-server/using-packages.md
versioned_docs/version-22.10/installation/installation-of-a-remote-server/using-packages.md
versioned_docs/version-22.10/upgrade/upgrade-from-18-10.md
versioned_docs/version-22.10/upgrade/upgrade-from-19-04.md
versioned_docs/version-22.10/upgrade/upgrade-from-19-10.md
versioned_docs/version-22.10/upgrade/upgrade-from-20-04.md
versioned_docs/version-22.10/upgrade/upgrade-from-20-10.md
versioned_docs/version-22.10/upgrade/upgrade-from-21-04.md
versioned_docs/version-22.10/upgrade/upgrade-from-21-10.md
versioned_docs/version-22.10/upgrade/upgrade-from-3-4.md

Add address of mariadb repo (next)

Add address of mariadb repo (next)

---

i18n/fr/docusaurus-plugin-content-docs/version-21.04/reporting/available-reports.md
i18n/fr/docusaurus-plugin-content-docs/version-21.04/reporting/generate-reports.md
i18n/fr/docusaurus-plugin-content-docs/version-21.04/reporting/introduction.md
i18n/fr/docusaurus-plugin-content-docs/version-21.10/reporting/available-reports.md
i18n/fr/docusaurus-plugin-content-docs/version-21.10/reporting/generate-reports.md
i18n/fr/docusaurus-plugin-content-docs/version-21.10/reporting/introduction.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/reporting/available-reports.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/reporting/generate-reports.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/reporting/introduction.md
versioned_docs/version-21.04/reporting/available-reports.md
versioned_docs/version-21.04/reporting/generate-reports.md
versioned_docs/version-21.04/reporting/introduction.md
versioned_docs/version-21.10/reporting/available-reports.md
versioned_docs/version-21.10/reporting/generate-reports.md
versioned_docs/version-21.10/reporting/introduction.md
versioned_docs/version-22.04/reporting/available-reports.md
versioned_docs/version-22.04/reporting/generate-reports.md
versioned_docs/version-22.04/reporting/introduction.md

Update attachment for MBI reports:
- FR for most recent data
- EN for date in footer

Update attachment for MBI reports

---

i18n/fr/docusaurus-plugin-content-docs/version-22.10/reporting/available-reports.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/reporting/generate-reports.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/reporting/introduction.md
versioned_docs/version-22.10/reporting/available-reports.md
versioned_docs/version-22.10/reporting/generate-reports.md
versioned_docs/version-22.10/reporting/introduction.md

Update attachment for MBI reports - next

Update attachment for MBI reports - next

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/update/update-centreon-platform.md
versioned_docs/version-22.04/update/update-centreon-platform.md

Move command to the right section.

Move command to the right section

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-huawei-snmp.md
pp/integrations/plugin-packs/procedures/network-huawei-snmp.md

Migrate Huawei documentation to the newest layout

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-microsoft-office365-azuread.md
i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-microsoft-office365-management.md
pp/integrations/plugin-packs/procedures/cloud-microsoft-office365-azuread.md
pp/integrations/plugin-packs/procedures/cloud-microsoft-office365-management.md
pp/sidebarsPp.js

Add Office365 Azure AD monproc

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-microsoft-office365-teams.md
pp/integrations/plugin-packs/procedures/cloud-microsoft-office365-teams.md

Update links to Microsoft documentation

Fix 404 links in MS Teams monitoring procedure

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04.json
i18n/fr/docusaurus-plugin-content-docs/version-22.04/developer/developer-gorgone-client-server-communication.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/developer/developer-gorgone-migrate-from-centcore.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/developer/developer-gorgone-pull-mode.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/developer/developer-gorgone-rebound-mode.md
versioned_docs/version-22.04/developer/developer-gorgone-client-server-communication.md
versioned_docs/version-22.04/developer/developer-gorgone-migrate-from-centcore.md
versioned_docs/version-22.04/developer/developer-gorgone-pull-mode.md
versioned_docs/version-22.04/developer/developer-gorgone-rebound-mode.md
versioned_sidebars/version-22.04-sidebars.json

Create and develop Gorgone concept.

Create and develop Gorgone concept

---

i18n/fr/docusaurus-plugin-content-docs/version-22.10/upgrade/centreon-ha/upgrade-from-21-04.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/upgrade/centreon-ha/upgrade-from-21-10.md
versioned_docs/version-22.10/upgrade/centreon-ha/upgrade-from-21-04.md
versioned_docs/version-22.10/upgrade/centreon-ha/upgrade-from-21-10.md

Fix too more constraints on HA 2 nodes

NEXT PS-62 - Fix constraints on HA 2 nodes

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-servers-dell-vxm-restapi.md
pp/integrations/plugin-packs/procedures/hardware-servers-dell-vxm-restapi.md
pp/sidebarsPp.js

add(epp): dell vxrail manager rest api

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/upgrade/centreon-ha/upgrade-from-21-04.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/upgrade/centreon-ha/upgrade-from-21-10.md
versioned_docs/version-22.04/upgrade/centreon-ha/upgrade-from-21-04.md
versioned_docs/version-22.04/upgrade/centreon-ha/upgrade-from-21-10.md

Fix too more constraints on HA 2 nodes

PS-62 - Fix constraints on HA 2 nodes

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/developer/about-developer-resources.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/developer/developer-broker-bbdo.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/developer/developer-broker-mapping.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/developer/developer-broker-stream-connector-migration.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/developer/developer-broker-stream-connector.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/developer/developer-module.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/developer/developer-stream-connector.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/developer/developer-translate-centreon.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/developer/developer-widget.md
versioned_docs/version-22.04/developer/developer-broker-mapping.md
versioned_docs/version-22.04/developer/developer-stream-connector.md
versioned_docs/version-22.04/developer/developer-widget.md

Translation provided by external agency

Translation into French of "developer resources" chapter

---

i18n/fr/docusaurus-plugin-content-docs/version-21.04/releases/centreon-core.md
versioned_docs/version-21.04/releases/centreon-core.md

enh(release): Add Centreon Web 21.04.16 RN

---

i18n/fr/docusaurus-plugin-content-docs/version-22.10/developer/about-developer-resources.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/developer/developer-broker-bbdo.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/developer/developer-broker-mapping.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/developer/developer-broker-stream-connector-migration.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/developer/developer-broker-stream-connector.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/developer/developer-module.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/developer/developer-stream-connector.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/developer/developer-translate-centreon.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/developer/developer-widget.md
versioned_docs/version-22.10/developer/developer-broker-mapping.md
versioned_docs/version-22.10/developer/developer-stream-connector.md
versioned_docs/version-22.10/developer/developer-translate-centreon.md
versioned_docs/version-22.10/developer/developer-widget.md

Translation into French of "developer resources" chapter - next
PR on staging : https://github.com/centreon/centreon-documentation/pull/1694

Translation into French of "developer resources" chapter - next

---

i18n/fr/docusaurus-plugin-content-docs/version-22.10.json
i18n/fr/docusaurus-plugin-content-docs/version-22.10/developer/developer-gorgone-client-server-communication.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/developer/developer-gorgone-migrate-from-centcore.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/developer/developer-gorgone-pull-mode.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/developer/developer-gorgone-rebound-mode.md
versioned_docs/version-22.10/developer/developer-gorgone-client-server-communication.md
versioned_docs/version-22.10/developer/developer-gorgone-migrate-from-centcore.md
versioned_docs/version-22.10/developer/developer-gorgone-pull-mode.md
versioned_docs/version-22.10/developer/developer-gorgone-rebound-mode.md
versioned_sidebars/version-22.10-sidebars.json

Add documentation on Gorgone concept - Next

Mon 11018 gorgone concept - next

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
versioned_docs/version-22.04/releases/centreon-core.md

enh(release): Add Centreon Web 22.04.2 RN

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/update/update-centreon-platform.md
versioned_docs/version-22.04/update/update-centreon-platform.md

Remove clear cache command from update topic

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-monitoring-kadiska-restapi.md
pp/integrations/plugin-packs/procedures/applications-monitoring-kadiska-restapi.md

Modifying outdated command option in Kadiska Plugin pack documentation.

fix(pp) - Fixing outdated command option in Kadiska PP documentation

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/administration/centreon-ha/troubleshooting-guide.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/administration/licenses.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/administration/postfix.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/getting-started/it100.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/graph-views/troubleshooter.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/resources/troubleshooting.md
versioned_docs/version-22.04/administration/centreon-ha/troubleshooting-guide.md
versioned_docs/version-22.04/administration/licenses.md
versioned_docs/version-22.04/administration/postfix.md
versioned_docs/version-22.04/getting-started/it100.md
versioned_docs/version-22.04/graph-views/troubleshooter.md
versioned_docs/version-22.04/resources/troubleshooting.md
versioned_sidebars/version-22.04-sidebars.json

Centralize troubleshooting content into one topic.

Mon 14584 add troubleshooting topic

---

i18n/fr/docusaurus-plugin-content-docs/version-22.10/administration/centreon-ha/troubleshooting-guide.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/administration/licenses.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/administration/postfix.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/getting-started/it100.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/graph-views/troubleshooter.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/resources/troubleshooting.md
versioned_docs/version-22.10/administration/centreon-ha/troubleshooting-guide.md
versioned_docs/version-22.10/administration/licenses.md
versioned_docs/version-22.10/administration/postfix.md
versioned_docs/version-22.10/getting-started/it100.md
versioned_docs/version-22.10/graph-views/troubleshooter.md
versioned_docs/version-22.10/resources/troubleshooting.md
versioned_sidebars/version-22.10-sidebars.json

Add troubleshooting topic - next

Add troubleshooting topic - next

---

i18n/fr/docusaurus-plugin-content-docs/version-22.10/reporting/installation.md
versioned_docs/version-22.10/reporting/installation.md

Fix anchor link in MBI installation topic - next

Fix anchor link in MBI installation topic - next

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/reporting/installation.md
versioned_docs/version-22.04/reporting/installation.md

Fix anchor link in MBI installation topic

Fix anchor link in MBI installation topic

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-netgear-sseries-snmp.md
pp/integrations/plugin-packs/procedures/network-netgear-sseries-snmp.md
pp/sidebarsPp.js

add(epp): netgear sseries snmp

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-commercial-extensions.md
versioned_docs/version-22.04/releases/centreon-commercial-extensions.md

doc(release): add release note for centreon-autodiscovery-22.04.1

---

cloud/installation/prerequisites.md
i18n/fr/docusaurus-plugin-content-docs-cloud/current/installation/prerequisites.md

Add partitioning recommendations on poller disk - Cloud

Mon 14374 add partition recommendations

---

i18n/fr/docusaurus-plugin-content-docs/version-22.10/monitoring/discovery/administration.md
versioned_docs/version-22.10/monitoring/discovery/administration.md

Fix API URL (next)

---

i18n/fr/docusaurus-plugin-content-docs/version-21.10/monitoring/discovery/administration.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/monitoring/discovery/administration.md
versioned_docs/version-21.10/monitoring/discovery/administration.md
versioned_docs/version-22.04/monitoring/discovery/administration.md

Fix API URL

---

i18n/fr/docusaurus-plugin-content-docs/version-22.10/monitoring/passive-monitoring/create-snmp-traps-definitions.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/monitoring/passive-monitoring/debug-snmp-traps-management.md
versioned_docs/version-22.10/monitoring/passive-monitoring/create-snmp-traps-definitions.md
versioned_docs/version-22.10/monitoring/passive-monitoring/debug-snmp-traps-management.md

(next) - Update snmp documentation

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-dell-powerstore-restapi.md
pp/integrations/plugin-packs/procedures/hardware-storage-dell-powerstore-restapi.md

enh(epp): dell powerstore rest api - update doc

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-aruba-aoscx-snmp.md
pp/integrations/plugin-packs/procedures/network-aruba-aoscx-snmp.md

enh(epp): aruba aoscx snmp - update doc

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-monitoring-centreon-ha.md
pp/integrations/plugin-packs/procedures/applications-monitoring-centreon-ha.md

Update centreon HA monitoring procedure for php resource

PS-88 Update-centreon-HA-monitoring for resource php

---

i18n/fr/docusaurus-plugin-content-docs/version-22.10/getting-started/monitor-cisco-router-with-snmp.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/getting-started/monitor-linux-server-with-snmp.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/getting-started/monitor-windows-server-with-snmp.md
versioned_docs/version-22.10/getting-started/monitor-cisco-router-with-snmp.md
versioned_docs/version-22.10/getting-started/monitor-linux-server-with-snmp.md
versioned_docs/version-22.10/getting-started/monitor-windows-server-with-snmp.md

Fix link for deploy configuration on first linux server, first windows server and first cisco router
https://centreon.atlassian.net/browse/PS-89

PS-89 NEXT - Fix-link-deploy-configuration-for-french

---

i18n/fr/docusaurus-plugin-content-docs/version-22.10/integrations/event-management/sc-pagerduty-events.md
versioned_docs/version-22.10/integrations/event-management/sc-pagerduty-events.md

Fix typo 22.10

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/integrations/event-management/sc-pagerduty-events.md
versioned_docs/version-22.04/integrations/event-management/sc-pagerduty-events.md

Fix typo 22.04

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/getting-started/monitor-cisco-router-with-snmp.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/getting-started/monitor-linux-server-with-snmp.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/getting-started/monitor-windows-server-with-snmp.md
versioned_docs/version-22.04/getting-started/monitor-cisco-router-with-snmp.md
versioned_docs/version-22.04/getting-started/monitor-linux-server-with-snmp.md
versioned_docs/version-22.04/getting-started/monitor-windows-server-with-snmp.md

Fix link for deploy configuration on first linux server and first windows server
https://centreon.atlassian.net/browse/PS-89

PS-89 - Fix-link-deploy-configuration-for-french

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/getting-started/monitor-windows-server-with-snmp.md
versioned_docs/version-22.04/getting-started/monitor-windows-server-with-snmp.md

Fix link (windows tutorial)
Complements https://github.com/centreon/centreon-documentation/pull/1737

Fix link (windows tutorial)

---

i18n/fr/docusaurus-plugin-content-docs/version-22.10/getting-started/monitor-windows-server-with-snmp.md
versioned_docs/version-22.10/getting-started/monitor-windows-server-with-snmp.md

Fix link (windows tutorial) - next
Complements https://github.com/centreon/centreon-documentation/pull/1738

Fix link (windows tutorial) - next

---

i18n/fr/docusaurus-plugin-content-docs/version-21.04/releases/centreon-core.md
versioned_docs/version-21.04/releases/centreon-core.md

enh(release): Add Centreon Web 21.04.17 RN

---

versioned_docs/version-22.04/resources/troubleshooting.md

Remove obsolete link

---

i18n/fr/docusaurus-plugin-content-docs/version-21.04/installation/prerequisites.md
i18n/fr/docusaurus-plugin-content-docs/version-21.10/installation/prerequisites.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/installation/prerequisites.md
versioned_docs/version-21.04/installation/prerequisites.md
versioned_docs/version-21.10/installation/prerequisites.md
versioned_docs/version-22.04/installation/prerequisites.md

Clarify supported OSs

---

i18n/fr/docusaurus-plugin-content-docs/version-22.10/installation/prerequisites.md
versioned_docs/version-22.10/installation/prerequisites.md

Clarify supported OSs - next

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-hp-moonshot-snmp.md
pp/integrations/plugin-packs/procedures/network-hp-moonshot-snmp.md
pp/sidebarsPp.js

add(epp): hp moonshot snmp

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-fortinet-fortigate-restapi.md
pp/integrations/plugin-packs/procedures/network-fortinet-fortigate-restapi.md
pp/sidebarsPp.js

add(epp): fortinet fortigate rest api

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
versioned_docs/version-22.04/releases/centreon-core.md

enh(release): Add Centreon Web 22.04.3 RN

---

i18n/fr/docusaurus-plugin-content-docs/version-21.10/releases/centreon-core.md
versioned_docs/version-21.10/releases/centreon-core.md

enh(release): Add Centreon Web 21.10.9 RN

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/getting-started/installation-first-steps.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/monitoring/basic-objects/services-templates.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/resources/glossary.md
versioned_docs/version-22.04/getting-started/installation-first-steps.md
versioned_docs/version-22.04/resources/glossary.md
versioned_sidebars/version-22.04-sidebars.json

Mon 14327 Create a glossary (staging)

Mon 14327 Create a glossary (staging)

---

i18n/fr/docusaurus-plugin-content-docs/version-22.10/installation/installation-of-a-central-server/using-packages.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/installation/installation-of-a-poller/using-packages.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/installation/installation-of-a-remote-server/using-packages.md
versioned_docs/version-22.10/installation/installation-of-a-central-server/using-packages.md
versioned_docs/version-22.10/installation/installation-of-a-poller/using-packages.md
versioned_docs/version-22.10/installation/installation-of-a-remote-server/using-packages.md

enh(documentation): Improve installation chapters (next)

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-cisco-umbrella-snmp.md
pp/integrations/plugin-packs/procedures/network-cisco-umbrella-snmp.md
pp/sidebarsPp.js

Adding Cisco Umbrella Plugin pack documentation.

add(pp) - Adding documentation for Cisco Umbrella Plugin pack

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-management-recovery.md
pp/integrations/plugin-packs/procedures/cloud-azure-management-recovery.md

Adding new replication-health service template to Plugin pack documentation.

enh(pp) Azure Recovery - Adding replication-health service template

---

i18n/fr/docusaurus-plugin-content-docs/version-22.10/getting-started/installation-first-steps.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/monitoring/basic-objects/services-templates.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/resources/glossary.md
versioned_docs/version-22.10/getting-started/installation-first-steps.md
versioned_docs/version-22.10/resources/glossary.md
versioned_sidebars/version-22.10-sidebars.json

Glossary (22.10)

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/api/clapi.md
versioned_docs/version-22.04/api/clapi.md

This PR intends to adapt the CLAPI documentation regarding changes incoming with PR:
https://github.com/centreon/centreon/pull/11332
The PR for the fixes and its 22.04 equivalent should be merged before merging this documentation PR.

fix(clapi): update clapi documentation for contact template

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/metrology/grafana.md
versioned_docs/version-22.04/metrology/grafana.md

Add a procedure to use the Centreon data source as an unsigned Grafana plugin

Add procedure to use unsigned Grafana plugin

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-oneaccess-snmp.md
pp/integrations/plugin-packs/procedures/network-oneaccess-snmp.md

enh(epp): one access snmp - add rtt-probes mode

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-hp-3par-ssh.md
pp/integrations/plugin-packs/procedures/hardware-storage-hp-3par-ssh.md
pp/sidebarsPp.js

enh(epp): hp 3par proc v2

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-iics-restapi.md
pp/integrations/plugin-packs/procedures/cloud-iics-restapi.md
pp/sidebarsPp.js

add(epp): iics rest api

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
versioned_docs/version-22.04/releases/centreon-core.md

enh(release): Add Centreon Web 22.04.4 RN

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
versioned_docs/version-22.04/releases/centreon-core.md

Release notes for Collect 22.04.1

doc(release): add release note for centreon-collect-22.04.1

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md

Fix wrong title levels (FR)

---

versioned_docs/version-22.04/releases/centreon-core.md

Fix wrong title levels (EN)

---

i18n/fr/docusaurus-plugin-content-docs/version-21.04/releases/centreon-commercial-extensions.md
versioned_docs/version-21.04/releases/centreon-commercial-extensions.md

enh(release): Add Centreon MAP 21.04.7 RN

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-emc-vplex-restapi.md
pp/integrations/plugin-packs/procedures/hardware-storage-emc-vplex-restapi.md

enh(epp): emc vplex rest api proc v2

---

i18n/fr/docusaurus-plugin-content-docs/version-22.10/installation/installation-of-a-central-server/using-packages.md
versioned_docs/version-22.10/installation/installation-of-a-central-server/using-packages.md

Update Debian installation for Central EN and FR for Next release (copy/paste since https://github.com/centreon/centreon-documentation/pull/1659)
https://centreon.atlassian.net/browse/PS-63

PS-63 debian installation of a central update NEXT

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/operatingsystems-windows-nsclient-05-nrpe.md
pp/integrations/plugin-packs/procedures/operatingsystems-windows-nsclient-05-nrpe.md

Adding NRPE discovery rule for disks on windows + translation FR
resumption of the new format of the PR https://github.com/centreon/centreon-documentation/pull/1220

Enh(doc) add discovery rule for windows NRPE + translation FR

---

versioned_docs/version-22.04/integrations/event-management/sc-pagerduty-events.md

Modify PagerDuty spelling as requested by our partner.

Fix PagerDuty spelling

---

versioned_docs/version-22.10/connect/openid.md

Fix typos (next)

---

i18n/fr/docusaurus-plugin-content-docs/version-21.10/installation/installation-of-centreon-ha/installation-2-nodes.md
i18n/fr/docusaurus-plugin-content-docs/version-21.10/installation/installation-of-centreon-ha/installation-4-nodes.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/installation/installation-of-centreon-ha/installation-2-nodes.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/installation/installation-of-centreon-ha/installation-4-nodes.md
versioned_docs/version-21.10/installation/installation-of-centreon-ha/installation-2-nodes.md
versioned_docs/version-21.10/installation/installation-of-centreon-ha/installation-4-nodes.md
versioned_docs/version-22.04/installation/installation-of-centreon-ha/installation-2-nodes.md
versioned_docs/version-22.04/installation/installation-of-centreon-ha/installation-4-nodes.md

Add a section to manage disabled resources after installation of the cluster. In few cases we need to manually activate some resrouces.
EN and FR versions

PS-56 - Add manage disabled resources.

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-management-costs.md
pp/integrations/plugin-packs/procedures/cloud-azure-management-costs.md
pp/sidebarsPp.js

Add Azure Costs monitoring proc

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/update/update-centreon-platform.md
versioned_docs/version-22.04/update/update-centreon-platform.md

Perform Centreon update via API

Perform Centreon update via API

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-databases-oracle.md
pp/integrations/plugin-packs/procedures/applications-databases-oracle.md

Closes https://github.com/centreon/centreon-documentation/pull/1554 
Thanks @ochoto !

Enhance Oracle prerequisites section

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/releases/release-notes.md
pp/integrations/plugin-packs/releases/release-notes.md

Fix tab alignment in monitoring pack release note

---

i18n/fr/docusaurus-plugin-content-docs/version-22.10/update/update-centreon-platform.md
versioned_docs/version-22.10/update/update-centreon-platform.md

Perform Centreon update via API - Next

Perform Centreon update via API - Next

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-commercial-extensions.md
versioned_docs/version-22.04/releases/centreon-commercial-extensions.md

enh(release): Add Centreon BAM 22.04.2

---

versioned_docs/version-22.10/getting-started/create-graphical-view.md

Spelling and wording adjustments - Next

Update create-graphical-view.md - Next

---

i18n/fr/docusaurus-plugin-content-docs/version-21.04.json
i18n/fr/docusaurus-plugin-content-docs/version-21.10.json
i18n/fr/docusaurus-plugin-content-docs/version-22.04.json

Fix incorrect label

---

versioned_docs/version-22.04/graph-views/remote-server.md

Review MAP-Install on a remote server topic

Review MAP-Install on a remote server topic

---

versioned_docs/version-22.10/graph-views/remote-server.md

Review MAP-Install on a remote server topic - Next

Review MAP-Install on a remote server topic - Next

---

docusaurus.config.js
i18n/en/code.json
i18n/en/docusaurus-plugin-content-docs-cloud/current.json
i18n/en/docusaurus-plugin-content-docs-pp/current.json
i18n/en/docusaurus-plugin-content-docs/version-20.04.json
i18n/en/docusaurus-plugin-content-docs/version-20.10.json
i18n/en/docusaurus-plugin-content-docs/version-21.04.json
i18n/en/docusaurus-plugin-content-docs/version-21.10.json
i18n/en/docusaurus-plugin-content-docs/version-22.04.json
i18n/en/docusaurus-theme-classic/footer.json
i18n/en/docusaurus-theme-classic/navbar.json
i18n/fr/code.json
src/css/custom.css

Mark older versions of the documentation as no longer maintained

Mark older versions of the documentation as no longer maintained

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
versioned_docs/version-22.04/releases/centreon-core.md

enh(release): Add Centreon Web 22.04.5 RN

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/installation/installation-of-a-central-server/using-packages.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/installation/installation-of-a-remote-server/using-packages.md
versioned_docs/version-22.04/installation/installation-of-a-central-server/using-packages.md
versioned_docs/version-22.04/installation/installation-of-a-remote-server/using-packages.md

fix(install): improve Debian installation (staging)

---

i18n/fr/docusaurus-plugin-content-docs/version-22.10/installation/installation-of-a-central-server/using-packages.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/installation/installation-of-a-remote-server/using-packages.md
versioned_docs/version-22.10/installation/installation-of-a-central-server/using-packages.md
versioned_docs/version-22.10/installation/installation-of-a-remote-server/using-packages.md

fix(install): improve Debian installation (next)

---

i18n/fr/docusaurus-plugin-content-docs/version-21.10/releases/centreon-core.md
versioned_docs/version-21.10/releases/centreon-core.md

enh(release): Add Centreon Web 21.10.10 RN

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/getting-started/which-install.md
versioned_docs/version-22.04/getting-started/which-install.md

Add Debian to list of supported OS in "which install" topic

Add Debian to list of supported OS in "which install" topic

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
versioned_docs/version-22.04/releases/centreon-core.md

enh(release): Add Centreon Gorgone 22.04.1 RN

---

package.json
yarn.lock

Upgrade to Docusaurus 2.1 (next)
staging: #1837

Upgrade to Docusaurus 2.1 (next)

---

i18n/fr/docusaurus-plugin-content-docs/version-22.10/reporting/generate-reports.md
versioned_docs/version-22.10/reporting/generate-reports.md

Remove dead link (next)

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/administration/secure-platform.md
versioned_docs/version-22.04/administration/secure-platform.md

Update HTTPS for Debian topic

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
versioned_docs/version-22.04/releases/centreon-core.md

enh(release): add Centreon Web 22.04.6 RN

---

i18n/fr/docusaurus-plugin-content-docs/version-21.10/releases/centreon-core.md
versioned_docs/version-21.10/releases/centreon-core.md

enh(release): Add Centreon Web 21.10.11 RN

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
versioned_docs/version-22.04/releases/centreon-core.md

fix(release): add missing ticket

---

i18n/fr/docusaurus-plugin-content-docs/version-22.10/integrations/event-management/sc-pagerduty-events.md
versioned_docs/version-22.10/integrations/event-management/sc-pagerduty-events.md

* Fix PagerDuty case
* Stick to PagerDuty partnership requirement
Report modification in the _next_ branch

(next) Fix PagerDuty spelling (#1800)

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-hp-moonshot-snmp.md
pp/integrations/plugin-packs/procedures/network-hp-moonshot-snmp.md

doc(update) hp.moonshoot.snmp

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/operatingsystems-windows-nsclient-05-nrpe.md
i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/operatingsystems-windows-nsclient-05-restapi.md
i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/operatingsystems-windows-wsman.md
pp/integrations/plugin-packs/procedures/operatingsystems-windows-nsclient-05-nrpe.md
pp/integrations/plugin-packs/procedures/operatingsystems-windows-nsclient-05-restapi.md
pp/integrations/plugin-packs/procedures/operatingsystems-windows-wsman.md

enh(epp): add service updates for windows pack

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-aruba-orchestrator-restapi.md
pp/integrations/plugin-packs/procedures/network-aruba-orchestrator-restapi.md
pp/sidebarsPp.js

add(epp): aruba orchestrator rest api

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-switchs-alcatel-omniswitch-snmp.md
pp/integrations/plugin-packs/procedures/network-switchs-alcatel-omniswitch-snmp.md

enh(epp): alcatel omniswitch snmp - add service virtual-chassis

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/operatingsystems-as400-connector.md
pp/integrations/plugin-packs/procedures/operatingsystems-as400-connector.md

Fix template name

---

i18n/fr/docusaurus-plugin-content-docs/version-22.10/migrate/migrate-from-el-to-debian.md
versioned_docs/version-22.10/migrate/migrate-from-el-to-debian.md

Improve wording of topic titleImprove wording of topic title

Improve wording of topic title

---

i18n/fr/docusaurus-plugin-content-docs/version-22.10/installation/introduction.md
versioned_docs/version-22.10/installation/introduction.md

Improve unattended installation procedure (next)

Improve unattended installation procedure (next)

---

i18n/fr/docusaurus-plugin-content-docs/version-21.10/installation/introduction.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/installation/introduction.md
versioned_docs/version-21.10/installation/introduction.md
versioned_docs/version-22.04/installation/introduction.md

Fix and improve unattended installation procedure

Fix and improve unattended installation procedure (staging)

---

versioned_docs/version-22.10/upgrade/upgrade-from-20-10.md

Fix upgrade procedure (php 8.1)

Fix upgrade procedure (php 8.1)

---

i18n/fr/docusaurus-plugin-content-docs/version-21.10/releases/centreon-core.md
versioned_docs/version-21.10/releases/centreon-core.md

enh(release): Add Centreon Web 21.10.12 RN

---

pp/integrations/plugin-packs/dev-resources/develop-with-centreon-plugins.md
pp/integrations/plugin-packs/dev-resources/introduction.md

Fix typos thanks to users' feedbacks

Fix typos in the dev tutorial

---

i18n/fr/docusaurus-plugin-content-docs/version-21.04/releases/centreon-core.md
versioned_docs/version-21.04/releases/centreon-core.md

enh(release): Add Centreon Web 21.04.20 RN

---

i18n/fr/docusaurus-plugin-content-docs/version-21.10/releases/centreon-core.md
versioned_docs/version-21.10/releases/centreon-core.md

enh(release): Add Centreon Web 21.10.13 RN

---

i18n/fr/docusaurus-plugin-content-docs/version-20.04/monitoring/anomaly-detection.md
i18n/fr/docusaurus-plugin-content-docs/version-20.10/monitoring/anomaly-detection.md
i18n/fr/docusaurus-plugin-content-docs/version-21.04/monitoring/anomaly-detection.md
i18n/fr/docusaurus-plugin-content-docs/version-21.10/monitoring/anomaly-detection.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/monitoring/anomaly-detection.md
versioned_docs/version-20.04/monitoring/anomaly-detection.md
versioned_docs/version-20.10/monitoring/anomaly-detection.md
versioned_docs/version-21.04/monitoring/anomaly-detection.md
versioned_docs/version-21.10/monitoring/anomaly-detection.md
versioned_docs/version-22.04/monitoring/anomaly-detection.md

Remove obsolete information from Anomaly Detection FAQ

Remove obsolete information from Anomaly Detection FAQ

---

i18n/fr/docusaurus-plugin-content-docs/version-22.10/alerts-notifications/resources-status.md
versioned_docs/version-22.10/alerts-notifications/resources-status.md

Add csv export of timeline and graphs

Add csv export of timeline and graphs

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-vmware-vcsa-snmp.md
pp/integrations/plugin-packs/procedures/applications-vmware-vcsa-snmp.md
pp/sidebarsPp.js

add(epp): applications-vmware-vcsa-snmp - new

---

i18n/fr/docusaurus-plugin-content-docs/version-22.10/migrate/migrate-from-el-to-debian.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/migrate/migrate-from-el-to-el.md
versioned_docs/version-22.10/migrate/migrate-from-el-to-debian.md
versioned_docs/version-22.10/migrate/migrate-from-el-to-el.md

Fix procedure to migrate poller (next)

Fix poller migration procedure (next)

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-monitoring-splunk-api.md
pp/integrations/plugin-packs/procedures/applications-monitoring-splunk-api.md
pp/sidebarsPp.js

Add Splunk monitoring procedure with latest script

---

i18n/fr/docusaurus-plugin-content-docs/version-21.10/upgrade/upgrade-from-21-04.md
i18n/fr/docusaurus-plugin-content-docs/version-21.10/upgrade/upgrade-mariadb.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/upgrade/upgrade-from-21-10.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/upgrade/upgrade-mariadb.md
versioned_docs/version-21.10/upgrade/upgrade-from-21-04.md
versioned_docs/version-21.10/upgrade/upgrade-mariadb.md
versioned_docs/version-22.04/upgrade/upgrade-from-21-10.md
versioned_docs/version-22.04/upgrade/upgrade-mariadb.md

Improve upgrade documentation with MariaDB

Improve upgrade documentation with MariaDB

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-monitoring-kadiska-restapi.md
pp/integrations/plugin-packs/procedures/applications-monitoring-kadiska-restapi.md

Adding new metrics and macro to Kadiska PP documentation.

Update Kadiska PP doc with latest modifications

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/releases/release-notes.md
pp/integrations/plugin-packs/releases/release-notes.md

Release note pack October (pending last docs)

Add October Monitoring Pack release note

---

i18n/fr/docusaurus-plugin-content-docs/version-22.10/upgrade/upgrade-from-22-04.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/upgrade/upgrade-mariadb.md
versioned_docs/version-22.10/upgrade/upgrade-from-22-04.md
versioned_docs/version-22.10/upgrade/upgrade-mariadb.md

Improve upgrade documentation with MariaDB - Next

Improve upgrade documentation with MariaDB - Next

---

i18n/fr/docusaurus-plugin-content-docs/version-22.10/migrate/migrate-from-el-to-debian.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/migrate/migrate-from-el-to-el.md
versioned_docs/version-22.10/migrate/migrate-from-el-to-debian.md
versioned_docs/version-22.10/migrate/migrate-from-el-to-el.md

Corrections in migration topics

Corrections in migration topics

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/migrate/migrate-from-el-to-debian.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/migrate/migrate-from-el-to-el.md
versioned_docs/version-22.04/migrate/migrate-from-el-to-debian.md
versioned_docs/version-22.04/migrate/migrate-from-el-to-el.md

Fix poller migration procedure (staging)
- [ x] 22.04.x (staging)

Fix poller migration procedure (staging)

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/upgrade/upgrade-from-18-10.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/upgrade/upgrade-from-19-04.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/upgrade/upgrade-from-19-10.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/upgrade/upgrade-from-20-04.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/upgrade/upgrade-from-20-10.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/upgrade/upgrade-from-21-04.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/upgrade/upgrade-from-21-10.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/upgrade/upgrade-from-3-4.md
versioned_docs/version-22.04/upgrade/upgrade-from-18-10.md
versioned_docs/version-22.04/upgrade/upgrade-from-19-04.md
versioned_docs/version-22.04/upgrade/upgrade-from-19-10.md
versioned_docs/version-22.04/upgrade/upgrade-from-20-04.md
versioned_docs/version-22.04/upgrade/upgrade-from-20-10.md
versioned_docs/version-22.04/upgrade/upgrade-from-21-04.md
versioned_docs/version-22.04/upgrade/upgrade-from-21-10.md
versioned_docs/version-22.04/upgrade/upgrade-from-3-4.md

Add ioncube and gnupg to upgrade doc (staging)

Add ioncube and gnupg to upgrade doc (staging)

---

i18n/fr/docusaurus-plugin-content-docs/version-22.10/upgrade/upgrade-from-18-10.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/upgrade/upgrade-from-19-04.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/upgrade/upgrade-from-19-10.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/upgrade/upgrade-from-20-04.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/upgrade/upgrade-from-20-10.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/upgrade/upgrade-from-21-04.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/upgrade/upgrade-from-21-10.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/upgrade/upgrade-from-22-04.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/upgrade/upgrade-from-3-4.md
versioned_docs/version-22.10/upgrade/upgrade-from-18-10.md
versioned_docs/version-22.10/upgrade/upgrade-from-19-04.md
versioned_docs/version-22.10/upgrade/upgrade-from-19-10.md
versioned_docs/version-22.10/upgrade/upgrade-from-20-04.md
versioned_docs/version-22.10/upgrade/upgrade-from-20-10.md
versioned_docs/version-22.10/upgrade/upgrade-from-21-04.md
versioned_docs/version-22.10/upgrade/upgrade-from-21-10.md
versioned_docs/version-22.10/upgrade/upgrade-from-22-04.md
versioned_docs/version-22.10/upgrade/upgrade-from-3-4.md
versioned_docs/version-22.10/upgrade/upgrade-mariadb.md

Fix MariaDB upgrade information (uninstallation step)

Fix MariaDB upgrade information

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-thales-mistral-vs9-restapi.md
pp/integrations/plugin-packs/procedures/applications-thales-mistral-vs9-restapi.md
pp/sidebarsPp.js

add(epp): thales mistral vs9 rest api

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/graph-views/secure-your-map-platform.md
versioned_docs/version-22.04/graph-views/secure-your-map-platform.md

Improve enable HTTPS/TLS for map

Improve enable HTTPS/TLS for map

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-pineapp-securemail-snmp.md
pp/integrations/plugin-packs/procedures/applications-pineapp-securemail-snmp.md
pp/sidebarsPp.js

MON-14432-create-pineapp-securemail-pack

---

i18n/fr/docusaurus-plugin-content-docs/version-22.10/graph-views/install.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/migrate/migrate-from-3-4.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/migrate/migrate-from-el-to-debian.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/migrate/migrate-from-el-to-el.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/monitoring/pluginpacks.md
versioned_docs/version-22.10/graph-views/install.md
versioned_docs/version-22.10/migrate/migrate-from-3-4.md
versioned_docs/version-22.10/migrate/migrate-from-el-to-debian.md
versioned_docs/version-22.10/migrate/migrate-from-el-to-el.md
versioned_docs/version-22.10/monitoring/pluginpacks.md

Replace obsolete link (next)

---

versioned_docs/version-22.10/api/clapi.md

Added missing parameters to parameter list table in CLAPI web documentation.

fix(clapi): Added missing parameters to parameter list table in CLAPI web documentation - 22.10

---

i18n/fr/docusaurus-plugin-content-docs/version-22.10/reporting/installation.md
versioned_docs/version-22.10/reporting/installation.md

Add commands to MBI installation procedure (22.10)

Add commands to MBI installation procedure (22.10)

---

i18n/fr/docusaurus-plugin-content-docs/version-22.10/graph-views/install.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/reporting/installation.md
versioned_docs/version-22.10/graph-views/install.md
versioned_docs/version-22.10/reporting/installation.md

Update java info for el7/el8

---

i18n/fr/docusaurus-plugin-content-docs/version-22.10/service-mapping/update.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/service-mapping/upgrade.md
versioned_docs/version-22.10/service-mapping/update.md
versioned_docs/version-22.10/service-mapping/upgrade.md

Add command to upgrade/update BAM on Debian (22.10)

Add command to upgrade/update BAM on Debian (22.10)

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/service-mapping/update.md
versioned_docs/version-22.04/service-mapping/update.md

Add command to update BAM on Debian (22.04)

Add command to update BAM on Debian (22.04)

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/installation/installation-of-a-central-server/using-packages.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/installation/installation-of-a-remote-server/using-packages.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/update/update-centreon-platform.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/upgrade/upgrade-mariadb.md
versioned_docs/version-22.04/installation/installation-of-a-central-server/using-packages.md
versioned_docs/version-22.04/installation/installation-of-a-remote-server/using-packages.md
versioned_docs/version-22.04/update/update-centreon-platform.md
versioned_docs/version-22.04/upgrade/upgrade-mariadb.md

Update installation procedures (staging)

Update installation procedures (staging)

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-commercial-extensions.md
versioned_docs/version-22.04/releases/centreon-commercial-extensions.md

doc(release): prepare release notes for Centreon MBI 22.04.3

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-huawei-oceanstor-snmp.md
pp/integrations/plugin-packs/procedures/hardware-storage-huawei-oceanstor-snmp.md

enh(epp): huawei oceanstor proc v2 updated

---

i18n/fr/docusaurus-plugin-content-docs/version-22.10/resources/known-issues.md
versioned_docs/version-22.10/resources/known-issues.md

Add known issue MON-15697 Web 22.10

Add known issue MON-15697 Web 22.10

---

i18n/fr/docusaurus-plugin-content-docs/version-22.10/graph-views/install.md
versioned_docs/version-22.10/graph-views/install.md

Fix Desktop client URL

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/reporting/installation.md
versioned_docs/version-22.04/reporting/installation.md

Fix docs for install MBI extension to Debian OS.

Fix-debian-OS-to-install-MBI

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/graph-views/remote-server.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/service-mapping/remote-server.md
versioned_docs/version-22.04/graph-views/remote-server.md
versioned_docs/version-22.04/service-mapping/remote-server.md

Improve wording on Broker configuration

Improve wording on Broker configuration

---

i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
versioned_docs/version-22.10/releases/centreon-os.md

Add item to RN 22.10

---

i18n/fr/docusaurus-plugin-content-docs/version-22.10/resources/known-issues.md
versioned_docs/version-22.10/resources/known-issues.md

Add known issues MON-15684 and MON-15597

Add known issues MON-15684 and MON-15597

---

i18n/fr/docusaurus-plugin-content-docs-pp/current.json
i18n/fr/docusaurus-plugin-content-docs/version-23.04.json
i18n/fr/docusaurus-theme-classic/navbar.json

Update newline characters + navbar translation cleanup (23.04)
(We kept the newline characters changed by the docusaurus script)

Update newline characters + navbar translation cleanup (23.04)

---

i18n/fr/docusaurus-plugin-content-docs/version-22.10/update/update-centreon-platform.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/upgrade/upgrade-from-22-04.md
versioned_docs/version-22.10/update/update-centreon-platform.md
versioned_docs/version-22.10/upgrade/upgrade-from-22-04.md

Improve upgrade topic from 22.04

Improve upgrade topic from 22.04

---

i18n/fr/docusaurus-plugin-content-docs/version-23.04/update/update-centreon-platform.md
i18n/fr/docusaurus-plugin-content-docs/version-23.04/upgrade/upgrade-from-22-04.md
versioned_docs/version-23.04/update/update-centreon-platform.md
versioned_docs/version-23.04/upgrade/upgrade-from-22-04.md

Mon 15745 improve upgrade topic -  Next

---

i18n/fr/docusaurus-plugin-content-docs/version-22.10/graph-views/install.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/graph-views/upgrade.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/reporting/installation.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/reporting/upgrade.md
versioned_docs/version-22.10/graph-views/install.md
versioned_docs/version-22.10/graph-views/upgrade.md
versioned_docs/version-22.10/reporting/installation.md
versioned_docs/version-22.10/reporting/upgrade.md

Includes [MON-15755](https://centreon.atlassian.net/browse/MON-15755) and [MON-15781](https://centreon.atlassian.net/browse/MON-15781)
Add notes for java 17 on Installation and Upgrade topics (MAP Legacy 22.10 / MBI 22.10)

Add note for java 17 on Install/Upgrade topics (MAP/MBI)

---

i18n/fr/docusaurus-plugin-content-docs/version-23.04/reporting/installation.md
i18n/fr/docusaurus-plugin-content-docs/version-23.04/reporting/upgrade.md
versioned_docs/version-23.04/reporting/installation.md
versioned_docs/version-23.04/reporting/upgrade.md

Same PR as this [one ](https://github.com/centreon/centreon-documentation/pull/1949) but apply to MBI 23.04

Add Java notes for MBI 23.04

---

i18n/fr/docusaurus-plugin-content-docs/version-22.10/graph-views/upgrade.md
versioned_docs/version-22.10/graph-views/upgrade.md

Improve MAP legacy upgrade topic

Improve MAP legacy upgrade topic

---

i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
versioned_docs/version-22.10/releases/centreon-os.md

RN for Centreon web release 22.10.1

prepare-rn-web-22.10.1

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-enterasys-snmp.md
pp/integrations/plugin-packs/procedures/network-enterasys-snmp.md
pp/sidebarsPp.js

add(epp): enterasys snmp

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-servers-xfusion-ibmc-snmp.md
pp/integrations/plugin-packs/procedures/hardware-servers-xfusion-ibmc-snmp.md
pp/sidebarsPp.js

add(epp): xfusion ibmc snmp

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-netapp-ontap-restapi.md
pp/integrations/plugin-packs/procedures/hardware-storage-netapp-ontap-restapi.md

enh(pp) - Adding Aggregates service template to Netapp Ontap PP doc

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-ups-himoinsa-snmp.md
pp/integrations/plugin-packs/procedures/hardware-ups-himoinsa-snmp.md
pp/sidebarsPp.js

Adding documentation for Himoinsa new Plugin pack.

add(epp) - Adding Himoinsa SNMP Plugin pack documentation

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/releases/release-notes.md
pp/integrations/plugin-packs/releases/release-notes.md

enh(rn): 20221115 Plugin Packs release

---

i18n/fr/docusaurus-plugin-content-docs/version-21.04/installation/installation-of-centreon-ha/installation-2-nodes.md
i18n/fr/docusaurus-plugin-content-docs/version-21.04/installation/installation-of-centreon-ha/installation-4-nodes.md
i18n/fr/docusaurus-plugin-content-docs/version-21.10/installation/installation-of-centreon-ha/installation-2-nodes.md
i18n/fr/docusaurus-plugin-content-docs/version-21.10/installation/installation-of-centreon-ha/installation-4-nodes.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/installation/installation-of-centreon-ha/installation-2-nodes.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/installation/installation-of-centreon-ha/installation-4-nodes.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/installation/installation-of-centreon-ha/installation-2-nodes.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/installation/installation-of-centreon-ha/installation-4-nodes.md
versioned_docs/version-21.04/installation/installation-of-centreon-ha/installation-2-nodes.md
versioned_docs/version-21.04/installation/installation-of-centreon-ha/installation-4-nodes.md
versioned_docs/version-21.10/installation/installation-of-centreon-ha/installation-2-nodes.md
versioned_docs/version-21.10/installation/installation-of-centreon-ha/installation-4-nodes.md
versioned_docs/version-22.04/installation/installation-of-centreon-ha/installation-2-nodes.md
versioned_docs/version-22.04/installation/installation-of-centreon-ha/installation-4-nodes.md
versioned_docs/version-22.10/installation/installation-of-centreon-ha/installation-2-nodes.md
versioned_docs/version-22.10/installation/installation-of-centreon-ha/installation-4-nodes.md

Improve HA install procedure

---

i18n/fr/docusaurus-plugin-content-docs/version-23.04/installation/introduction.md
i18n/fr/docusaurus-plugin-content-docs/version-23.04/security/key-rotation.md
versioned_docs/version-23.04/installation/introduction.md
versioned_docs/version-23.04/security/key-rotation.md

Update script path (next)

---

i18n/fr/docusaurus-plugin-content-docs/version-21.10/installation/introduction.md
i18n/fr/docusaurus-plugin-content-docs/version-21.10/security/key-rotation.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/installation/introduction.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/security/key-rotation.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/installation/introduction.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/security/key-rotation.md
versioned_docs/version-21.10/installation/introduction.md
versioned_docs/version-21.10/security/key-rotation.md
versioned_docs/version-22.04/installation/introduction.md
versioned_docs/version-22.04/security/key-rotation.md
versioned_docs/version-22.10/installation/introduction.md
versioned_docs/version-22.10/security/key-rotation.md

Update script path (staging)

---

i18n/fr/docusaurus-plugin-content-docs/version-23.04/reporting/installation.md
versioned_docs/version-23.04/reporting/installation.md

Add info to MBI installation procedure for Debian 11 - next

Add info to MBI installation procedure for Debian 11 - next

---

i18n/fr/docusaurus-plugin-content-docs/version-22.10/reporting/installation.md
versioned_docs/version-22.10/reporting/installation.md

Add info to MBI installation procedure for Debian 11

Add info to MBI installation procedure for Debian 11

---

i18n/fr/docusaurus-plugin-content-docs/version-20.04/security/key-rotation.md
i18n/fr/docusaurus-plugin-content-docs/version-20.10/security/key-rotation.md
i18n/fr/docusaurus-plugin-content-docs/version-21.04/security/key-rotation.md
versioned_docs/version-20.04/security/key-rotation.md
versioned_docs/version-20.10/security/key-rotation.md
versioned_docs/version-21.04/security/key-rotation.md

Update script path in old doc

---

i18n/fr/docusaurus-plugin-content-docs/version-23.04/installation/installation-of-centreon-ha/installation-2-nodes.md
i18n/fr/docusaurus-plugin-content-docs/version-23.04/installation/installation-of-centreon-ha/installation-4-nodes.md
versioned_docs/version-23.04/installation/installation-of-centreon-ha/installation-2-nodes.md
versioned_docs/version-23.04/installation/installation-of-centreon-ha/installation-4-nodes.md

PS-44 - Deploy staging doc Centreon-HAvto next branch

PS 44 staging to next 4 centreon ha

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-microsoft-office365-azuread.md
i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-microsoft-office365-exchange.md
i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-microsoft-office365-onedrive.md
i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-microsoft-office365-skype.md
pp/integrations/plugin-packs/procedures/cloud-microsoft-office365-azuread.md
pp/integrations/plugin-packs/procedures/cloud-microsoft-office365-exchange.md
pp/integrations/plugin-packs/procedures/cloud-microsoft-office365-onedrive.md
pp/integrations/plugin-packs/procedures/cloud-microsoft-office365-skype.md

Bring some enhancements to Cloud M365 monitoring procedures
- office365-skype - Switch FR<>EN and modernize installation section
- office365-exchange - Update installation steps & troubleshooting section
- Office365 OneDrive+Skype - Update installation steps

(pp) Enhancements to some Cloud M365 monitoring procedures

---

i18n/fr/docusaurus-plugin-content-docs/version-23.04/api/rest-api-v1.md
versioned_docs/version-23.04/api/rest-api-v1.md

Add info action restapiv1 (next)

---

i18n/fr/docusaurus-plugin-content-docs/version-22.10/graph-views/map-web-install.md
versioned_docs/version-22.10/graph-views/map-web-install.md

Remove business repo URL from MAP installation section

Remove business repo URL from MAP installation section

---

i18n/fr/docusaurus-plugin-content-docs/version-22.10/resources/known-issues.md
versioned_docs/version-22.10/resources/known-issues.md

Remove known issue about UI translation

Remove known issue about UI translation

---

i18n/fr/docusaurus-plugin-content-docs/version-23.04/reporting/concepts.md
versioned_docs/version-23.04/reporting/concepts.md

Improve BAM stats procedure - Next

Improve BAM stats procedure - Next

---

i18n/fr/docusaurus-plugin-content-docs/version-21.10/reporting/concepts.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/reporting/concepts.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/reporting/concepts.md
versioned_docs/version-21.10/reporting/concepts.md
versioned_docs/version-22.04/reporting/concepts.md
versioned_docs/version-22.10/reporting/concepts.md

Improve BAM stats procedure

---

i18n/fr/docusaurus-plugin-content-docs/version-22.10/resources/known-issues.md
versioned_docs/version-22.10/resources/known-issues.md

Add known issue for ETL script error

Add known issue for ETL script error

---

i18n/fr/docusaurus-plugin-content-docs/version-21.10/api/rest-api-v2.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/api/rest-api-v2.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/api/rest-api-v2.md
versioned_docs/version-21.10/api/rest-api-v2.md
versioned_docs/version-22.04/api/rest-api-v2.md
versioned_docs/version-22.10/api/rest-api-v2.md

Update URL for:
- centreon-api-v22.04.yaml
- centreon-api-v22.10.yaml

update(doc)URL API YML

---

i18n/fr/docusaurus-plugin-content-docs/version-22.10/reporting/installation.md
versioned_docs/version-22.10/reporting/installation.md

Add command to MBI installation procedure for EL8

Add command to MBI installation procedure for EL8

---

i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-commercial-extensions.md
versioned_docs/version-22.10/releases/centreon-commercial-extensions.md

doc(release): prepare release notes for Centreon MAP 22.10.1

---

versioned_docs/version-21.04/administration/database-partitioning.md
versioned_docs/version-21.10/administration/database-partitioning.md
versioned_docs/version-22.04/administration/database-partitioning.md
versioned_docs/version-22.10/administration/database-partitioning.md

Fix typo in database partitioning topic

---

i18n/fr/docusaurus-plugin-content-docs/version-23.04/upgrade/upgrade-from-20-10.md
i18n/fr/docusaurus-plugin-content-docs/version-23.04/upgrade/upgrade-from-21-04.md
i18n/fr/docusaurus-plugin-content-docs/version-23.04/upgrade/upgrade-from-21-10.md
i18n/fr/docusaurus-plugin-content-docs/version-23.04/upgrade/upgrade-from-22-04.md
versioned_docs/version-23.04/upgrade/upgrade-from-20-10.md
versioned_docs/version-23.04/upgrade/upgrade-from-21-04.md
versioned_docs/version-23.04/upgrade/upgrade-from-21-10.md
versioned_docs/version-23.04/upgrade/upgrade-from-22-04.md

Split codeblock (next)

---

i18n/fr/docusaurus-plugin-content-docs/version-22.10/upgrade/upgrade-from-20-10.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/upgrade/upgrade-from-21-04.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/upgrade/upgrade-from-21-10.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/upgrade/upgrade-from-22-04.md
versioned_docs/version-22.10/upgrade/upgrade-from-20-10.md
versioned_docs/version-22.10/upgrade/upgrade-from-21-04.md
versioned_docs/version-22.10/upgrade/upgrade-from-21-10.md
versioned_docs/version-22.10/upgrade/upgrade-from-22-04.md

Split codeblock

---

i18n/fr/docusaurus-plugin-content-docs/version-23.04/mobile/introduction.md
versioned_docs/version-23.04/mobile/introduction.md

Fix link to video about mobile site - next

Fix link to video about mobile site - next

---

i18n/fr/docusaurus-plugin-content-docs/version-20.04/mobile/introduction.md
i18n/fr/docusaurus-plugin-content-docs/version-20.10/mobile/introduction.md
i18n/fr/docusaurus-plugin-content-docs/version-21.04/mobile/introduction.md
i18n/fr/docusaurus-plugin-content-docs/version-21.10/mobile/introduction.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/mobile/introduction.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/mobile/introduction.md
versioned_docs/version-20.04/mobile/introduction.md
versioned_docs/version-20.10/mobile/introduction.md
versioned_docs/version-21.04/mobile/introduction.md
versioned_docs/version-21.10/mobile/introduction.md
versioned_docs/version-22.04/mobile/introduction.md
versioned_docs/version-22.10/mobile/introduction.md

Fix link to video on mobile site

Fix link to video about mobile site

---

i18n/fr/docusaurus-plugin-content-docs/version-21.10/releases/lifecycle.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/lifecycle.md
versioned_docs/version-21.10/releases/lifecycle.md
versioned_docs/version-22.04/releases/lifecycle.md

Mark some versions as unsupported in old topics

Mark some versions as unsupported in old topics

---

i18n/fr/docusaurus-plugin-content-docs/version-23.04/resources/contribute.md
versioned_docs/version-23.04/resources/contribute.md

MON-16235 improve contributing topic (next)

MON-16235-improve-contributing-topic-next

---

i18n/fr/docusaurus-plugin-content-docs/version-23.04/monitoring/passive-monitoring/debug-snmp-traps-management.md
versioned_docs/version-23.04/monitoring/passive-monitoring/debug-snmp-traps-management.md

Fix typo in passive monitoring topic - next

Fix typo in passive monitoring topic - next

---

i18n/fr/docusaurus-plugin-content-docs/version-21.10/monitoring/passive-monitoring/debug-snmp-traps-management.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/monitoring/passive-monitoring/debug-snmp-traps-management.md
versioned_docs/version-21.10/monitoring/passive-monitoring/debug-snmp-traps-management.md
versioned_docs/version-22.04/monitoring/passive-monitoring/debug-snmp-traps-management.md
versioned_docs/version-22.10/monitoring/passive-monitoring/debug-snmp-traps-management.md

Fix typo in passive monitoring topic.
Complements https://github.com/centreon/centreon-documentation/pull/2028

Fix typo in passive monitoring topic

---

i18n/fr/docusaurus-plugin-content-docs/version-22.10/graph-views/import-into-map-web.md
versioned_docs/version-22.10/graph-views/import-into-map-web.md
versioned_docs/version-22.10/graph-views/map-web-install.md

Improve MAP migration procedure

Improve MAP migration procedure

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-patton-smartnode-snmp.md
pp/integrations/plugin-packs/procedures/network-patton-smartnode-snmp.md
pp/sidebarsPp.js

Adding Patton SmartNode plugin pack

MON-15507-add-patton-snmp-pack

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-sensors-apc-snmp.md
pp/integrations/plugin-packs/procedures/hardware-sensors-apc-snmp.md
pp/sidebarsPp.js

add(epp): hardware-sensors-apc-snmp proc

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-hitachi-hnas-snmp.md
pp/integrations/plugin-packs/procedures/hardware-storage-hitachi-hnas-snmp.md

enh(epp): hitachi nas snmp proc v2

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-thales-mistral-vs9-restapi.md
pp/integrations/plugin-packs/procedures/applications-thales-mistral-vs9-restapi.md

enh(epp): mistral vs9 rest api - add service clusters

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-databases-oracle.md
pp/integrations/plugin-packs/procedures/applications-databases-oracle.md

- Update the monitoring procedure
- Add Debian sections

enh(epp): Oracle Database - add Debian sections

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-netapp-ontap-restapi.md
pp/integrations/plugin-packs/procedures/hardware-storage-netapp-ontap-restapi.md

enh(epp): netapp ontap restapi - add quotas

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-monitoring-kadiska-restapi.md
pp/integrations/plugin-packs/procedures/applications-monitoring-kadiska-restapi.md

enh(epp): kadiska - update stations to runners

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/releases/release-notes.md
pp/integrations/plugin-packs/releases/release-notes.md

enh(rn): 20221215 Plugin Packs release

---

i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-commercial-extensions.md
versioned_docs/version-22.10/releases/centreon-commercial-extensions.md

Prepare relese notes for Centreon MAP 22.10.3 (hotfix MON-16258)

doc(release): prepare release notes for Centreon MAP 22.10.3

---

i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-commercial-extensions.md
versioned_docs/version-22.10/releases/centreon-commercial-extensions.md

RN MAP 22.10.3

---

cloud/installation/prerequisites.md
i18n/fr/docusaurus-plugin-content-docs-cloud/current/installation/prerequisites.md

Remove incorrect information

---

i18n/fr/docusaurus-plugin-content-docs/version-21.10/graph-views/upgrade.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/graph-views/upgrade.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/graph-views/upgrade.md
versioned_docs/version-21.10/graph-views/upgrade.md
versioned_docs/version-22.04/graph-views/upgrade.md

Update MAP upgrade Legacy topic with dialects - 21.10 and 22.04

Update MAP upgrade Legacy topic with dialects - 21.10 and 22.04

---

cloud/alerts-notifications/resources-status.md
i18n/fr/docusaurus-plugin-content-docs-cloud/current/alerts-notifications/resources-status.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/alerts-notifications/resources-status.md
versioned_docs/version-22.10/alerts-notifications/resources-status.md

Add info on the search in Resources Status

Add info on the search in Resources Status

---

i18n/fr/docusaurus-plugin-content-docs/version-23.04/alerts-notifications/resources-status.md
versioned_docs/version-23.04/alerts-notifications/resources-status.md

Add info on the search in Resources Status (next)

Add info on the search in Resources Status (next)

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/graph-views/known-issues.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/graph-views/troubleshooter.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/resources/troubleshooting.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/graph-views/known-issues.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/graph-views/troubleshooter.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/resources/troubleshooting.md
versioned_docs/version-22.04/graph-views/known-issues.md
versioned_docs/version-22.04/graph-views/troubleshooter.md
versioned_docs/version-22.04/resources/troubleshooting.md
versioned_docs/version-22.10/resources/troubleshooting.md

Add link to MAP troubleshooting

Mon 16339 add link map troubleshooting

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/graph-views/import-into-map-web.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/graph-views/map-web-update.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/graph-views/upgrade.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/graph-views/map-web-update.md
versioned_docs/version-22.04/graph-views/import-into-map-web.md
versioned_docs/version-22.04/graph-views/map-web-update.md
versioned_docs/version-22.04/graph-views/upgrade.md

Report MAP updates into 22.04 version

Report MAP updates into 22.04 version

---

i18n/fr/docusaurus-plugin-content-docs/version-21.10/resources/known-issues.md
versioned_docs/version-21.10/resources/known-issues.md

MBI known issue for version 21.10

MBI known issue for version 21.10

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-commercial-extensions.md
versioned_docs/version-22.04/releases/centreon-commercial-extensions.md

Prepare release notes for MAP 22.04.3 (hotfix MON-16346)

doc(release): prepare release notes for MAP 22.04.3

---

i18n/fr/docusaurus-plugin-content-docs/version-23.04/reporting/installation.md
versioned_docs/version-23.04/reporting/installation.md

Push installation of MBI on Debian 11 on the branch next

Push MON-15001 to next branch

---

i18n/fr/docusaurus-plugin-content-docs/version-21.10/reporting/installation.md
i18n/fr/docusaurus-plugin-content-docs/version-21.10/service-mapping/install.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/reporting/installation.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/service-mapping/install.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/reporting/installation.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/service-mapping/install.md
versioned_docs/version-21.10/reporting/installation.md
versioned_docs/version-21.10/service-mapping/install.md
versioned_docs/version-22.04/reporting/installation.md
versioned_docs/version-22.04/service-mapping/install.md
versioned_docs/version-22.10/reporting/installation.md
versioned_docs/version-22.10/service-mapping/install.md

- Make step in MBI installation procedure more noticeable
- Add info to BAM installation procedure

Add info to installation procedures for business modules

---

i18n/fr/docusaurus-plugin-content-docs/version-23.04/reporting/installation.md
versioned_docs/version-23.04/reporting/installation.md

Change path php to branch next MON-15940
[MON-15940]: https://centreon.atlassian.net/browse/MON-15940?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Change php path to next branch MON-15940

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/reporting/installation.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/reporting/installation.md
versioned_docs/version-22.04/reporting/installation.md
versioned_docs/version-22.10/reporting/installation.md

Push install MBI on staging branch for 22.04 and 22.10 MON-15940.
[MON-15940]: https://centreon.atlassian.net/browse/MON-15940?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Push install MBI 22.04&22.10 MON-15940

---

i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
versioned_docs/version-22.10/releases/centreon-os.md

doc(release): prepare release notes for Centreon Web 22.10.4

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/graph-views/import-into-map-web.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/graph-views/import-into-map-web.md
versioned_docs/version-22.04/graph-views/import-into-map-web.md
versioned_docs/version-22.10/graph-views/import-into-map-web.md

Add MAP disk space requirement.

Add MAP disk space requirement

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
versioned_docs/version-22.04/releases/centreon-core.md

chore(release): prepare release notes for Web 22.04.8

---

i18n/fr/docusaurus-plugin-content-docs/version-21.10/releases/centreon-core.md
versioned_docs/version-21.10/releases/centreon-core.md

doc(release): add release note for centreon-collect-21.10.4

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-talend-tmc-api.md
pp/integrations/plugin-packs/procedures/cloud-talend-tmc-api.md
pp/sidebarsPp.js

add(epp): cloud talend tmc api

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/graph-views/install.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/graph-views/map-web-install.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/graph-views/install.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/graph-views/map-web-install.md
versioned_docs/version-22.04/graph-views/install.md
versioned_docs/version-22.04/graph-views/map-web-install.md
versioned_docs/version-22.10/graph-views/install.md
versioned_docs/version-22.10/graph-views/map-web-install.md

not all Os where mentionned there
- [X ] 22.04.x (staging)
- [X ] 23.04.x (next)

precise supported versions in prerequisite part

---

i18n/fr/docusaurus-plugin-content-docs/version-21.10/integrations/introduction-integrations.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/integrations/introduction-integrations.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/integrations/introduction-integrations.md
versioned_docs/version-21.10/integrations/introduction-integrations.md
versioned_docs/version-22.04/integrations/introduction-integrations.md
versioned_docs/version-22.10/integrations/introduction-integrations.md

Fix integrations introduction page.

Fix integrations introduction page

---

i18n/fr/docusaurus-plugin-content-docs/version-23.04/integrations/introduction-integrations.md
versioned_docs/version-23.04/integrations/introduction-integrations.md

Fix integrations introduction page - next

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/graph-views/map-web-install.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/graph-views/map-web-install.md
versioned_docs/version-22.04/graph-views/map-web-install.md
versioned_docs/version-22.10/graph-views/map-web-install.md

Add step when MAP Engine and Legacy are installed on the same server.

Add step when MAP Engine and Legacy are installed on the same server

---

cloud/installation/prerequisites.md
i18n/fr/docusaurus-plugin-content-docs-cloud/current/installation/prerequisites.md

Update poller prerequisites (Cloud)

Update poller prerequisites (Cloud)

---

cloud/installation/prerequisites.md
i18n/fr/docusaurus-plugin-content-docs-cloud/current/installation/prerequisites.md

Revert MON-16555

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/graph-views/install.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/graph-views/map-web-install.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/graph-views/install.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/graph-views/map-web-install.md
versioned_docs/version-22.04/graph-views/install.md
versioned_docs/version-22.04/graph-views/map-web-install.md
versioned_docs/version-22.10/graph-views/install.md
versioned_docs/version-22.10/graph-views/map-web-install.md

Remove protobuf config from MAP install topic.

Remove protobuf config from MAP install topic

---

cloud/graph-views/introduction-map.md
i18n/fr/docusaurus-plugin-content-docs-cloud/current/graph-views/introduction-map.md

Remove useless mention from MAP cloud.

Remove useless mention from MAP cloud

---

versioned_docs/version-22.10/releases/centreon-os.md

Remove extra bullet point

---

i18n/fr/docusaurus-plugin-content-docs/version-21.10/monitoring/discovery/services-discovery.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/monitoring/discovery/services-discovery.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/monitoring/discovery/services-discovery.md
versioned_docs/version-21.10/monitoring/discovery/services-discovery.md
versioned_docs/version-22.04/monitoring/discovery/services-discovery.md
versioned_docs/version-22.10/monitoring/discovery/services-discovery.md

Improve rules definition in service disco topic.

Improve rules definition in service disco topic

---

versioned_docs/version-20.04/reporting/concepts.md
versioned_docs/version-20.10/reporting/concepts.md
versioned_docs/version-21.04/reporting/concepts.md
versioned_docs/version-21.10/reporting/concepts.md
versioned_docs/version-22.04/reporting/concepts.md
versioned_docs/version-22.10/reporting/concepts.md

Remove extra restart command in MBI doc

---

i18n/fr/code.json
src/theme/DocItem/Footer/index.js
src/theme/DocItem/Footer/styles.module.css

Add feedback link in page footer
Preview container here: http://10.25.11.244:11777

Add feedback link in page footer

---

i18n/fr/docusaurus-plugin-content-docs/version-23.04/graph-views/install.md
i18n/fr/docusaurus-plugin-content-docs/version-23.04/installation/prerequisites.md
i18n/fr/docusaurus-plugin-content-docs/version-23.04/reporting/installation.md
i18n/fr/docusaurus-plugin-content-docs/version-23.04/service-mapping/install.md
versioned_docs/version-23.04/graph-views/install.md
versioned_docs/version-23.04/installation/prerequisites.md
versioned_docs/version-23.04/reporting/installation.md
versioned_docs/version-23.04/service-mapping/install.md

Unify OS requirements - 23.04

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/installation/prerequisites.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/installation/prerequisites.md
versioned_docs/version-22.04/installation/prerequisites.md
versioned_docs/version-22.10/installation/prerequisites.md

Add VM mention for Alma8 OS requirements

Add VM mention for Alma8 OS requirements

---

i18n/fr/docusaurus-plugin-content-docs/version-23.04/monitoring/discovery/services-discovery.md
versioned_docs/version-23.04/monitoring/discovery/services-discovery.md

Improve rules definition in service disco topic - 23.04

Improve rules definition in service disco topic - 23.04

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/operatingsystems-linux-nrpe3.md
pp/integrations/plugin-packs/procedures/operatingsystems-linux-nrpe3.md

Update operatingsystems-linux-nrpe3 documentation for Debian

MON-14477-debian-package-add-nrpe-3-package

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
versioned_docs/version-22.04/releases/centreon-core.md

Release note for Collect 22.04.2

doc(release):add release note for centreon-collect-22.04.2

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/graph-views/map-web-troubleshooting.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/graph-views/map-web-update.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/graph-views/map-web-troubleshooting.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/graph-views/map-web-update.md
versioned_docs/version-22.04/graph-views/map-web-troubleshooting.md
versioned_docs/version-22.04/graph-views/map-web-update.md
versioned_docs/version-22.10/graph-views/map-web-troubleshooting.md
versioned_docs/version-22.10/graph-views/map-web-update.md

Improve MAP update topic with broker config.

Improve MAP update topic with broker config

---

i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-commercial-extensions.md
versioned_docs/version-22.10/releases/centreon-commercial-extensions.md

doc(release): add release note for centreon-bam-22.10.1

---

i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-commercial-extensions.md
versioned_docs/version-22.10/releases/centreon-commercial-extensions.md

Prepare release note for Anomaly Detection 22.10.1

doc(release): prepare release note for Anomaly Detection 22.10.1

---

i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-commercial-extensions.md
versioned_docs/version-22.10/releases/centreon-commercial-extensions.md

Prepare release notes for MBI 22.10.1

doc(release): prepare release note for MBI 22.10.1

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-wd-nas-snmp.md
pp/integrations/plugin-packs/procedures/hardware-storage-wd-nas-snmp.md
pp/sidebarsPp.js

add(epp): wd nas snmp

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/reporting/update.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/reporting/installation.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/reporting/update.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/reporting/upgrade.md
versioned_docs/version-22.04/reporting/update.md
versioned_docs/version-22.10/reporting/installation.md
versioned_docs/version-22.10/reporting/update.md
versioned_docs/version-22.10/reporting/upgrade.md

Fix Debian and EL8 MBI upgrade procedures

Fix Debian and EL8 MBI upgrade procedures

---

i18n/fr/docusaurus-plugin-content-docs/version-23.04/update/update-centreon-platform.md
versioned_docs/version-23.04/update/update-centreon-platform.md

Fix poller update procedure (next)

Fix poller update procedure (next)

---

i18n/fr/docusaurus-plugin-content-docs/version-22.10/update/update-centreon-platform.md
versioned_docs/version-22.10/update/update-centreon-platform.md

Fix poller update procedure

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-oracle-ucp-jmx.md
pp/integrations/plugin-packs/procedures/applications-oracle-ucp-jmx.md
pp/sidebarsPp.js

add(epp): oracle ucp jmx

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-jenkins.md
pp/integrations/plugin-packs/procedures/applications-jenkins.md

enh(epp): application jenkins

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-kubernetes-api.md
pp/integrations/plugin-packs/procedures/cloud-kubernetes-api.md

enh(epp): cloud-kubernetes-api - add namespace option

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/releases/release-notes.md
pp/integrations/plugin-packs/releases/release-notes.md

doc(release): release note for Connectors 20230215

---

i18n/fr/docusaurus-plugin-content-docs/version-21.10/graph-views/advanced-configuration.md
i18n/fr/docusaurus-plugin-content-docs/version-21.10/graph-views/configuration.md
i18n/fr/docusaurus-plugin-content-docs/version-21.10/graph-views/secure-your-map-platform.md
i18n/fr/docusaurus-plugin-content-docs/version-21.10/graph-views/troubleshooter.md
i18n/fr/docusaurus-plugin-content-docs/version-21.10/graph-views/upgrade.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/graph-views/advanced-configuration.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/graph-views/configuration.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/graph-views/secure-your-map-platform.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/graph-views/troubleshooter.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/graph-views/upgrade.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/graph-views/advanced-configuration.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/graph-views/configuration.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/graph-views/secure-your-map-platform.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/graph-views/troubleshooter.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/graph-views/upgrade.md
versioned_docs/version-21.10/graph-views/advanced-configuration.md
versioned_docs/version-21.10/graph-views/configuration.md
versioned_docs/version-21.10/graph-views/secure-your-map-platform.md
versioned_docs/version-21.10/graph-views/troubleshooter.md
versioned_docs/version-21.10/graph-views/upgrade.md
versioned_docs/version-22.04/graph-views/advanced-configuration.md
versioned_docs/version-22.04/graph-views/configuration.md
versioned_docs/version-22.04/graph-views/secure-your-map-platform.md
versioned_docs/version-22.04/graph-views/troubleshooter.md
versioned_docs/version-22.04/graph-views/upgrade.md
versioned_docs/version-22.10/graph-views/advanced-configuration.md
versioned_docs/version-22.10/graph-views/configuration.md
versioned_docs/version-22.10/graph-views/secure-your-map-platform.md
versioned_docs/version-22.10/graph-views/troubleshooter.md
versioned_docs/version-22.10/graph-views/upgrade.md

Add warning on MAP config files edition.

Add warning on MAP config files edition

---

i18n/fr/docusaurus-plugin-content-docs/version-23.04/reporting/installation.md
i18n/fr/docusaurus-plugin-content-docs/version-23.04/reporting/update.md
i18n/fr/docusaurus-plugin-content-docs/version-23.04/reporting/upgrade.md
versioned_docs/version-23.04/reporting/installation.md
versioned_docs/version-23.04/reporting/update.md
versioned_docs/version-23.04/reporting/upgrade.md

Fix Debian and EL8 MBI upgrade procedures - next
- [ x] 23.04.x (next)

Fix Debian and EL8 MBI upgrade procedures - next

---

i18n/fr/docusaurus-plugin-content-docs/version-22.10/reporting/installation.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/reporting/upgrade.md
versioned_docs/version-22.10/reporting/installation.md
versioned_docs/version-22.10/reporting/upgrade.md

Fix Debian command (MBI)

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-os-extensions.md
versioned_docs/version-22.04/releases/centreon-core.md
versioned_docs/version-22.04/releases/centreon-os-extensions.md

Included:
* WEB 22.04.11
* Open-tickets 22.04.1

doc(release): Prepare release notes for next 22.04 

---

i18n/fr/docusaurus-plugin-content-docs/version-21.10/releases/centreon-core.md
versioned_docs/version-21.10/releases/centreon-core.md

chore(release): prepare release note for Collect 21.10.5

---

i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
versioned_docs/version-22.10/releases/centreon-os.md

doc(release): Prepare release notes for oss 22.10.6

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/graph-views/install.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/graph-views/upgrade.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/reporting/installation.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/reporting/upgrade.md
versioned_docs/version-22.04/graph-views/install.md
versioned_docs/version-22.04/graph-views/upgrade.md
versioned_docs/version-22.04/reporting/installation.md
versioned_docs/version-22.04/reporting/upgrade.md

Add link to Java 17 download in 22.04.

Add link to Java 17 download in 22.04

---

i18n/fr/docusaurus-plugin-content-docs/version-21.10/migrate/migrate-from-20-x.md
i18n/fr/docusaurus-plugin-content-docs/version-21.10/migrate/migrate-from-3-4.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/migrate/migrate-from-3-4.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/migrate/migrate-from-el-to-debian.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/migrate/migrate-from-el-to-el.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/migrate/migrate-from-3-4.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/migrate/migrate-from-el-to-debian.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/migrate/migrate-from-el-to-el.md
versioned_docs/version-21.10/migrate/migrate-from-20-x.md
versioned_docs/version-21.10/migrate/migrate-from-3-4.md
versioned_docs/version-22.04/migrate/migrate-from-3-4.md
versioned_docs/version-22.04/migrate/migrate-from-el-to-debian.md
versioned_docs/version-22.04/migrate/migrate-from-el-to-el.md
versioned_docs/version-22.10/migrate/migrate-from-3-4.md
versioned_docs/version-22.10/migrate/migrate-from-el-to-debian.md
versioned_docs/version-22.10/migrate/migrate-from-el-to-el.md

Add synchronization command to improve migration topic.

Add synchronization command to improve migration topic

---

i18n/fr/docusaurus-plugin-content-docs/version-23.04/migrate/migrate-from-3-4.md
i18n/fr/docusaurus-plugin-content-docs/version-23.04/migrate/migrate-from-el-to-debian.md
i18n/fr/docusaurus-plugin-content-docs/version-23.04/migrate/migrate-from-el-to-el.md
versioned_docs/version-23.04/migrate/migrate-from-3-4.md
versioned_docs/version-23.04/migrate/migrate-from-el-to-debian.md
versioned_docs/version-23.04/migrate/migrate-from-el-to-el.md

Add synchronization command to improve migration topic - Next

Add synchronization command to improve migration topic - Next

---

i18n/fr/docusaurus-plugin-content-docs/version-23.04/installation/offline.md
versioned_docs/version-23.04/installation/offline.md
versioned_sidebars/version-23.04-sidebars.json

Add topic about offline installation - next

Add topic about offline installation - next

---

i18n/fr/docusaurus-plugin-content-docs/version-21.10/installation/offline.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/installation/offline.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/installation/offline.md
versioned_docs/version-21.10/installation/offline.md
versioned_docs/version-22.04/installation/offline.md
versioned_docs/version-22.10/installation/offline.md
versioned_sidebars/version-21.10-sidebars.json
versioned_sidebars/version-22.04-sidebars.json
versioned_sidebars/version-22.10-sidebars.json

Add topic about offline installation

Add topic about offline installation

---

i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
versioned_docs/version-22.10/releases/centreon-os.md

doc(release): Prepare release notes for oss 22.10.7

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
versioned_docs/version-22.04/releases/centreon-core.md

Release notes for oss 22.04.12

doc(release): Prepare release notes for oss 22.04.12

---

cloud/getting-started/architecture.md
i18n/fr/docusaurus-plugin-content-docs-cloud/current/getting-started/architecture.md

Make the need to install pollers more obvious (Cloud)

Make the need to install pollers more obvious (Cloud)

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-ups-standard-rfc1628-snmp.md
pp/integrations/plugin-packs/procedures/hardware-ups-standard-rfc1628-snmp.md

enh(epp): hardware-ups-standard-rfc1628-snmp

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-ups-riello-snmp.md
pp/integrations/plugin-packs/procedures/hardware-ups-riello-snmp.md
pp/sidebarsPp.js

add(epp): hardware-ups-riello-snmp

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-controlm-restapi.md
pp/integrations/plugin-packs/procedures/applications-controlm-restapi.md
pp/sidebarsPp.js

ad(epp): applications-controlm-restapi

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-pdu-raritan-snmp.md
pp/integrations/plugin-packs/procedures/hardware-pdu-raritan-snmp.md

enh(epp): hardware-pdu-raritan-snmp

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/releases/release-notes.md
pp/integrations/plugin-packs/releases/release-notes.md

doc(release): release notes for Connectors 23.03

---

i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
versioned_docs/version-22.10/releases/centreon-os.md

Release note for Collect 22.10.1

doc(release): Prepare release notes for collect 22.10.1

---

i18n/fr/docusaurus-plugin-content-docs/version-21.10/releases/centreon-core.md
i18n/fr/docusaurus-plugin-content-docs/version-21.10/releases/centreon-os-extensions.md
versioned_docs/version-21.10/releases/centreon-core.md
versioned_docs/version-21.10/releases/centreon-os-extensions.md

Release notes for 21.10.14
- [ x] 21.10.x (staging)

doc(release): Prepare release notes for oss 21.10.14

---

i18n/fr/docusaurus-plugin-content-docs/version-23.04/installation/prerequisites.md
versioned_docs/version-23.04/installation/prerequisites.md

Update poller characteristics (OnPrem) - next
Make it consistent with Cloud version

Update poller characteristics (OnPrem) - next

---

i18n/fr/docusaurus-plugin-content-docs/version-21.10/monitoring/passive-monitoring/debug-snmp-traps-management.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/monitoring/passive-monitoring/debug-snmp-traps-management.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/monitoring/passive-monitoring/debug-snmp-traps-management.md
versioned_docs/version-21.10/monitoring/passive-monitoring/debug-snmp-traps-management.md
versioned_docs/version-22.04/monitoring/passive-monitoring/debug-snmp-traps-management.md
versioned_docs/version-22.10/monitoring/passive-monitoring/debug-snmp-traps-management.md

Fix wrong file name

---

i18n/fr/docusaurus-plugin-content-docs/version-23.04/monitoring/passive-monitoring/debug-snmp-traps-management.md
versioned_docs/version-23.04/monitoring/passive-monitoring/debug-snmp-traps-management.md

Fix wrong file name (next)

---

i18n/fr/docusaurus-plugin-content-docs/version-22.10/migrate/introduction.md
versioned_docs/version-22.10/migrate/introduction.md

Fix incorrect version numbers

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-management-discover.md
pp/integrations/plugin-packs/procedures/cloud-azure-management-discover.md

MON-15484-add-missing-packs-from-azure-discover

---

i18n/fr/docusaurus-plugin-content-docs/version-23.04/administration/secure-platform.md
versioned_docs/version-23.04/administration/secure-platform.md

Improve HTTPS documentation - next

Improve HTTPS documentation - next

---

i18n/fr/docusaurus-plugin-content-docs/version-22.10/upgrade/centreon-ha/upgrade-from-21-10.md
versioned_docs/version-22.10/upgrade/centreon-ha/upgrade-from-21-10.md

PS-112 Upgrade 21.10 to 22.10 RHEL8 HA 2nodes - distinct EL8 and EL7 for export command and some typo's
Ticket PS: https://centreon.atlassian.net/browse/PS-112

Ps 112 upgrading ha rhel8 21.10 to 22.10

---

i18n/fr/docusaurus-plugin-content-docs/version-22.10/upgrade/centreon-ha/upgrade-from-21-04.md
versioned_docs/version-22.10/upgrade/centreon-ha/upgrade-from-21-04.md

PS-112 Upgrade HA RHEL8 2 nodes 21.04 to 22.10 - update commands and outputs
Ticket PS: https://centreon.atlassian.net/browse/PS-112

PS-112 Upgrade 22.10 RHEL8 HA 2nodes 21.04 to 22.10 - update commands and outputs

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/graph-views/map-web-known-issues.md
versioned_docs/version-22.04/graph-views/map-web-known-issues.md

Add Known issues for MAP 22.04

Add Known issues for MAP 22.04

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
versioned_docs/version-22.04/releases/centreon-core.md

Release notes for Collect 22.04.3

doc(release): Prepare release notes for collect 22.04.3

---

i18n/fr/docusaurus-plugin-content-docs/version-23.04/graph-views/map-web-install.md
versioned_docs/version-23.04/graph-views/map-web-install.md

MAP sizing (next) (as provided by the consulting team).

MAP sizing (next)

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/graph-views/map-web-install.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/graph-views/map-web-install.md
versioned_docs/version-22.04/graph-views/map-web-install.md
versioned_docs/version-22.10/graph-views/map-web-install.md

MAP sizing (as provided by the consulting team).

MAP sizing

---

i18n/fr/docusaurus-plugin-content-docs/version-23.04/graph-views/install.md
i18n/fr/docusaurus-plugin-content-docs/version-23.04/graph-views/map-web-install.md
versioned_docs/version-23.04/graph-views/install.md
versioned_docs/version-23.04/graph-views/map-web-install.md

Add a note to apply SSL on MAP server when central server is in HTTPS - 23.04

Add a note to apply SSL on MAP server when central server is in HTTPS - 23.04

---

i18n/fr/docusaurus-plugin-content-docs/version-23.04/graph-views/install.md
i18n/fr/docusaurus-plugin-content-docs/version-23.04/graph-views/map-web-install.md
i18n/fr/docusaurus-plugin-content-docs/version-23.04/graph-views/upgrade.md
i18n/fr/docusaurus-plugin-content-docs/version-23.04/reporting/installation.md
versioned_docs/version-23.04/graph-views/install.md
versioned_docs/version-23.04/graph-views/map-web-install.md
versioned_docs/version-23.04/graph-views/upgrade.md
versioned_docs/version-23.04/reporting/installation.md

Standardize Java requirement on all OS - MAP and MBI - 23.04

Standardize Java requirement on all OS - MAP and MBI - 23.04

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/graph-views/install.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/graph-views/map-web-install.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/graph-views/install.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/graph-views/map-web-install.md
versioned_docs/version-22.04/graph-views/install.md
versioned_docs/version-22.04/graph-views/map-web-install.md
versioned_docs/version-22.10/graph-views/install.md
versioned_docs/version-22.10/graph-views/map-web-install.md

Add a note to apply SSL on MAP server when central server is in HTTPS.

Add a note to apply SSL on MAP server when central server is in HTTPS

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/graph-views/install.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/graph-views/map-web-install.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/graph-views/upgrade.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/reporting/installation.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/graph-views/install.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/graph-views/map-web-install.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/graph-views/upgrade.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/reporting/installation.md
versioned_docs/version-22.04/graph-views/install.md
versioned_docs/version-22.04/graph-views/map-web-install.md
versioned_docs/version-22.04/graph-views/upgrade.md
versioned_docs/version-22.04/reporting/installation.md
versioned_docs/version-22.10/graph-views/install.md
versioned_docs/version-22.10/graph-views/map-web-install.md
versioned_docs/version-22.10/graph-views/upgrade.md
versioned_docs/version-22.10/reporting/installation.md

Standardize Java requirement on all OS - MAP and MBI

Standardize Java requirement on all OS

---

i18n/fr/docusaurus-plugin-content-docs/version-21.10/graph-views/install.md
i18n/fr/docusaurus-plugin-content-docs/version-21.10/reporting/installation.md
i18n/fr/docusaurus-plugin-content-docs/version-21.10/reporting/migrate.md
i18n/fr/docusaurus-plugin-content-docs/version-21.10/service-mapping/install.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/graph-views/install.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/graph-views/map-web-install.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/graph-views/upgrade.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/reporting/installation.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/reporting/migrate.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/service-mapping/install.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/graph-views/install.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/graph-views/map-web-install.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/graph-views/upgrade.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/reporting/migrate.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/service-mapping/install.md
versioned_docs/version-21.10/graph-views/install.md
versioned_docs/version-21.10/graph-views/upgrade.md
versioned_docs/version-21.10/reporting/installation.md
versioned_docs/version-21.10/service-mapping/install.md
versioned_docs/version-22.04/graph-views/install.md
versioned_docs/version-22.04/graph-views/map-web-install.md
versioned_docs/version-22.04/graph-views/upgrade.md
versioned_docs/version-22.04/reporting/installation.md
versioned_docs/version-22.04/reporting/upgrade.md
versioned_docs/version-22.04/service-mapping/install.md
versioned_docs/version-22.10/graph-views/install.md
versioned_docs/version-22.10/graph-views/map-web-install.md
versioned_docs/version-22.10/graph-views/upgrade.md
versioned_docs/version-22.10/reporting/installation.md
versioned_docs/version-22.10/service-mapping/install.md

Rename "MAP/MBI/BAM repository" to "Business repository".

Rename "MAP/MBI/BAM repository" to "Business repository"

---

i18n/fr/docusaurus-plugin-content-docs/version-23.04/getting-started/interface.md
i18n/fr/docusaurus-plugin-content-docs/version-23.04/monitoring/basic-objects/contacts.md
versioned_docs/version-23.04/getting-started/interface.md
versioned_docs/version-23.04/monitoring/basic-objects/contacts.md

Add new feature to define default page - 23.04

Add new feature to define default page - 23.04

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-opengear-snmp.md
pp/integrations/plugin-packs/procedures/network-opengear-snmp.md
pp/sidebarsPp.js

add(epp): network-opengear-snmp

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-aruba-cppm-snmp.md
pp/integrations/plugin-packs/procedures/network-aruba-cppm-snmp.md
pp/sidebarsPp.js

add(epp): network-aruba-cppm-snmp

---

i18n/fr/docusaurus-plugin-content-docs/version-23.04/service-mapping/ba-management.md
versioned_docs/version-23.04/service-mapping/ba-management.md

Remove reference to ssv file import

Remove reference to ssv file import

---

i18n/fr/docusaurus-plugin-content-docs/version-23.04/service-mapping/install.md
i18n/fr/docusaurus-plugin-content-docs/version-23.04/service-mapping/migrate.md
i18n/fr/docusaurus-plugin-content-docs/version-23.04/service-mapping/update.md
i18n/fr/docusaurus-plugin-content-docs/version-23.04/service-mapping/upgrade.md
versioned_docs/version-23.04/service-mapping/install.md
versioned_docs/version-23.04/service-mapping/migrate.md
versioned_docs/version-23.04/service-mapping/remote-server.md
versioned_docs/version-23.04/service-mapping/update.md
versioned_docs/version-23.04/service-mapping/upgrade.md

Adapt BAM doc to new list of supported OSs (23.04)

Adapt BAM doc to new list of supported OSs (23.04)

---

i18n/fr/docusaurus-plugin-content-docs/version-23.04/metrology/grafana.md
versioned_docs/version-23.04/metrology/grafana.md

Labels in Grafana (23.04)

---

i18n/fr/docusaurus-plugin-content-docs/version-23.04/graph-views/map-web-install.md
i18n/fr/docusaurus-plugin-content-docs/version-23.04/graph-views/secure-your-map-platform.md
versioned_docs/version-23.04/graph-views/map-web-install.md
versioned_docs/version-23.04/graph-views/secure-your-map-platform.md

Add info to secure MAP in HTTPS - 23.04

Add info to secure MAP in HTTPS - 23.04

---

i18n/fr/docusaurus-plugin-content-docs/version-23.04/connect/saml.md
versioned_docs/version-23.04/connect/saml.md
versioned_sidebars/version-23.04-sidebars.json

enh(connect):  Add SAML authentication

---

i18n/fr/docusaurus-plugin-content-docs/version-23.04/monitoring/anomaly-detection.md
versioned_docs/version-23.04/monitoring/anomaly-detection.md

Warning for forward history of data

Warning for forward history of data (next)

---

i18n/fr/docusaurus-plugin-content-docs/version-23.04/monitoring/anomaly-detection.md
versioned_docs/version-23.04/monitoring/anomaly-detection.md

Adapt Anomaly Detection doc to new list of supported OSs (23.04)

Adapt Anomaly Detection doc to new list of supported OSs (23.04)

---

i18n/fr/docusaurus-plugin-content-docs/version-23.04/monitoring/discovery/administration.md
i18n/fr/docusaurus-plugin-content-docs/version-23.04/monitoring/discovery/installation.md
versioned_docs/version-23.04/monitoring/discovery/administration.md
versioned_docs/version-23.04/monitoring/discovery/installation.md

Adapt Autodisco doc to new list of supported OSs (23.04)

Adapt Autodisco doc to new list of supported OSs (23.04)

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/releases/release-notes.md
pp/integrations/plugin-packs/releases/release-notes.md

Add info in PP release note

---

i18n/fr/docusaurus-plugin-content-docs/version-23.04/alerts-notifications/acknowledge.md
i18n/fr/docusaurus-plugin-content-docs/version-23.04/alerts-notifications/concepts.md
i18n/fr/docusaurus-plugin-content-docs/version-23.04/alerts-notifications/manage-alerts.md
i18n/fr/docusaurus-plugin-content-docs/version-23.04/alerts-notifications/resources-status.md
i18n/fr/docusaurus-plugin-content-docs/version-23.04/getting-started/concepts.md
i18n/fr/docusaurus-plugin-content-docs/version-23.04/getting-started/create-custom-view.md
i18n/fr/docusaurus-plugin-content-docs/version-23.04/monitoring/about.md
i18n/fr/docusaurus-plugin-content-docs/version-23.04/resources/glossary.md
versioned_docs/version-23.04/alerts-notifications/acknowledge.md
versioned_docs/version-23.04/alerts-notifications/concepts.md
versioned_docs/version-23.04/alerts-notifications/manage-alerts.md
versioned_docs/version-23.04/alerts-notifications/resources-status.md
versioned_docs/version-23.04/getting-started/concepts.md
versioned_docs/version-23.04/getting-started/create-custom-view.md
versioned_docs/version-23.04/monitoring/about.md
versioned_docs/version-23.04/resources/glossary.md

Rename "problem" to "alert" (23.04)

Rename "problem" to "alert" (23.04)

---

i18n/fr/docusaurus-plugin-content-docs/version-23.04/reporting/installation.md
versioned_docs/version-23.04/reporting/installation.md

MBI sizing (next) (as provided by the consulting team).

MBI sizing (next)

---

i18n/fr/docusaurus-plugin-content-docs/version-23.04/monitoring/discovery/hosts-discovery.md
versioned_docs/version-23.04/monitoring/discovery/hosts-discovery.md

Automatic plugin installation (23.04)

Automatic plugin installation (23.04)

---

i18n/fr/docusaurus-plugin-content-docs/version-22.10/reporting/installation.md
versioned_docs/version-22.10/reporting/installation.md

MBI sizing (as provided by the consulting team).

MBI sizing

---

i18n/fr/docusaurus-plugin-content-docs/version-23.04/monitoring/anomaly-detection.md
i18n/fr/docusaurus-plugin-content-docs/version-23.04/resources/known-issues.md
i18n/fr/docusaurus-plugin-content-docs/version-23.04/service-mapping/ba-management.md
versioned_docs/version-23.04/monitoring/anomaly-detection.md
versioned_docs/version-23.04/resources/known-issues.md
versioned_docs/version-23.04/service-mapping/ba-management.md

AD services in BAM (23.04)

---

i18n/fr/docusaurus-plugin-content-docs/version-23.04/getting-started/autodisco-aws.md
i18n/fr/docusaurus-plugin-content-docs/version-23.04/getting-started/monitor-cisco-router-with-snmp.md
i18n/fr/docusaurus-plugin-content-docs/version-23.04/getting-started/monitor-linux-server-with-snmp.md
i18n/fr/docusaurus-plugin-content-docs/version-23.04/getting-started/monitor-windows-server-with-snmp.md
i18n/fr/docusaurus-plugin-content-docs/version-23.04/getting-started/mysql_tuto.md
versioned_docs/version-23.04/getting-started/autodisco-aws.md
versioned_docs/version-23.04/getting-started/monitor-cisco-router-with-snmp.md
versioned_docs/version-23.04/getting-started/monitor-linux-server-with-snmp.md
versioned_docs/version-23.04/getting-started/monitor-windows-server-with-snmp.md
versioned_docs/version-23.04/getting-started/mysql_tuto.md

Adapt getting started topics to OS - 23.04

Adapt getting started topics to OS - 23.04

---

i18n/fr/docusaurus-plugin-content-docs/version-23.04/graph-views/upgrade.md

Fix PR 2228

---

i18n/fr/docusaurus-plugin-content-docs/version-23.04/reporting/installation.md
versioned_docs/version-23.04/reporting/installation.md

missing link or content of view_creation.sql for 23.04 (fr/en) on page https://docs.centreon.com/fr/docs/reporting/installation/

Mbi view creation

---

i18n/fr/docusaurus-plugin-content-docs/version-23.04/administration/licenses.md
i18n/fr/docusaurus-plugin-content-docs/version-23.04/getting-started/it100.md
versioned_docs/version-23.04/administration/licenses.md
versioned_docs/version-23.04/getting-started/it100.md

Add network flows info - 23.04

Add network flows info - 23.04

---

i18n/fr/docusaurus-plugin-content-docs/version-22.10/graph-views/map-web-known-issues.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/resources/known-issues.md
versioned_docs/version-22.10/graph-views/map-web-known-issues.md
versioned_docs/version-22.10/resources/known-issues.md

Add MAP Known issues for 22.10.5 release.

Add MAP Known issues for 22.10.5 release

---

i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-commercial-extensions.md
versioned_docs/version-22.10/releases/centreon-commercial-extensions.md

Prepare release notes for Centreon Modules next 22.10

doc(release): Prepare release notes for modules next 22.10

---

i18n/fr/docusaurus-plugin-content-docs/version-23.04/integrations/npm/ntopng.md
i18n/fr/docusaurus-plugin-content-docs/version-23.04/upgrade/upgrade-from-22-04.md
i18n/fr/docusaurus-plugin-content-docs/version-23.04/upgrade/upgrade-from-22-10.md
versioned_docs/version-23.04/integrations/npm/ntopng.md
versioned_docs/version-23.04/upgrade/upgrade-from-22-04.md
versioned_docs/version-23.04/upgrade/upgrade-from-22-10.md

fix debian repo

---

i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-commercial-extensions.md
i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.md
versioned_docs/version-23.04/releases/centreon-commercial-extensions.md
versioned_docs/version-23.04/releases/centreon-os.md

doc(release): Prepare release notes for version 23.04

---

i18n/fr/docusaurus-plugin-content-docs/version-23.04/developer/developer-broker-mapping.md
versioned_docs/version-23.04/developer/developer-broker-bbdo.md
versioned_docs/version-23.04/developer/developer-broker-mapping.md
yarn.lock

Update Broker event mapping (23.04)

Update Broker event mapping (23.04)

---

i18n/fr/docusaurus-plugin-content-docs/version-21.10/administration/licenses.md
i18n/fr/docusaurus-plugin-content-docs/version-21.10/getting-started/it100.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/administration/licenses.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/getting-started/it100.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/administration/licenses.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/getting-started/it100.md
versioned_docs/version-21.10/administration/licenses.md
versioned_docs/version-21.10/getting-started/it100.md
versioned_docs/version-22.04/administration/licenses.md
versioned_docs/version-22.04/getting-started/it100.md
versioned_docs/version-22.10/administration/licenses.md
versioned_docs/version-22.10/getting-started/it100.md

Add network flows info for online license

Add network flows info for online license

---

i18n/fr/docusaurus-plugin-content-docs-cloud/current/resources/glossary.md
i18n/fr/docusaurus-plugin-content-docs/version-23.04/resources/glossary.md
versioned_docs/version-23.04/resources/glossary.md

Move monitoring connectors definition in glossary

Move monitoring connectors definition in glossary

---

i18n/fr/docusaurus-plugin-content-docs/version-21.10/monitoring/anomaly-detection.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/monitoring/anomaly-detection.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/monitoring/anomaly-detection.md
i18n/fr/docusaurus-plugin-content-docs/version-23.04/monitoring/anomaly-detection.md
versioned_docs/version-21.10/monitoring/anomaly-detection.md
versioned_docs/version-22.04/monitoring/anomaly-detection.md
versioned_docs/version-22.10/monitoring/anomaly-detection.md
versioned_docs/version-23.04/monitoring/anomaly-detection.md

Remove "beta" from AD doc

---

versioned_docs/version-23.04/releases/introduction.md

Fix version number

---

i18n/fr/docusaurus-plugin-content-docs/version-22.10/api/rest-api-v2.md
i18n/fr/docusaurus-plugin-content-docs/version-23.04/api/rest-api-v2.md
versioned_docs/version-22.10/api/rest-api-v2.md
versioned_docs/version-23.04/api/rest-api-v2.md

Update link to Rest API v2

---

i18n/fr/docusaurus-plugin-content-docs/version-23.04/graph-views/install.md
versioned_docs/version-23.04/graph-views/install.md

MON-18845 update map desktop download link

MON-18845 update map desktop download link

---

i18n/fr/docusaurus-plugin-content-docs/version-22.10/installation/installation-of-a-central-server/using-virtual-machines.md
i18n/fr/docusaurus-plugin-content-docs/version-23.04/installation/installation-of-a-central-server/using-virtual-machines.md
versioned_docs/version-22.10/installation/installation-of-a-central-server/using-virtual-machines.md
versioned_docs/version-23.04/installation/installation-of-a-central-server/using-virtual-machines.md

Update password for VM install

Update password for VM install

---

cloud/alerts-notifications/resources-status.md
i18n/fr/docusaurus-plugin-content-docs-cloud/current/alerts-notifications/resources-status.md

Add Check/Forced check feature - Cloud

Add Check/Forced check feature - Cloud

---

i18n/fr/docusaurus-plugin-content-docs/version-23.10/graph-views/install.md
i18n/fr/docusaurus-plugin-content-docs/version-23.10/graph-views/map-web-install.md
versioned_docs/version-23.10/graph-views/install.md
versioned_docs/version-23.10/graph-views/map-web-install.md

Add custom URI in MAP configuration file - 23.10

Add custom URI in MAP configuration file - 23.10

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-microsoft-office365-skype.md
i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-outscale.md
pp/integrations/plugin-packs/procedures/cloud-outscale.md
pp/sidebarsPp.js

add(epp): outscale

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-keysight-nvos-restapi.md
pp/integrations/plugin-packs/procedures/network-keysight-nvos-restapi.md
pp/sidebarsPp.js

Add Keysight NVOS API Pack

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/releases/release-notes.md
pp/integrations/plugin-packs/releases/release-notes.md

rn(mc): new monitoring connectors release

---

i18n/fr/docusaurus-plugin-content-docs/version-23.10/alerts-notifications/notif-flapping.md
i18n/fr/docusaurus-plugin-content-docs/version-23.10/monitoring/event-handler.md

Report PR #2267 to 23.10 version

Report PR #2267 to 23.10 version

---

versioned_docs/version-23.10/releases/introduction.md

Report PR #2269 to 23.10

---

i18n/fr/docusaurus-plugin-content-pages/index.js
src/pages/index.js

Report PR #2264 to 23.10

---

src/theme/NavbarItem/DocsVersionDropdownNavbarItem.js

do not display dropdown on pp and cloud doc

chore(ui): do not display dropdown on pp and cloud doc

---

i18n/fr/docusaurus-plugin-content-docs/version-23.10/developer/developer-translate-centreon.md
versioned_docs/version-23.10/developer/developer-translate-centreon.md

Update instructions to translate Centreon (next)

---

i18n/fr/docusaurus-plugin-content-docs/version-21.04/developer/developer-translate-centreon.md
i18n/fr/docusaurus-plugin-content-docs/version-21.10/developer/developer-translate-centreon.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/developer/developer-translate-centreon.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/developer/developer-translate-centreon.md
i18n/fr/docusaurus-plugin-content-docs/version-23.04/developer/developer-translate-centreon.md
versioned_docs/version-21.04/developer/developer-translate-centreon.md
versioned_docs/version-21.10/developer/developer-translate-centreon.md
versioned_docs/version-22.04/developer/developer-translate-centreon.md
versioned_docs/version-22.10/developer/developer-translate-centreon.md
versioned_docs/version-23.04/developer/developer-translate-centreon.md

Update instructions to translate Centreon

Update instructions to translate Centreon

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/graph-views/import-into-map-web.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/graph-views/import-into-map-web.md
i18n/fr/docusaurus-plugin-content-docs/version-23.04/graph-views/import-into-map-web.md

Fix MAP command in FR version

---

i18n/fr/docusaurus-plugin-content-docs/version-23.10/graph-views/import-into-map-web.md

Fix MAP command in FR version - 23.10

Fix MAP command in FR version - 23.10

---

i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.md
versioned_docs/version-23.04/releases/centreon-os.md

* Centreon Web 23.04.1
* Centreon Gorgone 23.04.1

chore(release): prepare release notes for OSS hotfix 23.04

---

i18n/fr/docusaurus-plugin-content-docs/version-23.10/installation/installation-of-a-central-server/using-virtual-machines.md

Report PR #2268 to 23.10

---

i18n/fr/docusaurus-plugin-content-docs/version-23.10/resources/glossary.md
versioned_docs/version-23.10/resources/glossary.md

Report #2260 to 23.10

---

i18n/fr/docusaurus-plugin-content-docs/version-23.10/monitoring/anomaly-detection.md
versioned_docs/version-23.10/monitoring/anomaly-detection.md

Report PR #2265 to 23.10

---

i18n/fr/docusaurus-plugin-content-docs/version-23.10/installation/installation-of-a-central-server/using-virtual-machines.md
versioned_docs/version-23.10/installation/installation-of-a-central-server/using-virtual-machines.md

Update PR 2308

---

i18n/fr/docusaurus-plugin-content-docs/version-23.10/api/rest-api-v2.md
versioned_docs/version-23.10/api/rest-api-v2.md

Report PR #2263 to 23.10

---

i18n/fr/docusaurus-plugin-content-docs/version-21.10/releases/centreon-commercial-extensions.md
versioned_docs/version-21.10/releases/centreon-commercial-extensions.md

* Centreon BAM 21.10.3
* Centreon MBI 21.10.3
* Centreon Autodiscovery 21.10.4

chore(release): prepare release notes for Modules 21.10

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/monitoring/pluginpacks.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/monitoring/pluginpacks.md
i18n/fr/docusaurus-plugin-content-docs/version-23.04/monitoring/pluginpacks.md
versioned_docs/version-22.04/monitoring/pluginpacks.md
versioned_docs/version-22.10/monitoring/pluginpacks.md
versioned_docs/version-23.04/monitoring/pluginpacks.md

Update tabs and Debian commands in Monitoring Connectors topic.

Update tabs and Debian commands in Monitoring Connectors topic

---

i18n/fr/docusaurus-plugin-content-docs/version-23.10/monitoring/pluginpacks.md
versioned_docs/version-23.10/monitoring/pluginpacks.md

Update tabs and Debian commands in Monitoring Connectors topic - 23.10

Update tabs and Debian commands in Monitoring Connectors topic - 23.10

---

i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
versioned_docs/version-22.10/releases/centreon-os.md

chore(release): prepare release notes for OSS 22.10

---

i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-commercial-extensions.md
versioned_docs/version-22.10/releases/centreon-commercial-extensions.md

chore(release): prepare release notes for Modules 22.10

---

i18n/fr/docusaurus-plugin-content-docs/version-23.10/monitoring/basic-objects/hosts-switch-poller.md
versioned_docs/version-23.10/monitoring/basic-objects/hosts-switch-poller.md
versioned_sidebars/version-23.10-sidebars.json

MON-16437-move-hosts (next 23.10)

MON-16437-move-hosts (next 23.10)

---

i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.md
versioned_docs/version-23.04/releases/centreon-os.md

chore(release): prepare release notes for OSS 23.04

---

i18n/fr/docusaurus-plugin-content-docs/version-21.10/administration/secure-platform.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/administration/secure-platform.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/administration/secure-platform.md
i18n/fr/docusaurus-plugin-content-docs/version-23.04/administration/secure-platform.md
versioned_docs/version-21.10/administration/secure-platform.md
versioned_docs/version-22.04/administration/secure-platform.md
versioned_docs/version-22.10/administration/secure-platform.md
versioned_docs/version-23.04/administration/secure-platform.md

Update firewall rules for poller

Update firewall rules for poller

---

i18n/fr/docusaurus-plugin-content-docs/version-23.10/administration/secure-platform.md
versioned_docs/version-23.10/administration/secure-platform.md

Update firewall rules for poller - next

Update firewall rules for poller - next

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
versioned_docs/version-22.04/releases/centreon-core.md
versioned_docs/version-22.10/releases/centreon-os.md

chore(release): prepare release notes for OSS 22.04

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/getting-started/how-to-guides/windows-winrm-wsman-tutorial.md
pp/integrations/plugin-packs/getting-started/how-to-guides/windows-winrm-wsman-tutorial.md

Proofread WSMAN topic

---

i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
versioned_docs/version-22.10/releases/centreon-os.md

chore(release): prepare release notes for collect 2210

---

i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-commercial-extensions.md
versioned_docs/version-23.04/releases/centreon-commercial-extensions.md

Release notes for modules:
* Centreon BAM 23.04.1
* Centreon ANOMALY DETECTION 23.04.1

chore(release): prepare release notes for modules 2304

---

i18n/fr/docusaurus-plugin-content-docs/version-21.10/monitoring/anomaly-detection.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/monitoring/anomaly-detection.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/monitoring/anomaly-detection.md
i18n/fr/docusaurus-plugin-content-docs/version-23.04/monitoring/anomaly-detection.md
versioned_docs/version-21.10/monitoring/anomaly-detection.md
versioned_docs/version-22.04/monitoring/anomaly-detection.md
versioned_docs/version-22.10/monitoring/anomaly-detection.md
versioned_docs/version-23.04/monitoring/anomaly-detection.md

Update AD prerequisites

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-commercial-extensions.md
i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-commercial-extensions.md
versioned_docs/version-22.04/releases/centreon-commercial-extensions.md
versioned_docs/version-23.04/releases/centreon-commercial-extensions.md

Fix title level

---

i18n/fr/docusaurus-plugin-content-docs/version-23.10/monitoring/anomaly-detection.md
versioned_docs/version-23.10/monitoring/anomaly-detection.md

Update AD prerequisites - next
staging here: https://github.com/centreon/centreon-documentation/pull/2368

Update AD prerequisites - next

---

i18n/fr/docusaurus-plugin-content-docs/version-23.04/upgrade/upgrade-from-22-04.md
i18n/fr/docusaurus-plugin-content-docs/version-23.04/upgrade/upgrade-from-22-10.md
versioned_docs/version-23.04/upgrade/upgrade-from-22-04.md
versioned_docs/version-23.04/upgrade/upgrade-from-22-10.md

Fix command for el8 (upgrade procedure)

Fix command for el8 (upgrade procedure)

---

i18n/fr/docusaurus-plugin-content-docs/version-23.10/upgrade/upgrade-from-22-04.md
i18n/fr/docusaurus-plugin-content-docs/version-23.10/upgrade/upgrade-from-22-10.md
versioned_docs/version-23.10/upgrade/upgrade-from-22-04.md
versioned_docs/version-23.10/upgrade/upgrade-from-22-10.md

Fix command for el8 (upgrade procedure) - next

Fix command for el8 (upgrade procedure) - next

---

versioned_docs/version-22.04/reporting/installation.md
versioned_docs/version-22.10/reporting/installation.md
versioned_docs/version-23.04/reporting/installation.md

best-practices-of-monitoring -> best-practices-for-monitoring

update(doc) best practices url

---

i18n/fr/docusaurus-plugin-content-docs/version-23.10/monitoring/event-handler.md
versioned_docs/version-23.10/monitoring/event-handler.md

Fix typo - next

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-commercial-extensions.md
versioned_docs/version-22.04/releases/centreon-commercial-extensions.md

Release notes for
* Centreon MAP 22.04.7
* Centreon MBI 22.04.4

doc(release): prepare release notes for modules 2204

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/graph-views/map-web-known-issues.md
versioned_docs/version-22.04/graph-views/map-web-known-issues.md

Update known issues - MAP 22.04.7

Update known issues - MAP 22.04.7

---

i18n/fr/docusaurus-plugin-content-docs/version-21.10/releases/centreon-core.md
versioned_docs/version-21.10/releases/centreon-core.md

doc(release): prepare release notes for oss 2110

---

i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
versioned_docs/version-22.10/releases/centreon-os.md

doc(release): prepare release notes for oss 2210

---

i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.md
versioned_docs/version-23.04/releases/centreon-os.md

Release notes for 
* WEB 23.04.3

doc(release): prepare release notes for oss 2304

---

i18n/fr/docusaurus-plugin-content-docs/version-21.10/releases/centreon-core.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.md
versioned_docs/version-21.10/releases/centreon-core.md
versioned_docs/version-22.04/releases/centreon-core.md
versioned_docs/version-22.10/releases/centreon-os.md
versioned_docs/version-23.04/releases/centreon-os.md

Fix bullet point in RNs

---

i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.md
versioned_docs/version-23.04/releases/centreon-os.md

doc(release): prepare release note for oss 2304

---

i18n/fr/docusaurus-plugin-content-docs/version-22.10/administration/secure-platform.md
i18n/fr/docusaurus-plugin-content-docs/version-23.04/administration/secure-platform.md
versioned_docs/version-22.10/administration/secure-platform.md
versioned_docs/version-23.04/administration/secure-platform.md

Secure gorgone HTTP API

---

versioned_docs/version-23.04/upgrade/upgrade-from-22-10.md

Fix typo -staging

---

versioned_docs/version-23.10/getting-started/actions.md
versioned_docs/version-23.10/getting-started/analyze-resources-availability.md
versioned_docs/version-23.10/getting-started/autodisco-aws.md
versioned_docs/version-23.10/getting-started/concepts.md
versioned_docs/version-23.10/getting-started/create-custom-view.md
versioned_docs/version-23.10/getting-started/create-graphical-view.md
versioned_docs/version-23.10/getting-started/first-supervision.md
versioned_docs/version-23.10/getting-started/installation-first-steps.md
versioned_docs/version-23.10/getting-started/interface.md
versioned_docs/version-23.10/getting-started/it100.md
versioned_docs/version-23.10/getting-started/model-it-services.md
versioned_docs/version-23.10/getting-started/monitor-cisco-router-with-snmp.md
versioned_docs/version-23.10/getting-started/monitor-printer-with-snmp.md
versioned_docs/version-23.10/getting-started/monitor-ups-with-snmp.md
versioned_docs/version-23.10/getting-started/monitor-windows-server-with-snmp.md
versioned_docs/version-23.10/getting-started/mysql_tuto.md
versioned_docs/version-23.10/getting-started/platform.md
versioned_docs/version-23.10/getting-started/welcome.md

Proofread getting started chapter.

Proofread getting started chapter

---

i18n/fr/docusaurus-plugin-content-docs/version-23.10/administration/secure-platform.md
versioned_docs/version-23.10/administration/secure-platform.md

Secure gorgone HTTP API - next 23.10

Secure gorgone HTTP API - next 23.10

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/graph-views/map-web-install.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/graph-views/map-web-install.md
i18n/fr/docusaurus-plugin-content-docs/version-23.04/graph-views/map-web-install.md
versioned_docs/version-22.04/graph-views/map-web-install.md
versioned_docs/version-22.10/graph-views/map-web-install.md
versioned_docs/version-23.04/graph-views/map-web-install.md

Enhance procedure to install Centreon MAP

Mon 17863 enh 22 04 centreon map installation

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-graylog-restapi.md
pp/integrations/plugin-packs/procedures/applications-graylog-restapi.md

Fixed a dead link and a spelling mistake

fix dead link and mistake

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/resources/glossary.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/resources/glossary.md
i18n/fr/docusaurus-plugin-content-docs/version-23.04/resources/glossary.md
versioned_docs/version-22.04/resources/glossary.md
versioned_docs/version-22.10/resources/glossary.md
versioned_docs/version-23.04/resources/glossary.md

update url for graph (en)
add url for graph (fr)

update(doc) graph url

---

i18n/fr/docusaurus-plugin-content-docs/version-23.10/installation/installation-of-centreon-ha/installation-2-nodes.md
i18n/fr/docusaurus-plugin-content-docs/version-23.10/installation/installation-of-centreon-ha/installation-4-nodes.md
i18n/fr/docusaurus-plugin-content-docs/version-23.10/upgrade/centreon-ha/upgrade-from-21-04.md
i18n/fr/docusaurus-plugin-content-docs/version-23.10/upgrade/centreon-ha/upgrade-from-21-10.md
i18n/fr/docusaurus-plugin-content-docs/version-23.10/upgrade/centreon-ha/upgrade-from-22-04.md
i18n/fr/docusaurus-plugin-content-docs/version-23.10/upgrade/centreon-ha/upgrade-from-22-10.md
versioned_docs/version-23.10/installation/installation-of-centreon-ha/installation-2-nodes.md
versioned_docs/version-23.10/installation/installation-of-centreon-ha/installation-4-nodes.md
versioned_docs/version-23.10/upgrade/centreon-ha/upgrade-from-21-04.md
versioned_docs/version-23.10/upgrade/centreon-ha/upgrade-from-21-10.md
versioned_docs/version-23.10/upgrade/centreon-ha/upgrade-from-22-04.md
versioned_docs/version-23.10/upgrade/centreon-ha/upgrade-from-22-10.md

MON-19101-cron-ha (next, 23.10)

MON-19101-cron-ha (next, 23.10)

---

cloud/alerts-notifications/acknowledge.md
cloud/alerts-notifications/concepts.md
cloud/alerts-notifications/manage-alerts.md
cloud/alerts-notifications/resources-status.md
cloud/getting-started/concepts.md
cloud/getting-started/create-custom-view.md
cloud/resources/glossary.md
i18n/fr/docusaurus-plugin-content-docs-cloud/current/alerts-notifications/acknowledge.md
i18n/fr/docusaurus-plugin-content-docs-cloud/current/alerts-notifications/concepts.md
i18n/fr/docusaurus-plugin-content-docs-cloud/current/alerts-notifications/manage-alerts.md
i18n/fr/docusaurus-plugin-content-docs-cloud/current/alerts-notifications/resources-status.md
i18n/fr/docusaurus-plugin-content-docs-cloud/current/getting-started/concepts.md
i18n/fr/docusaurus-plugin-content-docs-cloud/current/getting-started/create-custom-view.md
i18n/fr/docusaurus-plugin-content-docs-cloud/current/resources/glossary.md
versioned_docs/version-22.04/alerts-notifications/acknowledge.md
versioned_docs/version-22.10/alerts-notifications/acknowledge.md
versioned_docs/version-23.04/alerts-notifications/acknowledge.md

(Cloud) Replace problem by alert, 23.04

(Cloud) Replace problem by alert, 23.04

---

cloud/service-mapping/ba-management.md
i18n/fr/docusaurus-plugin-content-docs-cloud/current/service-mapping/ba-management.md

(Cloud) Remove section on ssv import - BAM

(Cloud) Remove section on ssv import - BAM

---

i18n/fr/docusaurus-plugin-content-docs/version-23.10/administration/secure-platform.md
versioned_docs/version-23.10/administration/secure-platform.md

Debian commands for http2 - next

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/administration/secure-platform.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/administration/secure-platform.md
i18n/fr/docusaurus-plugin-content-docs/version-23.04/administration/secure-platform.md
versioned_docs/version-22.04/administration/secure-platform.md
versioned_docs/version-22.10/administration/secure-platform.md
versioned_docs/version-23.04/administration/secure-platform.md

Debian commands for http2

---

i18n/fr/docusaurus-plugin-content-docs/version-22.10/installation/installation-of-a-central-server/using-packages.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/installation/installation-of-a-poller/using-packages.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/installation/installation-of-a-remote-server/using-packages.md
versioned_docs/version-22.10/installation/installation-of-a-central-server/using-packages.md
versioned_docs/version-22.10/installation/installation-of-a-poller/using-packages.md
versioned_docs/version-22.10/installation/installation-of-a-remote-server/using-packages.md

Add command for el8 installation

---

i18n/fr/docusaurus-plugin-content-docs/version-23.04/graph-views/map-web-install.md

Add MariaDB server install for EL9

---

i18n/fr/docusaurus-plugin-content-docs/version-23.10/reporting/available-reports.md
versioned_docs/version-23.10/reporting/available-reports.md

fix command error for saving pem file (next, 23.10)

---

i18n/fr/docusaurus-plugin-content-docs/version-23.10/reporting/installation.md
versioned_docs/version-23.10/reporting/installation.md

Add standard repo to MBI installation procedure (next, 23.10)

Add standard repo to MBI installation procedure (next, 23.10)

---

i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
versioned_docs/version-22.10/releases/centreon-os.md

doc(release): prepare release notes for collect 2210

---

versioned_docs/version-22.10/releases/centreon-os.md

fix offset in RN

---

i18n/fr/docusaurus-plugin-content-docs/version-23.10/connect/openid.md
versioned_docs/version-23.10/connect/openid.md

enh(oidc): improve groups & roles management

---

i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.md
versioned_docs/version-23.04/releases/centreon-os.md

doc(release): prepare release notes for Collect 23.04

---

i18n/fr/docusaurus-plugin-content-docs/version-23.10/graph-views/map-web-install.md
versioned_docs/version-23.10/graph-views/map-web-install.md

Update MAP installation procedure in 23.10

Update MAP installation procedure in 23.10

---

pp/sidebarsPp.js

Add ToC entry for SNMP protocol

Add ToC entry for SNMP protocol

---

i18n/fr/docusaurus-plugin-content-docs/version-23.10/api/clapi.md
versioned_docs/version-23.10/api/clapi.md

Update accepted parameters in CLAPI CENTBROKERCFG setparam

fix(clapi) update brokerConfig supported parameters in setparam

---

i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
versioned_docs/version-22.10/releases/centreon-os.md

doc(release): prepare rn for oss 22.10

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/migrate/migrate-from-el-to-debian.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/migrate/migrate-from-el-to-el.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/migrate/migrate-from-el-to-debian.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/migrate/migrate-from-el-to-el.md
i18n/fr/docusaurus-plugin-content-docs/version-23.04/migrate/migrate-from-el-to-debian.md
i18n/fr/docusaurus-plugin-content-docs/version-23.04/migrate/migrate-from-el-to-el.md
versioned_docs/version-22.04/migrate/migrate-from-el-to-debian.md
versioned_docs/version-22.04/migrate/migrate-from-el-to-el.md
versioned_docs/version-22.10/migrate/migrate-from-el-to-debian.md
versioned_docs/version-22.10/migrate/migrate-from-el-to-el.md
versioned_docs/version-23.04/migrate/migrate-from-el-to-debian.md
versioned_docs/version-23.04/migrate/migrate-from-el-to-el.md

Add info about requesting a new license when IP changes

Add info about requesting a new license when IP address changes

---

i18n/fr/docusaurus-plugin-content-docs/version-22.10/developer/developer-broker-bbdo.md
i18n/fr/docusaurus-plugin-content-docs/version-23.04/developer/developer-broker-bbdo.md
versioned_docs/version-22.10/developer/developer-broker-bbdo.md
versioned_docs/version-23.04/developer/developer-broker-bbdo.md

Warning about BBDOv2 and RS (you can't have both).

Warning about BBDOv2 and RS

---

i18n/fr/docusaurus-plugin-content-docs/version-23.04/administration/secure-platform.md
versioned_docs/version-23.04/administration/secure-platform.md

Add where to insert code in conf file

Add where to insert code in conf file

---

i18n/fr/docusaurus-plugin-content-docs/version-23.10/administration/secure-platform.md
versioned_docs/version-23.10/administration/secure-platform.md

Add where to insert code in conf file (next, 23.10)

Add where to insert code in conf file (next, 23.10)

---

i18n/fr/docusaurus-plugin-content-docs/version-23.10/developer/developer-broker-stream-connector.md
versioned_docs/version-23.10/developer/developer-broker-stream-connector.md

New Lua function to get check command.

enh(broker-developer): new lua command added: get_check_command()

---

i18n/fr/docusaurus-plugin-content-docs/version-23.04/administration/secure-platform.md
versioned_docs/version-23.04/administration/secure-platform.md

Please remove UUOC,
Although some may say that this is not important, it does not reflect well on experienced admins.

Update secure-platform.md removing UUOC

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-commercial-extensions.md
versioned_docs/version-22.04/releases/centreon-commercial-extensions.md

doc(release): prepare release notes for modules 22.04

---

i18n/fr/docusaurus-plugin-content-docs/version-23.10/administration/licenses.md
i18n/fr/docusaurus-plugin-content-docs/version-23.10/getting-started/autodisco-aws.md
i18n/fr/docusaurus-plugin-content-docs/version-23.10/integrations/digital-experience-monitoring/connector-mip.md
i18n/fr/docusaurus-plugin-content-docs/version-23.10/integrations/digital-experience-monitoring/connector-skylight-pvx.md
versioned_docs/version-23.10/administration/licenses.md
versioned_docs/version-23.10/getting-started/autodisco-aws.md
versioned_docs/version-23.10/integrations/digital-experience-monitoring/pack-skylight-pvx.md
versioned_docs/version-23.10/monitoring/pluginpacks.md

Online license first (next, 23.10)

Online license first (next, 23.10)

---

i18n/fr/docusaurus-plugin-content-docs/version-23.10/getting-started/interface.md
versioned_docs/version-23.10/getting-started/interface.md

Fix typo (next, 23.10)

---

i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-commercial-extensions.md
versioned_docs/version-23.04/releases/centreon-commercial-extensions.md

* ANOMALY DETECTION 23.04.2
* AUTODISCOVERY 23.04.1
* BAM 23.04.2
* LM 23.04.1
* PPM 23.04.1
* MAP 23.04.1
* MBI 23.04.1

doc(release): prepare release notes for modules 23.04

---

i18n/fr/docusaurus-plugin-content-docs/version-21.10/update/update-centreon-platform.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/update/update-centreon-platform.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/update/update-centreon-platform.md
i18n/fr/docusaurus-plugin-content-docs/version-23.04/update/update-centreon-platform.md
versioned_docs/version-21.10/update/update-centreon-platform.md
versioned_docs/version-22.04/update/update-centreon-platform.md
versioned_docs/version-22.10/update/update-centreon-platform.md
versioned_docs/version-23.04/update/update-centreon-platform.md

Change command to update pollers

---

i18n/fr/docusaurus-plugin-content-docs/version-23.10/update/update-centreon-platform.md
versioned_docs/version-23.10/update/update-centreon-platform.md

Change command to update pollers (next, 23.10)

---

i18n/fr/docusaurus-plugin-content-docs/version-22.10/update/update-centreon-platform.md
versioned_docs/version-22.10/update/update-centreon-platform.md

Remove obsolete info

---

i18n/fr/docusaurus-plugin-content-docs/version-22.10/installation/installation-of-a-central-server/using-packages.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/installation/installation-of-a-poller/using-packages.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/installation/installation-of-a-remote-server/using-packages.md
versioned_docs/version-22.10/installation/installation-of-a-central-server/using-packages.md
versioned_docs/version-22.10/installation/installation-of-a-poller/using-packages.md
versioned_docs/version-22.10/installation/installation-of-a-remote-server/using-packages.md

Add German translation files 22.10

---

i18n/fr/docusaurus-plugin-content-docs/version-23.10/installation/installation-of-a-remote-server/using-packages.md
versioned_docs/version-23.10/installation/installation-of-a-remote-server/using-packages.md

Clarify command (next, 23.10)

---

i18n/fr/docusaurus-plugin-content-docs/version-23.04/installation/installation-of-a-remote-server/using-packages.md
versioned_docs/version-23.04/installation/installation-of-a-remote-server/using-packages.md

Clarify command

---

i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx
versioned_docs/version-23.04/releases/centreon-os.mdx

doc(release): prepare release notes for collect 23.04.2

---

i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
versioned_docs/version-22.10/releases/centreon-os.md

doc(release): prepare release notes for collect 22.10.4

---

cloud/installation/deploy-poller.md
i18n/fr/docusaurus-plugin-content-docs-cloud/current/installation/deploy-poller.md

Correct command for each region in poller install documentation

Correct command for each region in poller install documentation

---

i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-commercial-extensions.md
versioned_docs/version-22.10/releases/centreon-commercial-extensions.md

Release notes for: 
* MAP 22.10.8
* MBI 22.10.4
* ANOMALY DETECTION 22.10.4

doc(release): prepare release notes for modules 22.10

---

i18n/fr/docusaurus-plugin-content-docs/version-23.10/reporting/concepts.md
versioned_docs/version-23.10/reporting/concepts.md

Fix snippets - next

---

i18n/fr/docusaurus-plugin-content-docs/version-23.04/reporting/concepts.md
versioned_docs/version-23.04/reporting/concepts.md

Fix snippets

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-purestorage-flasharray-v2-restapi.md
pp/integrations/plugin-packs/procedures/hardware-storage-purestorage-flasharray-v2-restapi.md

A bug has been fixed, so let's refresh the doc page.

enh(mc): refreshed PureStorage page

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-management-costs.md
pp/integrations/plugin-packs/procedures/cloud-azure-management-costs.md

enh(mc): refreshed doc page

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-ups-riello-snmp.md
pp/integrations/plugin-packs/procedures/hardware-ups-riello-snmp.md

Refreshing the connector's page

enh(mc): refreshing the doc page while the pack is updated

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-tosca-restapi.md
pp/integrations/plugin-packs/procedures/applications-tosca-restapi.md
pp/sidebarsPp.js

add(epp): applications-tosca-restapi

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-ups-apc-snmp.md
pp/integrations/plugin-packs/procedures/hardware-ups-apc-snmp.md

add(epp): hardware-ups-apc-snmp

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-monitoring-speedtest.md
pp/integrations/plugin-packs/procedures/applications-monitoring-speedtest.md

enh(epp): applications-monitoring-speedtest

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-audiocodes-snmp.md
pp/integrations/plugin-packs/procedures/network-audiocodes-snmp.md

add(epp): network-audiocodes-snmp

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-compute-functions.md
i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-web-appservice.md
pp/integrations/plugin-packs/procedures/cloud-azure-compute-functions.md
pp/integrations/plugin-packs/procedures/cloud-azure-web-appservice.md

enh(epp): azure remove privatebytes metric

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-monitoring-iplabel-newtest-restapi.md
pp/integrations/plugin-packs/procedures/applications-monitoring-iplabel-newtest-restapi.md

enh(epp): applications-monitoring-iplabel-newtest-restapi

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/releases/release-notes.md
pp/integrations/plugin-packs/releases/release-notes.md
yarn.lock

prepare(rn): new monthly connectors release

---

versioned_docs/version-23.10/graph-views/map-web-install.md

MON-17923 Remove CentOS references - next

---

i18n/fr/docusaurus-plugin-content-docs/version-21.10/service-mapping/install.md
i18n/fr/docusaurus-plugin-content-docs/version-22.04/service-mapping/install.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/service-mapping/install.md
i18n/fr/docusaurus-plugin-content-docs/version-23.04/service-mapping/install.md
versioned_docs/version-21.10/service-mapping/install.md
versioned_docs/version-22.04/service-mapping/install.md
versioned_docs/version-22.10/service-mapping/install.md
versioned_docs/version-23.04/service-mapping/install.md

Add link to SQL file

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
versioned_docs/version-22.04/releases/centreon-core.md

doc(release): prepare release notes for oss 22.04

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
versioned_docs/version-22.04/releases/centreon-core.md

RN OSS 22.04.15 - Fix headings

Fix headings

---

docusaurus.config.js

missing variable on next push trigger

fix(config): missing variable on next push trigger

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/reporting/update.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/reporting/update.md
i18n/fr/docusaurus-plugin-content-docs/version-23.04/reporting/update.md
versioned_docs/version-22.04/reporting/update.md
versioned_docs/version-22.10/reporting/update.md
versioned_docs/version-23.04/reporting/update.md

Fix Debian commands and topic headings

Fix Debian commands and topic headings

---

i18n/fr/docusaurus-plugin-content-docs/version-23.10/reporting/update.md
versioned_docs/version-23.10/reporting/update.md

Fix Debian commands and topic headings - 23.10

Fix Debian commands and topic headings - 23.10

---

i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-commercial-extensions.md
versioned_docs/version-22.10/releases/centreon-commercial-extensions.md

* MAP 22.10.10
* MBI 22.10.5
* AUTODISCOVERY 22.10.3

doc(release): Prepare release notes for MODULES 2210

---

versioned_docs/version-23.10/mobile/introduction.md

proofread mobile

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-x509.md
pp/integrations/plugin-packs/procedures/applications-protocol-x509.md
pp/sidebarsPp.js

Part of the test batch
REFS: MON-20691

MC test batch - applications protocol x509

---

.github/workflows/documentation.yml

avoid useless steps when build is not needed
Refs: MON-19765

enh(ci): avoid useless steps when build is not needed

---

i18n/fr/docusaurus-plugin-content-docs/version-23.04/api/rest-api-v2.md
versioned_docs/version-23.04/api/rest-api-v2.md

Accessing the API

---

i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx
versioned_docs/version-23.04/releases/centreon-os.mdx

doc(release): prepare release notes for oss 23.04

---

i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-commercial-extensions.md
versioned_docs/version-22.10/releases/centreon-commercial-extensions.md

Add release note for map 22.10.11

---

versioned_docs/version-23.10/metrology/chart-management.md
versioned_docs/version-23.10/metrology/chart_curves.md
versioned_docs/version-23.10/metrology/chart_template.md
versioned_docs/version-23.10/metrology/chart_virtual_metrics.md
versioned_docs/version-23.10/metrology/grafana.md

proofread performance graphs

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/operatingsystems-linux-ssh.md
pp/integrations/plugin-packs/procedures/operatingsystems-linux-ssh.md

operatingsystems-linux-ssh - updated proc new format with new services

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-devices-camera-optelecom-snmp.md
pp/integrations/plugin-packs/procedures/hardware-devices-camera-optelecom-snmp.md
pp/sidebarsPp.js

add(epp): hardware-devices-camera-optelecom-snmp

---

i18n/fr/docusaurus-plugin-content-docs/version-23.10/api/clapi.md
versioned_docs/version-23.10/api/clapi.md

Add API Tokens ACL in CLAPI documentation

Add API Tokens ACL in CLAPI documentation

---

i18n/fr/docusaurus-plugin-content-docs/version-23.10/graph-views/map-web-manage.md
versioned_docs/version-23.10/graph-views/map-web-manage.md

Add how to duplicate a map - 23.10

Add how to duplicate a map - 23.10

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/graph-views/map-web-update.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/graph-views/map-web-update.md
i18n/fr/docusaurus-plugin-content-docs/version-23.04/graph-views/map-web-update.md
versioned_docs/version-22.04/graph-views/map-web-update.md
versioned_docs/version-22.10/graph-views/map-web-update.md
versioned_docs/version-23.04/graph-views/map-web-update.md

Improve Debian commands in MAP update

Improve Debian commands in MAP update

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-loadbalancers-f5-bigip-snmp.md
pp/integrations/plugin-packs/procedures/network-loadbalancers-f5-bigip-snmp.md

add(epp): network-loadbalancers-f5-bigip-snmp

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-loadbalancers-netscaler-snmp.md
pp/integrations/plugin-packs/procedures/network-loadbalancers-netscaler-snmp.md

enh(mc): refresh netscaler doc page

---

i18n/fr/docusaurus-plugin-content-docs/version-23.10/graph-views/map-web-manage.md
versioned_docs/version-23.10/graph-views/map-web-manage.md

Add information about map status - 23.10

Add information about map status - 23.10

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/operatingsystems-linux-snmp.md
pp/integrations/plugin-packs/procedures/operatingsystems-linux-snmp.md
pp/sidebarsPp.js

operatingsystems-linux-snmp: Adding Disk IO service discovery

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-netapp-ontap-restapi.md
pp/integrations/plugin-packs/procedures/hardware-storage-netapp-ontap-restapi.md

enh(mc): refreshed Netapp Ontap Rest API pack's page

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/monitoring/anomaly-detection.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/monitoring/anomaly-detection.md
i18n/fr/docusaurus-plugin-content-docs/version-23.04/monitoring/anomaly-detection.md
versioned_docs/version-22.04/monitoring/anomaly-detection.md
versioned_docs/version-22.10/monitoring/anomaly-detection.md
versioned_docs/version-23.04/monitoring/anomaly-detection.md

Add FAQ item for Anomaly Detection

Add FAQ item for Anomaly Detection

---

i18n/fr/docusaurus-plugin-content-docs/version-23.10/monitoring/anomaly-detection.md
versioned_docs/version-23.10/monitoring/anomaly-detection.md

Add FAQ item for Anomaly Detection - next

Add FAQ item for Anomaly Detection - next

---

i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-commercial-extensions.md
versioned_docs/version-22.10/releases/centreon-commercial-extensions.md

prepare release notes for modules 22.10

---

i18n/fr/docusaurus-plugin-content-docs/version-23.10/migrate/migrate-from-el-to-debian.md
versioned_docs/version-23.10/migrate/migrate-from-el-to-debian.md

Add info about checking a parameter (migration from el to Debian) - next

---

i18n/fr/docusaurus-plugin-content-docs/version-23.04/migrate/migrate-from-el-to-debian.md
versioned_docs/version-23.04/migrate/migrate-from-el-to-debian.md

Add info about checking a parameter (migration from el to Debian)

Add info about checking a parameter (migration from el to Debian)

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/releases/release-notes.md
pp/integrations/plugin-packs/releases/release-notes.md

A new format has been used for the last release note, this PR applies it to all the previous ones.

Mon 21596 align monitoring connectors rn

---

versioned_docs/version-23.04/releases/lifecycle.md

Fix EOL date for 23.04 in EN version

---

pp/sidebarsPp.js

Corrections to sidebarsPp.js

---

versioned_docs/version-23.10/resources/contribute.md
versioned_docs/version-23.10/resources/glossary.md
versioned_docs/version-23.10/resources/known-issues.md
versioned_docs/version-23.10/resources/troubleshooting.md

proofread resources

---

i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
versioned_docs/version-22.10/releases/centreon-os.md

Mon 21668 prepare rn for oss 2210

---

i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md
versioned_docs/version-22.04/releases/centreon-core.md

Mon 21671 prepare rn for oss 2204

---

i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx
versioned_docs/version-23.04/releases/centreon-os.mdx

Fix RN OSS 23.04 alphabetical sorting

Fix RN OSS 23.04 alphabetical sorting

---

i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
versioned_docs/version-22.10/releases/centreon-os.md

doc(release): Prepare release notes for collect 22.10

---

i18n/fr/docusaurus-plugin-content-docs/version-22.10/installation/installation-of-a-central-server/using-packages.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/installation/installation-of-a-poller/using-packages.md
i18n/fr/docusaurus-plugin-content-docs/version-22.10/installation/installation-of-a-remote-server/using-packages.md
i18n/fr/docusaurus-plugin-content-docs/version-23.04/installation/installation-of-a-central-server/using-packages.md
i18n/fr/docusaurus-plugin-content-docs/version-23.04/installation/installation-of-a-poller/using-packages.md
i18n/fr/docusaurus-plugin-content-docs/version-23.04/installation/installation-of-a-remote-server/using-packages.md
versioned_docs/version-22.10/installation/installation-of-a-central-server/using-packages.md
versioned_docs/version-22.10/installation/installation-of-a-poller/using-packages.md
versioned_docs/version-22.10/installation/installation-of-a-remote-server/using-packages.md
versioned_docs/version-23.04/installation/installation-of-a-central-server/using-packages.md
versioned_docs/version-23.04/installation/installation-of-a-poller/using-packages.md
versioned_docs/version-23.04/installation/installation-of-a-remote-server/using-packages.md

Update installation procedure (--no-install-recommends).

Update installation procedure

---

i18n/fr/docusaurus-plugin-content-docs/version-23.10/installation/installation-of-a-central-server/using-packages.md
i18n/fr/docusaurus-plugin-content-docs/version-23.10/installation/installation-of-a-poller/using-packages.md
i18n/fr/docusaurus-plugin-content-docs/version-23.10/installation/installation-of-a-remote-server/using-packages.md
versioned_docs/version-23.10/installation/installation-of-a-central-server/using-packages.md
versioned_docs/version-23.10/installation/installation-of-a-poller/using-packages.md
versioned_docs/version-23.10/installation/installation-of-a-remote-server/using-packages.md

Update installation procedure - next (--no-install-recommends)

Update installation procedure - next

---

i18n/fr/docusaurus-plugin-content-docs/version-21.10/releases/centreon-commercial-extensions.md
versioned_docs/version-21.10/releases/centreon-commercial-extensions.md

doc(release): Prepare release notes for modules 21.10

---

.github/workflows/deploy-to-production.yml
.github/workflows/documentation.yml

fallback deployment to ip addresses

fix(ci): fallback deployment to ip addresses

---

.github/workflows/clean-previews.yml
.github/workflows/documentation.yml

* clean oldest previews
* fix build with lot of changes

enh(ci): clean oldest previews and fix build with lot of changes

---

versioned_docs/version-22.04/releases/centreon-commercial-extensions.md

Fix version number in RN 22.04.12

Fix version number in RN 22.04.12

---

.github/workflows/clean-previews.yml
.github/workflows/documentation.yml
versioned_docs/version-23.10/administration/access-control-lists.md

chore(ci): reduce size of preview branch

---

versioned_docs/version-23.10/getting-started/monitor-linux-server-with-snmp.md

Proofread missing file

---

.github/workflows/documentation.yml

fix trigger of next deployment

fix(ci): fix trigger of next deployment

---

versioned_docs/version-23.10/alerts-notifications/acknowledge.md
versioned_docs/version-23.10/alerts-notifications/concepts.md
versioned_docs/version-23.10/alerts-notifications/custom-views.md
versioned_docs/version-23.10/alerts-notifications/downtimes.md
versioned_docs/version-23.10/alerts-notifications/event-console.md
versioned_docs/version-23.10/alerts-notifications/event-log.md
versioned_docs/version-23.10/alerts-notifications/manage-alerts.md
versioned_docs/version-23.10/alerts-notifications/notif-advanced.md
versioned_docs/version-23.10/alerts-notifications/notif-concept.md
versioned_docs/version-23.10/alerts-notifications/notif-configuration.md
versioned_docs/version-23.10/alerts-notifications/notif-dependencies.md
versioned_docs/version-23.10/alerts-notifications/notif-escalation.md
versioned_docs/version-23.10/alerts-notifications/notif-flapping.md
versioned_docs/version-23.10/alerts-notifications/other.md
versioned_docs/version-23.10/alerts-notifications/resources-status.md
versioned_docs/version-23.10/alerts-notifications/submit.md
versioned_docs/version-23.10/alerts-notifications/ticketing-install.md
versioned_docs/version-23.10/alerts-notifications/ticketing.md

proofread events-alerts

---

.github/workflows/documentation.yml

do not build next version on staging environment

fix(ci): do not build next version on staging environment

---

i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md
versioned_docs/version-22.10/releases/centreon-os.md

Release: add rn for web 22.10.14

doc(release): Prepare release notes for oss 22.10

---

versioned_docs/version-23.10/api/clapi.md
versioned_docs/version-23.10/api/graph-views-api.md
versioned_docs/version-23.10/api/introduction.md
versioned_docs/version-23.10/api/rest-api-v1.md
versioned_docs/version-23.10/api/rest-api-v2.md
versioned_docs/version-23.10/developer/developer-broker-bbdo.md
versioned_docs/version-23.10/developer/developer-broker-mapping.md
versioned_docs/version-23.10/developer/developer-broker-stream-connector-migration.md
versioned_docs/version-23.10/developer/developer-broker-stream-connector.md
versioned_docs/version-23.10/developer/developer-gorgone-client-server-communication.md
versioned_docs/version-23.10/developer/developer-gorgone-migrate-from-centcore.md
versioned_docs/version-23.10/developer/developer-gorgone-pull-mode.md
versioned_docs/version-23.10/developer/developer-gorgone-rebound-mode.md
versioned_docs/version-23.10/developer/developer-module.md
versioned_docs/version-23.10/developer/developer-stream-connector.md
versioned_docs/version-23.10/developer/developer-translate-centreon.md
versioned_docs/version-23.10/developer/developer-widget.md

Proofread developer chapter

---

i18n/fr/docusaurus-plugin-content-docs/version-23.04/monitoring/basic-objects/customization.md
i18n/fr/docusaurus-plugin-content-docs/version-23.10/monitoring/basic-objects/customization.md
versioned_docs/version-23.04/monitoring/basic-objects/customization.md
versioned_docs/version-23.10/monitoring/basic-objects/customization.md
versioned_sidebars/version-23.04-sidebars.json
versioned_sidebars/version-23.10-sidebars.json

Only local accounts can change their password

---

i18n/fr/docusaurus-plugin-content-docs/version-23.10/security/user-data-storage/what-is-centreon-ceip.md
versioned_docs/version-23.10/security/user-data-storage/what-is-centreon-ceip.md

Display data collected by the CEIP program

Display data collected by the CEIP program

---

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-databases-mongodb.md
pp/integrations/plugin-packs/procedures/applications-databases-mongodb.md

add(epp): applications-databases-mongodb
