centreon/centreon-documentation

en/api/graph-views-api.md, fr/api/graph-views-api.md
The authentication method is now only the new one, so the doc need to be updated
=> enh(api): graph-view update authentication example

en/integrations/plugin-packs/procedures/cloud-aws-ebs.md, en/sidebars.json, fr/integrations/plugin-packs/procedures/cloud-aws-ebs.md, fr/sidebars.json
Amazon EBS monitoring procedure
=> add(epp): Amazon EBS monitoring procedure

en/api/graph-views-api.md, fr/api/graph-views-api.md
To see views created using APIs
=> enh(api): Restart needed for desktop client

en/reporting/report-development.md
The Report parameter chapter doesn't exist anymore. Remove the link
=> fix(mbi):remove non existing link

en/api/rest-api-v1.md, fr/api/restapi-v1.md
https://github.com/centreon/centreon/pull/7982
=> enh(apiv1) add child object relation

en/graph-views/install.md, en/graph-views/introduction.md, en/reporting/installation.md, en/reporting/introduction.md, en/service-mapping/install.md, en/service-mapping/introduction.md, fr/graph-views/install.md, fr/graph-views/introduction.md, fr/reporting/installation.md, fr/reporting/introduction.md, fr/service-mapping/install.md, fr/service-mapping/introduction.md
Update title so sections are known by the search engine so easier to find when you look for extension name
=> enh(business): enhance title to ease search

fr/integrations/plugin-packs/procedures/hardware-storage-purestorage-snmp.md, fr/sidebars.json
add(epp) Pure Storage monitoring procedure FR
=> add(epp) Pure Storage monitoring procedure FR

en/administration/secure-platform.md, fr/administration/secure-platform.md
Hide Apache & PHP versions in Headers
=> enh(secu): hide apache php information

en/releases/centreon-commercial-extensions.md, en/releases/centreon-core.md, fr/releases/centreon-commercial-extensions.md, fr/releases/centreon-core.md
Re-order release notes so you have the most recent one at top
=> enh(release): change RN order to improve readability

en/releases/centreon-commercial-extensions.md, fr/releases/centreon-commercial-extensions.md
To merge when release is ready
=> enh(rn): add BAM 20.04.1 release note

en/api/graph-views-api.md
Replaced user by login
Updated JSON format of Body
=> Updated Body json for API Authentication section

fr/api/graph-views-api.md
Replaced user by login
Updated JSON format of Body
=> fix(doc) Updated Authentication section

en/integrations/plugin-packs/procedures/applications-webservers-iis-nrpe.md, en/integrations/plugin-packs/procedures/applications-webservers-iis-nsclient-05-restapi.md, en/integrations/plugin-packs/procedures/applications-webservers-iis-restapi.md, en/sidebars.json, fr/integrations/plugin-packs/procedures/applications-webservers-iis-nrpe.md, fr/integrations/plugin-packs/procedures/applications-webservers-iis-nsclient-05-restapi.md, fr/integrations/plugin-packs/procedures/applications-webservers-iis-restapi.md, fr/sidebars.json
Need review for typo and global consistency
=> add(epp): MS IIS monitoring procedure

en/api/rest-api-v1.md
The Error codes part of the documentation wasn't well formatted, this PR format the array of error codes with markdown syntax.
=> Update the Error codes section

en/releases/introduction.md
correction of typos and formulation
=> fix(doc): correction of various typos

en/administration/secure-platform.md, fr/administration/secure-platform.md
=> doc(http): explain how to enable http2 on Centreon Web

en/administration/secure-platform.md, fr/administration/secure-platform.md
Reverts centreon/centreon-documentation#242
=> Revert "doc(http): explain how to enable http2 on Centreon Web"

en/administration/centreon-ha/installation-2-nodes.md, en/releases/centreon-os-extensions.md, fr/administration/centreon-ha/installation-2-nodes.md, fr/releases/centreon-os-extensions.md
centreon-ha 20.04.1 doc update and release note
=> feat(centreon-ha)prepare 20.04.1 release & minor enhancements

en/reporting/widgets.md, fr/reporting/widgets.md
=> enh(reporting): Add a note about service categories

en/integrations/plugin-packs/procedures/operatingsystems-linux-nrpe3.md, en/sidebars.json, fr/integrations/plugin-packs/procedures/operatingsystems-linux-nrpe3.md, fr/sidebars.json
This procedure is missing, so the sooner it is added to the website, the better it is.
=> add(epp): procedure was missing for Linux NRPE3 PP

en/administration/secure-platform.md, fr/administration/secure-platform.md
Refs: BAM-1012
/!\ wait releases before merge this PR (~19.10.14, ~20.04.4)
BAM & MBI need to be released with http2 bugfix too
=> doc(http): explain how to enable http2 on Centreon Web #242

en/integrations/plugin-packs/procedures/hardware-servers-hp-snmp.md
also direct links to the packages used in the command line
=> Update HP links

fr/integrations/plugin-packs/procedures/hardware-servers-hp-snmp.md
also added direct links to packages used in command line
=> Update HP broken link

en/developer/developer-broker-stream-connector.md, fr/developer/developer-broker-stream-connector.md
Streamconnector documentation updated.
=> enh(streamconnector): Documentation updated.

en/integrations/plugin-packs/procedures/hardware-devices-polycom-dma-snmp.md, en/integrations/plugin-packs/procedures/hardware-devices-polycom-hdx-snmp.md, en/sidebars.json
New monitoring procedure for Polycom devices.
FR will follow later
=> add(epp): Polycom DMA/HDX Monit Proc EN

en/installation/installation-of-a-central-server/using-centreon-iso.md, en/installation/installation-of-a-central-server/using-packages.md, en/installation/installation-of-a-central-server/using-sources.md, en/installation/installation-of-a-remote-server/using-centreon-iso.md, en/installation/installation-of-a-remote-server/using-packages.md
Let me know if the commit message needs a specific format and I will change it.
=> fix(installation): typo in web installation links

en/administration/centreon-ha/installation-2-nodes.md, fr/administration/centreon-ha/installation-2-nodes.md
Correct me if I'm wrong but I don't think sh-copy-id is valid.
=> Command should be ssh-copy-id

en/integrations/plugin-packs/procedures/hardware-devices-polycom-dma-snmp.md, fr/integrations/plugin-packs/procedures/hardware-devices-polycom-dma-snmp.md, fr/integrations/plugin-packs/procedures/hardware-devices-polycom-hdx-snmp.md
This comes in addition to https://github.com/centreon/centreon-documentation/pull/304.
Sidebars should be dealt with in a separate bulk PR as there are several monitoring procedures PRs pending that may cause conflicts.
=> add(epp): Polycom missing monit proc FR

fr/integrations/plugin-packs/procedures/operatingsystems-linux-ssh.md, fr/sidebars.json
=> add(epp): Operating system Linux SSH - FR

en/releases/centreon-commercial-extensions.md, fr/releases/centreon-commercial-extensions.md
=> release(mbi): Add 20.04.2 release note

Jenkinsfile
All in title. master will not build until this gets merged.
=> Use version-specific jobs in Jenkinsfile.

en/administration/centreon-ha/installation-2-nodes.md, fr/administration/centreon-ha/installation-2-nodes.md
- Manage RedHat & CentOS master resource creation CLI syntax
- Manage folder creation & privileges before first run
=> enh(centreon-ha) RedHat & CentOS CLI syntax / Specific folder mgmt 

en/administration/centreon-ha/monitoring-guide.md, en/sidebars.json, fr/administration/centreon-ha/monitoring-guide.md, fr/sidebars.json
WARNING: depends on the release of a new service template from
App-DB-MySQL plugin pack: MariaDB-Replication
=> enh(ha): adding the centreon-ha monitoring guide

en/installation/installation-of-a-central-server/using-packages.md, en/installation/installation-of-a-remote-server/using-packages.md, fr/installation/installation-of-a-central-server/using-packages.md, fr/installation/installation-of-a-remote-server/using-packages.md
=> enh(install): add widgets install when using remote database

en/reporting/available-reports.md, fr/reporting/available-reports.md
Add the procedure to load/update the trusted certificates database for the graph reports (look for curl in diff).
The rest is just linting.
=> enh(reporting): add certificat update procedure for graph reports

en/integrations/plugin-packs/procedures/network-dell-os10-snmp.md, en/sidebars.json
=> new(mp) : New Dell OS10 SNMP Monitoring Procedure [EN]

fr/integrations/plugin-packs/procedures/network-dell-os10-snmp.md, fr/sidebars.json
=> new(mp) : New Dell OS10 SNMP Monitoring Procedure [FR]

en/releases/centreon-core.md, fr/releases/centreon-core.md
Gorgone 20.04.6 release notes.
=> release(gorgone): prepare 20.04.6 release notes

en/installation/installation-of-a-central-server/using-packages.md, fr/installation/installation-of-a-central-server/using-packages.md
The goal of this PR is to get rid of this stale PR: https://github.com/centreon/centreon-documentation/pull/226 . 
It provides more details on how to setup an optimized MariaDB configuration.
=> enh(setup) add full mariadb config

en/integrations/plugin-packs/procedures/network-dlink-standard-snmp.md, fr/integrations/plugin-packs/procedures/network-dlink-standard-snmp.md
=> update(procedure): dlink standard snmp

en/integrations/plugin-packs/procedures/applications-google-gsuite-api.md, en/sidebars.json, fr/integrations/plugin-packs/procedures/applications-google-gsuite-api.md, fr/sidebars.json
=> add(epp): Google Gsuite monit proc

en/integrations/plugin-packs/procedures/applications-databases-elasticsearch.md, fr/integrations/plugin-packs/procedures/applications-databases-elasticsearch.md
git push --set-upstream origin monic-315
=> enh(epp) elasticsearch monitoring proc v2

en/installation/installation-of-a-remote-server/using-centreon-iso.md, en/installation/installation-of-a-remote-server/using-packages.md, fr/installation/installation-of-a-remote-server/using-centreon-iso.md, fr/installation/installation-of-a-remote-server/using-packages.md
Add a note about autodiscovery module on remote server.
=> enh(install): add a note about autodiscovery module on remote server

en/releases/centreon-os-extensions.md, fr/releases/centreon-os-extensions.md
Prepare release notes for OS extensions.
=> release(os-extensions): prepare release notes

website/static/js/versions-select.js
=> fix(ui): fix version select to manage current version

en/releases/centreon-core.md, fr/releases/centreon-core.md
Add known behaviour for remote server export/import process using SSH.
Also remove useless note.
=> enh(release): add known behaviour for remote server export

en/integrations/plugin-packs/procedures/applications-sccm-nsclient.md, fr/integrations/plugin-packs/procedures/applications-sccm-nsclient.md
Waiting for more info on the outputs
=> enh(mp) Migrate Microsoft SCCM Monitoring Procedure to v2

fr/integrations/plugin-packs/procedures/virtualization-vmware2-esx.md, fr/integrations/plugin-packs/procedures/virtualization-vmware2-vcenter-5.md, fr/integrations/plugin-packs/procedures/virtualization-vmware2-vcenter-6.md, fr/integrations/plugin-packs/procedures/virtualization-vmware2-vcenter-generic.md, fr/integrations/plugin-packs/procedures/virtualization-vmware2-vm.md
Refacto of the VMWare monitoring procedure in v2.
We can close the #315
=> (enh): refacto vmware FR monitoring procedure

en/integrations/plugin-packs/procedures/virtualization-vmware2-esx.md, en/integrations/plugin-packs/procedures/virtualization-vmware2-vcenter-generic.md, en/integrations/plugin-packs/procedures/virtualization-vmware2-vm.md
Refacto of the VMWare monitoring procedure in v2.
We can close the #316 and #318
=> (enh): refacto vmware EN monitoring procedure

en/administration/centreon-ha/installation-4-nodes.md
Fix page title & id (2 nodes is not available anymore ...).
=> fix(ha) wrong header resulting in wrong link

en/releases/centreon-core.md, fr/releases/centreon-core.md
Prepare Broker 20.04.9 release notes.
=> release(broker): prepare 20.04.9 release notes

en/releases/centreon-commercial-extensions.md, fr/releases/centreon-commercial-extensions.md
Prepare Autodiscovery 20.10.1 release notes
=> release(autodiscovery): prepare 20.10.1 release notes

en/releases/centreon-core.md, fr/releases/centreon-core.md
=> release(web): Centreon Web 20.04.6 RN

en/releases/centreon-commercial-extensions.md, fr/releases/centreon-commercial-extensions.md
=> release(mbi): Add 20.04.3 release note

en/releases/centreon-commercial-extensions.md, fr/releases/centreon-commercial-extensions.md
Prepare BAM 20.04.4 release notes
=> enh(release): prepare bam 20.04.4 release notes

en/releases/centreon-core.md, fr/releases/centreon-core.md
=> fix(release): wrong heading level

en/integrations/plugin-packs/procedures/hardware-devices-cisco-cts-snmp.md, en/integrations/plugin-packs/procedures/hardware-pdu-cyberpower-snmp.md, en/sidebars.json, fr/integrations/plugin-packs/procedures/hardware-devices-cisco-cts-snmp.md, fr/integrations/plugin-packs/procedures/hardware-pdu-cyberpower-snmp.md, fr/sidebars.json
New Cisco CTS and CyberPower PDU Systems Packs and monitoring procedure
=> add(epp)cisco-cts-and-cyberpower-proc

en/integrations/plugin-packs/procedures/applications-graylog-restapi.md, en/sidebars.json, fr/integrations/plugin-packs/procedures/applications-graylog-restapi.md, fr/sidebars.json
Monitoring procedure for the new pack Graylog-RestApi
- [X ] 20.04.x
- [ X] 20.10.x (master)
=> add(epp): Graylog monitoring procedure

en/integrations/plugin-packs/procedures/cloud-aws-ses.md, en/sidebars.json, fr/integrations/plugin-packs/procedures/cloud-aws-ses.md, fr/sidebars.json
Monitoring procedure for the new pack Aws-Ses
=> add(epp): Aws Ses monitoring procedure

en/integrations/plugin-packs/procedures/applications-monitoring-alyvix-restapi.md, en/sidebars.json, fr/integrations/plugin-packs/procedures/applications-monitoring-alyvix-restapi.md, fr/sidebars.json
=> add(epp): Alyvix Server monitoring procedure

en/administration/secure-platform.md, fr/administration/secure-platform.md
=> enh(security): improve Apache security

en/releases/centreon-commercial-extensions.md
20.04.5 release note /en
- [x ] 20.04.x
=> BAM 20.04.5 release note /en

fr/releases/centreon-commercial-extensions.md
BAM 20.04.5 release note in french.
=> BAM 20.40.5 release note /fr

en/releases/centreon-commercial-extensions.md
=> MAP 20.04.4 Release Note /en

fr/releases/centreon-commercial-extensions.md
=> MAP 20.04.4 Release Note /fr

en/integrations/plugin-packs/procedures/network-cisco-firepower-snmp.md, en/sidebars.json, fr/integrations/plugin-packs/procedures/network-cisco-firepower-snmp.md, fr/sidebars.json
Cisco Firepower SNMP Monitoring procedure
=> add(epp): cisco firepower snmp

en/releases/centreon-core.md, fr/releases/centreon-core.md
=> enh(release): Add Centreon Web 20.04.7 release notes

en/releases/centreon-commercial-extensions.md, fr/releases/centreon-commercial-extensions.md
Prepare Autodiscovery 20.04.6 release notes
=> release(autodiscovery): prepare 20.04.6 release notes

.gitignore, en/releases/centreon-commercial-extensions.md, fr/releases/centreon-commercial-extensions.md
=> Rn map 20 10 1

en/releases/centreon-core.md, fr/releases/centreon-core.md
Prepare gorgone 20.04.7 release notes
=> enh(release): prepare gorgone 20.04.7 release notes

en/releases/centreon-core.md, fr/releases/centreon-core.md
Centreon Web 20.10.1 release notes
=> enh(release): Add Centreon Web 20.10.1 Release Notes

en/releases/centreon-core.md, fr/releases/centreon-core.md
Prepare Broker 20.10.1 release notes
=> enh(release): prepare broker 20.10.1 release notes

en/releases/centreon-core.md, fr/releases/centreon-core.md
Prepare broker 20.04.10 release notes
=> enh(release): prepare broker 20.04.10 release notes

en/releases/centreon-commercial-extensions.md, fr/releases/centreon-commercial-extensions.md
=> enh(release): Add Anomaly Detection 20.04.4 Release Notes

en/releases/centreon-commercial-extensions.md, fr/releases/centreon-commercial-extensions.md
Add Centreon LM 20.04.3 & 20.04.2 releases notes
=> enh(release): Add Centreon LM 20.04.3 & .2 release notes

en/releases/centreon-commercial-extensions.md, fr/releases/centreon-commercial-extensions.md
=> fix(release): move LM release note to correct part

en/installation/introduction.md, fr/installation/introduction.md
Set the correct stable version (for documentation) so as not to generate errors in the installation.
=> set version in url git raw

en/installation/introduction.md, fr/installation/introduction.md
missing words, spaces, also cound not understand one line in english
=> doc: small typos fixed

fr/integrations/plugin-packs/procedures/applications-sccm-nsclient.md
=> enh(epp): SCCM plugin needs the sccm admin console

en/releases/centreon-commercial-extensions.md, fr/releases/centreon-commercial-extensions.md
Prepare Autodiscovery 20.10.2 release notes
=> enh(release): prepare autodiscovery 20.10.2 release notes

en/releases/centreon-commercial-extensions.md, fr/releases/centreon-commercial-extensions.md
Prepare Autodiscovery 20.04.7 release notes
=> enh(release): prepare autodiscovery 20.04.7 release notes

en/integrations/plugin-packs/procedures/applications-rubrik-restapi.md, en/sidebars.json, fr/integrations/plugin-packs/procedures/applications-rubrik-restapi.md, fr/sidebars.json
Add Rubrik Rest API monitoring procedure
=> add(epp) rubrik-restapi-monitoring-proc

en/integrations/plugin-packs/procedures/cloud-aws-ses.md, fr/integrations/plugin-packs/procedures/cloud-aws-ses.md
=> fix(epp): AWS SES monitoring proc typo

en/integrations/plugin-packs/procedures/network-fortinet-fortiauthenticator-snmp.md, en/sidebars.json, fr/integrations/plugin-packs/procedures/network-fortinet-fortiauthenticator-snmp.md, fr/sidebars.json
Monitoring procedure for Fortinet FortiAuthenticator SNMP Plugin-Pack
=> add(epp): FortiAuthenticator monitoring procedure

en/integrations/plugin-packs/procedures/applications-databases-rrdtool.md, en/sidebars.json, fr/integrations/plugin-packs/procedures/applications-databases-rrdtool.md, fr/sidebars.json
=> add(epp): databases rrdtool

en/integrations/plugin-packs/procedures/applications-databases-oracle.md, fr/integrations/plugin-packs/procedures/applications-databases-oracle.md
* odd markdown format
* uncopiable commands
* unnoticeable notices
* missing RPMs
=> enh(epp): improve oracle procedure

en/integrations/plugin-packs/procedures/applications-cisco-dnac-restapi.md, en/sidebars.json, fr/integrations/plugin-packs/procedures/applications-cisco-dnac-api.md, fr/sidebars.json
=> add(epp): cisco dnac rest api

en/integrations/plugin-packs/procedures/network-cisco-firepower-fmc-restapi.md, en/sidebars.json, fr/integrations/plugin-packs/procedures/network-cisco-firepower-fmc-restapi.md, fr/sidebars.json
=> add(epp): cisco firepower fmc rest api

en/integrations/plugin-packs/procedures/applications-protocol-dns.md
This is an update of the monitoring procedure for the Plugin-Pack DNS Service
=> monitoring procedure dns service

en/integrations/plugin-packs/procedures/cloud-aws-vpn.md, fr/integrations/plugin-packs/procedures/cloud-aws-vpn.md
Several fixes and enhancements following the Plugin & EPP modifications
=> enh(epp): rework AWS VPN monit proc

en/api/clapi.md, fr/api/clapi.md
Based on PR #167 with adding FR part from copy of EN part.
=> enh(apiv1): Add Getparam for objects

en/releases/centreon-core.md, fr/releases/centreon-core.md
Prepare Broker 20.10.2 release notes
=> enh(release): prepare broker 20.10.2 release notes

fr/reporting/widgets.md
Correct misspelling in french documentation
=> fix(typo): correct widgets.md

en/releases/centreon-core.md, fr/releases/centreon-core.md
Prepare Engine 20.04.8 release notes
=> enh(release): prepare engine 20.04.8 release notes

en/releases/centreon-commercial-extensions.md, fr/releases/centreon-commercial-extensions.md
=> Release notes map 20.10.2

en/releases/centreon-core.md, fr/releases/centreon-core.md
Prepare Engine 20.10.1 release notes
=> enh(release): prepare engine 20.10.1 release notes

en/releases/centreon-core.md, fr/releases/centreon-core.md
Prepare Broker 20.04.11 release notes
=> enh(release): prepare broker 20.04.11 release notes

en/releases/centreon-core.md, fr/releases/centreon-core.md
Prepare Gorgone 20.10.1 release notes
=> enh(release): prepare gorgone 20.10.1 release notes

en/releases/centreon-core.md, fr/releases/centreon-core.md
Prepare Gorgone 20.04.8 release notes
=> enh(release): prepare gorgone 20.04.8 release notes

fr/graph-views/install.md
=> [FR] [20.04] Add link for .rpm

en/graph-views/install.md
=> [EN] [20.04] Add link for .rpm

en/service-mapping/install.md
Add link repository BAM for version 20.10.
Add link repository BAM for version 20.10.
- [ x] 20.10.x (master)
=> [EN] Add link repository BAM for version 20.10.md

fr/service-mapping/install.md
Add link repository BAM for version 20.10
=> [FR] Add link repository BAM for version 20.10

fr/reporting/installation.md
Add link repository for MBI 20.04 & 20.10
=> [FR] Add link repository for MBI 20.10

en/reporting/installation.md
Add link repository for MBI 20.04 & 20.10
=> [EN] Add link repository for MBI 20.10

en/graph-views/install.md
=> [EN] [20.10] Add link for .rpm

fr/graph-views/install.md
=> [FR] [20.10] Add link for .rpm

en/reporting/installation.md
Add link repository for MBI 20.04 in section "Install the extension on Centreon"
=> [EN] Add link repository MBI 20.04

fr/reporting/installation.md
Add link repository for MBI 20.04 in section "Installer l'extension sur Centreon"
=> [FR] Add link repository MBI 20.04

en/releases/centreon-os-extensions.md, fr/releases/centreon-os-extensions.md
Adding the release notes for centreon-ha 20.10.1
=> enh(release): Add centreon-ha 20.10.1 release notes

en/releases/centreon-os-extensions.md, fr/releases/centreon-os-extensions.md
Adding the release notes for version 20.04.3 of centreon-ha
=> Fix add release notes ha 20.04.3

en/installation/installation-of-a-remote-server/using-centreon-iso.md, en/installation/installation-of-a-remote-server/using-packages.md
Fix typos and enhance some command descriptions to ease comprehension of the setup of a remote server.
=> Fix typos and enhance some command descriptions

en/developer/developer-module.md, fr/developer/developer-module.md
Improve documentation to explain how to develop a module
Link centreon-dummy readme : https://github.com/centreon/centreon-dummy/blob/master/README.md
=> doc(module): improve documentation to dev a module

en/graph-views/install.md, en/reporting/installation.md, en/service-mapping/install.md, fr/graph-views/install.md, fr/reporting/installation.md, fr/service-mapping/install.md
=> enh(install): Add links to support portal for repos 20.04

en/integrations/plugin-packs/introduction.md, en/monitoring/pluginpacks.md, fr/integrations/plugin-packs/introduction.md, fr/monitoring/pluginpacks.md
=> enh(install): Add EPP links to support portal for repos 20.04

en/integrations/plugin-packs/introduction.md, en/monitoring/pluginpacks.md, fr/integrations/plugin-packs/introduction.md, fr/monitoring/pluginpacks.md
=> enh(install): Add EPP links to support portal for repos

en/releases/centreon-core.md, fr/releases/centreon-core.md
=> enh(release): Add Centreon web 20.04.8 RN

en/integrations/plugin-packs/procedures/hardware-storage-hitachi-hcp-snmp.md, en/sidebars.json, fr/integrations/plugin-packs/procedures/hardware-storage-hitachi-hcp-snmp.md, fr/sidebars.json
=> add(epp): hitachi hcp snmp proc

en/integrations/plugin-packs/procedures/cloud-azure-management-loganalytics.md, en/sidebars.json, fr/integrations/plugin-packs/procedures/cloud-azure-management-loganalytics.md, fr/sidebars.json
Add the monitoring procedure for Azure Log Analytics Plugin-Pack
=> new(mp)cloud-azure-management-log-analytics

en/integrations/plugin-packs/procedures/hardware-devices-hms-ewon-snmp.md, en/sidebars.json, fr/integrations/plugin-packs/procedures/hardware-devices-hms-ewon-snmp.md, fr/sidebars.json
=> add(epp): hms ewon snmp monitoring proc

en/integrations/plugin-packs/procedures/applications-commvault-commserve-restapi.md, en/sidebars.json, fr/integrations/plugin-packs/procedures/applications-commvault-commserve-restapi.md, fr/sidebars.json
=>  add(epp): commvault commserve rest api

en/integrations/plugin-packs/procedures/applications-monitoring-alyvix-restapi.md, fr/integrations/plugin-packs/procedures/applications-monitoring-alyvix-restapi.md
Updating the monitoring procedure following the plugin update (new label testcase-freshness)
=> enh(mp): application-monitoring-alyvix-restapi

en/integrations/plugin-packs/procedures/hardware-storage-hitachi-hcp-snmp.md, fr/integrations/plugin-packs/procedures/hardware-storage-hitachi-hcp-snmp.md
=> fix(epp): hitachi hcp snmp - some typo

en/releases/introduction.md, fr/releases/introduction.md
=> enh(release): add release date for major version

en/developer/developer-broker-mapping.md, fr/developer/developer-broker-mapping.md
=> enh(developer): add missing event

en/releases/centreon-core.md, fr/releases/centreon-core.md
Prepare Broker 20.10.3 release notes
=> enh(release): prepare broker 20.10.3 release notes

en/releases/centreon-core.md, fr/releases/centreon-core.md
Prepare Broker 20.04.12 release notes
=> enh(release): prepare broker 20.04.12 release notes

en/releases/centreon-core.md, fr/releases/centreon-core.md
Prepare Engine 20.10.2 release notes
=> enh(release): prepare engine 20.10.2 release notes

en/releases/centreon-core.md, fr/releases/centreon-core.md
Prepare Engine 20.04.9 release notes
=> enh(release): prepare engine 20.04.9 release notes

fr/monitoring/discovery/services-discovery.md
the param explanation states the opposite of what it does.
=> fix(doc) wrong param explanation

en/api/clapi.md, fr/api/clapi.md
document pool_size broker property in clapi setparam
Refs: MON-6191
=> enh(clapi): document pool_size broker property

en/releases/centreon-commercial-extensions.md, en/releases/centreon-core.md, en/releases/centreon-os-extensions.md, fr/releases/centreon-commercial-extensions.md, fr/releases/centreon-core.md, fr/releases/centreon-os-extensions.md
=> enh(release): change dates to render as tag

fr/releases/centreon-core.md
=> fix(release): wrong date language

en/releases/centreon-core.md, fr/releases/centreon-core.md
=> enh(release): add Centreon Web 20.04.9 RN

en/releases/centreon-os-extensions.md, fr/releases/centreon-os-extensions.md
=> enh(release): Add Centreon Open Tickets 20.04.1 RN

en/releases/centreon-os-extensions.md, fr/releases/centreon-os-extensions.md
=> enh(release): Add Centreon Open Tickets 20.10.1 RN

en/releases/centreon-commercial-extensions.md, fr/releases/centreon-commercial-extensions.md
=> feat(rn): prepare map 20.10.3 release

en/releases/centreon-commercial-extensions.md, fr/releases/centreon-commercial-extensions.md
=> feat(rn): prepare map 20.04.6 release

.github/PULL_REQUEST_TEMPLATE.md, Jenkinsfile, website/static/js/versions-select.js
prepare the 21.04 documentation.
New maintenance branch created (20.10.x)
=> chore(build): update serie to 21.04

en/integrations/plugin-packs/procedures/applications-oracle-goldengate-ssh.md, en/sidebars.json, fr/integrations/plugin-packs/procedures/applications-oracle-goldengate-ssh.md, fr/sidebars.json
=> add(epp): oracle goldengate ssh proc

en/integrations/plugin-packs/procedures/applications-microsoft-dhcp-snmp.md, en/sidebars.json, fr/integrations/plugin-packs/procedures/applications-microsoft-dhcp-snmp.md, fr/sidebars.json
=> add(epp): microsoft dhcp snmp

en/integrations/stream-connectors/sc-service-now.md
This PR is here to provide more details about the possibilities of the new service now stream connector (https://github.com/centreon/centreon-stream-connector-scripts/pull/39)
=> update snow SC doc to match new SC script

en/integrations/plugin-packs/procedures/network-fiberstore-snmp.md, en/sidebars.json, fr/integrations/plugin-packs/procedures/network-fiberstore-snmp.md, fr/sidebars.json
=> add(epp): fiberstore snmp

en/integrations/plugin-packs/procedures/hardware-ups-socomec-netvision-snmp.md, en/sidebars.json, fr/integrations/plugin-packs/procedures/hardware-ups-socomec-netvision-snmp.md, fr/sidebars.json
=> add(epp): ups socomec netvision snmp

en/integrations/plugin-packs/procedures/network-athonet-epc-snmp.md, en/sidebars.json, fr/integrations/plugin-packs/procedures/network-athonet-epc-snmp.md, fr/sidebars.json
=> add(epp): athonet ePC snmp monitoring proc

en/integrations/plugin-packs/procedures/applications-antivirus-kaspersky-snmp.md, fr/integrations/plugin-packs/procedures/applications-antivirus-kaspersky-snmp.md
Documenation enhancements following the new metrics.
=> enh(pack)app antivirus kasperskysnmp metricsv2

en/integrations/plugin-packs/procedures/cloud-azure-network-publicip.md, fr/integrations/plugin-packs/procedures/cloud-azure-network-publicip.md
** The host disco images will have to be uploaded and the sidebars updated after the PR https://github.com/centreon/centreon-documentation/pull/567 is merged **
Please don't merge before!
=> add(epp): Azure Public IP monitoring proc

en/integrations/plugin-packs/procedures/cloud-azure-security-keyvault.md, fr/integrations/plugin-packs/procedures/cloud-azure-security-keyvault.md
** The host disco images will have to be uploaded and the sidebars updated after the PR #567 is merged **
Please don't merge before!
=> Azure Key Vault monitoring proc

en/integrations/plugin-packs/procedures/cloud-gcp-compute-computeengine.md, en/sidebars.json, fr/integrations/plugin-packs/procedures/cloud-gcp-compute-computeengine.md, fr/sidebars.json
=> add(epp): google compute engine

en/integrations/plugin-packs/procedures/cloud-azure-network-firewall.md, fr/integrations/plugin-packs/procedures/cloud-azure-network-firewall.md
** The host disco images will have to be uploaded and the sidebars updated after the PR #567 is merged **
Please don't merge before!
=> Azure Firewall monitoring proc

en/releases/centreon-commercial-extensions.md, fr/releases/centreon-commercial-extensions.md
=> enh(release): prepare BAM 20.10.1 release notes

en/releases/centreon-commercial-extensions.md, fr/releases/centreon-commercial-extensions.md
=> enh(release): prepare BAM 20.04.6 release notes

fr/releases/centreon-commercial-extensions.md
=> fix(doc): fixed incorrect section marker

en/installation/installation-of-a-central-server/using-packages.md, en/installation/installation-of-a-central-server/using-sources.md, en/installation/installation-of-a-poller/using-centreon-iso.md, en/installation/installation-of-a-poller/using-packages.md, en/installation/installation-of-a-remote-server/using-centreon-iso.md, en/installation/installation-of-a-remote-server/using-packages.md, en/integrations/plugin-packs/procedures/applications-webservers-iis-restapi.md, en/migrate/poller-display-to-remote-server.md, fr/administration/centreon-ha/upgrade-from-centreon-failover.md, fr/installation/installation-of-a-central-server/using-sources.md, fr/installation/installation-of-a-poller/using-centreon-iso.md, fr/installation/installation-of-a-poller/using-packages.md, fr/installation/installation-of-a-remote-server/using-centreon-iso.md, fr/installation/installation-of-a-remote-server/using-packages.md, fr/integrations/plugin-packs/procedures/applications-webservers-iis-restapi.md, fr/migrate/poller-display-to-remote-server.md
Update documentation to use the new registration script.
=> enh(install): update platform registration documentation and translation

en/releases/centreon-commercial-extensions.md, fr/releases/centreon-commercial-extensions.md
=> enh(release): prepare BAM 20.10.2 release notes

en/releases/centreon-core.md, fr/releases/centreon-core.md
=> enh(release): Add Centreon Web 20.04.10 RN

en/releases/centreon-core.md, fr/releases/centreon-core.md
=> enh(release): Add Centreon Web 20.10.4 RN

en/releases/centreon-core.md, fr/releases/centreon-core.md
=> enh(release): prepare Gorgone 20.04.10 release notes

en/releases/centreon-core.md, fr/releases/centreon-core.md
=> enh(release): prepare Gorgone 20.10.3 release notes 

en/graph-views/install.md, en/installation/installation-of-a-poller/using-centreon-iso.md, en/installation/installation-of-a-poller/using-packages.md, en/installation/installation-of-a-remote-server/using-centreon-iso.md, en/installation/installation-of-a-remote-server/using-packages.md, en/installation/web-and-post-installation.md, en/sidebars.json, en/upgrade/upgrade-from-18-10.md, en/upgrade/upgrade-from-19-04.md, en/upgrade/upgrade-from-19-10.md, en/upgrade/upgrade-from-20-04.md, en/upgrade/upgrade-from-3-4.md, fr/graph-views/install.md, fr/installation/installation-of-a-poller/using-centreon-iso.md, fr/installation/installation-of-a-poller/using-packages.md, fr/installation/installation-of-a-remote-server/using-centreon-iso.md, fr/installation/installation-of-a-remote-server/using-packages.md, fr/installation/web-and-post-installation.md, fr/sidebars.json, fr/upgrade/upgrade-from-18-10.md, fr/upgrade/upgrade-from-19-04.md, fr/upgrade/upgrade-from-19-10.md, fr/upgrade/upgrade-from-20-04.md, fr/upgrade/upgrade-from-3-4.md
=> enh(security) Move secure chapter for better visibility

en/graph-views/advanced-configuration.md, en/graph-views/migrate.md, fr/graph-views/advanced-configuration.md, fr/graph-views/migrate.md
Deduplicate migration procedure.
=> fix(graph-views): deduplicate migration procedure

en/administration/centreon-ha/upgrade-from-centreon-failover.md, en/graph-views/install.md, en/releases/introduction.md, en/reporting/installation.md, en/reporting/migrate.md, en/upgrade/upgrade-from-18-10.md, en/upgrade/upgrade-from-19-04.md, en/upgrade/upgrade-from-19-10.md, en/upgrade/upgrade-from-20-04.md, en/upgrade/upgrade-from-20-10.md, en/upgrade/upgrade-from-3-4.md, fr/administration/centreon-ha/upgrade-from-centreon-failover.md, fr/graph-views/install.md, fr/installation/prerequisites.md, fr/reporting/installation.md, fr/reporting/migrate.md
=> fix(typo): correct MariaDB version

en/monitoring/discovery/administration.md, fr/monitoring/discovery/administration.md
Add parameters with example for service discovery job.
=> enh(discovery/service): add custom parameters with example

en/alerts-notifications/resources-status.md, fr/alerts-notifications/resources-status.md
=> fix(doc): small corrections

en/releases/centreon-commercial-extensions.md, fr/releases/centreon-commercial-extensions.md
=> enh(release): prepare map 20.04.7 release notes

en/administration/centreon-ha/installation-2-nodes.md, en/administration/centreon-ha/installation-4-nodes.md, fr/administration/centreon-ha/installation-2-nodes.md, fr/administration/centreon-ha/installation-4-nodes.md
this PR adds new chmod in the HA installation procedure. Those permissions are required for centreon_central_sync
=> fix chmod and add new chmod in ha procedure

fr/administration/backup.md
Backup taball names are wrong.
=> Update backup name

en/integrations/plugin-packs/procedures/applications-emc-ppma-restapi.md, en/sidebars.json, fr/integrations/plugin-packs/procedures/applications-emc-ppma-restapi.md, fr/sidebars.json
=> add(epp): emc ppma rest api

en/integrations/plugin-packs/procedures/network-denyall-snmp.md, en/sidebars.json, fr/integrations/plugin-packs/procedures/network-denyall-snmp.md, fr/sidebars.json
=> add(epp): denyall snmp

en/integrations/plugin-packs/procedures/network-ubiquiti-airfiber-snmp.md, en/sidebars.json, fr/integrations/plugin-packs/procedures/network-ubiquiti-airfiber-snmp.md, fr/sidebars.json
=> add(epp): ubiquiti airfiber snmp

en/integrations/plugin-packs/procedures/network-meru-snmp.md, en/sidebars.json, fr/integrations/plugin-packs/procedures/network-meru-snmp.md, fr/sidebars.json
=> add(epp): meru snmp

en/integrations/plugin-packs/procedures/hardware-servers-ibm-hmc-ssh.md, en/sidebars.json, fr/integrations/plugin-packs/procedures/hardware-servers-ibm-hmc-ssh.md, fr/sidebars.json
=> add(epp): ibm hmc ssh

en/integrations/plugin-packs/procedures/cloud-azure-network-publicip.md, en/integrations/plugin-packs/procedures/cloud-gcp-cloudsql-mysql.md, en/integrations/plugin-packs/procedures/cloud-gcp-management-stackdriver.md, en/integrations/plugin-packs/procedures/cloud-gcp-storage.md, en/integrations/plugin-packs/procedures/cloud-prometheus-api.md, fr/integrations/plugin-packs/procedures/cloud-prometheus-api.md
This PR introduces the new version of the Prometheus Api monitoring procedure. 
Also add information in the GCP Prerequisites
=> enh(pack)rewrite-prom-mp-and-misc[en]

en/sidebars.json, fr/sidebars.json
=> fix(sidebar)typo-in-sidebar

en/releases/centreon-commercial-extensions.md, fr/releases/centreon-commercial-extensions.md
=> enh(release): prepare Autodisco 20.04.8 release notes

en/releases/centreon-commercial-extensions.md, fr/releases/centreon-commercial-extensions.md
Release note for the new version
=> enh(release): prepare Autodisco 20.10.3 release notes

en/releases/centreon-core.md, fr/releases/centreon-core.md
=> enh(release): add Centreon Web 20.04.11 RN

en/releases/centreon-commercial-extensions.md, fr/releases/centreon-commercial-extensions.md
=> enh(ppm): Add 20.10.1 RN

en/releases/centreon-commercial-extensions.md, fr/releases/centreon-commercial-extensions.md
=> enh(ppm): Add 20.04.2 RN

en/releases/centreon-commercial-extensions.md, fr/releases/centreon-commercial-extensions.md
=> enh(lm): Add LM 20.10.2 RN

en/releases/centreon-commercial-extensions.md, fr/releases/centreon-commercial-extensions.md
=> enh(lm): Add LM 20.04.4 RN

en/releases/centreon-commercial-extensions.md, fr/releases/centreon-commercial-extensions.md
=> Add lm 20.04.4 rn release date

en/releases/centreon-commercial-extensions.md, fr/releases/centreon-commercial-extensions.md
=> Add lm 20.10.2 rn release date

en/releases/centreon-core.md, fr/releases/centreon-core.md
=> enh(release): Add Centreon Web 20.04.12 RN

en/releases/centreon-core.md, fr/releases/centreon-core.md
=> enh(release): Add Centreon Web 20.10.5 RN

en/graph-views/configuration.md
Fixed typo on the section "Define views & status computation parameters".
=> Fixing typo

en/installation/installation-of-a-central-server/using-sources.md, fr/installation/installation-of-a-central-server/using-sources.md
Add openssl dependency in source install
Refs: MON-6772
=> doc(dependencies): add openssl dependency in source install

en/developer/developer-broker-mapping.md, fr/developer/developer-broker-mapping.md
=> doc(broker): remove correlation module

en/graph-views/install.md, en/graph-views/upgrade.md, en/installation/installation-of-a-central-server/using-packages.md, en/installation/installation-of-a-poller/using-packages.md, en/installation/installation-of-a-remote-server/using-packages.md, en/integrations/plugin-packs/procedures/operatingsystems-linux-nrpe3.md, en/upgrade/upgrade-from-18-10.md, en/upgrade/upgrade-from-19-04.md, en/upgrade/upgrade-from-19-10.md, en/upgrade/upgrade-from-20-04.md, en/upgrade/upgrade-from-20-10.md, en/upgrade/upgrade-from-3-4.md, fr/graph-views/install.md, fr/graph-views/upgrade.md, fr/installation/installation-of-a-central-server/using-packages.md, fr/installation/installation-of-a-poller/using-packages.md, fr/installation/installation-of-a-remote-server/using-packages.md, fr/integrations/plugin-packs/procedures/operatingsystems-linux-nrpe3.md, fr/upgrade/upgrade-from-18-10.md, fr/upgrade/upgrade-from-19-04.md, fr/upgrade/upgrade-from-19-10.md, fr/upgrade/upgrade-from-20-04.md, fr/upgrade/upgrade-from-20-10.md, fr/upgrade/upgrade-from-3-4.md
=> enh(install): fix centeron-release version

en/administration/secure-platform.md, fr/administration/secure-platform.md
=> fix(security): correct gorgone account name

en/upgrade/upgrade-from-20-10.md, fr/upgrade/upgrade-from-20-10.md
=> fix(upgrade): correct 20.10 21.04 upgrade

en/administration/secure-platform.md, en/installation/installation-of-a-central-server/using-packages.md, en/installation/installation-of-a-poller/using-packages.md, en/installation/installation-of-a-remote-server/using-packages.md, fr/administration/secure-platform.md, fr/installation/installation-of-a-central-server/using-packages.md, fr/installation/installation-of-a-poller/using-packages.md, fr/installation/installation-of-a-remote-server/using-packages.md
=> Security add selinux fail2ban

en/integrations/plugin-packs/procedures/applications-google-gsuite-api.md
=> fix(pack) wrong Plugin package name in Gsuite monitoring procedure (en)

fr/integrations/plugin-packs/procedures/applications-google-gsuite-api.md
=> fix(pack) wrong Plugin package name in Gsuite monitoring procedure (fr)

en/administration/secure-platform.md, fr/administration/secure-platform.md
=> secure-add-selinux

en/integrations/plugin-packs/procedures/cloud-azure-management-automation.md, fr/integrations/plugin-packs/procedures/cloud-azure-management-automation.md
=> Fix(mp): Azure Management Automation

en/integrations/plugin-packs/procedures/cloud-azure-integration-eventgrid.md
Fixing a typo in the Plugin RPM.
=> fix(plugin)azure integration

en/integrations/plugin-packs/procedures/network-athonet-epc-snmp.md, fr/integrations/plugin-packs/procedures/network-athonet-epc-snmp.md
=> enh(epp): athonet epc snmp - add aggregate/apns services

en/integrations/plugin-packs/procedures/network-acmepacket-snmp.md, fr/integrations/plugin-packs/procedures/network-acmepacket-snmp.md
=> enh(epp): acmepacket snmp - procedure v2

en/integrations/plugin-packs/procedures/cloud-azure-analytics-eventhubs.md
=> fix(epp): Azure Event Hubs provider image EN

en/integrations/plugin-packs/procedures/applications-antivirus-clamav-ssh.md, fr/integrations/plugin-packs/procedures/applications-antivirus-clamav-ssh.md
=> fix(pack) wrong Plugin package name in monitoring procedure

en/upgrade/upgrade-from-20-10.md
=> fix broken link

en/installation/installation-of-a-poller/using-packages.md, fr/installation/installation-of-a-poller/using-packages.md
=> fix(install): fix RPM path

en/administration/secure-platform.md, fr/administration/secure-platform.md
=> Wording about SIEM

en/administration/secure-platform.md, fr/administration/secure-platform.md
=> fix(typo): Improve title wording for FR chapter

en/releases/centreon-core.md, fr/releases/centreon-core.md
=> enh(release): Add Centreon Engine 21.04.1 RN

en/releases/centreon-core.md, fr/releases/centreon-core.md
=> enh(release): prepare Engine 20.04.10 release notes

en/releases/centreon-core.md, fr/releases/centreon-core.md
=> enh(release): add Centreon Broker 20.04.13 RN

en/monitoring/anomaly-detection.md, fr/monitoring/anomaly-detection.md
=> fix(anomaly): add missing repo for el7

en/releases/centreon-core.md, fr/releases/centreon-core.md
=> enh(release): add Centreon Broker 20.10.4 RN

en/releases/centreon-core.md, fr/releases/centreon-core.md
=> enh(release): prepare Engine 20.10.3 release notes 

en/releases/centreon-commercial-extensions.md, fr/releases/centreon-commercial-extensions.md
=> enh(release): Add Centreon BAM 20.04.7 RN

en/releases/centreon-commercial-extensions.md, fr/releases/centreon-commercial-extensions.md
=> enh(release): Add Centreon BAM 20.10.3 RN

en/upgrade/upgrade-from-20-10.md
- Enhance the description to update MariaDB.
- Include "update repo" instructions for architectures featuring remote DBMS servers.
- Fix a couple of typos.
=> Enhance the upgrade document

en/releases/centreon-commercial-extensions.md, fr/releases/centreon-commercial-extensions.md
=> enh(release): Add Centreon MBI 20.04.4 RN

en/releases/centreon-commercial-extensions.md, fr/releases/centreon-commercial-extensions.md
=> enh(release): Add Centreon MBI 20.10.1 RN

en/sidebars.json, fr/sidebars.json, fr/update/update-centreon-ha.md
Change/fix the organization of the sidebar for more logic :)
=> enh(organization): change sidebar.json organization

en/releases/centreon-commercial-extensions.md, fr/releases/centreon-commercial-extensions.md
=> enh(release): Add Centreon MAP 20.10.4 RN

en/integrations/plugin-packs/procedures/hardware-storage-huawei-oceanstor-snmp.md, en/sidebars.json, fr/integrations/plugin-packs/procedures/hardware-storage-huawei-oceanstor-snmp.md, fr/sidebars.json
=> add(epp): huawei oceanstor snmp proc

en/integrations/plugin-packs/procedures/hardware-storage-bdt-multistak-snmp.md, en/sidebars.json, fr/integrations/plugin-packs/procedures/hardware-storage-bdt-multistak-snmp.md, fr/sidebars.json
=> add(epp): bdt multistak snmp

en/integrations/plugin-packs/procedures/operatingsystems-aix-ssh.md, en/sidebars.json, fr/integrations/plugin-packs/procedures/operatingsystems-aix-ssh.md, fr/sidebars.json
=> Enh(mp) add new aix ssh monitoring procedure

en/upgrade/upgrade-from-18-10.md, en/upgrade/upgrade-from-19-04.md, en/upgrade/upgrade-from-19-10.md, en/upgrade/upgrade-from-20-04.md, en/upgrade/upgrade-from-3-4.md, fr/upgrade/upgrade-from-18-10.md, fr/upgrade/upgrade-from-19-04.md, fr/upgrade/upgrade-from-19-10.md, fr/upgrade/upgrade-from-20-04.md, fr/upgrade/upgrade-from-3-4.md
=> fix(upgrade): improve upgrade chapters

en/integrations/plugin-packs/procedures/applications-proxmox-mg-api.md, en/sidebars.json, fr/integrations/plugin-packs/procedures/applications-proxmox-mg-api.md, fr/sidebars.json
=> add(epp): proxmox mg api proc

en/releases/centreon-commercial-extensions.md, fr/releases/centreon-commercial-extensions.md
=> enh(release): add License Manager 20.10.3 RN

en/releases/centreon-commercial-extensions.md, fr/releases/centreon-commercial-extensions.md
=> enh(release): add License Manager 20.04.5 RN

en/administration/secure-platform.md, en/upgrade/upgrade-from-18-10.md, en/upgrade/upgrade-from-19-04.md, en/upgrade/upgrade-from-19-10.md, en/upgrade/upgrade-from-3-4.md, fr/administration/secure-platform.md, fr/upgrade/upgrade-from-18-10.md, fr/upgrade/upgrade-from-19-04.md, fr/upgrade/upgrade-from-19-10.md, fr/upgrade/upgrade-from-3-4.md
avoid 404 redirection on react routes
=> conf(apache): avoid 404 redirection on react routes

en/releases/centreon-commercial-extensions.md, fr/releases/centreon-commercial-extensions.md
=> rn en & fr

en/integrations/stream-connectors/sc-service-now.md, en/integrations/stream-connectors/sc-splunk-events.md, en/integrations/stream-connectors/sc-splunk-metrics.md, fr/integrations/stream-connectors/sc-service-now.md, fr/integrations/stream-connectors/sc-splunk-events.md, fr/integrations/stream-connectors/sc-splunk-metrics.md
change url to match the current stream connector structure
require https://github.com/centreon/centreon-stream-connector-scripts/pull/47
=> change github url to match new organization

en/integrations/plugin-packs/procedures/cloud-azure-network-appgateway.md
=> fix(epp): Azure App GW monitoring proc provider URL fix

en/integrations/plugin-packs/procedures/applications-databases-oracle.md
=> fix(epp):  Oracle plugin correct path [EN]

en/releases/centreon-core.md, fr/releases/centreon-core.md
=> enh(release): Add Centreon Web 20.10.7 RN

en/releases/centreon-core.md, fr/releases/centreon-core.md
=> enh(release): Add Centreon Web 20.04.13 RN

en/installation/introduction.md, fr/installation/introduction.md
=> fix(install): correct unattended.sh path

en/releases/centreon-core.md, fr/releases/centreon-core.md
=> enh(release): Add Centreon Web 21.04.1 RN

en/monitoring/about.md, fr/monitoring/about.md, fr/monitoring/anomaly-detection.md, fr/monitoring/basic-objects/commands.md, fr/monitoring/basic-objects/contacts.md, fr/monitoring/basic-objects/hosts.md, fr/monitoring/basic-objects/macros.md, fr/monitoring/basic-objects/services.md, fr/monitoring/basic-objects/timeperiods.md, fr/monitoring/generic-actions.md, fr/monitoring/pluginpacks.md, fr/monitoring/templates.md
=> PR736 from master

fr/monitoring/discovery/administration.md, fr/monitoring/discovery/hosts-discovery.md, fr/monitoring/discovery/installation.md, fr/monitoring/discovery/introduction.md, fr/monitoring/discovery/services-discovery.md, fr/monitoring/monitoring-servers/add-a-poller-to-configuration.md, fr/monitoring/monitoring-servers/add-a-remote-server-to-configuration.md, fr/monitoring/pluginpacks.md
=> fix(monitoring): typos

en/integrations/plugin-packs/procedures/cloud-azure-management-applicationinsights.md, fr/integrations/plugin-packs/procedures/cloud-azure-management-applicationinsights.md
Fix following our discussion in centreon/centreon-plugins/pull/2762
=> fix(mp): Azure Application Insights

en/graph-views/install-ha.md
Add the new chapters about the 2 nodes HA Map architecutre.
@Sims24, if you're ok with the content, I will update the sidebars.json and doing the translation + add 4 nodes HA Map Architecture.
=> enh(ha): add ha map 2 nodes

en/upgrade/introduction.md, fr/upgrade/introduction.md
Add module repo part on the upgrade process in order to avoid dependency problems
=> [ENH] Add module repo part for upgrade proc

en/integrations/plugin-packs/procedures/applications-haproxy-snmp.md, fr/integrations/plugin-packs/procedures/applications-haproxy-snmp.md
Updating the monitoring procedure to the new format.
=> enh(mp): HAProxy SNMP

en/integrations/plugin-packs/procedures/cloud-azure-network-appgateway.md, fr/integrations/plugin-packs/procedures/cloud-azure-network-appgateway.md
=> enh(epp): Azure Application GW versions management

en/integrations/plugin-packs/procedures/applications-protocol-ssh.md, fr/integrations/plugin-packs/procedures/applications-protocol-ssh.md
Updating the monitoring procedure to the new format.
=> enh(mp): SSH Protocol

en/upgrade/upgrade-from-20-04.md
Fix "migration procedure" link for "Upgrade from Centreon 20.04" chapter
=> Fix "migration procedure" link

fr/administration/secure-platform.md
=> fix(security): FR typos in SELinux chapter

fr/graph-views/install-ha.md
Add the translate in FR of new chapters about the 2 nodes HA Map architecutre.
@Sims24, if you're ok with the content, I will update the sidebars.json and translate 4 nodes HA Map Architecture.
=> (enh): add ha map 2 nodes FR

en/graph-views/install-ha.md
fix terminologys ha map 2 nodes english version.
=> fix terms ha map 2 nodes-EN

en/integrations/plugin-packs/procedures/network-aruba-instant-snmp.md, fr/integrations/plugin-packs/procedures/network-aruba-instant-snmp.md
This is a rewrite in version 2 of the monitoring procedure of the Aruba Instant SNMP Plugin-Pack.
=> feat(pack): update monproc_v2_Aruba_Instant_SNMP_4

en/releases/centreon-core.md, fr/releases/centreon-core.md
=> enh(release): Prepare Centreon Web 20.04.14 RN

en/releases/centreon-commercial-extensions.md, fr/releases/centreon-commercial-extensions.md
=> enh(release): Add Centreon MBI 20.10.3 RN

en/releases/centreon-core.md, fr/releases/centreon-core.md
=> enh(rn): prepare release notes for broker 20.04.14

en/administration/centreon-ha/operating-guide.md, en/administration/parameters/data-management.md, en/administration/secure-platform.md, en/alerts-notifications/notif-advanced.md, en/graph-views/secure-your-map-platform.md, en/installation/installation-of-centreon-ha/installation-2-nodes.md, en/installation/installation-of-centreon-ha/installation-4-nodes.md, en/integrations/plugin-packs/procedures/applications-sccm-nsclient.md, en/integrations/plugin-packs/procedures/cloud-azure-network-frontdoor.md, en/migrate/nagios-to-centreon.md, en/monitoring/anomaly-detection.md, en/upgrade/centreon-ha/upgrade-from-centreon-failover.md, en/upgrade/upgrade-from-18-10.md, en/upgrade/upgrade-from-19-04.md, en/upgrade/upgrade-from-19-10.md, fr/getting-started/installation-first-steps.md, fr/graph-views/secure-your-map-platform.md, fr/installation/installation-of-a-central-server/using-virtual-machines.md, fr/installation/installation-of-centreon-ha/installation-2-nodes.md, fr/installation/installation-of-centreon-ha/installation-4-nodes.md, fr/installation/prerequisites.md, fr/monitoring/anomaly-detection.md, fr/upgrade/upgrade-from-18-10.md, fr/upgrade/upgrade-from-19-04.md, fr/upgrade/upgrade-from-19-10.md, fr/upgrade/upgrade-from-20-04.md
=> Fix broken links

en/releases/centreon-core.md, fr/releases/centreon-core.md
=> enh(release): prepare release notes for engine 20.04.12

en/releases/centreon-core.md, fr/releases/centreon-core.md
=> enh(rn): prepare release notes for broker 20.10.5

en/releases/centreon-core.md, fr/releases/centreon-core.md
=> enh(release): prepare engine 20.10.5 release notes

en/releases/centreon-core.md, fr/releases/centreon-core.md
=> enh(rn): prepare release notes for centreon-broker 21.04.1

en/releases/centreon-core.md, fr/releases/centreon-core.md
=> enh(rn): prepare release notes engine 21.04.2

en/integrations/plugin-packs/procedures/network-cisco-wap-snmp.md, en/sidebars.json, fr/integrations/plugin-packs/procedures/network-cisco-wap-snmp.md, fr/sidebars.json
This is the Monitoring Procedure of the Cisco Wap package in SNMP
=> add(mp) : add Cisco Wap snmp

en/integrations/plugin-packs/procedures/applications-webservers-nginx-serverstatus.md, fr/integrations/plugin-packs/procedures/applications-webservers-nginx-serverstatus.md
I rewrited the monitoring procedure of Nginx Servers.
=> feat(pack): update monproc_v2_nginx_serverstatus

fr/integrations/plugin-packs/procedures/applications-netbackup-nrpe.md
Remove wrong Exchange part on the Netbackup Pack documentation
=> Remove wrong Exchange part

en/monitoring/basic-objects/contacts.md
=> Update URL Autologin (EN)

fr/monitoring/basic-objects/contacts.md
=> Update URL Autologin

en/releases/centreon-core.md, fr/releases/centreon-core.md
=> enh(release): Prepare Centreon Web 20.10.8 RN

en/security/security.md, en/sidebars.json, fr/security/security.md, fr/sidebars.json
=> Add topic on security

en/monitoring/passive-monitoring/enable-snmp-traps.md, fr/monitoring/passive-monitoring/enable-snmp-traps.md
Remove obsolete SNMP Traps configuration
Replace #400 by adding FR part
=> fix(traps): remove obsolete part

fr/integrations/plugin-packs/procedures/applications-protocol-modbus.md
typo correction in the link modbus protocol
=> Update applications-protocol-modbus.md [EN]

en/integrations/plugin-packs/procedures/hardware-servers-cisco-ucs-snmp.md, fr/integrations/plugin-packs/procedures/hardware-servers-cisco-ucs-snmp.md
i rewrited the monitoring procedure of Cisco UCS Servers.
=> feat(pack): monproc_v2_cisco_ucs_snmp

en/monitoring/discovery/services-discovery.md
correction on filter options like github documentation
=> fix(disco) fix typo in configuration directive name

fr/integrations/plugin-packs/procedures/applications-protocol-modbus.md
erreur dans l'URL d'accès (espace manquant)
=> Update applications-protocol-modbus.md [FR]

en/developer/developer-broker-mapping.md, fr/developer/developer-broker-mapping.md
This PR is a sister to #783, as I had second thoughts about not fixing all files in versions 20.04 and 20.10
=> Mon 7397 remove obsolete contents

en/monitoring/basic-objects/timeperiods.md, fr/monitoring/basic-objects/timeperiods.md
Improved topic on time periods. Added info on how to exclude a time period using the Time Range Exceptions tab.
=> enh(monitoring): Revise topic about time periods

en/releases/centreon-core.md, fr/releases/centreon-core.md
=> enh(release): Prepare Centreon Gorgone 20.04.11 RN

en/releases/centreon-core.md, fr/releases/centreon-core.md
=> enh(release): Prepare Centreon Gorgone 20.10.4 RN

en/releases/centreon-core.md, fr/releases/centreon-core.md
=> enh(release): Prepare Centreon Gorgone 21.04.1 RN

en/releases/centreon-core.md, fr/releases/centreon-core.md
=> enh(release): Prepare Centreon Web 20.04.15 RN

en/releases/centreon-commercial-extensions.md, fr/releases/centreon-commercial-extensions.md
=> enh(release): Add Centreon MBI 20.04.6 RN

fr/integrations/stream-connectors/sc-opsgenie.md
For some reason the FR doc on opsgenie isn't in the 21.04 branch, resulting in a dead link in the doc. This commit fixes this.
=> Restore file that had disappeared

en/integrations/plugin-packs/procedures/network-tplink-snmp.md, en/sidebars.json, fr/integrations/plugin-packs/procedures/network-tplink-snmp.md, fr/sidebars.json
Monitoring procedure for Plugin Pack TP-Link SNMP
=> add(MP): Add Network TP-Link SNMP

en/administration/secure-platform.md, fr/administration/secure-platform.md
=> fix(administration): Remove extra yum in command

en/graph-views/install.md, en/installation/prerequisites.md, fr/graph-views/install.md, fr/installation/prerequisites.md
Add info about browser requirements.
=> Add info about browser requirements

en/graph-views/upgrade.md, en/reporting/upgrade.md, en/sidebars.json, en/upgrade/upgrade-mariadb.md, fr/graph-views/upgrade.md, fr/reporting/upgrade.md, fr/sidebars.json, fr/upgrade/upgrade-mariadb.md
Create specific topic about MariaDB upgrade, add link to it in MBI and MAP doc
=> MariaDB upgrade

en/upgrade/upgrade-from-18-10.md, en/upgrade/upgrade-from-19-04.md, en/upgrade/upgrade-from-19-10.md, en/upgrade/upgrade-from-20-04.md, en/upgrade/upgrade-from-20-10.md, en/upgrade/upgrade-from-3-4.md, fr/upgrade/upgrade-from-18-10.md, fr/upgrade/upgrade-from-19-04.md, fr/upgrade/upgrade-from-19-10.md, fr/upgrade/upgrade-from-20-04.md, fr/upgrade/upgrade-from-20-10.md, fr/upgrade/upgrade-from-3-4.md
Add info about deploying configuration
=> Add info about deploying configuration

en/reporting/installation.md, fr/reporting/installation.md
=> Add info about enabling cbis

en/installation/installation-of-a-central-server/using-packages.md, en/installation/installation-of-a-central-server/using-sources.md, en/installation/installation-of-a-remote-server/using-packages.md, en/upgrade/centreon-ha/upgrade-from-20.04.md, en/upgrade/centreon-ha/upgrade-from-20.10.md, en/upgrade/upgrade-from-18-10.md, en/upgrade/upgrade-from-19-04.md, en/upgrade/upgrade-from-19-10.md, en/upgrade/upgrade-from-20-04.md, en/upgrade/upgrade-from-20-10.md, en/upgrade/upgrade-from-3-4.md, fr/installation/installation-of-a-central-server/using-packages.md, fr/installation/installation-of-a-central-server/using-sources.md, fr/installation/installation-of-a-remote-server/using-packages.md, fr/upgrade/centreon-ha/upgrade-from-20.04.md, fr/upgrade/centreon-ha/upgrade-from-20.10.md, fr/upgrade/upgrade-from-18-10.md, fr/upgrade/upgrade-from-19-04.md, fr/upgrade/upgrade-from-19-10.md, fr/upgrade/upgrade-from-20-04.md, fr/upgrade/upgrade-from-20-10.md, fr/upgrade/upgrade-from-3-4.md
Add warning about not just copying the example given about the php timezone
=> Add warning about replacing timezone

en/releases/centreon-commercial-extensions.md, fr/releases/centreon-commercial-extensions.md
=> enh(release): enh(release): Add Centreon MBI 21.04.1 RN

en/integrations/plugin-packs/procedures/cloud-azure-analytics-eventhubs.md
=> Fix broken path to image

en/releases/centreon-core.md, fr/releases/centreon-core.md
=> enh(release): Add Centreon Web 21.04.3 RN

en/releases/centreon-commercial-extensions.md, fr/releases/centreon-commercial-extensions.md
Clarify the release notes:
* make it understandable
* warn the user of the impact of not updating components in the right order
* give a procedure to fix the issue they might experience
=> enh(rn): clarify the impact of autodiscovery 20.10.3 in the rn

en/releases/centreon-core.md, fr/releases/centreon-core.md
=> enh(release): Add Centreon Web 20.10.9 RN

en/releases/centreon-core.md, fr/releases/centreon-core.md
=> enh(release): Add Centreon Web 20.04.16 RN

en/monitoring/anomaly-detection.md, fr/monitoring/anomaly-detection.md
Add info to prevent problems with the Anomaly Detection module.
=> Add info about the LC_ALL variable

en/api/clapi.md, fr/api/clapi.md
Update outdated doc for parameter "Add"
=> Update parameter "Add"

contrib/list_missing_links_in_pp.sh
- Check if all files in [fr/en]/integrations/plugin-packs/procedures directories have an entry in [fr/en]/sidebars.json
- Check if entries in [fr/en]/sidebars.json have a markdown file in [fr/en]/integrations/plugin-packs/procedures directories
=> enh(contrib): Add script to check missing procedures in TOC

en/releases/centreon-core.md, fr/releases/centreon-core.md
The fix versions field had been wrongly filled for the Jira ticket MON-6670.
=> Update release note

en/migrate/migrate-from-20-x.md, en/migrate/migrate-from-3-4.md, en/upgrade/upgrade-from-18-10.md, en/upgrade/upgrade-from-19-04.md, en/upgrade/upgrade-from-19-10.md, en/upgrade/upgrade-from-20-04.md, en/upgrade/upgrade-from-20-10.md, en/upgrade/upgrade-from-3-4.md, en/upgrade/upgrade-mariadb.md, fr/migrate/migrate-from-20-x.md, fr/migrate/migrate-from-3-4.md, fr/upgrade/upgrade-from-18-10.md, fr/upgrade/upgrade-from-19-04.md, fr/upgrade/upgrade-from-19-10.md, fr/upgrade/upgrade-from-20-04.md, fr/upgrade/upgrade-from-20-10.md, fr/upgrade/upgrade-from-3-4.md, fr/upgrade/upgrade-mariadb.md
Add -p option to mysql_upgrade
=> Add -p option to mysql_upgrade

en/reporting/installation.md, fr/reporting/installation.md
Add info about granting rights to user cbis
=> Add info about granting rights to user cbis

en/graph-views/remote-server.md
add Administration  >  Parameters  >  Images in the remote console's menu
=> enh(doc) add missing menu

en/integrations/plugin-packs/procedures/cloud-azure-management-apimanagement.md, fr/integrations/plugin-packs/procedures/cloud-azure-management-apimanagement.md
=> Enh(mp) azure management api add capacity mode

en/resources/known-issues.md, fr/resources/known-issues.md
Add known issue about error message in autodiscovery
=> MON-10778 Add known issue about error message in autodiscovery

en/releases/centreon-commercial-extensions.md, fr/releases/centreon-commercial-extensions.md
=> Prepare autodisco 20.10.4 rn

en/releases/centreon-commercial-extensions.md, fr/releases/centreon-commercial-extensions.md
=> Added mbi 21.04.2 rn

en/monitoring/discovery/installation.md, fr/monitoring/discovery/installation.md
Add a section about creating a dedicated autodiscovery account
=> MON-10743 dedicated autodiscovery account

en/releases/centreon-commercial-extensions.md, fr/releases/centreon-commercial-extensions.md
=> enh(release): release notes for centreon-autodiscovery 21.04.1

en/integrations/plugin-packs/procedures/applications-exchange-nrpe.md, en/integrations/plugin-packs/procedures/applications-exchange-nsclient-restapi.md, en/integrations/plugin-packs/procedures/network-switchs-dell-xseries-snmp.md, fr/integrations/plugin-packs/procedures/applications-exchange-nrpe.md, fr/integrations/plugin-packs/procedures/applications-exchange-nsclient-restapi.md, fr/integrations/plugin-packs/procedures/network-switchs-dell-xseries-snmp.md
Previous (shitty) commit wasn't enough. Need to rename and change page id to get rid of dead links.
=> fix(mp) align mp with sidebars

en/releases/centreon-commercial-extensions.md, fr/releases/centreon-commercial-extensions.md
=> Prepare autodisco 20.04.9 rn

en/releases/centreon-commercial-extensions.md, fr/releases/centreon-commercial-extensions.md
=> Added mbi-20.10.4 rn

en/releases/centreon-commercial-extensions.md, fr/releases/centreon-commercial-extensions.md
=> added mbi-20.04.7 rn

en/resources/known-issues.md, fr/resources/known-issues.md
Add known issue (autodiscovery: 0s lost in host names)
=> MON-10833 Add known issue

en/installation/installation-of-a-central-server/using-centreon-iso.md, fr/installation/installation-of-a-central-server/using-centreon-iso.md
Make a step optional in the ISO installation procedure.
=> Make step optional

en/getting-started/first-supervision.md, fr/getting-started/first-supervision.md
=> Add link to autodisco

en/installation/installation-of-a-central-server/using-virtual-machines.md, fr/installation/installation-of-a-central-server/using-virtual-machines.md
Tell users to update ova after install
=> Tell users to update ova after install

en/getting-started/first-supervision.md, fr/getting-started/first-supervision.md
Changed screenshot that was in French in the English version. Refreshed the section a little bit.
=> MON-10840 Change screenshot

en/administration/secure-platform.md, en/getting-started/first-supervision.md, en/graph-views/install-ha.md, en/installation/installation-of-a-central-server/using-centreon-iso.md, en/installation/installation-of-a-central-server/using-packages.md, en/installation/installation-of-a-central-server/using-sources.md, en/installation/installation-of-a-remote-server/using-centreon-iso.md, en/installation/installation-of-centreon-ha/installation-2-nodes.md, en/installation/installation-of-centreon-ha/installation-4-nodes.md, fr/administration/secure-platform.md, fr/getting-started/first-supervision.md, fr/installation/installation-of-a-central-server/using-centreon-iso.md, fr/installation/installation-of-a-central-server/using-packages.md, fr/installation/installation-of-a-central-server/using-sources.md, fr/installation/installation-of-a-remote-server/using-centreon-iso.md, fr/installation/installation-of-a-remote-server/using-packages.md, fr/installation/installation-of-centreon-ha/installation-2-nodes.md, fr/monitoring/discovery/installation.md
https://centreon.atlassian.net/browse/MON-10847
=> Improve topic on installing from packages

en/installation/installation-of-a-central-server/using-sources.md, fr/installation/installation-of-a-central-server/using-sources.md
fix nodejs installation instructions
=> fix(nodejs): fix nodejs installation instructions

en/mobile/introduction.md, fr/mobile/introduction.md
Add info about enabling Reach Configuration API
=> Add info about enabling Reach Configuration API

en/integrations/plugin-packs/tutorials/troubleshooting-plugins.md, en/sidebars.json
Dedicated page to help users troubleshoot the most common Plugin issues.
=> Enh(doc)dedicated plugins troubleshooting page

en/integrations/plugin-packs/procedures/applications-squid-snmp.md, fr/integrations/plugin-packs/procedures/applications-squid-snmp.md
=> enh(mp): Squid SNMP

en/integrations/plugin-packs/procedures/applications-antivirus-clamav-ssh.md, fr/integrations/plugin-packs/procedures/applications-antivirus-clamav-ssh.md
=> enh(mp): ClamAV SSH

en/releases/centreon-core.md, fr/releases/centreon-core.md
=> enh(release): Add Centreon Web 20.04.17 RN

en/releases/centreon-core.md, fr/releases/centreon-core.md
=> enh(release): Add Centreon Web 20.10.10 RN

en/releases/centreon-core.md, fr/releases/centreon-core.md
=> enh(release): Add Centreon Web 21.04.4 RN

en/releases/centreon-commercial-extensions.md, fr/releases/centreon-commercial-extensions.md
=> enh(release): Add Centreon Map 21.04.1 RN

en/releases/centreon-commercial-extensions.md, fr/releases/centreon-commercial-extensions.md
Add spacing to make it clear and readable.
=> add spacing

en/administration/licenses.md, fr/administration/licenses.md
Add link to support portal/email
=> Add link to support portal/email

en/integrations/plugin-packs/procedures/applications-jvm-jmx.md, en/sidebars.json, fr/integrations/plugin-packs/procedures/applications-jvm-jmx.md, fr/sidebars.json
=> add(epp): jvm jmx proc

en/integrations/plugin-packs/procedures/network-ubiquiti-unifi-snmp.md, en/sidebars.json, fr/integrations/plugin-packs/procedures/network-ubiquiti-unifi-snmp.md, fr/sidebars.json
=> add(epp): ubiquiti unifi proc

en/integrations/plugin-packs/procedures/hardware-storage-lenovo-iomega-snmp.md, en/sidebars.json, fr/sidebars.json
=> add(epp): lenovo iomega snmp

en/integrations/plugin-packs/procedures/hardware-ups-cyberpower-snmp.md, en/sidebars.json, fr/integrations/plugin-packs/procedures/hardware-ups-cyberpower-snmp.md, fr/sidebars.json
=> add(epp): cyberpower ups snmp proc

en/integrations/plugin-packs/procedures/applications-slack-restapi.md, en/sidebars.json, fr/integrations/plugin-packs/procedures/applications-slack-restapi.md, fr/sidebars.json
=> add(epp): slack api proc

en/integrations/plugin-packs/procedures/hardware-ups-phoenixtec-snmp.md, en/sidebars.json, fr/integrations/plugin-packs/procedures/hardware-ups-phoenixtec-snmp.md, fr/sidebars.json
=> add(epp): phoenixtec ups snmp proc

en/integrations/plugin-packs/procedures/hardware-ups-hp-snmp.md, fr/integrations/plugin-packs/procedures/hardware-ups-hp-snmp.md
=> enh(epp): ups hp snmp - procedure v2

en/integrations/plugin-packs/procedures/hardware-storage-dell-me4-restapi.md, fr/integrations/plugin-packs/procedures/hardware-storage-dell-me4-restapi.md
=> enh(epp): dell me4 rest api - procedure v2

en/getting-started/first-supervision.md, en/monitoring/discovery/hosts-discovery.md, fr/getting-started/first-supervision.md, fr/monitoring/discovery/hosts-discovery.md
Add links to tutorial on discovering AWS instances.
=> Add links to tutorial

en/integrations/plugin-packs/procedures/operatingsystems-linux-snmp.md, fr/integrations/plugin-packs/procedures/operatingsystems-linux-snmp.md
=> Add missing backslashes

en/administration/secure-platform.md, fr/administration/secure-platform.md
Change permissions for configuration files
=> Change permissions for configuration files

en/getting-started/autodisco-aws.md, fr/getting-started/autodisco-aws.md
Add info about installing packs only on the central server
=> Add info about installing packs

en/integrations/plugin-packs/procedures/applications-protocol-x509.md, fr/integrations/plugin-packs/procedures/applications-protocol-x509.md
Spelling
Certificat -> Certificate
=> enh(doc): spelling

en/integrations/plugin-packs/procedures/operatingsystems-windows-nsclient-05-nrpe.md, fr/integrations/plugin-packs/procedures/operatingsystems-windows-nsclient-05-nrpe.md
remove 'plugin-packs' from link to fix broken link
=> enh(doc): update link

fr/integrations/notifications/telegram.md
Typo - FR (see https://github.com/centreon/centreon-documentation/pull/934)
=> Fix typo (FR)

en/installation/prerequisites.md, fr/installation/prerequisites.md
Refresh section on supported OSs
=> Refresh section on supported OSs

en/alerts-notifications/manage-alerts.md, fr/alerts-notifications/manage-alerts.md
Specify that downtimes cannot start or end after 31/12/2037
=> Downtimes cannot start or end after 31/12/2037

en/alerts-notifications/manage-alerts.md, fr/alerts-notifications/manage-alerts.md
Specify that downtimes cannot start or end after 31/12/1099
=> Downtimes cannot start or end after 31/12/1099

en/releases/lifecycle.md, fr/releases/lifecycle.md
Use correct year 2021 for 21.04 release
=> enh(doc) update release date

en/monitoring/pluginpacks.md, fr/monitoring/pluginpacks.md
=> Refresh topic on Plugin Packs

en/releases/centreon-core.md, fr/releases/centreon-core.md
=> eng(release): Add Centreon Broker 20.04.16 RN

en/releases/centreon-core.md, fr/releases/centreon-core.md
=> eng(release): Add Centreon Broker 20.10.7 RN

en/releases/centreon-core.md, fr/releases/centreon-core.md
=> eng(release): Add Centreon Broker 21.04.3 RN

en/installation/architectures.md, fr/installation/architectures.md
Add info to titles within tabs so that you can create a link to the contents of each tab
=> Add info in title

en/integrations/plugin-packs/procedures/hardware-storage-lenovo-iomega-snmp.md, fr/integrations/plugin-packs/procedures/hardware-storage-lenovo-iomega-snmp.md
=> enh(epp): lenovo iomega snmp - typo

en/integrations/plugin-packs/procedures/hardware-servers-supermicro-bmc-snmp.md, en/integrations/plugin-packs/procedures/hardware-servers-supermicro-snmp.md, en/integrations/plugin-packs/procedures/hardware-servers-supermicro-superdoctor-snmp.md, en/sidebars.json, fr/integrations/plugin-packs/procedures/hardware-servers-supermicro-bmc-snmp.md, fr/integrations/plugin-packs/procedures/hardware-servers-supermicro-snmp.md, fr/integrations/plugin-packs/procedures/hardware-servers-supermicro-superdoctor-snmp.md, fr/sidebars.json
=> add(epp): supermicro superdoctor snmp proc v2 - supermicro bmc snmp proc v2 - deprecate supermicro snmp

en/integrations/plugin-packs/procedures/applications-hashicorp-vault-restapi.md, en/sidebars.json, fr/integrations/plugin-packs/procedures/applications-hashicorp-vault-restapi.md, fr/sidebars.json
HashiCorp Vault RestAPI monitoring procedure
=> add(epp): HashiCorp Vault RestAPI monit proc

en/releases/centreon-core.md, fr/releases/centreon-core.md
=> enh(release): Add Centreon Gorgone 21.0.4.2 RN

en/releases/centreon-core.md, fr/releases/centreon-core.md
=> enh(release): Add Centreon Gorgone 20.10.5 RN

en/releases/centreon-os-extensions.md, fr/releases/centreon-os-extensions.md
=> add-release-note-centreon-ha

en/api/clapi.md, fr/api/clapi.md
Add info about adding a poller via clapi
=> Add info about adding a poller via clapi

en/monitoring/about.md
Remove some extra text at the bottom of the page
=> MON-11015 remove unwanted text

en/administration/postfix.md, fr/administration/postfix.md
=> Add mailx install command

en/sidebars.json, fr/sidebars.json
Move API chapter to dev resources chapter
=> Move API chapter to dev resources

en/monitoring/pluginpacks.md
A plugin pack does not technically "contain" a plugin and a pack.
=> Improve wording

en/monitoring/pluginpacks.md
=> Fix titles

en/monitoring/about.md, fr/monitoring/about.md
Add info to the introduction, to give a better overview of Centreon
=> Add info to introduction

en/releases/centreon-core.md, fr/releases/centreon-core.md
=> enh(release): Add Centreon Web 20.04.18 RN

en/integrations/plugin-packs/procedures/cloud-prometheus-api.md
=> Fix cloud-prometheus-api

en/releases/centreon-core.md, fr/releases/centreon-core.md
=> enh(release): Add Centreon Web 20.10.11 RN

en/releases/centreon-core.md, fr/releases/centreon-core.md
=> enh(release): Add Centreon Web 21.04.5 RN

fr/releases/centreon-commercial-extensions.md, fr/releases/centreon-core.md
fix french header translations 20.10
REFS: MON-11079
=> fix header translations

fr/installation/installation-of-a-central-server/using-virtual-machines.md
=> Remove underscore

en/installation/installation-of-a-poller/using-centreon-iso.md
Change title level to be consistent with FR
=> Change title level

en/integrations/plugin-packs/procedures/applications-sccm-nsclient.md
=> Fix display

en/integrations/open-tickets/ot-service-now.md, fr/integrations/open-tickets/ot-service-now.md
=> enh(doc): typo fix #973

en/integrations/itsm/ot-service-now.md, fr/integrations/itsm/ot-service-now.md
See https://github.com/centreon/centreon-documentation/pull/976.
=> Change Itop to ServiceNow

fr/upgrade/upgrade-from-20-10.md
=> Remove unnecessary word

en/administration/secure-platform.md, fr/administration/secure-platform.md, fr/graph-views/secure-your-map-platform.md
=> Add missing translation

en/releases/centreon-commercial-extensions.md, fr/releases/centreon-commercial-extensions.md
=> enh(release): Add Centreon MAP 20.10.5 RN

en/installation/installation-of-a-poller/using-packages.md, fr/installation/installation-of-a-poller/using-packages.md
=> Add missing service

en/graph-views/install.md, fr/graph-views/install.md
Remove ambiguous mentions of MySQL
=> Remove ambiguous mentions of MySQL

fr/upgrade/centreon-ha/upgrade-from-20.10.md
update for MariaDB upgrade 10.3 -> 10.5
update macro names
=> Update for mariaDB upgrade

en/upgrade/centreon-ha/upgrade-from-20.10.md
Update MariaDB Procedure by remove steps 10.3 -> 10.4 -> 10.5
corrections of Macros name
=> update MariaDB procedure

en/releases/centreon-core.md, fr/releases/centreon-core.md
=> enh(release): Add Centreon Gorgone 21.04.3 RN

en/releases/centreon-commercial-extensions.md, fr/releases/centreon-commercial-extensions.md
=> enh(release): Add Centreon Anomaly Detection 21.04.1 RN

en/releases/centreon-core.md, fr/releases/centreon-core.md
=> enh(release): Add Centreon Web 20.04.19 RN

en/releases/centreon-core.md, fr/releases/centreon-core.md
=> enh(release): Add Centreon Web 21.04.6 RN

en/releases/centreon-core.md, fr/releases/centreon-core.md
=> enh(release): Add Centreon Web 20.10.12 RN

Jenkinsfile
=> core(doc): make 21.10 releasable

.github/PULL_REQUEST_TEMPLATE.md, website/static/js/versions-select.js
This PR intends to prepare the next serie. (_22.04_)
=> core(doc): prepare 22.04

website/static/js/versions-select.js
Fix versions dropdown list (20.04)
- [x ] 20.04.x
=> Fix versions dropdown list (20.04)

website/static/js/versions-select.js
Fix versions dropdown menu (21.04)
=> Fix versions dropdown menu (21.04)

website/static/js/versions-select.js
Fix versions dropdown menu (20.10)
=> Fix versions dropdown menu (20.10)

website/static/js/versions-select.js
=> fix(select): add 21.10 as current

en/graph-views/troubleshooter.md, fr/graph-views/troubleshooter.md
Fix wrong path to Centreon web UI
=> Fix wrong path

en/installation/installation-of-a-central-server/using-centreon-iso.md, en/installation/installation-of-a-poller/using-centreon-iso.md, en/installation/installation-of-a-remote-server/using-centreon-iso.md, fr/installation/installation-of-a-central-server/using-centreon-iso.md, fr/installation/installation-of-a-poller/using-centreon-iso.md, fr/installation/installation-of-a-remote-server/using-centreon-iso.md
Add address of download site to ISO installation pages
=> Add address of download site to ISO installation pages

en/upgrade/upgrade-from-18-10.md, en/upgrade/upgrade-from-19-04.md, en/upgrade/upgrade-from-19-10.md, en/upgrade/upgrade-from-20-04.md, en/upgrade/upgrade-from-20-10.md, en/upgrade/upgrade-from-21-04.md, en/upgrade/upgrade-from-3-4.md, fr/upgrade/upgrade-from-18-10.md, fr/upgrade/upgrade-from-19-04.md, fr/upgrade/upgrade-from-19-10.md, fr/upgrade/upgrade-from-20-04.md, fr/upgrade/upgrade-from-20-10.md, fr/upgrade/upgrade-from-21-04.md, fr/upgrade/upgrade-from-3-4.md
Copy new conf to customized Apache conf
=> Copy new conf to customized Apache conf

en/administration/secure-platform.md, fr/administration/secure-platform.md
=> fix(security): correct Apache HTTPS configuration for 21.10

en/upgrade/upgrade-from-18-10.md, en/upgrade/upgrade-from-19-04.md, en/upgrade/upgrade-from-19-10.md, en/upgrade/upgrade-from-3-4.md, fr/administration/secure-platform.md, fr/upgrade/upgrade-from-18-10.md, fr/upgrade/upgrade-from-19-04.md, fr/upgrade/upgrade-from-19-10.md, fr/upgrade/upgrade-from-3-4.md
=> fix(security): add missing Apache configuration

en/releases/centreon-commercial-extensions.md, fr/releases/centreon-commercial-extensions.md
=> doc(release): add release note for Centreon Autodiscovery 21.04.2

en/developer/developer-module.md, en/graph-views/install.md, en/installation/installation-of-a-poller/using-centreon-iso.md, en/installation/installation-of-a-poller/using-packages.md, en/installation/installation-of-a-remote-server/using-centreon-iso.md, en/installation/installation-of-a-remote-server/using-packages.md, en/migrate/introduction.md, en/migrate/migrate-from-20-x.md, en/migrate/migrate-from-3-4.md, en/monitoring/discovery/administration.md, en/reporting/upgrade.md, en/service-mapping/install.md, en/upgrade/upgrade-from-3-4.md, en/upgrade/upgrade-mariadb.md, fr/developer/developer-module.md, fr/graph-views/install.md, fr/installation/installation-of-a-poller/using-centreon-iso.md, fr/installation/installation-of-a-poller/using-packages.md, fr/installation/installation-of-a-remote-server/using-centreon-iso.md, fr/installation/installation-of-a-remote-server/using-packages.md, fr/migrate/introduction.md, fr/migrate/migrate-from-20-x.md, fr/migrate/migrate-from-3-4.md, fr/migrate/poller-display-to-remote-server.md, fr/monitoring/discovery/administration.md, fr/reporting/installation.md, fr/reporting/upgrade.md, fr/service-mapping/install.md, fr/upgrade/upgrade-from-3-4.md, fr/upgrade/upgrade-mariadb.md
* Reworded a few sentences about compatibility
* Cleaned up leftover mentions of version 21.04
=> Mon 11566 rewording cleanup

en/monitoring/pluginpacks.md, fr/monitoring/pluginpacks.md
=> Add info about pp repo

en/graph-views/secure-your-map-platform.md, fr/graph-views/secure-your-map-platform.md
=> Remove unnecessary parameter

en/releases/centreon-core.md, fr/releases/centreon-core.md
=> Prepare web 21.04.8

en/releases/centreon-core.md, fr/releases/centreon-core.md
=> enh(release): Add Centreon Web 20.10.13

en/administration/secure-platform.md
=> Fix example

en/releases/centreon-commercial-extensions.md, fr/releases/centreon-commercial-extensions.md
=> doc(release): add release note for centreon-autodiscovery-21.10.1

en/releases/centreon-commercial-extensions.md, fr/releases/centreon-commercial-extensions.md
=> doc(release): add release note for centreon-autodiscovery-21.04.3

en/releases/centreon-commercial-extensions.md, fr/releases/centreon-commercial-extensions.md
=> enh(release): add release note for Centreon Map 21.04.2

en/releases/centreon-core.md, fr/releases/centreon-core.md
=> enh(release): add Centreon Web 20.10.14 RN

Jenkinsfile, sonar-project.properties
Add sonarqube analysis to pipelines
=> enh(chore): add SQ conf file

en/releases/centreon-core.md, fr/releases/centreon-core.md
=> enh(release): Add Centreon Web 20.04.20

en/releases/centreon-core.md, fr/releases/centreon-core.md
=> enh(release): add Centreon Web 21.04.9 RN

en/releases/centreon-core.md, fr/releases/centreon-core.md
=> enh(release): add Centreon Web 21.10.1 RN

en/releases/centreon-core.md, fr/releases/centreon-core.md
=> doc(release): add release note for Centreon Engine 20.04.14

en/releases/centreon-core.md, fr/releases/centreon-core.md
=> doc(release): add release note for Centreon Broker 20.04.17

en/integrations/plugin-packs/procedures/operatingsystems-linux-nrpe3.md, fr/integrations/plugin-packs/procedures/operatingsystems-linux-nrpe3.md
=> Replace http by https

en/releases/centreon-commercial-extensions.md, fr/releases/centreon-commercial-extensions.md
=> enh(release): Add Centreon Bam 21.10.1

en/health/centreon-agent.md, fr/health/centreon-agent.md
Install centreon-helios with the agent
=> Install centreon-helios with the agent

en/integrations/plugin-packs/procedures/applications-databases-db2.md, en/sidebars.json, fr/integrations/plugin-packs/procedures/applications-databases-db2.md, fr/sidebars.json
=> add(epp): DB2 proc

en/integrations/plugin-packs/procedures/applications-databases-redis.md, en/integrations/plugin-packs/procedures/applications-redis-cli.md, en/integrations/plugin-packs/procedures/applications-redis-restapi.md, en/integrations/plugin-packs/procedures/applications-redis-rlec-restapi.md, en/sidebars.json, fr/integrations/plugin-packs/procedures/applications-databases-redis.md, fr/integrations/plugin-packs/procedures/applications-redis-cli.md, fr/integrations/plugin-packs/procedures/applications-redis-restapi.md, fr/integrations/plugin-packs/procedures/applications-redis-rlec-restapi.md, fr/sidebars.json
=> refactoring(epp): redis procedures

en/integrations/plugin-packs/procedures/applications-wallix-bastion-snmp.md, en/sidebars.json, fr/integrations/plugin-packs/procedures/applications-wallix-bastion-snmp.md, fr/sidebars.json
=> add(epp): wallix bastion snmp proc

en/integrations/data-analytics/sc-elastic-events.md, en/integrations/data-analytics/sc-elasticsearch-events.md, fr/integrations/data-analytics/sc-elastic-events.md
Following rewriting of the elastic events [stream connector here](https://github.com/centreon/centreon-stream-connector-scripts/pull/72)
=> (stream) rewrite elastic apiv2 doc

en/integrations/plugin-packs/procedures/applications-openvpn-omi.md, fr/integrations/plugin-packs/procedures/applications-openvpn-omi.md
=> enh(mp): Open VPN OMI

en/integrations/plugin-packs/procedures/applications-php-fpm-web.md, fr/integrations/plugin-packs/procedures/applications-php-fpm-web.md
=> enh(mp): PHP FPM Web

en/integrations/plugin-packs/procedures/applications-php-apc-web.md, fr/integrations/plugin-packs/procedures/applications-php-apc-web.md
=> enh(mp): PHP APC Web

en/integrations/plugin-packs/procedures/hardware-devices-nvidia-gpu-smi-ssh.md, en/sidebars.json, fr/integrations/plugin-packs/procedures/hardware-devices-nvidia-gpu-smi-ssh.md, fr/sidebars.json
=> add(epp): nvidia gpu smi ssh proc

en/integrations/plugin-packs/procedures/applications-ericsson-enm-api.md, en/sidebars.json, fr/integrations/plugin-packs/procedures/applications-ericsson-enm-api.md, fr/sidebars.json
=> add(pack): ericsson enmp api monitoring proc

en/integrations/plugin-packs/procedures/applications-ibm-tsamp-ssh.md, en/sidebars.json, fr/integrations/plugin-packs/procedures/applications-ibm-tsamp-ssh.md, fr/sidebars.json
=> add(epp): IBM TSAMP SSH proc

en/integrations/plugin-packs/procedures/hardware-pdu-gude-epc-snmp.md, en/sidebars.json, fr/integrations/plugin-packs/procedures/hardware-pdu-gude-epc-snmp.md, fr/sidebars.json
=> add(epp): gude epc pdu snmp proc

en/releases/centreon-commercial-extensions.md, fr/releases/centreon-commercial-extensions.md
=> enh(release): Add Centreon PPM 20.10.2 RN

en/releases/centreon-commercial-extensions.md, fr/releases/centreon-commercial-extensions.md
=> enh(release): Add Centreon PPM 21.04.1 RN

en/api/rest-api-v2.md, fr/api/rest-api-v2.md
=> enh(doc) update links

en/administration/centreon-ha/installation-2-nodes.md, fr/administration/centreon-ha/installation-2-nodes.md
=> Update install ha

en/releases/centreon-core.md, fr/releases/centreon-core.md
=> enh(release): Add Centreon Gorgone 21.10.1

en/releases/centreon-core.md, fr/releases/centreon-core.md
=> enh(release): Add Centreon Gorgone 21.04.4

en/releases/centreon-core.md, fr/releases/centreon-core.md
=> enh(release): Add Centreon Gorgone 20.10.6

en/releases/centreon-commercial-extensions.md, fr/releases/centreon-commercial-extensions.md
Release note for centreon map 21.04.3
=> doc: added map 21.04.3 rn

en/releases/centreon-commercial-extensions.md, fr/releases/centreon-commercial-extensions.md
Release note for centreon map 21.10.1 (LOG4J included)
=> doc: added release note for map 21.10.1

en/releases/centreon-commercial-extensions.md, fr/releases/centreon-commercial-extensions.md
Release note for centreon map 20.10.7.
=> doc: added release note for map 20.10.7

en/graph-views/install.md, en/graph-views/upgrade.md, en/installation/installation-of-a-central-server/using-packages.md, en/installation/installation-of-a-poller/using-packages.md, en/installation/installation-of-a-remote-server/using-packages.md, en/upgrade/upgrade-from-18-10.md, en/upgrade/upgrade-from-19-04.md, en/upgrade/upgrade-from-19-10.md, en/upgrade/upgrade-from-20-04.md, en/upgrade/upgrade-from-3-4.md, fr/graph-views/install.md, fr/graph-views/upgrade.md, fr/installation/installation-of-a-central-server/using-packages.md, fr/installation/installation-of-a-poller/using-packages.md, fr/upgrade/upgrade-from-18-10.md, fr/upgrade/upgrade-from-19-04.md, fr/upgrade/upgrade-from-19-10.md, fr/upgrade/upgrade-from-20-04.md, fr/upgrade/upgrade-from-3-4.md
upgrade centreon release rpm
Refs: MON-11903
=> chore(release): upgrade centreon release rpm

en/graph-views/install.md, en/graph-views/upgrade.md, en/health/centreon-agent.md, en/installation/installation-of-a-central-server/using-packages.md, en/installation/installation-of-a-poller/using-packages.md, en/installation/installation-of-a-remote-server/using-packages.md, en/integrations/plugin-packs/procedures/operatingsystems-linux-nrpe3.md, en/upgrade/centreon-ha/upgrade-from-20.04.md, en/upgrade/centreon-ha/upgrade-from-20.10.md, en/upgrade/upgrade-from-18-10.md, en/upgrade/upgrade-from-19-04.md, en/upgrade/upgrade-from-19-10.md, en/upgrade/upgrade-from-20-04.md, en/upgrade/upgrade-from-20-10.md, en/upgrade/upgrade-from-3-4.md, fr/graph-views/install.md, fr/graph-views/upgrade.md, fr/health/centreon-agent.md, fr/installation/installation-of-a-central-server/using-packages.md, fr/installation/installation-of-a-poller/using-packages.md, fr/installation/installation-of-a-remote-server/using-packages.md, fr/integrations/plugin-packs/procedures/operatingsystems-linux-nrpe3.md, fr/upgrade/centreon-ha/upgrade-from-20.04.md, fr/upgrade/centreon-ha/upgrade-from-20.10.md, fr/upgrade/upgrade-from-18-10.md, fr/upgrade/upgrade-from-19-04.md, fr/upgrade/upgrade-from-19-10.md, fr/upgrade/upgrade-from-20-04.md, fr/upgrade/upgrade-from-20-10.md, fr/upgrade/upgrade-from-3-4.md
upgrade centreon release rpm
Refs: MON-11903
=> chore(release): upgrade centreon release rpm (21.04)

en/integrations/plugin-packs/procedures/blockchain-parity-ethpoller-restapi.md, en/sidebars.json, fr/integrations/plugin-packs/procedures/blockchain-parity-ethpoller-restapi.md, fr/sidebars.json
Closes https://github.com/centreon/centreon-documentation/pull/935
=> fix(doc) wrong link to access to blockchain Packs + reorder

en/releases/centreon-commercial-extensions.md, fr/releases/centreon-commercial-extensions.md
=> doc: added release note for map 21.04.4

en/releases/centreon-commercial-extensions.md, fr/releases/centreon-commercial-extensions.md
=> doc: added release note for map 20.10.8

en/releases/centreon-commercial-extensions.md, fr/releases/centreon-commercial-extensions.md
=> doc: added release note for map 21.10.2

en/releases/centreon-commercial-extensions.md, fr/releases/centreon-commercial-extensions.md
=> enh(release): Anomaly 21.04.2 RN

en/getting-started/which-install.md, fr/getting-started/which-install.md
=> enh(getting-started): improve selection of installation type

en/releases/centreon-core.md, fr/releases/centreon-core.md
=> enh(release): Add Centreon Web 21.04.10 RN

en/releases/centreon-core.md, fr/releases/centreon-core.md
=> enh(release): Add Centreon Web 20.10.15 RN

en/releases/centreon-commercial-extensions.md, fr/releases/centreon-commercial-extensions.md
=> enh(release): Add Centreon Anomaly Detection 20.10.1 RN

en/releases/centreon-core.md, fr/releases/centreon-core.md
=> enh(release): Add Centreon Web 21.10.2 RN

en/releases/centreon-commercial-extensions.md, fr/releases/centreon-commercial-extensions.md
=> enh(release): Anomaly 21.10.1 RN

en/releases/centreon-commercial-extensions.md, fr/releases/centreon-commercial-extensions.md
=> enh(release): add release notes for BAM 20.10.5

en/releases/centreon-os-extensions.md, fr/releases/centreon-os-extensions.md
=> enh(release): add Centreon Open Ticket 20.10.3 RN

en/releases/centreon-os-extensions.md, fr/releases/centreon-os-extensions.md
=> enh(release): add Centreon Open Ticket 21.04.2 RN

en/releases/centreon-commercial-extensions.md, fr/releases/centreon-commercial-extensions.md
=> fix release date

en/releases/centreon-commercial-extensions.md, fr/releases/centreon-commercial-extensions.md
=> enh(release): add Centreon License Manager 21.04.1 RN

en/integrations/plugin-packs/procedures/network-microsens-g6-snmp.md, en/sidebars.json, fr/integrations/plugin-packs/procedures/network-microsens-g6-snmp.md, fr/sidebars.json
=> add(epp): microsens g6 snmp proc

en/integrations/plugin-packs/procedures/applications-redis-sentinel.md, en/sidebars.json, fr/integrations/plugin-packs/procedures/applications-redis-sentinel.md, fr/sidebars.json
=> add(epp): redis sentinel proc

en/releases/centreon-commercial-extensions.md, fr/releases/centreon-commercial-extensions.md
=> enh(release): add Centreon License Manager 20.04.6 RN

en/releases/centreon-commercial-extensions.md, fr/releases/centreon-commercial-extensions.md
=> enh(release): add Centreon License Manager 20.10.4 RN

en/graph-views/troubleshooter.md, en/graph-views/update.md, en/graph-views/upgrade.md, en/releases/centreon-commercial-extensions.md, fr/graph-views/troubleshooter.md, fr/graph-views/update.md, fr/graph-views/upgrade.md, fr/releases/centreon-commercial-extensions.md
MON-12000 Add update table for metric names (21.10)
=> MON-12000 Add update table for metric names (21.10)

en/graph-views/troubleshooter.md, en/graph-views/update.md, en/graph-views/upgrade.md, en/releases/centreon-commercial-extensions.md, fr/graph-views/troubleshooter.md, fr/graph-views/update.md, fr/graph-views/upgrade.md, fr/releases/centreon-commercial-extensions.md
MON-12000 Add update table for metric names (21.04)
=> MON-12000 Add update table for metric names (21.04)

en/graph-views/troubleshooter.md, en/graph-views/update.md, en/graph-views/upgrade.md, en/releases/centreon-commercial-extensions.md, fr/graph-views/troubleshooter.md, fr/graph-views/update.md, fr/graph-views/upgrade.md, fr/releases/centreon-commercial-extensions.md
MON-12000 Add update table for metric names (20.10)
=> MON-12000 Add update table for metric names (20.10)

en/integrations/plugin-packs/procedures/virtualization-vmware2-esx.md, en/integrations/plugin-packs/procedures/virtualization-vmware2-vcenter-generic.md, fr/integrations/plugin-packs/procedures/virtualization-vmware2-esx.md, fr/integrations/plugin-packs/procedures/virtualization-vmware2-vcenter-generic.md
=> enh(pack): vmware proc - add services for connector 3.2.2

en/integrations/plugin-packs/procedures/network-fortinet-fortiswitch-snmp.md, en/sidebars.json, fr/integrations/plugin-packs/procedures/network-fortinet-fortiswitch-snmp.md, fr/sidebars.json
=> add(epp): fortinet fortiswitch proc

en/integrations/plugin-packs/procedures/applications-monitoring-centreon-poller.md, fr/integrations/plugin-packs/procedures/applications-monitoring-centreon-poller.md
Refactoring global body of monitoring document, adding SSH configuration details.
Closes https://github.com/centreon/centreon-plugin-packs/issues/857
=> enh(doc) add ssh conf details and refactoring body

en/integrations/plugin-packs/procedures/virtualization-hpe-simplivity-restapi.md, en/sidebars.json, fr/integrations/plugin-packs/procedures/virtualization-hpe-simplivity-restapi.md, fr/sidebars.json
=> add(epp): hpe simplivity restapi proc

en/integrations/plugin-packs/procedures/applications-pvx-restapi.md, en/sidebars.json, fr/integrations/plugin-packs/procedures/applications-pvx-restapi.md, fr/sidebars.json
Documentation enhancement with the new monitoring procedure format.
=> enh(epp): PVX Rest API

en/integrations/plugin-packs/procedures/applications-voip-asterisk-snmp.md, fr/integrations/plugin-packs/procedures/applications-voip-asterisk-snmp.md
Documentation enhancement with the new monitoring procedure format.
=> enh(epp): Asterisk SNMP

en/integrations/plugin-packs/procedures/applications-voip-asterisk-ami.md, fr/integrations/plugin-packs/procedures/applications-voip-asterisk-ami.md
Documentation enhancement with the new monitoring procedure format.
=> enh(epp): Asterisk AMI

en/integrations/plugin-packs/procedures/applications-nmap-cli.md, fr/integrations/plugin-packs/procedures/applications-nmap-cli.md
Following comment on The Watch: https://thewatch.centreon.com/product-how-to-21/network-discovery-nmap-snmp-how-does-it-work-and-how-can-you-help-162?postid=429#post429
Closes https://github.com/centreon/centreon-plugin-packs/issues/974 
Closes https://github.com/centreon/centreon-plugin-packs/issues/979
=> (doc) add more details about how to install Nmap RPMs

en/integrations/plugin-packs/procedures/cloud-microsoft-office365-management.md, fr/integrations/plugin-packs/procedures/cloud-microsoft-office365-management.md
=> update(epp): office365 management proc

en/integrations/plugin-packs/procedures/hardware-devices-hikvision-nvr-snmp.md, en/sidebars.json, fr/integrations/plugin-packs/procedures/hardware-devices-hikvision-nvr-snmp.md, fr/sidebars.json
=> add(epp): hikvision nvr proc

en/integrations/plugin-packs/procedures/hardware-servers-dell-omem-snmp.md, en/sidebars.json, fr/integrations/plugin-packs/procedures/hardware-servers-dell-omem-snmp.md, fr/sidebars.json
=> add(epp): dell omem snmp proc

en/integrations/plugin-packs/procedures/network-barracuda-bma-snmp.md, en/sidebars.json, fr/integrations/plugin-packs/procedures/network-barracuda-bma-snmp.md, fr/sidebars.json
=> add(epp): barracuda bma snmp proc

en/releases/centreon-commercial-extensions.md, fr/releases/centreon-commercial-extensions.md
=> enh(release): Anomaly 20.04.5 RN

en/releases/centreon-core.md, fr/releases/centreon-core.md
broker 20.10.11 release notes
- [x ] 20.10.x
=> doc(release): add release note for centreon-broker-20.10.11

en/releases/centreon-commercial-extensions.md, fr/releases/centreon-commercial-extensions.md
=> Prepare bam 21.04.1

en/releases/centreon-core.md, fr/releases/centreon-core.md
=> enh(release): Add Centreon Web 21.10.3 RN

en/graph-views/troubleshooter.md, en/graph-views/update.md, en/graph-views/upgrade.md, en/releases/centreon-commercial-extensions.md, fr/graph-views/troubleshooter.md, fr/graph-views/update.md, fr/graph-views/upgrade.md, fr/releases/centreon-commercial-extensions.md
MON-12213 Remove section on update tables (20.10)
=> MON-12213 Remove section on update tables (20.10)

en/graph-views/troubleshooter.md, en/graph-views/update.md, en/graph-views/upgrade.md, en/releases/centreon-commercial-extensions.md, fr/graph-views/troubleshooter.md, fr/graph-views/update.md, fr/graph-views/upgrade.md, fr/releases/centreon-commercial-extensions.md
MON-12213 remove section on update table (21-04)
=> MON-12213 remove section on update table (21-04)

en/graph-views/troubleshooter.md, en/graph-views/update.md, en/graph-views/upgrade.md, en/releases/centreon-commercial-extensions.md, fr/graph-views/troubleshooter.md, fr/graph-views/update.md, fr/graph-views/upgrade.md, fr/releases/centreon-commercial-extensions.md
MON-12213 Remove section on update table 21.10
=> MON-12213 Remove section on update table 21.10

en/releases/centreon-commercial-extensions.md, fr/releases/centreon-commercial-extensions.md
=> enh(release): Add Centreon PPM 20.04.3 RN

en/releases/centreon-core.md, fr/releases/centreon-core.md
=> enh(release): Add Centreon Web 21.04.11 RN

i18n/fr/docusaurus-plugin-content-docs/version-20.04/releases/centreon-commercial-extensions.md, versioned_docs/version-20.04/releases/centreon-commercial-extensions.md
Migration: enh(release): Add Centreon PPM 20.04.3 RN (#1290)
=> Migration: enh(release): Add Centreon PPM 20.04.3 RN (#1290)

i18n/fr/docusaurus-plugin-content-docs/version-21.04/releases/centreon-core.md, i18n/fr/docusaurus-plugin-content-docs/version-21.10/releases/centreon-core.md, versioned_docs/version-21.04/releases/centreon-core.md, versioned_docs/version-21.10/releases/centreon-core.md
- Add Gorgone 21.10.2 RN
- Fix Gorgone 21.10.0 RN
- Add Gorgone 21.04.5 RN
- Fix Gorgone 21.04.2 RN
=> enh(release): Add Centreon Gorgone v21.10.2 & 21.04.5 RN

i18n/fr/docusaurus-plugin-content-docs/version-20.10/monitoring/monitoring-servers/add-a-remote-server-to-configuration.md, i18n/fr/docusaurus-plugin-content-docs/version-21.04/monitoring/monitoring-servers/add-a-remote-server-to-configuration.md, i18n/fr/docusaurus-plugin-content-docs/version-21.10/monitoring/monitoring-servers/add-a-remote-server-to-configuration.md, versioned_docs/version-20.10/monitoring/monitoring-servers/add-a-remote-server-to-configuration.md, versioned_docs/version-21.04/monitoring/monitoring-servers/add-a-remote-server-to-configuration.md, versioned_docs/version-21.10/monitoring/monitoring-servers/add-a-remote-server-to-configuration.md
=> Fix incorrect end of tab

i18n/fr/docusaurus-plugin-content-docs/version-21.04/releases/centreon-commercial-extensions.md, versioned_docs/version-21.04/releases/centreon-commercial-extensions.md
=> Release note MBI 21.04

i18n/fr/docusaurus-plugin-content-docs/version-22.04/administration/secure-platform.md, versioned_docs/version-22.04/administration/secure-platform.md
This PR intends to add samesite parameter to set cookie directive
=> add samesite parameter to set cookie (next)

i18n/fr/docusaurus-plugin-content-docs/version-20.04/administration/secure-platform.md, i18n/fr/docusaurus-plugin-content-docs/version-20.10/administration/secure-platform.md, i18n/fr/docusaurus-plugin-content-docs/version-21.04/administration/secure-platform.md, i18n/fr/docusaurus-plugin-content-docs/version-21.10/administration/secure-platform.md, versioned_docs/version-20.04/administration/secure-platform.md, versioned_docs/version-20.10/administration/secure-platform.md, versioned_docs/version-21.04/administration/secure-platform.md, versioned_docs/version-21.10/administration/secure-platform.md
This PR intends to add samesite parameter to set cookie directive
=> add samesite parameter to set cookie

i18n/fr/docusaurus-plugin-content-docs/version-21.04/releases/centreon-core.md, i18n/fr/docusaurus-plugin-content-docs/version-21.10/releases/centreon-core.md, versioned_docs/version-21.04/releases/centreon-core.md, versioned_docs/version-21.10/releases/centreon-core.md
Collect 21.10.1 RN + few 21.04 typos fixes
=> enh(release): Add Centreon Collect 21.10.1 RN + fix 21.04 typos

i18n/fr/docusaurus-plugin-content-docs/version-21.10/getting-started/monitor-linux-server-with-snmp.md, i18n/fr/docusaurus-plugin-content-docs/version-21.10/getting-started/mysql_tuto.md, versioned_docs/version-21.10/getting-started/monitor-linux-server-with-snmp.md, versioned_docs/version-21.10/getting-started/mysql_tuto.md
Fix minor problems in tutorials
=> Fix minor problems in tutorials

i18n/fr/docusaurus-plugin-content-docs/version-20.04/releases/centreon-commercial-extensions.md, versioned_docs/version-20.04/releases/centreon-commercial-extensions.md
=> Update centreon-commercial-extensions.md MAP 20.04.8 notice

i18n/fr/docusaurus-plugin-content-docs/version-22.04/administration/secure-platform.md, versioned_docs/version-22.04/administration/secure-platform.md
Fix MON-12149
Related to [this ticket](https://centreon.atlassian.net/jira/software/c/projects/MON/boards/113?modal=detail&selectedIssue=MON-12149&sprint=662)
=> Improve Apache configuration to enable HSTS (next)

versioned_docs/version-21.04/releases/centreon-core.md
=> Remove incorrect ticket - EN

i18n/fr/docusaurus-plugin-content-docs/version-21.04/releases/centreon-core.md
=> Remove incorrect ticket - FR

i18n/fr/docusaurus-plugin-content-docs/version-21.10/releases/centreon-commercial-extensions.md, versioned_docs/version-21.10/releases/centreon-commercial-extensions.md
=> enh(release): Prepare Centreon MAP 21.10.3 RN

i18n/fr/docusaurus-plugin-content-docs/version-20.10/releases/centreon-commercial-extensions.md, versioned_docs/version-20.10/releases/centreon-commercial-extensions.md
=> enh(release): Add Centreon MAP 20.10.9 RN

i18n/fr/docusaurus-plugin-content-docs/version-20.04/integrations/plugin-packs/procedures/applications-monitoring-centreon-database.md, i18n/fr/docusaurus-plugin-content-docs/version-20.10/integrations/plugin-packs/procedures/applications-monitoring-centreon-database.md, i18n/fr/docusaurus-plugin-content-docs/version-21.04/integrations/plugin-packs/procedures/applications-monitoring-centreon-database.md, i18n/fr/docusaurus-plugin-content-docs/version-21.10/integrations/plugin-packs/procedures/applications-monitoring-centreon-database.md, versioned_docs/version-20.04/integrations/plugin-packs/procedures/applications-monitoring-centreon-database.md, versioned_docs/version-20.10/integrations/plugin-packs/procedures/applications-monitoring-centreon-database.md, versioned_docs/version-21.04/integrations/plugin-packs/procedures/applications-monitoring-centreon-database.md, versioned_docs/version-21.10/integrations/plugin-packs/procedures/applications-monitoring-centreon-database.md
New PR to improve centreon database documenation.
[Previous PR in docv1 format](https://github.com/centreon/centreon-documentation/pull/1274) that was approved.
=> enh(pp) : centreon database documentation for doc v2

i18n/fr/docusaurus-plugin-content-docs/version-21.10/releases/centreon-core.md, versioned_docs/version-21.10/releases/centreon-core.md
=> enh(release): Add Centreon Web 21.10.4 RN

i18n/fr/docusaurus-plugin-content-docs/version-22.04/administration/secure-platform.md, versioned_docs/version-22.04/administration/secure-platform.md
=> (22.04) add .html to avoid 500 error

i18n/fr/docusaurus-plugin-content-docs/version-21.04/releases/centreon-core.md, versioned_docs/version-21.04/releases/centreon-core.md
=> enh(release): Add Centreon Broker 21.04.7 RN

i18n/fr/docusaurus-plugin-content-docs/version-21.10/releases/centreon-core.md, versioned_docs/version-21.10/releases/centreon-core.md
=> fix(doc): add web 21.10.4 rn date

i18n/fr/docusaurus-plugin-content-docs/version-20.04/integrations/plugin-packs/procedures/network-viptela-snmp.md, i18n/fr/docusaurus-plugin-content-docs/version-20.10/integrations/plugin-packs/procedures/network-viptela-snmp.md, i18n/fr/docusaurus-plugin-content-docs/version-21.04/integrations/plugin-packs/procedures/network-viptela-snmp.md, i18n/fr/docusaurus-plugin-content-docs/version-21.10/integrations/plugin-packs/procedures/network-viptela-snmp.md, versioned_docs/version-20.04/integrations/plugin-packs/procedures/network-viptela-snmp.md, versioned_docs/version-20.10/integrations/plugin-packs/procedures/network-viptela-snmp.md, versioned_docs/version-21.04/integrations/plugin-packs/procedures/network-viptela-snmp.md, versioned_docs/version-21.10/integrations/plugin-packs/procedures/network-viptela-snmp.md
next : https://github.com/centreon/centreon-documentation/pull/1359
=> add(epp): viptela snmp docusaurus v2 staging

i18n/fr/docusaurus-plugin-content-docs/version-20.04/integrations/plugin-packs/procedures/applications-monitoring-iplabel-ekara-restapi.md, i18n/fr/docusaurus-plugin-content-docs/version-20.10/integrations/plugin-packs/procedures/applications-monitoring-iplabel-ekara-restapi.md, i18n/fr/docusaurus-plugin-content-docs/version-21.04/integrations/plugin-packs/procedures/applications-monitoring-iplabel-ekara-restapi.md, i18n/fr/docusaurus-plugin-content-docs/version-21.10/integrations/plugin-packs/procedures/applications-monitoring-iplabel-ekara-restapi.md, versioned_docs/version-20.04/integrations/plugin-packs/procedures/applications-monitoring-iplabel-ekara-restapi.md, versioned_docs/version-20.10/integrations/plugin-packs/procedures/applications-monitoring-iplabel-ekara-restapi.md, versioned_docs/version-21.04/integrations/plugin-packs/procedures/applications-monitoring-iplabel-ekara-restapi.md, versioned_docs/version-21.10/integrations/plugin-packs/procedures/applications-monitoring-iplabel-ekara-restapi.md, versioned_sidebars/version-20.04-sidebars.json, versioned_sidebars/version-20.10-sidebars.json, versioned_sidebars/version-21.04-sidebars.json, versioned_sidebars/version-21.10-sidebars.json
Monitoring procedure for IP-Label Ekara RestAPI (all versions)
next : https://github.com/centreon/centreon-documentation/pull/1369
=> add(epp): Ekara monitoring proc

i18n/fr/docusaurus-plugin-content-docs/version-20.04/integrations/plugin-packs/procedures/network-fortinet-fortiadc-snmp.md, i18n/fr/docusaurus-plugin-content-docs/version-20.10/integrations/plugin-packs/procedures/network-fortinet-fortiadc-snmp.md, i18n/fr/docusaurus-plugin-content-docs/version-21.04/integrations/plugin-packs/procedures/network-fortinet-fortiadc-snmp.md, i18n/fr/docusaurus-plugin-content-docs/version-21.10/integrations/plugin-packs/procedures/network-fortinet-fortiadc-snmp.md, versioned_docs/version-20.04/integrations/plugin-packs/procedures/network-fortinet-fortiadc-snmp.md, versioned_docs/version-20.10/integrations/plugin-packs/procedures/network-fortinet-fortiadc-snmp.md, versioned_docs/version-21.04/integrations/plugin-packs/procedures/network-fortinet-fortiadc-snmp.md, versioned_docs/version-21.10/integrations/plugin-packs/procedures/network-fortinet-fortiadc-snmp.md
=> add(epp): fortinet fortiadc snmp docusaurus v2 staging

i18n/fr/docusaurus-plugin-content-docs/version-20.10/releases/centreon-commercial-extensions.md, i18n/fr/docusaurus-plugin-content-docs/version-21.10/releases/centreon-commercial-extensions.md, versioned_docs/version-20.10/releases/centreon-commercial-extensions.md, versioned_docs/version-21.10/releases/centreon-commercial-extensions.md
=> enh(doc): add notice about additional actions after upgrade

i18n/fr/docusaurus-plugin-content-docs/version-22.04/integrations/plugin-packs/procedures/applications-monitoring-centreon-database.md, versioned_docs/version-22.04/integrations/plugin-packs/procedures/applications-monitoring-centreon-database.md
Improving centreon database documenation.
[Staging PR](https://github.com/centreon/centreon-documentation/pull/1331)
=> Next 22.04 - Adding details for Centreon DB monitoring proc

i18n/fr/docusaurus-plugin-content-docs/version-21.04/mobile/introduction.md, i18n/fr/docusaurus-plugin-content-docs/version-21.10/mobile/introduction.md, versioned_docs/version-21.04/mobile/introduction.md, versioned_docs/version-21.10/mobile/introduction.md
=> enh(mobile): remove Configuration API access

i18n/fr/docusaurus-plugin-content-docs/version-22.04/mobile/introduction.md, versioned_docs/version-22.04/mobile/introduction.md
=> enh(mobile): remove Configuation API access (next)

i18n/fr/docusaurus-plugin-content-docs/version-20.10/releases/centreon-core.md, versioned_docs/version-20.10/releases/centreon-core.md
=> doc(release): add release note for centreon-broker-20.10.12

versioned_docs/version-21.10/api/clapi.md
=> Explain «setmacro»

i18n/fr/docusaurus-plugin-content-docs/version-21.10/api/clapi.md
EN : https://github.com/centreon/centreon-documentation/pull/1379
=> Explain "setmacro" FR

cloud/alerts-notifications/notif-configuration.md, cloud/getting-started/architecture.md, cloud/getting-started/interface.md, cloud/getting-started/monitoring.md, cloud/installation/deploy-poller.md, cloud/monitoring/pluginpacks.md, docusaurus.config.js, i18n/fr/docusaurus-plugin-content-docs-cloud/current/getting-started/architecture.md, i18n/fr/docusaurus-plugin-content-docs-cloud/current/getting-started/autodisco-aws.md, i18n/fr/docusaurus-plugin-content-docs-cloud/current/getting-started/interface.md, i18n/fr/docusaurus-plugin-content-docs-cloud/current/installation/deploy-poller.md, i18n/fr/docusaurus-plugin-content-docs/version-21.10/getting-started/monitor-windows-server-with-snmp.md, i18n/fr/docusaurus-plugin-content-pages/index.js, src/pages/index.js, static/js/fix-location.js
=> enhancement: add trailing slash in config

i18n/fr/docusaurus-plugin-content-docs/version-21.04/releases/centreon-core.md, versioned_docs/version-21.04/releases/centreon-core.md
=> enh(release): Add Centreon Web 21.04.12 RN

i18n/fr/docusaurus-plugin-content-docs/version-21.10/releases/centreon-commercial-extensions.md, versioned_docs/version-21.10/releases/centreon-commercial-extensions.md
=> enh(release): prepare Auto Discovery 21.10.2 RN

versioned_docs/version-21.04/releases/centreon-core.md
=> Add date to RN (EN)

i18n/fr/docusaurus-plugin-content-docs/version-21.04/releases/centreon-core.md
=> Add date to RN (FR)

i18n/fr/docusaurus-plugin-content-pages/index.js, src/pages/index.js
Clean up before exclamation mark on home page (EN remove space, FR insert nonbreaking space)
=> Clean up before exclamation mark 

versioned_docs/version-21.10/administration/licenses.md
=> French word in EN

i18n/fr/docusaurus-plugin-content-docs/version-22.04/getting-started/it100.md, versioned_docs/version-22.04/getting-started/it100.md
Troubleshooting IT-100 on branch next
=> Troubleshooting IT-100 (next)

i18n/fr/docusaurus-plugin-content-docs/version-21.10/getting-started/it100.md, versioned_docs/version-21.10/getting-started/it100.md
FIx incorrect path for error log
=> FIx incorrect path

versioned_docs/version-20.04/reporting/installation.md, versioned_docs/version-20.10/reporting/installation.md, versioned_docs/version-21.04/reporting/installation.md
=> Fix wrong version of MariaDB

.github/PULL_REQUEST_TEMPLATE.md
Add Cloud and PP sections to pull request template
=> Add Cloud and PP sections to pull request template

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-monitoring-centreon-central.md, pp/integrations/plugin-packs/procedures/applications-monitoring-centreon-central.md
New PR to improve centreon central documentation.
Previous PR before PP migration https://github.com/centreon/centreon-documentation/pull/1333
=> enh(pp) : centreon central monitoring documentation Staging

i18n/fr/docusaurus-plugin-content-docs/version-21.10/releases/centreon-commercial-extensions.md, versioned_docs/version-21.10/releases/centreon-commercial-extensions.md
RN for centreon-autodiscovery-21.10.3
=> doc(release): add release note for centreon-autodiscovery-21.10.3

i18n/fr/docusaurus-plugin-content-docs/version-22.04/monitoring/monitoring-servers/advanced-configuration.md, versioned_docs/version-22.04/monitoring/monitoring-servers/advanced-configuration.md
=> Add authorized directories for Broker Cache Directory

i18n/fr/docusaurus-plugin-content-docs/version-21.04/releases/centreon-commercial-extensions.md, versioned_docs/version-21.04/releases/centreon-commercial-extensions.md
RN for centreon-autodiscovery-21.04.4
=> doc(release): add release note for centreon-autodiscovery-21.04.4

i18n/fr/docusaurus-plugin-content-docs/version-20.10/releases/centreon-core.md, versioned_docs/version-20.10/releases/centreon-core.md
=> enh(release): Add Centreon Web 20.10.16 RN v2

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-activemq-jmx.md, i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-google-workspace-api.md, i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-jvm-jmx.md, i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-webservers-iis-restapi.md, i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-freebox-restapi.md, i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/tutorials/collect-openmetrics.md, pp/integrations/plugin-packs/procedures/applications-activemq-jmx.md, pp/integrations/plugin-packs/procedures/applications-antivirus-kaspersky-snmp.md, pp/integrations/plugin-packs/procedures/applications-google-workspace-api.md, pp/integrations/plugin-packs/procedures/applications-jvm-jmx.md, pp/integrations/plugin-packs/procedures/applications-webservers-iis-restapi.md, pp/integrations/plugin-packs/procedures/cloud-microsoft-office365-teams.md, pp/integrations/plugin-packs/procedures/network-freebox-restapi.md, pp/integrations/plugin-packs/procedures/operatingsystems-windows-nsclient-05-nrpe.md, pp/integrations/plugin-packs/tutorials/collect-openmetrics.md, versioned_docs/version-21.10/upgrade/upgrade-from-20-04.md, versioned_docs/version-21.10/upgrade/upgrade-from-20-10.md, versioned_docs/version-21.10/upgrade/upgrade-from-21-04.md
Remove extra sentence + fix various things
=> Minor corrections

i18n/fr/docusaurus-plugin-content-docs/version-22.04/monitoring/basic-objects/commands.md, versioned_docs/version-22.04/monitoring/basic-objects/commands.md
Completing connectors documentation
=> enh(connectors): complete connector documentation for future release

i18n/fr/docusaurus-plugin-content-docs/version-21.10/getting-started/it100.md, versioned_docs/version-21.10/getting-started/it100.md
=> Change text for IT-100 token

versioned_docs/version-22.04/alerts-notifications/custom-views.md, versioned_docs/version-22.04/monitoring/basic-objects/hosts.md, versioned_docs/version-22.04/monitoring/basic-objects/meta-services.md, versioned_docs/version-22.04/monitoring/basic-objects/services.md, versioned_docs/version-22.04/monitoring/discovery/hosts-discovery.md, versioned_docs/version-22.04/monitoring/generic-actions.md, versioned_docs/version-22.04/monitoring/monitoring-servers/add-a-poller-to-configuration.md, versioned_docs/version-22.04/monitoring/monitoring-servers/add-a-remote-server-to-configuration.md, versioned_docs/version-22.04/monitoring/monitoring-servers/communications.md, versioned_docs/version-22.04/monitoring/monitoring-servers/move-poller.md
Migrate <img> elements to markdown format
=> Migrate <img> elements

i18n/fr/docusaurus-plugin-content-docs/version-22.04/getting-started/it100.md, versioned_docs/version-22.04/getting-started/it100.md
=> Change text for IT-100 token - Next

i18n/fr/docusaurus-plugin-content-docs/version-22.04/alerts-notifications/custom-views.md, i18n/fr/docusaurus-plugin-content-docs/version-22.04/monitoring/basic-objects/hosts.md, i18n/fr/docusaurus-plugin-content-docs/version-22.04/monitoring/basic-objects/services.md, i18n/fr/docusaurus-plugin-content-docs/version-22.04/monitoring/discovery/hosts-discovery.md, i18n/fr/docusaurus-plugin-content-docs/version-22.04/monitoring/generic-actions.md, i18n/fr/docusaurus-plugin-content-docs/version-22.04/monitoring/monitoring-servers/add-a-poller-to-configuration.md, i18n/fr/docusaurus-plugin-content-docs/version-22.04/monitoring/monitoring-servers/add-a-remote-server-to-configuration.md, i18n/fr/docusaurus-plugin-content-docs/version-22.04/monitoring/monitoring-servers/communications.md, i18n/fr/docusaurus-plugin-content-docs/version-22.04/monitoring/monitoring-servers/move-poller.md
Migrate img elements to markdown format (FR)
=> Migrate <img> elements (FR)

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-aws-backup.md, pp/integrations/plugin-packs/procedures/cloud-aws-backup.md
Adding information about how to donwload awscli latest version.
=> enh(epp): adding more accurate info about awscli install

i18n/fr/docusaurus-plugin-content-pages/index.js, src/pages/index.js
=> Fix link on homepage

i18n/fr/docusaurus-plugin-content-docs/version-20.10/releases/centreon-core.md, versioned_docs/version-20.10/releases/centreon-core.md
=> enh(release): Add Centreon Web 20.10.17 RN

i18n/fr/docusaurus-plugin-content-docs/version-20.10/releases/centreon-commercial-extensions.md, versioned_docs/version-20.10/releases/centreon-commercial-extensions.md
=> enh(release): Add Centreon MAP 20.10.10 RN

i18n/fr/docusaurus-plugin-content-docs/version-20.10/installation/installation-of-a-remote-server/using-packages.md, i18n/fr/docusaurus-plugin-content-docs/version-21.04/installation/installation-of-a-remote-server/using-packages.md, i18n/fr/docusaurus-plugin-content-docs/version-21.10/installation/installation-of-a-remote-server/using-packages.md, versioned_docs/version-20.10/installation/installation-of-a-remote-server/using-packages.md, versioned_docs/version-21.04/installation/installation-of-a-remote-server/using-packages.md, versioned_docs/version-21.10/installation/installation-of-a-remote-server/using-packages.md
=> Fix incorrect command

i18n/fr/docusaurus-plugin-content-docs/version-21.10/releases/centreon-commercial-extensions.md, versioned_docs/version-21.10/releases/centreon-commercial-extensions.md
=> enh(release): Add Centreon MAP 21.10.4 RN

i18n/fr/docusaurus-plugin-content-docs/version-22.04/resources/known-issues.md, versioned_docs/version-22.04/resources/known-issues.md
* Move known issues section from table to chapters
* Add procedure to upgrade MBI columns from int to bigint
* Remove BAM known issues which is not relevant anymore
=> known-issues(mbi): refacto known issues + add procedure for MBI bigint columns

i18n/fr/docusaurus-plugin-content-docs/version-21.10/releases/lifecycle.md, versioned_docs/version-21.10/releases/lifecycle.md
Update table of Centreon versions
=> Update table of Centreon versions

i18n/fr/docusaurus-plugin-content-docs/version-22.04/monitoring/pluginpacks.md, versioned_docs/version-22.04/monitoring/pluginpacks.md
Automatic installation of plugin packs
=> Automatic installation of plugin packs

i18n/fr/docusaurus-plugin-content-docs/version-22.04/graph-views/update.md, i18n/fr/docusaurus-plugin-content-docs/version-22.04/graph-views/upgrade.md, versioned_docs/version-22.04/graph-views/update.md, versioned_docs/version-22.04/graph-views/upgrade.md
Add info about centreon-map.conf file (next)
=> Add info about centreon-map.conf file (next)
