centreon/centreon-documentation

en/upgrade/upgrade-from-3-4.md, fr/upgrade/upgrade-from-3-4.md
Add information about the "new" plugins location for old platforms to avoid the "unknow" output from not found plugins
=> enh: add plugins symbolic link to new location

fr/api/restapi-v1.md
The Error codes part of the documentation wasn't well formatted, this PR format the array of error codes with markdown syntax.
=> Update the Error codes section

en/administration/centreon-ha/installation-2-nodes.md, en/administration/centreon-ha/update.md, fr/administration/centreon-ha/installation-2-nodes.md, fr/administration/centreon-ha/update.md
Gorgone manages cron in HA setup. It's important to remove legacy ones. 
This documentation will only be applicable with the next centreon-ha bugfix release.
=> enh(doc)ha-cron-management

en/administration/centreon-ha/installation-2-nodes.md, fr/administration/centreon-ha/installation-2-nodes.md
In despite of specify the values:
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
The service was listening on Ipv6 (::5403). After add the value "-4" to the parameter "COROSYNC_QNETD_OPTIONS" the service is just listening on IPv4.
=> enh(doc)centreon-ha disable ipv6 on corosync-qnetd

en/releases/introduction.md
Link to HA was broken and refering to old page. It has been fixed with the current path.
=> fix(doc): fixed wrong link to ha architectures

en/integrations/plugin-packs/procedures/operatingsystems-windows-nsclient-05-restapi.md, fr/integrations/plugin-packs/procedures/operatingsystems-windows-nsclient-05-restapi.md
* yum install x 2
* there must be a space before colon in French
* there must not be one in English
* useless double empty lines
=> enh(pp): typos in windows nsclient restapi pp procedure

en/administration/centreon-ha/update.md, fr/administration/centreon-ha/update.md
The symfony cache needs to be regenerated on the slave server after an update.
=> fix(centreon-ha): Missing cache regeneration in update procedure

en/assets/reporting/installation/centreon.cnf, fr/assets/reporting/installation/centreon.cnf
tmp_table_size can't be smaller than max_heap_table_size 
https://mariadb.com/kb/en/server-system-variables/#tmp_table_size
=> enh(conf) - max_heap_table_size wrong value

en/administration/centreon-ha/installation-4-nodes.md, en/administration/centreon-ha/upgrade-from-centreon-failover.md, en/sidebars.json, fr/administration/centreon-ha/installation-4-nodes.md, fr/administration/centreon-ha/upgrade-from-centreon-failover.md, fr/sidebars.json
This PR introduces 4 nodes HA setup and gives a very standard procedure about migration process from legacy centreon-failover to centreon-ha architecture.
=> enh(centreon-ha)4-nodes-setup_and_upgrade_from_centreon-failover

en/administration/centreon-ha/upgrade-from-centreon-failover.md, fr/administration/centreon-ha/upgrade-from-centreon-failover.md
this PR aims at fixing broken links in the upgrade documentation for centreon-ha/centreon-failover
=> Fix link ha migration

en/administration/secure-platform.md, fr/administration/secure-platform.md
Add Documentation to disable mod_security unmatched boundary rules.
This rule block the license uploading with a platform in https.
Their is no possibility to override this SecRule into Centreon apache conf.
Fixes: #MON-5881
=> fix(license upload):disable mod_security

en/administration/centreon-ha/installation-2-nodes.md, fr/administration/centreon-ha/installation-2-nodes.md
Manage both Redhat and CentOS best practices about ms_mysql resource configuration
=> Fix(anomaly) remove master redhat ha documentation paragraph

en/administration/secure-platform.md, fr/administration/secure-platform.md
Improve Apache security by disabling trace.
=> enh(security): disable http trace option in http configuration

en/releases/centreon-commercial-extensions.md, fr/releases/centreon-commercial-extensions.md
Centreon License Manager 20.10.1 release notes
=> enh(release): Add Centreon LM 20.10.1 release notes

en/integrations/plugin-packs/procedures/applications-sccm-nsclient.md
Added the extra precision about needing to run the plugin on the server hosting the sccm admin console (multiples users tried to run it on other nodes resulting in errors)
=> SCCM plugins needs the sccm admin console

en/integrations/plugin-packs/procedures/applications-gorgone-restapi.md, fr/integrations/plugin-packs/procedures/applications-gorgone-restapi.md
* uncopiable commands because trailing spaces/tabs
* docusaurus tabs not working because of triple back-quotes instead of
single ones
* other minor issues
=> enh(epp): markdown issues in the Gorgone monitoring procedure

en/integrations/plugin-packs/procedures/cloud-cloudfoundry-api.md
The package is currently named :
centreon-plugin-Cloud-Cloudfoundry-Restapi 
and not 
centreon-plugin-Cloud-Cloudfoundry-Api
=> fix(epp) error in the Plugin package name in Cloudfoundry monitoring procedure

en/administration/centreon-ha/monitoring-guide.md, en/integrations/plugin-packs/procedures/applications-monitoring-centreon-ha.md, fr/administration/centreon-ha/monitoring-guide.md, fr/integrations/plugin-packs/procedures/applications-monitoring-centreon-ha.md
The addition of centreon-engine in haclient group was missing in the procedure
=> fix(pp): haclient group missing in centreon-ha monitoring procedure

en/releases/centreon-core.md, fr/releases/centreon-core.md
Release notes for Centreon Web 20.10.2
=> enh(release): add Centreon Web 20.10.2 release notes

en/installation/architectures.md, en/installation/prerequisites.md, en/monitoring/monitoring-servers/add-a-poller-to-configuration.md, en/monitoring/monitoring-servers/add-a-remote-server-to-configuration.md, fr/installation/architectures.md, fr/installation/prerequisites.md, fr/monitoring/monitoring-servers/add-a-poller-to-configuration.md, fr/monitoring/monitoring-servers/add-a-remote-server-to-configuration.md
Update communication type notes when adding monitoring servers (SSH with Remote Server deprecated, SSH legacy port not used anymore).
Update centreon-gorgone group membership.
Update network flows tables (remove HTTP between Central and Remote Server, better show difference between Poller and Remote Server, add registration action).
=> enh(multi): monitoring servers addition, group membership, network flows

en/getting-started/installation-first-steps.md, en/installation/web-and-post-installation.md, fr/getting-started/installation-first-steps.md, fr/installation/web-and-post-installation.md
When we follow the documentation, there are totally illogical actions.
My experience on the simple use of the documentation is not very good: we ask users to create an online account without explaining why, and then do the installation. At the end of the web installation, we redirect the users directly to the integration of Linux controls. It would be much better to get them to connect for the first time, to discover how the product works, to put their token to benefit from the PPs, setting up PP and finally to configure the first controls. There are some steps that are not logical.
The path is almost the same when you come from the website except that you invite the user directly to create an account. However, the path remains the same afterwards. 
- At the end of the web installation, …
=> improve user xp during the first steps of installation process

en/integrations/plugin-packs/procedures/applications-databases-oracle.md, fr/integrations/plugin-packs/procedures/applications-databases-oracle.md
The current monitoring procedure for Oracle Database does not correctly describe the export of the two variables: ORACLE_HOME and LD_LIBRARY_PATH. This request fixes the paths and rewrites all in the new documentation format.
=> feat(pack): add new-procedure-database-oracle-v3

en/administration/centreon-ha/installation-2-nodes.md, en/administration/centreon-ha/installation-4-nodes.md, en/administration/centreon-ha/integrating-pollers.md, en/sidebars.json, fr/administration/centreon-ha/installation-2-nodes.md, fr/administration/centreon-ha/installation-4-nodes.md, fr/administration/centreon-ha/integrating-pollers.md, fr/sidebars.json
* Since centreon-ha 20.10 and the addition of centreon-gorgone, there are new actions to perform to make both central nodes able to connect to a poller's gorgone service.
* pcs, pacemaker, corosync and corosync-qdevice are no longer dependencies of centreon-ha (to ease the setup of manual failover) so they have to be explicitely installed in the installation process
=> Ome ha fix installation issues 20210112

en/installation/installation-of-a-poller/using-packages.md, en/integrations/plugin-packs/procedures/operatingsystems-linux-nrpe3.md, fr/installation/installation-of-a-poller/using-packages.md, fr/integrations/plugin-packs/procedures/operatingsystems-linux-nrpe3.md
Small typo fixed in the name of the centreon-release rpm for centos8
=> fix(doc): update release rpm link in doc

en/integrations/plugin-packs/procedures/cloud-azure-compute-virtualmachine.md, fr/integrations/plugin-packs/procedures/cloud-azure-compute-virtualmachine.md
MON-7111: if using a proxy, perl-LWP-Protocol-connect̀ is needed
=> enh(pp): adding the instruction to install perl dependancy (MON-7111)

en/monitoring/monitoring-servers/advanced-configuration.md, fr/monitoring/monitoring-servers/advanced-configuration.md
* New log parameters in *General* tab for broker logs v2 :heart: 
* Old logs are being deprecated
=> enh(broker): add doc for new logs + deprecated old logs

en/administration/secure-platform.md, en/graph-views/secure-your-map-platform.md
In order to help users who want secure their platforms, but does not have necesseraly the need of passing through a certification authority, we add sections where self-signed certification procedure is explained. 
Targeted parts are:
- Map server
- Broker <-> Map server sockets
- Map server <-> Centreon web
=> Prepare map ssl config documentation

en/administration/secure-platform.md, en/graph-views/secure-your-map-platform.md
In order to help users who want secure their platforms, but does not have necesseraly the need of passing through a certification authority, we add sections where self-signed certification procedure is explained.
Targeted parts are:
Map server
Broker <-> Map server sockets
Map server <-> Centreon web
=> add self-signed certificat procedures to secure map and centreon web

en/administration/secure-platform.md, en/graph-views/secure-your-map-platform.md
Update the "Securing the Apache web server with self-signed certificat" section to prompt users to use AES 256 over DES 3.
=> replace des3 algo by aes256

fr/upgrade/upgrade-from-20-10.md
missing .html at fr/migrate/migrate-from-20-x.html reported by an user from Centreon Community Slack
=> fix broken link

fr/integrations/plugin-packs/procedures/applications-databases-oracle.md
/usr/lib/oracle/21.1/client64 -> /usr/lib/oracle/21/client64
=> fix(epp):  Oracle plugin correct path [FR]

en/integrations/stream-connectors/sc-opsgenie.md, fr/integrations/stream-connectors/sc-opsgenie.md
add a warning message because the stream connector documentation describes what must be done in opsgenie. And since it can change....
=> add a warning message in opsgenie doc

.github/PULL_REQUEST_TEMPLATE.md
=> enh(doc): remove master from 21.04.x

website/static/css/main.css
Made tabs in documentation easier to see :
- The text of the selected tab is now bold.
- The appearance of the tab on mouseover matches that of selected tabs, to make it more obvious you can click them.
=> Make tabs easier to see

en/administration/secure-platform.md, en/upgrade/upgrade-from-18-10.md, en/upgrade/upgrade-from-19-04.md, en/upgrade/upgrade-from-19-10.md, en/upgrade/upgrade-from-3-4.md, fr/administration/secure-platform.md, fr/upgrade/upgrade-from-18-10.md, fr/upgrade/upgrade-from-19-04.md, fr/upgrade/upgrade-from-19-10.md, fr/upgrade/upgrade-from-3-4.md
Users have complained that the procedure on how to enable HTTPS on the web server does not appear in the search results. Changing the corresponding title in the doc would solve that.
=> Improve title on enabling HTTPS on the web server

en/releases/centreon-core.md, fr/releases/centreon-core.md
=> enh(rn): prepare release notes for connectors 20.04.1

en/releases/centreon-core.md, fr/releases/centreon-core.md
=> enh(rn): prepare release notes for centreon connectors 20.10.1

en/releases/centreon-core.md, fr/releases/centreon-core.md
=> enh(rh): prepare release notes for centreon connectors 21.04.1

en/administration/knowledge-base.md
Fixes the link to MediaWiki documentation.
Fixes the link to MediaWiki documentation.
=> Fixes the link to MediaWiki documentation.

en/releases/centreon-core.md, fr/releases/centreon-core.md
Release notes **for all poller components**
=> Prepare broker 20.10.6 / engine 20.10.6 / clib 20.10.3 / connectors 20.10.2 release notes

en/releases/centreon-core.md, fr/releases/centreon-core.md
Release notes 
- centreon-engine 21.04.3
- centreon-broker 21.04.2
- centreon-clib 21.04.2
- centreon-connector-perl 21.04.2
- centreon-connector-ssh 21.04.2
=> Prepare poller 21.04.2-3 rn

en/integrations/plugin-packs/procedures/hardware-storage-netapp-restapi.md, en/integrations/plugin-packs/procedures/hardware-storage-netapp-snmp.md, fr/integrations/plugin-packs/procedures/hardware-storage-netapp-restapi.md, fr/integrations/plugin-packs/procedures/hardware-storage-netapp-snmp.md
This PR creates pages to manage deprecated Packs. 
The sidebar is not updated on purpose. The main goal is to avoid dead links when the user clicks on the documentation link from the Plugin Pack page.
=> enh(doc) deprecating old NetApp Packs

en/integrations/plugin-packs/procedures/network-switchs-dell-xseries-snmp.md, fr/integrations/plugin-packs/procedures/network-switchs-dell-xseries-snmp.md
The package name of the Plugin is wrong. Then when users follow the documentation they can't install the Plugin. 
Let's fix this.
=> + fix xseries Plugin package name

en/releases/centreon-core.md, fr/releases/centreon-core.md
- engine 20.04.13
- broker 20.04.15
=> enh(release): prepare release notes for poller 20.04

en/installation/prerequisites.md, fr/installation/prerequisites.md
Qt no longer a software dependency
=> docs(installation): update software dependencies 21.04.x

en/installation/prerequisites.md, fr/installation/prerequisites.md
Qt no longer a software dependency
=> docs(installation): update software dependencies 20.10.x

en/installation/prerequisites.md, fr/installation/prerequisites.md
Qt no longer a software dependency
=> docs(installation): update software dependencies 20.04.x

en/installation/prerequisites.md, fr/installation/prerequisites.md
Qt no longer a software dependency
=> docs(installation): update software dependencies 21.10.x

en/upgrade/upgrade-from-18-10.md, en/upgrade/upgrade-from-19-04.md, en/upgrade/upgrade-from-19-10.md, en/upgrade/upgrade-from-20-04.md, en/upgrade/upgrade-from-20-10.md, en/upgrade/upgrade-from-3-4.md, en/upgrade/upgrade-mariadb.md, fr/upgrade/upgrade-from-18-10.md, fr/upgrade/upgrade-from-19-04.md, fr/upgrade/upgrade-from-19-10.md, fr/upgrade/upgrade-from-20-04.md, fr/upgrade/upgrade-from-20-10.md, fr/upgrade/upgrade-from-3-4.md, fr/upgrade/upgrade-mariadb.md
It is possible to upgrade directly between major versions of MariaDB, you don't have to do it one version at a time.
=> Upgrade directly between major versions of MariaDB

en/installation/installation-of-a-central-server/using-centreon-iso.md, en/installation/installation-of-a-central-server/using-packages.md, en/installation/installation-of-a-central-server/using-sources.md, en/installation/installation-of-a-poller/using-centreon-iso.md, en/installation/installation-of-a-poller/using-packages.md, en/installation/installation-of-a-remote-server/using-centreon-iso.md, en/installation/installation-of-a-remote-server/using-packages.md, fr/installation/installation-of-a-central-server/using-centreon-iso.md, fr/installation/installation-of-a-central-server/using-packages.md, fr/installation/installation-of-a-central-server/using-sources.md, fr/installation/installation-of-a-poller/using-centreon-iso.md, fr/installation/installation-of-a-poller/using-packages.md, fr/installation/installation-of-a-remote-server/using-centreon-iso.md, fr/installation/installation-of-a-remote-server/using-packages.md
Replace underscores by hyphens in exemple hostname, as underscores are not RFC-compliant.
=> Remove underscores in hostname

en/api/clapi.md, fr/api/clapi.md
Old documentation misses available values for the variable inherit_kpi_downtimes  
We had "0 or 1" but in reality we also can put 2 to to ignore the indicator in the calculation.
=> S duret ba downtime

en/releases/centreon-commercial-extensions.md, fr/releases/centreon-commercial-extensions.md
Release note for Centreon MAP 20.10.6
=> enh(release): add release note for Centreon Map 20.10.6

en/releases/centreon-core.md, fr/releases/centreon-core.md
=> doc(release): add release note for Centreon Connector SSH 20.04.2

en/releases/centreon-core.md, fr/releases/centreon-core.md
=> doc(release): add release note for Centreon Connector Perl 20.04.2

en/integrations/event-management/sc-signl4-events.md, en/sidebars.json, fr/integrations/event-management/sc-signl4-events.md, fr/sidebars.json
Add documentation about setting up Signl4 integration
Relates to: 
- https://github.com/centreon/centreon-stream-connector-scripts/pull/86 
- https://github.com/centreon/centreon-stream-connector-scripts/pull/87
=> (integration) add signl4 documentation

en/administration/secure-platform.md, en/upgrade/upgrade-from-18-10.md, en/upgrade/upgrade-from-19-04.md, en/upgrade/upgrade-from-19-10.md, en/upgrade/upgrade-from-3-4.md, fr/administration/secure-platform.md, fr/upgrade/upgrade-from-18-10.md, fr/upgrade/upgrade-from-19-04.md, fr/upgrade/upgrade-from-19-10.md, fr/upgrade/upgrade-from-3-4.md
disable mod security rule 200003
this fix import of license files and MIB when https is enabled
=> fix(apache): disable mod security rule 200003

en/integrations/plugin-packs/procedures/network-moxa-switch-snmp.md, fr/integrations/plugin-packs/procedures/network-moxa-switch-snmp.md
=> fix(doc) typo in the name of the moxa plugin rpm

en/installation/prerequisites.md, fr/installation/prerequisites.md
MON-12264 CentOS 8 no longer supported (20.10)
=> MON-12264 CentOS 8 no longer supported (20.10)

en/getting-started/which-install.md, en/installation/prerequisites.md, fr/getting-started/which-install.md, fr/installation/prerequisites.md
MON-12264 CentOS 8 no longer supported
=> MON-12264 CentOS 8 no longer supported

i18n/fr/docusaurus-plugin-content-docs/version-20.04/releases/centreon-commercial-extensions.md, versioned_docs/version-20.04/releases/centreon-commercial-extensions.md
Prepare release notes for map 20.04.8.
=> enh(release): prepare MAP 20.04.8 release notes

.github/PULL_REQUEST_TEMPLATE.md
Remove 22.04 from PR template for branch "staging".
=> Remove 22.04 from PR template for staging

i18n/fr/docusaurus-plugin-content-docs/version-20.04/administration/secure-platform.md, i18n/fr/docusaurus-plugin-content-docs/version-20.10/administration/secure-platform.md, i18n/fr/docusaurus-plugin-content-docs/version-21.04/administration/secure-platform.md, i18n/fr/docusaurus-plugin-content-docs/version-21.10/administration/secure-platform.md, versioned_docs/version-20.04/administration/secure-platform.md, versioned_docs/version-20.10/administration/secure-platform.md, versioned_docs/version-21.04/administration/secure-platform.md, versioned_docs/version-21.10/administration/secure-platform.md
If a user copy/paste this configuration, it will not working due to the missing of the .html extension.
=> Add .html to avoid 500 errors

i18n/fr/docusaurus-plugin-content-docs/version-20.04/integrations/plugin-packs/procedures/applications-vtom-restapi.md, i18n/fr/docusaurus-plugin-content-docs/version-20.04/integrations/plugin-packs/procedures/cloud-microsoft-office365-management.md, i18n/fr/docusaurus-plugin-content-docs/version-20.10/integrations/plugin-packs/procedures/applications-vtom-restapi.md, i18n/fr/docusaurus-plugin-content-docs/version-20.10/integrations/plugin-packs/procedures/cloud-microsoft-office365-management.md, i18n/fr/docusaurus-plugin-content-docs/version-21.04/integrations/plugin-packs/procedures/applications-vtom-restapi.md, i18n/fr/docusaurus-plugin-content-docs/version-21.04/integrations/plugin-packs/procedures/cloud-microsoft-office365-management.md, i18n/fr/docusaurus-plugin-content-docs/version-21.10/integrations/plugin-packs/procedures/applications-vtom-restapi.md, i18n/fr/docusaurus-plugin-content-docs/version-21.10/integrations/plugin-packs/procedures/cloud-microsoft-office365-management.md, versioned_docs/version-20.04/integrations/plugin-packs/procedures/applications-vtom-restapi.md, versioned_docs/version-20.04/integrations/plugin-packs/procedures/cloud-microsoft-office365-management.md, versioned_docs/version-20.10/integrations/plugin-packs/procedures/applications-vtom-restapi.md, versioned_docs/version-20.10/integrations/plugin-packs/procedures/cloud-microsoft-office365-management.md, versioned_docs/version-21.04/integrations/plugin-packs/procedures/applications-vtom-restapi.md, versioned_docs/version-21.04/integrations/plugin-packs/procedures/cloud-microsoft-office365-management.md, versioned_docs/version-21.10/integrations/plugin-packs/procedures/applications-vtom-restapi.md, versioned_docs/version-21.10/integrations/plugin-packs/procedures/cloud-microsoft-office365-management.md
Replace 
https://github.com/centreon/centreon-documentation/pull/1271
and 
https://github.com/centreon/centreon-documentation/pull/1272
Docusaurus v2
=> (monproc) migrate m365 & absyss vtom to docusaurus v2

i18n/fr/docusaurus-plugin-content-docs/version-20.10/releases/centreon-commercial-extensions.md, versioned_docs/version-20.10/releases/centreon-commercial-extensions.md
=> enh(release): Add Centreon MBI 20.10.5 RN

i18n/fr/docusaurus-plugin-content-docs/version-21.10/integrations/plugin-packs/procedures/operatingsystems-windows-nsclient-05-nrpe.md, versioned_docs/version-21.10/integrations/plugin-packs/procedures/operatingsystems-windows-nsclient-05-nrpe.md
Additionnal modifications to [original PR](https://github.com/centreon/centreon-documentation/pull/1319).
Since 21.10, centreon-nrpe-plugin is not available anymore.
Doc has to be updated to make people use centreon-nrpe3-plugin and replace some macro values.
=> fix(epp): nrpe nsclient 0.5 monitoring proc modification for 21.10 and higher

i18n/fr/docusaurus-plugin-content-docs/version-22.04/integrations/plugin-packs/procedures/operatingsystems-windows-nsclient-05-nrpe.md, versioned_docs/version-22.04/integrations/plugin-packs/procedures/operatingsystems-windows-nsclient-05-nrpe.md
Modification on NRPE windows documentation because missing and outdated information.
[Staging PR](https://github.com/centreon/centreon-documentation/pull/1347)
=> Next 22.04 - fix(epp): nrpe nsclient 0.5 monitoring proc modif

versioned_docs/version-22.04/administration/secure-platform.md, versioned_docs/version-22.04/upgrade/upgrade-from-18-10.md, versioned_docs/version-22.04/upgrade/upgrade-from-19-04.md, versioned_docs/version-22.04/upgrade/upgrade-from-19-10.md, versioned_docs/version-22.04/upgrade/upgrade-from-3-4.md
adapt apache configuration to new routing mechanism
Refs: MON-6687
=> fix(apache): adapt apache configuration to new routing mechanism

i18n/fr/docusaurus-plugin-content-docs/version-22.04/administration/secure-platform.md, i18n/fr/docusaurus-plugin-content-docs/version-22.04/upgrade/upgrade-from-18-10.md, i18n/fr/docusaurus-plugin-content-docs/version-22.04/upgrade/upgrade-from-19-04.md, i18n/fr/docusaurus-plugin-content-docs/version-22.04/upgrade/upgrade-from-19-10.md, i18n/fr/docusaurus-plugin-content-docs/version-22.04/upgrade/upgrade-from-3-4.md
adapt apache configuration to new routing mechanism
Refs: MON-6687
=> fix(apache): adapt apache configuration to new routing mechanism (fr)

i18n/fr/docusaurus-plugin-content-docs/version-20.10/integrations/event-management/sc-pagerduty-events.md, i18n/fr/docusaurus-plugin-content-docs/version-21.04/integrations/event-management/sc-pagerduty-events.md, i18n/fr/docusaurus-plugin-content-docs/version-21.10/integrations/event-management/sc-pagerduty-events.md, versioned_docs/version-20.10/integrations/event-management/sc-pagerduty-events.md, versioned_docs/version-21.04/integrations/event-management/sc-pagerduty-events.md, versioned_docs/version-21.10/integrations/event-management/sc-pagerduty-events.md
Replaces https://github.com/centreon/centreon-documentation/pull/1273 post-migration.
=> Fix incorrect title

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/tutorials/azure-credential-configuration.md, pp/integrations/plugin-packs/tutorials/azure-credential-configuration.md, pp/sidebarsPp.js
Adding a new documentation describing how to get tokens for setting up Azure monitoring.
This procedure aims to be part of each "Prerequisites" part of any Azure Plugin Pack documentation to ease update management.
Previous PR that was approved https://github.com/centreon/centreon-documentation/pull/1342.
=> add(epp) : prerequisites for Azure monitoring - staging

i18n/fr/docusaurus-plugin-content-docs/version-22.04/integrations/itsm/ot-glpi.md, i18n/fr/docusaurus-plugin-content-docs/version-22.04/integrations/itsm/ot-glpirestapi.md, i18n/fr/docusaurus-plugin-content-docs/version-22.04/integrations/itsm/ot-itop.md, versioned_docs/version-22.04/integrations/itsm/ot-glpi.md, versioned_docs/version-22.04/integrations/itsm/ot-glpirestapi.md, versioned_docs/version-22.04/integrations/itsm/ot-itop.md
Fix wrong links for 22.04 version.
=> Fix wrong links. Next branch.

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-monitoring-centreon-sql-metrics.md, pp/integrations/plugin-packs/procedures/applications-monitoring-centreon-sql-metrics.md, pp/sidebarsPp.js
- Missing monitoring procedure for *Centreon SQL Metrics* Pack
=> (monproc) add Centreon SQL Metrics monitoring procedure

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-databases-oracle.md, pp/integrations/plugin-packs/procedures/applications-databases-oracle.md
Thank to @Zequan
We had missing permissions to fully used our Oracle plugin.
=> fix-oracle-permissions

i18n/fr/docusaurus-plugin-content-docs/version-22.04/integrations/data-analytics/sc-datadog-events.md, i18n/fr/docusaurus-plugin-content-docs/version-22.04/integrations/data-analytics/sc-datadog-metrics.md, i18n/fr/docusaurus-plugin-content-docs/version-22.04/integrations/event-management/sc-service-now-em-events.md, i18n/fr/docusaurus-plugin-content-docs/version-22.04/integrations/event-management/sc-service-now-incident-events.md, versioned_docs/version-22.04/integrations/data-analytics/sc-datadog-events.md, versioned_docs/version-22.04/integrations/data-analytics/sc-datadog-metrics.md, versioned_docs/version-22.04/integrations/event-management/sc-service-now-em-events.md, versioned_docs/version-22.04/integrations/event-management/sc-service-now-incident-events.md, versioned_sidebars/version-22.04-sidebars.json
this PR adds the documentation for the new service-now incident and datadog metrics stream connectors.
It also updates the splunk metrics and service-now event manager stream connector to reflect incoming changes to the stream connector lib
=> add docs for datadog and snow incident (+ updates)

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-monitoring-kadiska-restapi.md, pp/integrations/plugin-packs/procedures/applications-monitoring-kadiska-restapi.md
- Modifying tracer-statistics mode name in command example 
- Adding the 'loading page duration' metric in watcher service metrics
=> update(epp) - Minor changes according to new kadiska plugin version

i18n/fr/docusaurus-plugin-content-docs/version-20.04/administration/centreon-ha/installation-2-nodes.md, i18n/fr/docusaurus-plugin-content-docs/version-20.04/administration/centreon-ha/installation-4-nodes.md, i18n/fr/docusaurus-plugin-content-docs/version-20.10/administration/centreon-ha/installation-2-nodes.md, i18n/fr/docusaurus-plugin-content-docs/version-20.10/administration/centreon-ha/installation-4-nodes.md, i18n/fr/docusaurus-plugin-content-docs/version-21.04/graph-views/install-ha.md, i18n/fr/docusaurus-plugin-content-docs/version-21.04/installation/installation-of-centreon-ha/installation-2-nodes.md, i18n/fr/docusaurus-plugin-content-docs/version-21.04/installation/installation-of-centreon-ha/installation-4-nodes.md, i18n/fr/docusaurus-plugin-content-docs/version-21.10/graph-views/install-ha.md, i18n/fr/docusaurus-plugin-content-docs/version-21.10/installation/installation-of-centreon-ha/installation-2-nodes.md, i18n/fr/docusaurus-plugin-content-docs/version-21.10/installation/installation-of-centreon-ha/installation-4-nodes.md, versioned_docs/version-20.04/administration/centreon-ha/installation-2-nodes.md, versioned_docs/version-20.04/administration/centreon-ha/installation-4-nodes.md, versioned_docs/version-20.10/administration/centreon-ha/installation-2-nodes.md, versioned_docs/version-20.10/administration/centreon-ha/installation-4-nodes.md, versioned_docs/version-21.04/graph-views/install-ha.md, versioned_docs/version-21.04/installation/installation-of-centreon-ha/installation-2-nodes.md, versioned_docs/version-21.04/installation/installation-of-centreon-ha/installation-4-nodes.md, versioned_docs/version-21.10/graph-views/install-ha.md, versioned_docs/version-21.10/installation/installation-of-centreon-ha/installation-2-nodes.md, versioned_docs/version-21.10/installation/installation-of-centreon-ha/installation-4-nodes.md
Some labels were not grouping
CentOS7 vs CentOS 7
=> fix(doc) group CentOS 7

i18n/fr/docusaurus-plugin-content-docs/version-21.10/releases/centreon-commercial-extensions.md, versioned_docs/version-21.10/releases/centreon-commercial-extensions.md
=> enh(release) Add Centreon MAP 21.10.5 RN

i18n/fr/docusaurus-plugin-content-docs/version-22.04/api/clapi.md, versioned_docs/version-21.10/api/clapi.md, versioned_docs/version-22.04/api/clapi.md
Add parameters to setmacro
Complements https://github.com/centreon/centreon-documentation/pull/1384
=> Add parameters to setmacro

i18n/fr/docusaurus-plugin-content-docs/version-22.10/upgrade/upgrade-from-20-10.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/upgrade/upgrade-from-21-04.md, versioned_docs/version-22.10/upgrade/upgrade-from-20-10.md, versioned_docs/version-22.10/upgrade/upgrade-from-21-04.md
Fix PHP upgrade procedure for RHEL/OL 8 - next
=> Fix PHP upgrade procedure for RHEL/OL 8 - next

i18n/fr/docusaurus-plugin-content-docs/version-21.10/upgrade/upgrade-from-20-10.md, i18n/fr/docusaurus-plugin-content-docs/version-21.10/upgrade/upgrade-from-21-04.md, i18n/fr/docusaurus-plugin-content-docs/version-22.04/upgrade/upgrade-from-20-10.md, i18n/fr/docusaurus-plugin-content-docs/version-22.04/upgrade/upgrade-from-21-04.md, versioned_docs/version-21.10/upgrade/upgrade-from-20-10.md, versioned_docs/version-21.10/upgrade/upgrade-from-21-04.md, versioned_docs/version-22.04/upgrade/upgrade-from-20-10.md, versioned_docs/version-22.04/upgrade/upgrade-from-21-04.md
Fix PHP upgrade procedure for RHEL/OL 8
=> Fix PHP upgrade procedure for RHEL/OL 8

i18n/fr/docusaurus-plugin-content-docs/version-22.04/api/rest-api-v2.md, versioned_docs/version-22.04/api/rest-api-v2.md
=> fix(url) APIv22.04

i18n/fr/docusaurus-plugin-content-docs/version-21.04/releases/centreon-core.md, versioned_docs/version-21.04/releases/centreon-core.md
=> doc(release): add release note for centreon-engine-21.04.5

i18n/fr/docusaurus-plugin-content-docs/version-21.04/upgrade/upgrade-from-3-4.md, i18n/fr/docusaurus-plugin-content-docs/version-21.10/upgrade/upgrade-from-3-4.md, i18n/fr/docusaurus-plugin-content-docs/version-22.04/upgrade/upgrade-from-3-4.md, versioned_docs/version-21.04/upgrade/upgrade-from-3-4.md, versioned_docs/version-21.10/upgrade/upgrade-from-3-4.md, versioned_docs/version-22.04/upgrade/upgrade-from-3-4.md
=> enh(upgrade): recent versions of broker do not support failover

i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md, versioned_docs/version-22.04/releases/centreon-core.md
Prepare release of centreon ntopng 22.04.0
=> enh(doc): add release note for centreon ntopng widget 22.04.0

i18n/fr/docusaurus-plugin-content-docs/version-22.04/installation/installation-of-a-central-server/using-packages.md, i18n/fr/docusaurus-plugin-content-docs/version-22.04/installation/installation-of-a-remote-server/using-packages.md, i18n/fr/docusaurus-plugin-content-docs/version-22.04/upgrade/upgrade-from-18-10.md, i18n/fr/docusaurus-plugin-content-docs/version-22.04/upgrade/upgrade-from-19-04.md, i18n/fr/docusaurus-plugin-content-docs/version-22.04/upgrade/upgrade-from-19-10.md, i18n/fr/docusaurus-plugin-content-docs/version-22.04/upgrade/upgrade-from-20-04.md, i18n/fr/docusaurus-plugin-content-docs/version-22.04/upgrade/upgrade-from-20-10.md, i18n/fr/docusaurus-plugin-content-docs/version-22.04/upgrade/upgrade-from-21-04.md, i18n/fr/docusaurus-plugin-content-docs/version-22.04/upgrade/upgrade-from-21-10.md, i18n/fr/docusaurus-plugin-content-docs/version-22.04/upgrade/upgrade-from-3-4.md, versioned_docs/version-22.04/installation/installation-of-a-central-server/using-packages.md, versioned_docs/version-22.04/installation/installation-of-a-remote-server/using-packages.md, versioned_docs/version-22.04/upgrade/upgrade-from-18-10.md, versioned_docs/version-22.04/upgrade/upgrade-from-19-04.md, versioned_docs/version-22.04/upgrade/upgrade-from-19-10.md, versioned_docs/version-22.04/upgrade/upgrade-from-20-04.md, versioned_docs/version-22.04/upgrade/upgrade-from-20-10.md, versioned_docs/version-22.04/upgrade/upgrade-from-21-04.md, versioned_docs/version-22.04/upgrade/upgrade-from-21-10.md, versioned_docs/version-22.04/upgrade/upgrade-from-3-4.md
Add address of mariadb repo as the mariadb packages will no longer be available on the Centreon repos.
=> Add address of mariadb repo

i18n/fr/docusaurus-plugin-content-docs/version-22.04/installation/installation-of-a-poller/using-packages.md, versioned_docs/version-22.04/installation/installation-of-a-poller/using-packages.md
Remove Sury repo from poller installation procedure (staging)
=> Remove Sury repo from poller installation procedure (staging)

i18n/fr/docusaurus-plugin-content-docs/version-21.04/releases/centreon-commercial-extensions.md, versioned_docs/version-21.04/releases/centreon-commercial-extensions.md
prepare release notes for Centreon MBI 21.04.4
=> enh(doc): prepare release notes for Centreon MBI 21.04.4

i18n/fr/docusaurus-plugin-content-docs/version-21.04/administration/postfix.md, i18n/fr/docusaurus-plugin-content-docs/version-21.10/administration/postfix.md, i18n/fr/docusaurus-plugin-content-docs/version-22.04/administration/postfix.md, versioned_docs/version-21.04/administration/postfix.md, versioned_docs/version-21.10/administration/postfix.md, versioned_docs/version-22.04/administration/postfix.md
Refer to: https://github.com/centreon/centreon-documentation/issues/1678
Fix dead link on Postfix topic
=> Fix dead link on Postfix topic

i18n/fr/docusaurus-plugin-content-docs/version-20.10/releases/centreon-core.md, versioned_docs/version-20.10/releases/centreon-core.md
Prepare release note for Centreon Gorgone 20.10.7 release
=> enh(doc): prepare release notes for Centreon Gorgone 20.10.7

i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md, versioned_docs/version-22.04/releases/centreon-core.md
add security policy information in release note
=> enh(release): add security policy information in release note

i18n/fr/docusaurus-plugin-content-docs/version-22.04/graph-views/install.md, versioned_docs/version-22.04/graph-views/install.md
Fix incorrect link to install MAP Desktop
=> Fix incorrect link to install MAP Desktop

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/getting-started/how-to-guides/troubleshooting-plugins.md, pp/integrations/plugin-packs/getting-started/how-to-guides/troubleshooting-plugins.md
Adding SNMPv3 mapping between snmpwalk and plugin option.
=> enh(doc): add snmpv3 mapping option

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-monitoring-node-exporter-windows.md, pp/integrations/plugin-packs/procedures/applications-monitoring-node-exporter-windows.md, pp/sidebarsPp.js
Adding Windows node exporter plugin pack documentation.
=> add(epp): adding Windows node exporter documentation

i18n/fr/docusaurus-plugin-content-docs/version-21.04/upgrade/centreon-ha/upgrade-from-20.04.md, i18n/fr/docusaurus-plugin-content-docs/version-21.04/upgrade/centreon-ha/upgrade-from-20.10.md, i18n/fr/docusaurus-plugin-content-docs/version-21.10/upgrade/centreon-ha/upgrade-from-20-04.md, i18n/fr/docusaurus-plugin-content-docs/version-21.10/upgrade/centreon-ha/upgrade-from-20-10.md, i18n/fr/docusaurus-plugin-content-docs/version-21.10/upgrade/centreon-ha/upgrade-from-21-04.md, versioned_docs/version-21.04/upgrade/centreon-ha/upgrade-from-20.04.md, versioned_docs/version-21.04/upgrade/centreon-ha/upgrade-from-20.10.md, versioned_docs/version-21.10/upgrade/centreon-ha/upgrade-from-20-04.md, versioned_docs/version-21.10/upgrade/centreon-ha/upgrade-from-20-10.md, versioned_docs/version-21.10/upgrade/centreon-ha/upgrade-from-21-04.md
New PR for the new documentation tree structure.
cc @cg-tw 
Now we can close #1150 and #1149 
- [] 21.10.x (staging)
=> (fix) ha upgrade process for old versions

i18n/fr/docusaurus-plugin-content-docs/version-20.04/monitoring/passive-monitoring/debug-snmp-traps-management.md, i18n/fr/docusaurus-plugin-content-docs/version-20.10/monitoring/passive-monitoring/debug-snmp-traps-management.md, i18n/fr/docusaurus-plugin-content-docs/version-21.04/monitoring/passive-monitoring/debug-snmp-traps-management.md, i18n/fr/docusaurus-plugin-content-docs/version-21.10/monitoring/passive-monitoring/debug-snmp-traps-management.md, i18n/fr/docusaurus-plugin-content-docs/version-22.04/monitoring/passive-monitoring/debug-snmp-traps-management.md, versioned_docs/version-20.04/monitoring/passive-monitoring/create-snmp-traps-definitions.md, versioned_docs/version-20.04/monitoring/passive-monitoring/debug-snmp-traps-management.md, versioned_docs/version-20.10/monitoring/passive-monitoring/create-snmp-traps-definitions.md, versioned_docs/version-20.10/monitoring/passive-monitoring/debug-snmp-traps-management.md, versioned_docs/version-21.04/monitoring/passive-monitoring/create-snmp-traps-definitions.md, versioned_docs/version-21.04/monitoring/passive-monitoring/debug-snmp-traps-management.md, versioned_docs/version-21.10/monitoring/passive-monitoring/create-snmp-traps-definitions.md, versioned_docs/version-21.10/monitoring/passive-monitoring/debug-snmp-traps-management.md, versioned_docs/version-22.04/monitoring/passive-monitoring/create-snmp-traps-definitions.md, versioned_docs/version-22.04/monitoring/passive-monitoring/debug-snmp-traps-management.md
This PR updates the SNMP traps documentation as proposed by [vmonegatto](https://github.com/vmonegatto) with older PR [8334](https://github.com/centreon/centreon/pull/8334)
=> Update SNMP traps documentation (proposal of vmonegatto)

versioned_docs/version-20.04/alerts-notifications/concepts.md
typo issue on service status
I think there is a typo error for services status. DOWN should be CRITICAL.
this error is on 20.04 20.10 21.04 version of documentation
=> service status modification

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-compute-virtualmachine.md, pp/integrations/plugin-packs/procedures/cloud-azure-compute-virtualmachine.md
Removing mention of deprecated service template from Azure Compute Virtal Machine Plugin pack documentation.
=> fix(pp) - Removing deprecated stpl mention in documentation

i18n/fr/docusaurus-plugin-content-docs/version-22.10/metrology/grafana.md, versioned_docs/version-22.10/metrology/grafana.md
Use the Centreon data source as an unsigned plugin (next)
=> Use the Centreon data source as an unsigned plugin (next)

i18n/fr/docusaurus-plugin-content-docs/version-22.10/administration/secure-platform.md, versioned_docs/version-22.10/administration/secure-platform.md
=> Add HTTPS info for Debian - Next

i18n/fr/docusaurus-plugin-content-docs/version-22.10/installation/installation-of-centreon-ha/installation-2-nodes.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/installation/installation-of-centreon-ha/installation-4-nodes.md, versioned_docs/version-22.10/installation/installation-of-centreon-ha/installation-2-nodes.md, versioned_docs/version-22.10/installation/installation-of-centreon-ha/installation-4-nodes.md
Add a section to manage disabled resources after installation of the cluster. In few cases we need to manually activate some resources.
EN and FR versions for NEXT
It's a copy paste of 22.04 since https://github.com/centreon/centreon-documentation/pull/1640
=> PS-56 Centreon-HA manage disabled resources NEXT

i18n/fr/docusaurus-plugin-content-docs/version-22.04/migrate/migrate-from-el-to-debian.md, versioned_docs/version-22.04/migrate/migrate-from-el-to-debian.md
Add info about path to a macro on Debian
=> Add info about path to a macro on Debian

i18n/fr/docusaurus-plugin-content-docs/version-21.10/releases/centreon-core.md, versioned_docs/version-21.10/releases/centreon-core.md
=> doc(release): add release note for centreon-collect-21.10.3

i18n/fr/docusaurus-plugin-content-pages/index.js, src/pages/index.js
Fix incorrect link on next homepage
=> Fix incorrect link on next homepage

i18n/fr/docusaurus-plugin-content-docs/version-21.10/releases/centreon-core.md, versioned_docs/version-21.10/releases/centreon-core.md
Wait for https://github.com/centreon/centreon-documentation/pull/1818 to be merged before merging this one.
=> fix(typo): double whitespaces in header of release notes

src/theme/DocCard/index.tsx, src/theme/DocCard/styles.module.css
=> Remove ToC icons (staging)

i18n/fr/docusaurus-plugin-content-docs/version-21.10/releases/centreon-commercial-extensions.md, versioned_docs/version-21.10/releases/centreon-commercial-extensions.md
doc(release): prepare release notes for Centreon MAP 21.10.6
=> doc(release): prepare release notes for Centreon MAP 21.10.6

i18n/fr/docusaurus-plugin-content-docs/version-22.10/upgrade/upgrade-from-22-04.md, versioned_docs/version-22.10/upgrade/upgrade-from-22-04.md
REFS: MON-15399
This PR intends to add to the 22.10 upgrade procedure the restart of the php-fpm process. This is necessary to avoid errors due to the upgrade of sourceguardian loader from 8.0 to 8.1.
=> restart php-fpm process post rpm upgrade

i18n/fr/docusaurus-plugin-content-docs/version-21.04/releases/centreon-commercial-extensions.md, versioned_docs/version-21.04/releases/centreon-commercial-extensions.md
=> enh(release): Add Centreon MBI 21.04.5

i18n/fr/docusaurus-plugin-content-docs/version-21.10/releases/centreon-commercial-extensions.md, versioned_docs/version-21.10/releases/centreon-commercial-extensions.md
=> enh(release): Add Centreon MBI 21.10.2

i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-commercial-extensions.md, versioned_docs/version-22.04/releases/centreon-commercial-extensions.md
=> enh(release): Add Centreon MBI 22.04.2

i18n/fr/docusaurus-plugin-content-docs/version-22.10/api/clapi.md
Added missing parameters to parameter list table in CLAPI web documentation (French version on top of https://github.com/centreon/centreon-documentation/pull/1877).
=> fix(clapi): Added missing parameters to parameter list table in CLAPI web documentation - 22.10

i18n/fr/docusaurus-plugin-content-docs/version-22.10/installation/installation-of-a-central-server/using-packages.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/installation/installation-of-a-remote-server/using-packages.md, versioned_docs/version-22.10/installation/installation-of-a-central-server/using-packages.md, versioned_docs/version-22.10/installation/installation-of-a-remote-server/using-packages.md
Add crond start/enable at install
=> Add crond start/enable at install

i18n/fr/docusaurus-plugin-content-docs/version-22.10/update/update-centreon-platform.md, versioned_docs/version-22.10/update/update-centreon-platform.md
Uninstall debuginfo packages before update (next)
=> Uninstall debuginfo packages before update (next)

i18n/fr/docusaurus-plugin-content-docs/version-22.04/update/update-centreon-platform.md, versioned_docs/version-22.04/update/update-centreon-platform.md
Uninstall debuginfo packages before update (staging)
=> Uninstall debuginfo packages before update (staging)

i18n/fr/docusaurus-plugin-content-docs/version-21.10/releases/centreon-commercial-extensions.md, versioned_docs/version-21.10/releases/centreon-commercial-extensions.md
Prepare release notes for map 21.10.7 (includes hotfix https://centreon.atlassian.net/browse/MON-15576 )
=> doc(release): prepare release notes for Centreon MAP 21.10.7

i18n/fr/docusaurus-plugin-content-docs/version-22.10/upgrade/upgrade-from-18-10.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/upgrade/upgrade-from-19-04.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/upgrade/upgrade-from-19-10.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/upgrade/upgrade-from-20-04.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/upgrade/upgrade-from-20-10.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/upgrade/upgrade-from-21-04.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/upgrade/upgrade-from-21-10.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/upgrade/upgrade-from-3-4.md, versioned_docs/version-22.10/upgrade/upgrade-from-18-10.md, versioned_docs/version-22.10/upgrade/upgrade-from-19-04.md, versioned_docs/version-22.10/upgrade/upgrade-from-19-10.md, versioned_docs/version-22.10/upgrade/upgrade-from-20-04.md, versioned_docs/version-22.10/upgrade/upgrade-from-20-10.md, versioned_docs/version-22.10/upgrade/upgrade-from-21-04.md, versioned_docs/version-22.10/upgrade/upgrade-from-21-10.md, versioned_docs/version-22.10/upgrade/upgrade-from-3-4.md
Remove ioncube from upgrade procedure (22.10)
=> Remove ioncube from upgrade procedure (22.10)

i18n/fr/docusaurus-plugin-content-docs/version-22.04/upgrade/upgrade-from-18-10.md, i18n/fr/docusaurus-plugin-content-docs/version-22.04/upgrade/upgrade-from-19-04.md, i18n/fr/docusaurus-plugin-content-docs/version-22.04/upgrade/upgrade-from-19-10.md, i18n/fr/docusaurus-plugin-content-docs/version-22.04/upgrade/upgrade-from-20-04.md, i18n/fr/docusaurus-plugin-content-docs/version-22.04/upgrade/upgrade-from-20-10.md, i18n/fr/docusaurus-plugin-content-docs/version-22.04/upgrade/upgrade-from-21-04.md, i18n/fr/docusaurus-plugin-content-docs/version-22.04/upgrade/upgrade-from-21-10.md, i18n/fr/docusaurus-plugin-content-docs/version-22.04/upgrade/upgrade-from-3-4.md, versioned_docs/version-22.04/upgrade/upgrade-from-18-10.md, versioned_docs/version-22.04/upgrade/upgrade-from-19-04.md, versioned_docs/version-22.04/upgrade/upgrade-from-19-10.md, versioned_docs/version-22.04/upgrade/upgrade-from-20-04.md, versioned_docs/version-22.04/upgrade/upgrade-from-20-10.md, versioned_docs/version-22.04/upgrade/upgrade-from-21-04.md, versioned_docs/version-22.04/upgrade/upgrade-from-21-10.md, versioned_docs/version-22.04/upgrade/upgrade-from-3-4.md
Remove ioncube from upgrade procedures (22.04)
=> Remove ioncube from upgrade procedures (22.04)

i18n/fr/docusaurus-plugin-content-docs/version-22.10/upgrade/upgrade-from-18-10.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/upgrade/upgrade-from-19-04.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/upgrade/upgrade-from-19-10.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/upgrade/upgrade-from-20-04.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/upgrade/upgrade-from-20-10.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/upgrade/upgrade-from-21-04.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/upgrade/upgrade-from-21-10.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/upgrade/upgrade-from-22-04.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/upgrade/upgrade-from-3-4.md, versioned_docs/version-22.10/upgrade/upgrade-from-18-10.md, versioned_docs/version-22.10/upgrade/upgrade-from-19-04.md, versioned_docs/version-22.10/upgrade/upgrade-from-19-10.md, versioned_docs/version-22.10/upgrade/upgrade-from-20-04.md, versioned_docs/version-22.10/upgrade/upgrade-from-20-10.md, versioned_docs/version-22.10/upgrade/upgrade-from-21-04.md, versioned_docs/version-22.10/upgrade/upgrade-from-21-10.md, versioned_docs/version-22.10/upgrade/upgrade-from-22-04.md, versioned_docs/version-22.10/upgrade/upgrade-from-3-4.md
Add note to clear browser cache in order to display new 22.10 theme
=> Add note to clear browser cache in order to display new 22.10 theme

i18n/fr/docusaurus-plugin-content-docs/version-21.10/api/rest-api-v1.md, i18n/fr/docusaurus-plugin-content-docs/version-22.04/api/rest-api-v1.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/api/rest-api-v1.md, versioned_docs/version-21.10/api/rest-api-v1.md, versioned_docs/version-22.04/api/rest-api-v1.md, versioned_docs/version-22.10/api/rest-api-v1.md
The action was tested via curl :  
curl --location --request  POST 'http://localhost/centreon/api/index.php?action=action&object=centreon_clapi' --header 'centreon-auth-token: TOKEN' --header 'Content-Type: application/json' -d '{"action": "gethosttemplate","object": "STPL","values": "App-Ansible-Tower-Hosts-Api-custom"}'
result : 
{"result":[{"id":"88","name":"App-Ansible-Tower-custom"}]}
=> Add missing action restapiv1 (staging)

i18n/fr/docusaurus-plugin-content-docs/version-22.10/graph-views/map-web-install.md, versioned_docs/version-22.10/graph-views/map-web-install.md
Fix map naming (map instead of studio)
=> Fix map naming

i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md, versioned_docs/version-22.10/releases/centreon-os.md
prepare release notes for Centroen WEB 22.10.2 (hotfix)
=> doc(release): prepare release notes for Centreon WEB 22.10.2

i18n/fr/docusaurus-plugin-content-docs/version-21.10/monitoring/passive-monitoring/debug-snmp-traps-management.md, i18n/fr/docusaurus-plugin-content-docs/version-22.04/monitoring/passive-monitoring/debug-snmp-traps-management.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/monitoring/passive-monitoring/debug-snmp-traps-management.md, versioned_docs/version-21.10/monitoring/passive-monitoring/debug-snmp-traps-management.md, versioned_docs/version-22.04/monitoring/passive-monitoring/debug-snmp-traps-management.md, versioned_docs/version-22.10/monitoring/passive-monitoring/debug-snmp-traps-management.md
Enable debug mode for centreontrapd
=> Enable debug mode for centreontrapd

i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-commercial-extensions.md, versioned_docs/version-22.10/releases/centreon-commercial-extensions.md
Prepare release notes for MAP 22.10.2 (hotfix MON-16125)
=> doc(release): prepare release notes for Centreon MAP 22.10.2

i18n/fr/docusaurus-plugin-content-docs/version-22.10/resources/contribute.md, versioned_docs/version-22.10/resources/contribute.md
The intro talks about features and docs, I suggest to specifically target documentation.
- [] 21.10.x (staging)
- [] 22.04.x (staging)
- [] Cloud (staging)
- [] 23.04.x (next)
=> Update contribute.md to be more doc specific

i18n/fr/docusaurus-plugin-content-docs/version-23.04/upgrade/upgrade-from-18-10.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/upgrade/upgrade-from-19-04.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/upgrade/upgrade-from-19-10.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/upgrade/upgrade-from-20-04.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/upgrade/upgrade-from-20-10.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/upgrade/upgrade-from-21-04.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/upgrade/upgrade-from-21-10.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/upgrade/upgrade-from-3-4.md, versioned_docs/version-23.04/upgrade/upgrade-from-18-10.md, versioned_docs/version-23.04/upgrade/upgrade-from-19-04.md, versioned_docs/version-23.04/upgrade/upgrade-from-19-10.md, versioned_docs/version-23.04/upgrade/upgrade-from-20-04.md, versioned_docs/version-23.04/upgrade/upgrade-from-20-10.md, versioned_docs/version-23.04/upgrade/upgrade-from-21-04.md, versioned_docs/version-23.04/upgrade/upgrade-from-21-10.md, versioned_docs/version-23.04/upgrade/upgrade-from-3-4.md
In the documentation, the mariadb upgrade procedure is not correct (anymore).
https://docs.centreon.com/docs/22.04/upgrade/upgrade-from-21-10/
"Install the MariaDB repository":
cd /tmp
curl -JO https://downloads.mariadb.com/MariaDB/mariadb_repo_setup
bash ./mariadb_repo_setup
sed -ri 's/10\../10.5/' /etc/yum.repos.d/mariadb.repo
rm -f ./mariadb_repo_setup
-> The sed command is not sufficient anymore since mariadb version 10.10 was released. The command substitutes the version to "10.50" in the repo file.
before: baseurl = https://dlm.mariadb.com/repo/mariadb-server/10.10/yum/rhel/7/x86_64
after: baseurl = https://dlm.mariadb.com/repo/mariadb-server/10.50/yum/rhel/7/x86_64
Suggested command:
sed -ri 's/10\.[0-9]+/10.5/' /etc/yum.repos.d/mariadb.repo
before: baseurl = …
=> Sed command mariadb version for next branch

i18n/fr/docusaurus-plugin-content-docs/version-22.10/graph-views/map-web-install.md, versioned_docs/version-22.10/graph-views/map-web-install.md
=> MAP Web install centreon-release path fix

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-loadbalancers-netscaler-mpx8000-snmp.md, pp/integrations/plugin-packs/procedures/network-loadbalancers-netscaler-mpx8000-snmp.md, pp/sidebarsPp.js
=> enh(epp): deprecated netscaler nmpx8000 snmp

i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-commercial-extensions.md, versioned_docs/version-22.04/releases/centreon-commercial-extensions.md
Prepare release notes for MAP 22.04.2
=> doc(release): prepare release notes for Centreon MAP 22.04.2

i18n/fr/docusaurus-plugin-content-docs/version-22.04/graph-views/install.md, i18n/fr/docusaurus-plugin-content-docs/version-22.04/graph-views/update.md, i18n/fr/docusaurus-plugin-content-docs/version-22.04/graph-views/upgrade.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/graph-views/install.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/graph-views/map-web-install.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/graph-views/map-web-update.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/graph-views/update.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/graph-views/upgrade.md, versioned_docs/version-22.04/graph-views/install.md, versioned_docs/version-22.04/graph-views/update.md, versioned_docs/version-22.04/graph-views/upgrade.md, versioned_docs/version-22.10/graph-views/install.md, versioned_docs/version-22.10/graph-views/map-web-install.md, versioned_docs/version-22.10/graph-views/map-web-update.md, versioned_docs/version-22.10/graph-views/update.md, versioned_docs/version-22.10/graph-views/upgrade.md
Add Debian to MAP upgrade topic
- MAP Legacy 22.04 / 22.10
- MAP 22.10 (as MAP 22.04 does not exist yet)
=> Add Debian to MAP upgrade topic

i18n/fr/docusaurus-plugin-content-docs/version-21.10/releases/centreon-commercial-extensions.md, versioned_docs/version-21.10/releases/centreon-commercial-extensions.md
Prepare release notes for MAP 21.10.8
=> doc(release): prepare release notes for MAP 21.10.8

i18n/fr/docusaurus-plugin-content-docs/version-22.04/graph-views/map-web-update.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/graph-views/install.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/graph-views/map-web-update.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/graph-views/upgrade.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/reporting/installation.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/reporting/upgrade.md, versioned_docs/version-22.04/graph-views/map-web-update.md, versioned_docs/version-22.10/graph-views/install.md, versioned_docs/version-22.10/graph-views/map-web-update.md, versioned_docs/version-22.10/graph-views/upgrade.md, versioned_docs/version-22.10/reporting/installation.md, versioned_docs/version-22.10/reporting/upgrade.md
- Remove warning from MAP update topic
- Change link to java 17 download
- Remove warning from MAP update topic
=> Change link to java 17 download

i18n/fr/docusaurus-plugin-content-docs/version-22.04/graph-views/install.md, i18n/fr/docusaurus-plugin-content-docs/version-22.04/graph-views/remote-server.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/graph-views/install.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/graph-views/remote-server.md, versioned_docs/version-22.04/graph-views/install.md, versioned_docs/version-22.04/graph-views/remote-server.md, versioned_docs/version-22.10/graph-views/install.md, versioned_docs/version-22.10/graph-views/remote-server.md
Add warning to promote MAP instead of MAP Legacy.
=> Add warning to promote MAP instead of MAP Legacy

i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md, versioned_docs/version-22.10/releases/centreon-os.md
Prepare release notes for Centreon Web 22.10.3
=> doc(release): prepare release notes for Centreon Web 22.10.3

i18n/fr/docusaurus-plugin-content-docs/version-23.04/api/clapi.md, versioned_docs/version-23.04/api/clapi.md
Remove timeperiod exclusions from clapi doc (next)
=> Remove timeperiod exclusions from clapi doc (next)

i18n/fr/docusaurus-plugin-content-docs/version-21.10/api/clapi.md, i18n/fr/docusaurus-plugin-content-docs/version-22.04/api/clapi.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/api/clapi.md, versioned_docs/version-21.10/api/clapi.md, versioned_docs/version-22.04/api/clapi.md, versioned_docs/version-22.10/api/clapi.md
Remove timeperiod exclusions from clapi doc (staging)
=> Remove timeperiod exclusions from clapi doc (staging)

i18n/fr/docusaurus-plugin-content-docs/version-21.10/installation/installation-of-a-central-server/using-sources.md
it was working in the english version.
I reported it in the french page
- [ X] 21.10.x (staging)
=> CLIB installation link was dead

i18n/fr/docusaurus-plugin-content-docs/version-22.10/upgrade/centreon-ha/upgrade-from-20-04.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/upgrade/centreon-ha/upgrade-from-20-10.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/upgrade/centreon-ha/upgrade-from-21-04.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/upgrade/centreon-ha/upgrade-from-21-10.md, versioned_docs/version-22.10/upgrade/centreon-ha/upgrade-from-20-04.md, versioned_docs/version-22.10/upgrade/centreon-ha/upgrade-from-20-10.md, versioned_docs/version-22.10/upgrade/centreon-ha/upgrade-from-21-04.md, versioned_docs/version-22.10/upgrade/centreon-ha/upgrade-from-21-10.md
22.04 changed to 22.10
- [X ] 22.10.x (staging)
=> Wrong target version in HA upgrade to 22.10 topic

i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-commercial-extensions.md, versioned_docs/version-22.10/releases/centreon-commercial-extensions.md
Prepare release notes for Centreon MAP 22.10.4 release.
=> doc(release): prepare release notes for MAP 22.10.4

i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-commercial-extensions.md, versioned_docs/version-22.10/releases/centreon-commercial-extensions.md
Add missing Centreon MAP legacy entry for 22.10.4
=> update map 22.10.4 rn legacy section

cloud/installation/prerequisites.md, i18n/fr/docusaurus-plugin-content-docs-cloud/current/installation/prerequisites.md
Update Cloud poller prerequisites (Alma8 instead of Centos7)
=> Update Cloud poller prerequisites (Alma8)

i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-commercial-extensions.md, versioned_docs/version-22.04/releases/centreon-commercial-extensions.md
Prepare release notes for Centreon MAP 22.04.4
=> doc(release): prepare release notes for MAP 22.04.4

docusaurus.config.js, i18n/en/docusaurus-theme-classic/footer.json, i18n/fr/docusaurus-theme-classic/footer.json
Update copyright end year in the footer of the doc as the function that updated it automatically is somehow not working. Also, @Nohzoh has questioned the legality of having a dynamic date.
=> Update copyright end year

i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md, versioned_docs/version-22.04/releases/centreon-core.md
Prepare release note for Centreon WEB 22.04.9 (hotfix)
=> doc(release): prepare release notes for WEB 22.04.9

i18n/fr/docusaurus-plugin-content-docs/version-21.10/graph-views/install.md, i18n/fr/docusaurus-plugin-content-docs/version-21.10/installation/prerequisites.md, i18n/fr/docusaurus-plugin-content-docs/version-21.10/reporting/installation.md, i18n/fr/docusaurus-plugin-content-docs/version-21.10/service-mapping/install.md, i18n/fr/docusaurus-plugin-content-docs/version-22.04/graph-views/install.md, i18n/fr/docusaurus-plugin-content-docs/version-22.04/graph-views/map-web-install.md, i18n/fr/docusaurus-plugin-content-docs/version-22.04/installation/prerequisites.md, i18n/fr/docusaurus-plugin-content-docs/version-22.04/reporting/installation.md, i18n/fr/docusaurus-plugin-content-docs/version-22.04/service-mapping/install.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/graph-views/install.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/graph-views/map-web-install.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/installation/prerequisites.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/reporting/installation.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/service-mapping/install.md, versioned_docs/version-21.10/graph-views/install.md, versioned_docs/version-21.10/installation/prerequisites.md, versioned_docs/version-21.10/reporting/installation.md, versioned_docs/version-22.04/graph-views/install.md, versioned_docs/version-22.04/graph-views/map-web-install.md, versioned_docs/version-22.04/installation/prerequisites.md, versioned_docs/version-22.04/reporting/installation.md, versioned_docs/version-22.04/service-mapping/install.md, versioned_docs/version-22.10/graph-views/install.md, versioned_docs/version-22.10/graph-views/map-web-install.md, versioned_docs/version-22.10/installation/prerequisites.md, versioned_docs/version-22.10/reporting/installation.md, versioned_docs/version-22.10/service-mapping/install.md
Unify OS requirements and warn about the coming end of centos7.
=> Unify OS requirements and warn about the coming end of centos7

i18n/fr/docusaurus-plugin-content-docs/version-22.04/graph-views/map-web-update.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/graph-views/map-web-update.md, versioned_docs/version-22.04/graph-views/map-web-update.md, versioned_docs/version-22.10/graph-views/map-web-update.md
Remove drop database section from MAP update.
=> Remove drop database section from MAP update

pp/sidebarsPp.js
Move plugin packs release notes to top of ToC
=> Move plugin packs release notes to top of ToC

i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md, versioned_docs/version-22.04/releases/centreon-core.md
Prepare release note for Web 22.04.10 (hotfix)
- x ] 22.04.x (staging)
=> doc(release): prepare release note for Web 22.04.10

i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md, versioned_docs/version-22.10/releases/centreon-os.md
Prepare release note for Web 22.10.5 (hotfix)
=> doc(release): prepare release note for Web 22.10.5

i18n/fr/docusaurus-plugin-content-docs/version-21.10/monitoring/monitoring-servers/add-a-remote-server-to-configuration.md, versioned_docs/version-21.10/monitoring/monitoring-servers/add-a-remote-server-to-configuration.md
Made a fix on this page : https://docs.centreon.com/docs/21.10/monitoring/monitoring-servers/add-a-remote-server-to-configuration/#step-1-configure-a-new-remote-server
where the broker output is speficied, but it is written Output 1 - Unified SQL (not yet existing on 21.10), the existing sql output is "Output 1 - Broker SQL database"
=> Correct broker ouput sql

i18n/fr/docusaurus-plugin-content-docs/version-22.10/upgrade/upgrade-from-22-04.md, versioned_docs/version-22.10/upgrade/upgrade-from-22-04.md
Restart centreon after poller upgrade
=> Restart centreon after poller upgrade

i18n/fr/docusaurus-plugin-content-docs/version-23.04/installation/installation-of-a-poller/using-packages.md, versioned_docs/version-23.04/installation/installation-of-a-poller/using-packages.md
Gorgoned service is not enabled by default: incomplete command in the documentation for poller installation.
=> Update poller installation doc (next)

i18n/fr/docusaurus-plugin-content-docs/version-21.10/administration/secure-platform.md, i18n/fr/docusaurus-plugin-content-docs/version-22.04/administration/secure-platform.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/administration/secure-platform.md, versioned_docs/version-21.10/administration/secure-platform.md, versioned_docs/version-22.04/administration/secure-platform.md, versioned_docs/version-22.10/administration/secure-platform.md
Fixes when a Centreon plateform uses HTTPS are missing. Theses fixes can be found on the internet or are only known by the Centreon members. Enhancing the documentation will reduce the number of support tickets and related thread on The Watch.
Those parts include:
* Gorgone/Auto discovery fix 
* Export your configuration” button fix (does not exists for Centreon 21.10 so no modifications here) -> This part has been removed from the PR. A fix should come making thoses changes not needed
=> Enhance HTTPS documentation

i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-commercial-extensions.md, versioned_docs/version-22.04/releases/centreon-commercial-extensions.md
Remove mbi 22.04.4 from releases
=> doc(release):remove mbi 22.04.4 from releases

i18n/fr/docusaurus-plugin-content-docs/version-21.10/upgrade/upgrade-from-20-10.md, i18n/fr/docusaurus-plugin-content-docs/version-21.10/upgrade/upgrade-from-21-04.md, i18n/fr/docusaurus-plugin-content-docs/version-22.04/upgrade/upgrade-from-20-10.md, i18n/fr/docusaurus-plugin-content-docs/version-22.04/upgrade/upgrade-from-21-04.md, i18n/fr/docusaurus-plugin-content-docs/version-22.04/upgrade/upgrade-from-21-10.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/upgrade/upgrade-from-20-10.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/upgrade/upgrade-from-21-04.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/upgrade/upgrade-from-21-10.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/upgrade/upgrade-from-22-04.md, versioned_docs/version-21.10/upgrade/upgrade-from-20-10.md, versioned_docs/version-21.10/upgrade/upgrade-from-21-04.md, versioned_docs/version-22.04/upgrade/upgrade-from-20-10.md, versioned_docs/version-22.04/upgrade/upgrade-from-21-04.md, versioned_docs/version-22.04/upgrade/upgrade-from-21-10.md, versioned_docs/version-22.10/upgrade/upgrade-from-21-04.md, versioned_docs/version-22.10/upgrade/upgrade-from-21-10.md, versioned_docs/version-22.10/upgrade/upgrade-from-22-04.md
Path changed from _/opt/rh/httpd24/root/etc/httpd/conf.d/10-centreon.conf_ to _/etc/httpd/conf.d/10-centreon.conf_
=> Correct new path to file 10-centreon.conf

i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-commercial-extensions.md, versioned_docs/version-22.04/releases/centreon-commercial-extensions.md
Prepare release notes for Centreon Modules next 22.04 (MAP 22.04.6)
=> doc(release): Add release notes for MAP 22.04.6

i18n/fr/docusaurus-plugin-content-docs/version-22.04/reporting/installation.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/reporting/installation.md, versioned_docs/version-22.04/reporting/installation.md, versioned_docs/version-22.10/reporting/installation.md
The link of content of view_creation.sql is not present on 22.04 and 22.10.
I got the link from 21.10, please check if this content is still correct and compatible to 22.04 and 22.10.
=> Mbi view creation

i18n/fr/docusaurus-plugin-content-docs/version-23.04/graph-views/install.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/graph-views/map-web-install.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/graph-views/upgrade.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/installation/installation-of-a-central-server/using-packages.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/installation/installation-of-a-poller/using-packages.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/installation/installation-of-a-remote-server/using-packages.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/upgrade/upgrade-from-22-04.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/upgrade/upgrade-from-22-10.md, versioned_docs/version-23.04/graph-views/install.md, versioned_docs/version-23.04/graph-views/map-web-install.md, versioned_docs/version-23.04/graph-views/upgrade.md, versioned_docs/version-23.04/installation/installation-of-a-central-server/using-packages.md, versioned_docs/version-23.04/installation/installation-of-a-poller/using-packages.md, versioned_docs/version-23.04/installation/installation-of-a-remote-server/using-packages.md, versioned_docs/version-23.04/upgrade/upgrade-from-22-04.md, versioned_docs/version-23.04/upgrade/upgrade-from-22-10.md
instructions to install plugins repository in order to avoid dependencies issue when installing centreon
=> fix(debian): instructions to install plugins repository

i18n/fr/docusaurus-plugin-content-docs/version-23.04/integrations/notifications/plugin-telegram.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/integrations/npm/ntopng.md, versioned_docs/version-23.04/integrations/notifications/plugin-telegram.md, versioned_docs/version-23.04/integrations/npm/ntopng.md
Adapt doc to list of supported OSs (leftover integrations - the rest was one in https://github.com/centreon/centreon-documentation/pull/2246)
=> Adapt doc to list of supported OSs (leftover integrations)

i18n/fr/docusaurus-plugin-content-docs/version-20.04/alerts-notifications/notif-flapping.md, i18n/fr/docusaurus-plugin-content-docs/version-20.04/monitoring/event-handler.md, i18n/fr/docusaurus-plugin-content-docs/version-20.10/alerts-notifications/notif-flapping.md, i18n/fr/docusaurus-plugin-content-docs/version-20.10/monitoring/event-handler.md, i18n/fr/docusaurus-plugin-content-docs/version-21.04/alerts-notifications/notif-flapping.md, i18n/fr/docusaurus-plugin-content-docs/version-21.04/monitoring/event-handler.md, i18n/fr/docusaurus-plugin-content-docs/version-21.10/alerts-notifications/notif-flapping.md, i18n/fr/docusaurus-plugin-content-docs/version-21.10/monitoring/event-handler.md, i18n/fr/docusaurus-plugin-content-docs/version-22.04/alerts-notifications/notif-flapping.md, i18n/fr/docusaurus-plugin-content-docs/version-22.04/monitoring/event-handler.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/alerts-notifications/notif-flapping.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/monitoring/event-handler.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/alerts-notifications/notif-flapping.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/monitoring/event-handler.md
Fix typing mistakes on notif flapping doc FR for all version : REndez --> Rendez
=> Fix typing mistakes notif flapping doc all version

i18n/fr/docusaurus-plugin-content-docs/version-22.04/graph-views/map-web-troubleshooting.md, i18n/fr/docusaurus-plugin-content-docs/version-22.04/graph-views/map-web-update.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/graph-views/map-web-troubleshooting.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/graph-views/map-web-update.md, versioned_docs/version-22.04/graph-views/map-web-troubleshooting.md, versioned_docs/version-22.04/graph-views/map-web-update.md, versioned_docs/version-22.10/graph-views/map-web-troubleshooting.md, versioned_docs/version-22.10/graph-views/map-web-update.md
Remove Broker storage output from MAP topics.
=> Remove Broker storage output from MAP topics

i18n/fr/docusaurus-plugin-content-docs/version-23.04/api/rest-api-v2.md, versioned_docs/version-23.04/api/rest-api-v2.md
=> Fixed the openAPI yaml link

.github/PULL_REQUEST_TEMPLATE.md
Rename PP to MC in PR template
=> Rename PP to MC in PR template

cloud/alerts-notifications/resources-status.md, i18n/fr/docusaurus-plugin-content-docs-cloud/current/alerts-notifications/resources-status.md
Remove cloud update temporarily: removed this update that has to be published only when the cloud version is released.
=> Remove cloud update temporarily

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-snmp.md, pp/integrations/plugin-packs/procedures/applications-protocol-snmp.md, pp/sidebarsPp.js
Add standard SNMP host check command and host template in applications-protocol-snmp
=> Add standard SNMP host check command and host template in protocol snmp PP

i18n/fr/docusaurus-plugin-content-docs/version-23.04/installation/installation-of-a-central-server/using-packages.md
=> Fix EL9 Apache command in FR

i18n/fr/docusaurus-plugin-content-docs/version-23.10/installation/installation-of-a-central-server/using-packages.md
Fix EL9 Apache command in FR - 23.10
=> Fix EL9 Apache command in FR - 23.10

i18n/fr/docusaurus-plugin-content-docs/version-22.04/graph-views/map-web-install.md, versioned_docs/version-22.04/graph-views/map-web-install.md
missing minor version number for MAP release installation resulting with a 404 error
=> MON-19289 - missing minor version number for MAP release installation

i18n/fr/docusaurus-plugin-content-docs/version-23.10/administration/secure-platform.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/graph-views/advanced-configuration.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/graph-views/configuration.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/graph-views/troubleshooter.md, versioned_docs/version-23.10/administration/secure-platform.md, versioned_docs/version-23.10/graph-views/advanced-configuration.md, versioned_docs/version-23.10/graph-views/configuration.md, versioned_docs/version-23.10/graph-views/troubleshooter.md
Replace vim by vi (next, 23.10)
=> Replace vim by vi (next, 23.10)

i18n/fr/docusaurus-plugin-content-docs/version-23.10/installation/installation-of-a-central-server/using-packages.md, versioned_docs/version-23.10/installation/installation-of-a-central-server/using-packages.md
curl missing in Debian dependencies for poller - next 23.10
=> curl missing in Debian dependencies for poller - next 23.10

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-monitoring-centreon-central.md, pp/integrations/plugin-packs/procedures/applications-monitoring-centreon-central.md
=> enh(pack): add a workaround for self-monitored hosts

cloud/installation/prerequisites.md, i18n/fr/docusaurus-plugin-content-docs-cloud/current/installation/prerequisites.md
Remove warning about CentOS7 in Cloud section
=> Remove warning about CentOS7 in Cloud section

i18n/fr/docusaurus-plugin-content-docs/version-22.04/reporting/installation.md, versioned_docs/version-22.04/reporting/installation.md
Remove java in 22.04 MBI installation procedure
=> Remove java in 22.04 MBI installation procedure

i18n/fr/docusaurus-plugin-content-docs/version-20.04/monitoring/event-handler.md, i18n/fr/docusaurus-plugin-content-docs/version-20.10/monitoring/event-handler.md, i18n/fr/docusaurus-plugin-content-docs/version-21.04/monitoring/event-handler.md, i18n/fr/docusaurus-plugin-content-docs/version-21.10/monitoring/event-handler.md, i18n/fr/docusaurus-plugin-content-docs/version-22.04/monitoring/event-handler.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/monitoring/event-handler.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/monitoring/event-handler.md, versioned_docs/version-20.04/monitoring/event-handler.md, versioned_docs/version-20.10/monitoring/event-handler.md, versioned_docs/version-21.04/monitoring/event-handler.md, versioned_docs/version-21.10/monitoring/event-handler.md, versioned_docs/version-22.04/monitoring/event-handler.md, versioned_docs/version-22.10/monitoring/event-handler.md, versioned_docs/version-23.04/monitoring/event-handler.md
Fix typing mistakes on event handler doc FR for all version and for all languages: Opyions --> Options 
https://docs.centreon.com/docs/monitoring/event-handler/
https://docs.centreon.com/fr/docs/monitoring/event-handler/
=> Fix typing mistakes on event handler doc for all version and all languages

i18n/fr/docusaurus-plugin-content-docs/version-22.10/resources/contribute.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/resources/contribute.md
Fix typing mistakes on contrib FR doc : dosier --> dossier
https://docs.centreon.com/fr/docs/resources/contribute/
=> fix typing mistakes on contrib FR doc

i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md, versioned_docs/version-22.04/releases/centreon-core.md
=> doc(release): prepare release notes for oss 22.04

i18n/fr/docusaurus-plugin-content-docs/version-23.10/api/clapi.md, versioned_docs/version-23.10/api/clapi.md
Remove obsolete CLAPI params - next
=> Remove obsolete CLAPI params - next

i18n/fr/docusaurus-plugin-content-docs/version-21.10/api/clapi.md, i18n/fr/docusaurus-plugin-content-docs/version-22.04/api/clapi.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/api/clapi.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/api/clapi.md, versioned_docs/version-21.10/api/clapi.md, versioned_docs/version-22.04/api/clapi.md, versioned_docs/version-22.10/api/clapi.md, versioned_docs/version-23.04/api/clapi.md
=> Remove obsolete CLAPI params

i18n/fr/docusaurus-plugin-content-docs/version-21.10/reporting/available-reports.md, i18n/fr/docusaurus-plugin-content-docs/version-22.04/reporting/available-reports.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/reporting/available-reports.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/reporting/available-reports.md, versioned_docs/version-21.10/reporting/available-reports.md, versioned_docs/version-22.04/reporting/available-reports.md, versioned_docs/version-22.10/reporting/available-reports.md, versioned_docs/version-23.04/reporting/available-reports.md
Fixed issue with openssl command to save .pem file for Host-Graphs-V2 and Hostgroup-Graphs-V2 reports and SSL/TLS Central server case.
=> fix command error for saving pem file

i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md, versioned_docs/version-22.10/releases/centreon-os.md
Move Collect 22.10.3 entry about macros from broker section to engine section.
=> fix(doc): update collect 22.10.3 release note

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/releases/release-notes.md, pp/integrations/plugin-packs/releases/release-notes.md
=> rn(connectors): monitoring connectors release 20230706

i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-commercial-extensions.mdx, versioned_docs/version-23.04/releases/centreon-commercial-extensions.mdx
Update MAP 23.04.1 release note, as two entries were missing.
=> doc: Update map rn 23.04.1 with missing entries

i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-commercial-extensions.md, versioned_docs/version-22.10/releases/centreon-commercial-extensions.md
Update MAP 22.10.7 release note, as two entries were missing.
=> doc: Update map rn 22.10.7 with missing entries

i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx, versioned_docs/version-23.04/releases/centreon-os.mdx
Prepare release notes for
* WEB 23.04.6
* GORGONE 23.04.4
* OPEN TICKETS 23.04.2
=> doc(release): prepare release notes for oss 23.04

i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md, versioned_docs/version-22.10/releases/centreon-os.md
* WEB 22.10.11
* GORGONE 22.10.2
* OPENTICKETS 22.10.2
* HA 22.10.1
=> doc(release): prepare release notes for oss 22.10

i18n/fr/docusaurus-plugin-content-docs/version-22.04/graph-views/install.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/graph-views/install.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/graph-views/map-web-install.md, versioned_docs/version-21.10/graph-views/install.md, versioned_docs/version-22.04/graph-views/install.md, versioned_docs/version-22.10/graph-views/install.md, versioned_docs/version-23.04/graph-views/map-web-install.md
Just removed "CentOS" references for MAP installation.
=> MON-17923 Remove CentOS references

i18n/fr/docusaurus-plugin-content-docs/version-22.10/administration/secure-platform.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/administration/secure-platform.md, versioned_docs/version-22.10/administration/secure-platform.md, versioned_docs/version-23.04/administration/secure-platform.md
Anchors for this part ar now (from 22.10) on its own "technical" part
=> correct user/group security anchor for 23.04 & 22.10

i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-commercial-extensions.md, versioned_docs/version-22.10/releases/centreon-commercial-extensions.md
Fix AD version in 22.10 release notes
=> Fix AD version in 22.10 release notes

.github/workflows/documentation.yml
enh(ci): retrieve github runners instead of collect
collect runners are too slow to be triggered
=> enh(ci): retrieve github runners instead of collect

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-bgp.md, pp/integrations/plugin-packs/procedures/applications-protocol-bgp.md
=> Make deprecated BGP connector doc consistent

i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx, versioned_docs/version-23.04/releases/centreon-os.mdx
"Bug fixes" sections must not be expanded by default. Remove the "open" attribute from the "details" element.
=> Clean up "open" attribute in RNs

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/releases/release-notes.md, pp/integrations/plugin-packs/releases/release-notes.md
Requalify enhancement on Windows SNMP to breaking change
=> Requalify enhancement on Windows SNMP to breaking change

i18n/fr/docusaurus-plugin-content-docs/version-23.10/developer/developer-broker-mapping.md, versioned_docs/version-23.10/developer/developer-broker-mapping.md
add missing fields in metric protobuf object
=> fix(doc): add missing fields to metric protobug object

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-monitoring-speedtest.md, pp/integrations/plugin-packs/procedures/applications-monitoring-speedtest.md
=> MON-21590 - [Documentation] apps::monitoring::speedtest - add jitter unit

.github/workflows/actionlint.yml, .github/workflows/dependabot_jira.yml
=> feat(ci): add linting to worflow and actions files

i18n/fr/docusaurus-plugin-content-docs/version-23.10/api/rest-api-v2.md, versioned_docs/version-23.10/api/rest-api-v2.md
Title. Current link status is 404
=> Fix the Postman 23.10 collection link

i18n/fr/docusaurus-plugin-content-docs/version-23.10/releases/centreon-os.mdx, versioned_docs/version-23.10/releases/centreon-os.mdx
Add missing release note entry for gorgone 23.10.1 (original release date 17/11/2023)
REF #MON-25024 #MON-24485
=> doc(release): add missing release note entry for gorgone 23.10.1

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-switchs-alcatel-omniswitch-snmp.md, pp/integrations/plugin-packs/procedures/network-switchs-alcatel-omniswitch-snmp.md
Update network-switchs-alcatel-omniswitch-snmp doc
=> enh(mc): update network-switchs-alcatel-omniswitch-snmp doc

versioned_docs/version-24.04/api/clapi.md
Add ldap_sync_interval and ldap_auto_sync in clapi LDAP parameters list
=> fix(clapi) add ldap_sync_interval and ldap_auto_sync in clapi LDAP parameters list

cloud/getting-started/welcome.md, cloud/sidebarsCloud.js, docusaurus.config.js, i18n/fr/docusaurus-plugin-content-docs-cloud/current.json, i18n/fr/docusaurus-plugin-content-docs-cloud/current/getting-started/welcome.md, i18n/fr/docusaurus-plugin-content-docs/version-22.04.json, i18n/fr/docusaurus-plugin-content-docs/version-22.10.json, i18n/fr/docusaurus-plugin-content-docs/version-22.10/getting-started/welcome.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04.json, i18n/fr/docusaurus-plugin-content-docs/version-23.04/getting-started/welcome.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10.json, i18n/fr/docusaurus-plugin-content-docs/version-23.10/getting-started/welcome.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04.json, i18n/fr/docusaurus-plugin-content-docs/version-24.04/getting-started/welcome.md, i18n/fr/docusaurus-plugin-content-pages/index.js, src/pages/index.js, versioned_docs/version-22.10/getting-started/welcome.md, versioned_docs/version-22.10/releases/centreon-os.md, versioned_docs/version-23.04/getting-started/welcome.md, versioned_docs/version-23.10/getting-started/welcome.md, versioned_docs/version-24.04/getting-started/welcome.md, versioned_sidebars/version-22.04-sidebars.json, versioned_sidebars/version-22.10-sidebars.json, versioned_sidebars/version-23.04-sidebars.json, versioned_sidebars/version-23.10-sidebars.json, versioned_sidebars/version-24.04-sidebars.json
Add a header page for the getting started chapter in the Cloud section so that people can send/save a link to it.
=> Add header page for Cloud "getting started"

docusaurus.config.js
Add "last updated" date to Cloud and MC pages.
=> Add "last updated" date to Cloud and MC pages

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/operatingsystems-linux-ssh.md, pp/integrations/plugin-packs/procedures/operatingsystems-linux-ssh.md
Update documentation with systemd modifications
=>  [CTOR-139] [Documentation] Operatingsystems linux local mode systemd sc status not working in RHEL 9

i18n/fr/docusaurus-plugin-content-docs/version-23.10/installation/installation-of-centreon-ha/installation-2-nodes.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/installation/installation-of-centreon-ha/installation-4-nodes.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/installation/installation-of-centreon-ha/installation-2-nodes.md, versioned_docs/version-23.10/installation/installation-of-centreon-ha/installation-2-nodes.md, versioned_docs/version-23.10/installation/installation-of-centreon-ha/installation-4-nodes.md, versioned_docs/version-24.04/installation/installation-of-centreon-ha/installation-2-nodes.md
to be consistent with the central installation requirements and the official mariadb repository, the configuration file to be taken into account is server.cnf. The mariadb-server.cnf file is used when mariadb-server is installed from the appstream EL repository.
=> Enh ha installation el9

i18n/fr/docusaurus-plugin-content-docs/version-23.10/releases/centreon-os.mdx, versioned_docs/version-23.10/releases/centreon-os.mdx
added : - [Broker] Fixed an issue causing hostgroups to fail to appear if they had been used before and emptied of their hosts and then populated again.
=> doc(release): Fix release notes for Collect 23.10

i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md, versioned_docs/version-22.10/releases/centreon-os.md
=> doc(release): Deleted mysql8 mention in release notes for OSS 22.10

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/operatingsystems-linux-nrpe4.md, pp/integrations/plugin-packs/procedures/operatingsystems-linux-nrpe4.md
=> fix(mc): removed direct link to packages + trailing spaces

i18n/fr/docusaurus-plugin-content-docs/version-23.10/releases/centreon-commercial-extensions.mdx, i18n/fr/docusaurus-plugin-content-docs/version-24.04/releases/centreon-commercial-extensions.mdx, versioned_docs/version-23.10/releases/centreon-commercial-extensions.mdx, versioned_docs/version-24.04/releases/centreon-commercial-extensions.mdx
Replaced "Packaged SELinux rules" with "Packaged SELinux rules for EL distributions".
=> doc(release): Modification release notes 24.04 and 23.10

i18n/fr/docusaurus-plugin-content-docs/version-23.10/installation/installation-of-centreon-ha/installation-2-nodes.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/installation/installation-of-centreon-ha/installation-4-nodes.md, versioned_docs/version-23.10/installation/installation-of-centreon-ha/installation-2-nodes.md, versioned_docs/version-23.10/installation/installation-of-centreon-ha/installation-4-nodes.md
Modify the order of centreon group resources.
cbd-broker-sql will be move before grogone resource like as define in the upgrade documentation make few month ago.
=> MON-147214 [ENH] HA optimize resource order

i18n/fr/docusaurus-plugin-content-docs/version-23.10/installation/installation-of-centreon-ha/installation-2-nodes.md, versioned_docs/version-23.10/installation/installation-of-centreon-ha/installation-2-nodes.md
Fix for centreon-repl account in EL9 HA 2 nodes install
=> [FIX] HA centreon-repl user and password for EL9

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-databases-oracle.md, pp/integrations/plugin-packs/procedures/applications-databases-oracle.md
Oracle Database missing informations in perl librairies step
=> CTOR-788 : Oracle Database missing informations in perl librairies step

i18n/fr/docusaurus-plugin-content-docs/version-22.10/reporting/installation.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/reporting/installation.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/reporting/installation.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/reporting/installation.md, i18n/fr/docusaurus-plugin-content-docs/version-24.10/reporting/installation.md, versioned_docs/version-22.10/reporting/installation.md, versioned_docs/version-23.04/reporting/installation.md, versioned_docs/version-23.10/reporting/installation.md, versioned_docs/version-24.04/reporting/installation.md, versioned_docs/version-24.10/reporting/installation.md
Editing command for mbi access to the central database after changing files permissions for the mbi module to 644
=> fix(mbi): edit command for MBI :  Access to the Central database

package.json
Yesterday we couldn't build the doc locally, with an error that said that the roboto typeface was missing. We ran the "yarn add typeface-roboto" command and that solved the problem. The diff showed that only this had changed, so I'm doing a PR in the hope that prevents any problem on the production machines (but, yes, it is weird).
=> Fix weird problem with roboto typeface

pp/sidebarsPp.js
Remove docker rest api from cloud section
=> Wrong directory for Docker RestAPI plugin

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-webservers-iis-restapi.md, pp/integrations/plugin-packs/procedures/applications-webservers-iis-restapi.md
Add prerequisites in applications-webservers-iis-restapi
Doc feedback:
HI, The IIS Restapi plugin uses the IIS Administration api component. The version available for download from Microsoft (6.0.0) has a major bug when the supervised servers are not in the UTC timezone. All my servers are in UTC-10 and using the plugin generates an error in the application event log. 
The solution was to upgrade to version 2.3.0 of the IIS Administration API. Best regards
Patrick
=> CTOR-1011 : Add prerequisites in applications-webservers-iis-restapi

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/getting-started/how-to-guides/windows-winrm-wsman-tutorial.md, pp/integrations/plugin-packs/getting-started/how-to-guides/windows-winrm-wsman-tutorial.md
=> CTOR-1014 : Problem with windows-winrm-wsman-tutorial page

cloud/alerts-notifications/dashboards.md, i18n/fr/docusaurus-plugin-content-docs-cloud/current/alerts-notifications/dashboards.md
Add Web page widget for 24.11 cloud release
=> Add Web page widget for 24.11 cloud release

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/operatingsystems-as400-connector.md, pp/integrations/plugin-packs/procedures/operatingsystems-as400-connector.md
Update prerequisites for AS400 daemon
=> CTOR-1199 : Java version for operatingsystems-as400-connector

pp/sidebarsPp.js
Swap SAP HANA in Database section in the sidebar.
=> CTOR-1100: Change SAP Hana doc repertory

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/getting-started/how-to-guides/troubleshooting-plugins.md, pp/integrations/plugin-packs/getting-started/how-to-guides/troubleshooting-plugins.md
Add troubleshooting section for snmp uptime issue
=> CTOR-1075 : Doc(operatingsystems-linux-snmp) : Add troubleshooting section for snmp uptime issue

i18n/fr/docusaurus-plugin-content-docs/version-24.04/releases/centreon-os.mdx, versioned_docs/version-24.04/releases/centreon-os.mdx
=> doc(release) Release notes web 24.04.9

i18n/fr/docusaurus-plugin-content-docs/version-24.10/releases/centreon-os.mdx, versioned_docs/version-24.10/releases/centreon-os.mdx
=> doc(release) Release notes for web 24.10.3
