i18n/fr/docusaurus-plugin-content-docs/version-23.10/alerts-notifications/event-console.md, versioned_docs/version-23.10/alerts-notifications/event-console.md
=> Deprecated pages will be removed in the next major version

i18n/fr/docusaurus-plugin-content-docs/version-22.10/installation/installation-of-centreon-ha/installation-4-nodes.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/installation/installation-of-centreon-ha/installation-4-nodes.md
Fix the command for the FR version.
=> Centreon-HA - Fix SQL collocation constraints

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/releases/release-notes.md, pp/integrations/plugin-packs/releases/release-notes.md
=> Fix weird label in connector release notes

i18n/fr/docusaurus-plugin-content-docs/version-21.10/security/key-rotation.md, i18n/fr/docusaurus-plugin-content-docs/version-22.04/security/key-rotation.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/security/key-rotation.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/security/key-rotation.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/security/key-rotation.md, versioned_docs/version-21.10/security/key-rotation.md, versioned_docs/version-22.04/security/key-rotation.md, versioned_docs/version-22.10/security/key-rotation.md, versioned_docs/version-23.04/security/key-rotation.md, versioned_docs/version-23.10/security/key-rotation.md
=> Remove key expiration date

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-cadvisor-api.md, pp/integrations/plugin-packs/procedures/cloud-cadvisor-api.md
=> Updating cAdvisor procedure

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-aws-ec2.md, pp/integrations/plugin-packs/procedures/cloud-aws-ec2.md
=> Update EC2 MC procedure

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-fortinet-fortigate-restapi.md, pp/integrations/plugin-packs/procedures/network-fortinet-fortigate-restapi.md
=> Update Fortigate RestAPI procedure

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-aws-rds.md, pp/integrations/plugin-packs/procedures/cloud-aws-rds.md
=> Update AWS RDS procedure

i18n/fr/docusaurus-plugin-content-docs/version-23.10/alerts-notifications/acknowledge.md, versioned_docs/version-23.10/alerts-notifications/acknowledge.md
=> Remove persistent option from acknowledgement window

versioned_docs/version-23.10/administration/logging-configuration-changes.md, versioned_docs/version-23.10/monitoring/basic-objects/hosts-switch-poller.md, versioned_docs/version-23.10/monitoring/generic-actions.md
Fix any "massive change" labels left by our proofreader in version 23.10 of the documentation.
=> Mass change 23.10

i18n/fr/docusaurus-plugin-content-docs/version-23.10/alerts-notifications/resources-status.md, versioned_docs/version-23.10/alerts-notifications/resources-status.md
=> View by host/by service

versioned_docs/version-23.04/migrate/migrate-from-el-to-el.md
=> Fix typo 23.04

i18n/fr/docusaurus-plugin-content-docs/version-22.04/graph-views/install.md, i18n/fr/docusaurus-plugin-content-docs/version-22.04/graph-views/map-web-install.md, i18n/fr/docusaurus-plugin-content-docs/version-22.04/installation/installation-of-a-central-server/using-packages.md, i18n/fr/docusaurus-plugin-content-docs/version-22.04/installation/installation-of-a-poller/using-packages.md, i18n/fr/docusaurus-plugin-content-docs/version-22.04/installation/installation-of-a-remote-server/using-packages.md, i18n/fr/docusaurus-plugin-content-docs/version-22.04/installation/offline.md, versioned_docs/version-22.04/graph-views/install.md, versioned_docs/version-22.04/graph-views/map-web-install.md, versioned_docs/version-22.04/installation/installation-of-a-central-server/using-packages.md, versioned_docs/version-22.04/installation/installation-of-a-poller/using-packages.md, versioned_docs/version-22.04/installation/installation-of-a-remote-server/using-packages.md, versioned_docs/version-22.04/installation/offline.md
=> Update 22.04 repo for Debian

i18n/fr/docusaurus-plugin-content-docs/version-22.10/graph-views/install.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/graph-views/map-web-install.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/graph-views/upgrade.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/installation/installation-of-a-central-server/using-packages.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/installation/installation-of-a-poller/using-packages.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/installation/installation-of-a-remote-server/using-packages.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/installation/offline.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/reporting/installation.md, versioned_docs/version-22.10/graph-views/install.md, versioned_docs/version-22.10/graph-views/map-web-install.md, versioned_docs/version-22.10/graph-views/upgrade.md, versioned_docs/version-22.10/installation/installation-of-a-central-server/using-packages.md, versioned_docs/version-22.10/installation/installation-of-a-poller/using-packages.md, versioned_docs/version-22.10/installation/installation-of-a-remote-server/using-packages.md, versioned_docs/version-22.10/installation/offline.md, versioned_docs/version-22.10/reporting/installation.md
=> Update 22.10 repo for Debian

i18n/fr/docusaurus-plugin-content-docs/version-23.10/graph-views/map-web-create-standard-map.md, versioned_docs/version-23.10/graph-views/map-web-create-standard-map.md
MAP - Add info for untied element
=> MAP - Add info for untied element

cloud/graph-views/map-web-create-standard-map.md, i18n/fr/docusaurus-plugin-content-docs-cloud/current/graph-views/map-web-create-standard-map.md
This reverts commit 5a68cd4b20f1737a3dd255a5dc51eed52298cb41.
=> Revert "MAP - Add info for untied element for Cloud (#2746)"

cloud/installation/deploy-poller.md, i18n/fr/docusaurus-plugin-content-docs-cloud/current/installation/deploy-poller.md
=> Poller installation command

i18n/fr/docusaurus-plugin-content-docs/version-23.10/api/clapi.md, versioned_docs/version-23.10/api/clapi.md
=> Ignore empty and commented lines for CLAPI import

i18n/fr/docusaurus-plugin-content-docs/version-23.10/mobile/introduction.md, versioned_docs/version-23.10/mobile/introduction.md
=> Delegated authentication supported by mobile app

i18n/fr/docusaurus-plugin-content-docs/version-23.10/monitoring/monitoring-servers/advanced-configuration.md, versioned_docs/version-23.10/monitoring/monitoring-servers/advanced-configuration.md
=> Document Broker's new behaviour with multiple database connections

versioned_sidebars/version-23.10-sidebars.json
Complements https://github.com/centreon/centreon-documentation/pull/2744
=> Add missing ToC item

i18n/fr/docusaurus-plugin-content-docs/version-23.10/api/graph-views-api.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/api/graph-views-map-api.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/api/rest-api-v2.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/graph-views/introduction-map.md, versioned_docs/version-23.10/api/graph-views-api.md, versioned_docs/version-23.10/api/graph-views-map-api.md, versioned_docs/version-23.10/api/rest-api-v2.md, versioned_docs/version-23.10/graph-views/introduction-map.md
update links to api documentation 23.10
Refs: MON-24087
=> enh(api): update links to api documentation 23.10

cloud/installation/deploy-poller.md, i18n/fr/docusaurus-plugin-content-docs-cloud/current/installation/deploy-poller.md
=> [Cloud] Organization_token

i18n/fr/docusaurus-plugin-content-docs/version-23.10/installation/installation-of-centreon-ha/installation-2-nodes.md, versioned_docs/version-23.10/installation/installation-of-centreon-ha/installation-2-nodes.md
=> HA 23.10 - 2 nodes

pp/sidebarsPp.js
=> Remove duplicate entry from ToC

.github/PULL_REQUEST_TEMPLATE.md
=> Add version 24.04 to PR template

i18n/fr/docusaurus-plugin-content-docs/version-23.10/releases/centreon-os.mdx, versioned_docs/version-23.10/releases/centreon-os.mdx
=> Add AWIE to OSS RN

i18n/fr/docusaurus-plugin-content-docs/version-23.10/upgrade/upgrade-from-23-04.md, versioned_docs/version-23.10/upgrade/upgrade-from-23-04.md, versioned_sidebars/version-23.10-sidebars.json, versioned_sidebars/version-24.04-sidebars.json
=> Add missing upgrade page

i18n/fr/docusaurus-plugin-content-docs/version-23.04.json, i18n/fr/docusaurus-plugin-content-docs/version-23.10.json, i18n/fr/docusaurus-plugin-content-docs/version-23.10/administration/backup-poller.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/administration/backup.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/administration/disaster-recovery.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04.json, i18n/fr/docusaurus-plugin-content-docs/version-24.04/administration/backup-poller.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/administration/backup.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/administration/disaster-recovery.md, versioned_docs/version-23.10/administration/backup-poller.md, versioned_docs/version-23.10/administration/backup.md, versioned_docs/version-23.10/administration/disaster-recovery.md, versioned_docs/version-24.04/administration/backup-poller.md, versioned_docs/version-24.04/administration/backup.md, versioned_docs/version-24.04/administration/disaster-recovery.md, versioned_sidebars/version-23.10-sidebars.json, versioned_sidebars/version-24.04-sidebars.json
=> Disaster recovery (23.10 and 24.04)

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-php-fpm-web.md, pp/integrations/plugin-packs/procedures/applications-php-fpm-web.md
=> fix(doc) link

i18n/fr/docusaurus-plugin-content-docs/version-22.04/graph-views/map-web-troubleshooting.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/graph-views/map-web-troubleshooting.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/graph-views/map-web-troubleshooting.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/graph-views/map-web-troubleshooting.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/graph-views/map-web-troubleshooting.md, versioned_docs/version-22.04/graph-views/map-web-troubleshooting.md, versioned_docs/version-22.10/graph-views/map-web-troubleshooting.md, versioned_docs/version-23.04/graph-views/map-web-troubleshooting.md, versioned_docs/version-23.10/graph-views/map-web-troubleshooting.md, versioned_docs/version-24.04/graph-views/map-web-troubleshooting.md
=> Fix missing beta in Map URL

versioned_docs/version-22.04/installation/installation-of-centreon-ha/installation-4-nodes.md, versioned_docs/version-22.10/installation/installation-of-centreon-ha/installation-4-nodes.md, versioned_docs/version-23.04/installation/installation-of-centreon-ha/installation-4-nodes.md
=> Fix typo (HA 4 nodes), 23.04 and earlier

i18n/fr/docusaurus-plugin-content-docs/version-23.04/installation/installation-of-a-remote-server/using-packages.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/installation/installation-of-a-central-server/using-packages.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/installation/installation-of-a-central-server/using-packages.md
=> Fix some repo URLs in FR

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-monitoring-centreon-sql-metrics.md, pp/integrations/plugin-packs/procedures/applications-monitoring-centreon-sql-metrics.md
=> enh(epp): applications-monitoring-centreon-sql-metrics

i18n/fr/docusaurus-plugin-content-docs/version-22.10/resources/known-issues.md, versioned_docs/version-22.10/resources/known-issues.md
Add MBI 22.10 EL7 troubleshooting
=> Add MBI 22.10 EL7 troubleshooting

i18n/fr/docusaurus-plugin-content-pages/index.js, src/pages/index.js
fix links in homepage on previews
=> fix(doc): fix links in homepage on previews

i18n/fr/docusaurus-plugin-content-docs/version-22.04/installation/installation-of-a-central-server/unattended.md, i18n/fr/docusaurus-plugin-content-docs/version-22.04/installation/installation-of-a-remote-server/unattended.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/installation/installation-of-a-central-server/unattended.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/installation/installation-of-a-poller/unattended.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/installation/installation-of-a-remote-server/unattended.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/installation/installation-of-a-central-server/unattended.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/installation/installation-of-a-poller/unattended.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/installation/installation-of-a-remote-server/unattended.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/installation/installation-of-a-central-server/unattended.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/installation/installation-of-a-poller/unattended.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/installation/installation-of-a-remote-server/unattended.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/installation/installation-of-a-central-server/unattended.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/installation/installation-of-a-poller/unattended.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/installation/installation-of-a-remote-server/unattended.md, versioned_docs/version-22.04/installation/installation-of-a-central-server/unattended.md, versioned_docs/version-22.04/installation/installation-of-a-poller/unattended.md, versioned_docs/version-22.04/installation/installation-of-a-remote-server/unattended.md, versioned_docs/version-22.10/installation/installation-of-a-central-server/unattended.md, versioned_docs/version-22.10/installation/installation-of-a-poller/unattended.md, versioned_docs/version-22.10/installation/installation-of-a-remote-server/unattended.md, versioned_docs/version-23.04/installation/installation-of-a-central-server/unattended.md, versioned_docs/version-23.04/installation/installation-of-a-poller/unattended.md, versioned_docs/version-23.04/installation/installation-of-a-remote-server/unattended.md, versioned_docs/version-23.10/installation/installation-of-a-poller/unattended.md, versioned_docs/version-23.10/installation/installation-of-a-remote-server/unattended.md, versioned_docs/version-24.04/installation/installation-of-a-central-server/unattended.md, versioned_docs/version-24.04/installation/installation-of-a-poller/unattended.md, versioned_docs/version-24.04/installation/installation-of-a-remote-server/unattended.md
=> Fix unattended command

i18n/fr/docusaurus-plugin-content-docs/version-23.04/monitoring/anomaly-detection.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/monitoring/anomaly-detection.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/monitoring/anomaly-detection.md, versioned_docs/version-23.04/monitoring/anomaly-detection.md, versioned_docs/version-23.10/monitoring/anomaly-detection.md, versioned_docs/version-24.04/monitoring/anomaly-detection.md
=> Remove obsolete FAQ entry from Anomaly Detection topic

i18n/fr/docusaurus-plugin-content-docs/version-23.10/releases/centreon-commercial-extensions.mdx, versioned_docs/version-23.10/releases/centreon-commercial-extensions.mdx
Hotfix : add rn for map 23.10.1
=> doc(release): Prepare release notes for modules 23.10

i18n/fr/docusaurus-plugin-content-docs/version-23.10/releases/centreon-os.mdx
=> Move Awie section to the right place

i18n/fr/docusaurus-plugin-content-docs/version-23.10/releases/centreon-os.mdx, versioned_docs/version-23.10/releases/centreon-os.mdx
Update RN 23.10 (dashboards section)
=> Update RN 23.10 (dashboards section)

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/releases/release-notes.md, pp/integrations/plugin-packs/releases/release-notes.md
=> enh(rn): 23.11 release notes

i18n/fr/docusaurus-plugin-content-docs/version-23.04/integrations/data-analytics/sc-splunk-metrics.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/integrations/data-analytics/sc-splunk-metrics.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/integrations/data-analytics/sc-splunk-metrics.md, versioned_docs/version-23.10/integrations/data-analytics/sc-splunk-metrics.md, versioned_docs/version-24.04/integrations/data-analytics/sc-splunk-metrics.md
=> Splunk metrics 23.10, 24.04

i18n/fr/docusaurus-plugin-content-docs/version-23.10/releases/centreon-os.mdx, versioned_docs/version-23.10/releases/centreon-os.mdx
=> doc(release): prepare release notes for OSS 23.10

i18n/fr/docusaurus-plugin-content-docs/version-21.10/releases/centreon-core.md, versioned_docs/version-21.10/releases/centreon-core.md
=> doc(release): prepare release notes for OSS 21.10

.github/CODEOWNERS
=> enh(chore): new code_owners (#2826)

.github/CODEOWNERS
=> enh(chore): backend code owners

i18n/fr/docusaurus-plugin-content-docs/version-23.10/integrations/data-analytics/sc-elasticsearch-metrics.md, versioned_docs/version-23.10/integrations/data-analytics/sc-elasticsearch-metrics.md
=> Elasticmetrics

i18n/fr/docusaurus-plugin-content-docs/version-23.10/integrations/itsm/ot-easyvista-rest-api.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/integrations/itsm/ot-easyvista.md, versioned_docs/version-23.10/integrations/itsm/ot-easyvista-rest-api.md, versioned_docs/version-23.10/integrations/itsm/ot-easyvista.md, versioned_sidebars/version-23.10-sidebars.json
Document EasyVista RestAPI stream connector
=> Document EasyVista RestAPI stream connector

versioned_docs/version-22.10/administration/logging-configuration-changes.md, versioned_docs/version-22.10/monitoring/basic-objects/hosts-switch-poller.md, versioned_docs/version-22.10/monitoring/generic-actions.md, versioned_docs/version-22.10/releases/centreon-os.md
=> Mass change 22.10

i18n/fr/docusaurus-plugin-content-docs/version-22.04/graph-views/import-into-map-web.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/graph-views/import-into-map-web.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/graph-views/import-into-map-web.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/graph-views/import-into-map-web.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/graph-views/import-into-map-web.md, versioned_docs/version-22.04/graph-views/import-into-map-web.md, versioned_docs/version-22.10/graph-views/import-into-map-web.md, versioned_docs/version-23.04/graph-views/import-into-map-web.md, versioned_docs/version-23.10/graph-views/import-into-map-web.md, versioned_docs/version-24.04/graph-views/import-into-map-web.md, versioned_docs/version-24.04/graph-views/map-web-manage.md
Update MAP images migration process
=> Update MAP images migration process

i18n/fr/docusaurus-plugin-content-docs/version-23.04/graph-views/map-web-create-standard-map.md, versioned_docs/version-23.04/graph-views/map-web-create-standard-map.md
MAP Add resources in bulk mode - 23.04
=> MAP Add resources in bulk mode - 23.04

i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-commercial-extensions.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-commercial-extensions.mdx, versioned_docs/version-22.10/releases/centreon-commercial-extensions.md, versioned_docs/version-23.04/releases/centreon-commercial-extensions.mdx
Update MAP RNs 22.10 and 23.04 (Bulk ticket is missing)
=> Update MAP RNs 22.10 and 23.04 (Bulk ticket is missing)

i18n/fr/docusaurus-plugin-content-docs/version-22.04/graph-views/import-into-map-web.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/graph-views/import-into-map-web.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/graph-views/import-into-map-web.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/graph-views/import-into-map-web.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/graph-views/import-into-map-web.md, versioned_docs/version-22.04/graph-views/import-into-map-web.md, versioned_docs/version-22.10/graph-views/import-into-map-web.md, versioned_docs/version-23.04/graph-views/import-into-map-web.md, versioned_docs/version-24.04/graph-views/import-into-map-web.md
Update MAP image process for all versions
=> Update MAP image process for all versions

.github/CODEOWNERS
=> enh(chore): JS owners feedback

docusaurus.config.js
add automatically unmaintained banner for archived version
=> enh(ci): add automatically unmaintained banner for archived version

cloud/alerts-notifications/resources-status.md, i18n/fr/docusaurus-plugin-content-docs-cloud/current/alerts-notifications/resources-status.md
=> [Cloud] Remove notifications tab

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-pdu-cyberpower-snmp.md, pp/integrations/plugin-packs/procedures/hardware-pdu-cyberpower-snmp.md
=> enh(mc): hardware-pdu-cyberpower-snmp

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-adva-fsp3000-snmp.md, pp/integrations/plugin-packs/procedures/network-adva-fsp3000-snmp.md
=> enh(mc): refresh network-adva-fsp3000-snmp procedure

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-avid-isis-snmp.md, pp/integrations/plugin-packs/procedures/hardware-storage-avid-isis-snmp.md
=> enh(mc): hardware-storage-avid-isis-snmp

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-stormshield-api.md, pp/integrations/plugin-packs/procedures/network-stormshield-api.md
=> CTOR-176-network-stormshield-api

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-synology-snmp.md, pp/integrations/plugin-packs/procedures/hardware-storage-synology-snmp.md
Another MC PR for the next release
=> enh(mc): refresh hardware-storage-synology-snmp

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-monitoring-centreon-database.md, pp/integrations/plugin-packs/procedures/applications-monitoring-centreon-database.md
=> enh(mc): update applications-monitoring-centreon-database

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-monitoring-centreon-central.md, pp/integrations/plugin-packs/procedures/applications-monitoring-centreon-central.md
EDIT by @omercier:
REFS: CTOR-149
=> Refrech the centreon central doc

cloud/monitoring/anomaly-detection.md, i18n/fr/docusaurus-plugin-content-docs-cloud/current/alerts-notifications/notif-configuration.md, i18n/fr/docusaurus-plugin-content-docs-cloud/current/monitoring/anomaly-detection.md
=> Typos and wording

.github/PULL_REQUEST_TEMPLATE.md
=> Remove 21.10 from PR template

i18n/fr/docusaurus-plugin-content-docs/version-23.10/releases/centreon-os.mdx, versioned_docs/version-23.10/releases/centreon-os.mdx
=> doc(release): prepare release notes for collect 23.10

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/releases/release-notes.md, pp/integrations/plugin-packs/releases/release-notes.md
=> Release note for MC Release 23.12

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/operatingsystems-linux-snmp.md, pp/integrations/plugin-packs/procedures/operatingsystems-linux-snmp.md
=> fix(docusaurus): build must pass

i18n/fr/docusaurus-plugin-content-docs/version-23.04/administration/backup-poller.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/administration/backup-poller.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/administration/backup-poller.md, versioned_docs/version-23.04/administration/backup-poller.md, versioned_docs/version-23.10/administration/backup-poller.md, versioned_docs/version-24.04/administration/backup-poller.md
=> Add info for backing up the poller

i18n/fr/docusaurus-plugin-content-docs/version-22.04/administration/secure-platform.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/administration/secure-platform.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/administration/secure-platform.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/administration/secure-platform.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/administration/secure-platform.md
=> Fix incorrect file path

.github/CODEOWNERS, .github/dependabot.yml, .github/workflows/actionlint.yml
=> ench(chore): code owners feedbacks

versioned_docs/version-22.04/installation/installation-of-a-poller/unattended.md, versioned_docs/version-22.10/installation/installation-of-a-poller/unattended.md, versioned_docs/version-23.04/installation/installation-of-a-poller/unattended.md, versioned_docs/version-23.10/installation/installation-of-a-poller/unattended.md, versioned_docs/version-24.04/installation/installation-of-a-poller/unattended.md
=> Fix Alma8 command for unattended installation

cloud/administration/media.md, cloud/sidebarsCloud.js, i18n/fr/docusaurus-plugin-content-docs-cloud/current.json, i18n/fr/docusaurus-plugin-content-docs-cloud/current/administration/media.md
Document how to add images - Cloud
=> Document how to add images - Cloud

cloud/installation/poller-secure.md, cloud/installation/prerequisites.md, cloud/sidebarsCloud.js, i18n/fr/docusaurus-plugin-content-docs-cloud/current/installation/poller-secure.md, i18n/fr/docusaurus-plugin-content-docs-cloud/current/installation/prerequisites.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/administration/secure-platform.md
=> Securing a poller (Cloud)

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/releases/release-notes.md, pp/integrations/plugin-packs/releases/release-notes.md
=> enh(rn): MCR 24.01 release notes

i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md, versioned_docs/version-22.10/releases/centreon-os.md
added in collect 22.10.7 :
[Broker] Fixed a bug occurring when a Business Activity was updated after a status change for a KPI with a BA type.
=> doc(release): Prepare release notes for collect 22.10.7

i18n/fr/docusaurus-plugin-content-docs/version-22.04/installation/installation-of-centreon-ha/installation-2-nodes.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/installation/installation-of-centreon-ha/installation-2-nodes.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/installation/installation-of-centreon-ha/installation-2-nodes.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/installation/installation-of-centreon-ha/installation-2-nodes.md, versioned_docs/version-22.04/installation/installation-of-centreon-ha/installation-2-nodes.md, versioned_docs/version-22.10/installation/installation-of-centreon-ha/installation-2-nodes.md, versioned_docs/version-23.04/installation/installation-of-centreon-ha/installation-2-nodes.md
=> Fix typos in HA disclaimer

i18n/fr/docusaurus-plugin-content-docs/version-23.04/upgrade/upgrade-from-22-04.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/upgrade/upgrade-from-22-10.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/upgrade/upgrade-from-22-04.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/upgrade/upgrade-from-22-10.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/upgrade/upgrade-from-22-04.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/upgrade/upgrade-from-22-10.md, versioned_docs/version-23.04/upgrade/upgrade-from-22-04.md, versioned_docs/version-23.04/upgrade/upgrade-from-22-10.md, versioned_docs/version-23.10/upgrade/upgrade-from-22-04.md, versioned_docs/version-23.10/upgrade/upgrade-from-22-10.md, versioned_docs/version-24.04/upgrade/upgrade-from-22-04.md, versioned_docs/version-24.04/upgrade/upgrade-from-22-10.md
=> Change repo address in upgrade procedures

i18n/fr/docusaurus-plugin-content-docs/version-22.04/api/rest-api-v2.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/api/rest-api-v2.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/api/rest-api-v2.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/api/rest-api-v2.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/api/rest-api-v2.md, versioned_docs/version-22.04/api/rest-api-v2.md, versioned_docs/version-22.10/api/rest-api-v2.md, versioned_docs/version-23.04/api/rest-api-v2.md, versioned_docs/version-23.10/api/rest-api-v2.md, versioned_docs/version-24.04/api/rest-api-v2.md, versioned_sidebars/version-22.04-sidebars.json, versioned_sidebars/version-22.10-sidebars.json, versioned_sidebars/version-23.04-sidebars.json, versioned_sidebars/version-23.10-sidebars.json, versioned_sidebars/version-24.04-sidebars.json
=> Make API doc easier to find

i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-commercial-extensions.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-commercial-extensions.mdx, i18n/fr/docusaurus-plugin-content-docs/version-23.10/releases/centreon-commercial-extensions.mdx, versioned_docs/version-22.10/releases/centreon-commercial-extensions.md, versioned_docs/version-23.04/releases/centreon-commercial-extensions.mdx, versioned_docs/version-23.10/releases/centreon-commercial-extensions.mdx
- [UI] You can now freely resize basic geometric shapes.
=> Add info to Release Note

i18n/fr/docusaurus-plugin-content-docs/version-23.04/administration/custom-login.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/administration/custom-login.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/administration/custom-login.md, versioned_docs/version-23.04/administration/custom-login.md, versioned_docs/version-23.10/administration/custom-login.md, versioned_docs/version-24.04/administration/custom-login.md
Add Debian update command for CIEE
=> Add Debian update command for CIEE

i18n/fr/docusaurus-plugin-content-docs/version-23.10/releases/centreon-os.mdx, versioned_docs/version-23.10/releases/centreon-os.mdx
added missing RN: 
- [API] Fixed an issue where service queries didn't return all the results.
=> doc(release): Prepare release notes for web 23.10.2

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-switchs-aruba-standard-snmp.md, pp/integrations/plugin-packs/procedures/network-switchs-aruba-standard-snmp.md
=> enh(mc): Great Reboot - network-switchs-aruba-standard-snmp

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/virtualization-vmware2-esx.md, i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/virtualization-vmware2-vcenter-6.md, i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/virtualization-vmware2-vcenter-generic.md, i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/virtualization-vmware2-vm.md, pp/integrations/plugin-packs/procedures/virtualization-vmware2-esx.md, pp/integrations/plugin-packs/procedures/virtualization-vmware2-vcenter-6.md, pp/integrations/plugin-packs/procedures/virtualization-vmware2-vcenter-generic.md, pp/integrations/plugin-packs/procedures/virtualization-vmware2-vm.md
Added the compatibililty information for vmware 6 & 7
=> enh(mc): added the compatibililty information for vmware 6 & 7

.github/workflows/archive.yml, .github/workflows/documentation.yml
=> chore(ci): update gha dependencies

cloud/installation/poller-secure.md, i18n/fr/docusaurus-plugin-content-docs-cloud/current/installation/poller-secure.md, i18n/fr/docusaurus-plugin-content-docs/version-22.04/administration/secure-platform.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/administration/secure-platform.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/administration/secure-platform.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/administration/secure-platform.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/administration/secure-platform.md, versioned_docs/version-22.04/administration/secure-platform.md, versioned_docs/version-22.10/administration/secure-platform.md, versioned_docs/version-23.04/administration/secure-platform.md, versioned_docs/version-23.10/administration/secure-platform.md, versioned_docs/version-24.04/administration/secure-platform.md
=> Gorgone whitelists

i18n/fr/docusaurus-plugin-content-docs/version-22.04/resources/known-issues.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/resources/known-issues.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/resources/known-issues.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/resources/known-issues.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/resources/known-issues.md, versioned_docs/version-22.04/resources/known-issues.md, versioned_docs/version-22.10/resources/known-issues.md, versioned_docs/version-23.04/resources/known-issues.md, versioned_docs/version-23.10/resources/known-issues.md, versioned_docs/version-24.04/resources/known-issues.md
Add autologin known issue for MAP
=> Add autologin known issue for MAP

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-monitoring-centreon-central.md, pp/integrations/plugin-packs/procedures/applications-monitoring-centreon-central.md
=> Remove obsolete paragraph

i18n/fr/docusaurus-plugin-content-docs/version-23.04/installation/architectures.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/migrate/introduction.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/migrate/migrate-from-3-4.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/migrate/migrate-from-el-to-debian.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/migrate/migrate-from-el-to-el.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/installation/architectures.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/migrate/introduction.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/migrate/migrate-from-3-4.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/migrate/migrate-from-el-to-debian.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/migrate/migrate-from-el-to-el.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/installation/architectures.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/migrate/introduction.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/migrate/migrate-from-3-4.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/migrate/migrate-from-el-to-debian.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/migrate/migrate-from-el-to-el.md, versioned_docs/version-23.04/installation/architectures.md, versioned_docs/version-23.04/migrate/introduction.md, versioned_docs/version-23.04/migrate/migrate-from-3-4.md, versioned_docs/version-23.04/migrate/migrate-from-el-to-debian.md, versioned_docs/version-23.04/migrate/migrate-from-el-to-el.md, versioned_docs/version-23.10/installation/architectures.md, versioned_docs/version-23.10/migrate/introduction.md, versioned_docs/version-23.10/migrate/migrate-from-3-4.md, versioned_docs/version-23.10/migrate/migrate-from-el-to-debian.md, versioned_docs/version-23.10/migrate/migrate-from-el-to-el.md, versioned_docs/version-24.04/installation/architectures.md, versioned_docs/version-24.04/migrate/introduction.md, versioned_docs/version-24.04/migrate/migrate-from-3-4.md, versioned_docs/version-24.04/migrate/migrate-from-el-to-debian.md, versioned_docs/version-24.04/migrate/migrate-from-el-to-el.md
=> Improve migration procedure

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-ups-inmatics-sputnik-snmp.md, pp/integrations/plugin-packs/procedures/hardware-ups-inmatics-sputnik-snmp.md, pp/sidebarsPp.js
=> add(mc): new inmatics sputnik monitoring connector

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-compute-aks.md, pp/integrations/plugin-packs/procedures/cloud-azure-compute-aks.md
=> enh(mc): update Azure AKS pack

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-monitoring-centreon-map-engine-actuator.md, pp/integrations/plugin-packs/procedures/applications-monitoring-centreon-map-engine-actuator.md, pp/sidebarsPp.js
=> Ctor 8 new map mc

en/integrations/event-management/sc-hp-omi.md, fr/integrations/event-management/sc-hp-omi.md, fr/integrations/event-management/sc-omi.md
This is the documentation of the HP OMi events stream connector, which applies the refactor in apiv2
=> Enh(doc) enhancement documentation of HP OMi to apiv2

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/releases/release-notes.md, pp/integrations/plugin-packs/releases/release-notes.md
=> release(mc): add new release notes

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-monitoring-centreon-map-engine-actuator.md, i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-compute-aks.md, i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-ups-inmatics-sputnik-snmp.md, i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/releases/release-notes.md, pp/integrations/plugin-packs/procedures/applications-monitoring-centreon-map-engine-actuator.md, pp/integrations/plugin-packs/procedures/cloud-azure-compute-aks.md, pp/integrations/plugin-packs/procedures/hardware-ups-inmatics-sputnik-snmp.md, pp/integrations/plugin-packs/releases/release-notes.md, pp/sidebarsPp.js
=> Release connectors 24.02

i18n/fr/docusaurus-plugin-content-docs/version-23.10/releases/centreon-commercial-extensions.mdx, versioned_docs/version-23.10/releases/centreon-commercial-extensions.mdx
BAM 23.10.5
Anomaly D 23.10.1
map: 23.10.7
=> doc(release) prepare release notes for modules 23.10

i18n/fr/docusaurus-plugin-content-docs/version-23.10/releases/centreon-os.mdx, versioned_docs/version-23.10/releases/centreon-os.mdx
Update RN Web 23.10.8 as some tickets were missing
=> Update RN Web 23.10.8 as some tickets were missing

i18n/fr/docusaurus-plugin-content-docs/version-23.10/alerts-notifications/dashboards.md, versioned_docs/version-23.10/alerts-notifications/dashboards.md
Dashboards - add the list of available widgets
=> Dashboards - add the list of available widgets

cloud/alerts-notifications/dashboards.md, i18n/fr/docusaurus-plugin-content-docs-cloud/current/alerts-notifications/dashboards.md
Dashboards - add the list of available widgets - Cloud
=> Dashboards - add the list of available widgets - Cloud

i18n/fr/docusaurus-plugin-content-docs/version-23.10/alerts-notifications/dashboards.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/alerts-notifications/dashboards.md, versioned_docs/version-23.10/alerts-notifications/dashboards.md, versioned_docs/version-24.04/alerts-notifications/dashboards.md
Dashboards - Add link to RS page
+ List of widgets (missing in 24.04)
=> Dashboards - Add link to RS page

cloud/alerts-notifications/dashboards.md, i18n/fr/docusaurus-plugin-content-docs-cloud/current/alerts-notifications/dashboards.md
Dashboards - Add link to RS page
=> Dashboards - Add link to RS page - Cloud

i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx, i18n/fr/docusaurus-plugin-content-docs/version-23.10/releases/centreon-os.mdx, versioned_docs/version-22.04/releases/centreon-core.md, versioned_docs/version-22.10/releases/centreon-os.md, versioned_docs/version-23.04/releases/centreon-os.mdx, versioned_docs/version-23.10/releases/centreon-os.mdx
Add missing CVE numbers in release notes
=> Add missing CVE numbers in release notes

i18n/fr/docusaurus-plugin-content-docs/version-22.04/releases/centreon-core.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx, i18n/fr/docusaurus-plugin-content-docs/version-23.10/releases/centreon-os.mdx, versioned_docs/version-22.04/releases/centreon-core.md, versioned_docs/version-22.10/releases/centreon-os.md, versioned_docs/version-23.04/releases/centreon-os.mdx, versioned_docs/version-23.10/releases/centreon-os.mdx
=> Update Gorgone rn

cloud/releases/cloud-release-notes.md, i18n/fr/docusaurus-plugin-content-docs-cloud/current/releases/cloud-release-notes.md
=> doc(release): Prepare release notes for cloud release January 24.04

cloud/monitoring/basic-objects/hosts-create.md, cloud/monitoring/basic-objects/hosts-templates.md, cloud/monitoring/basic-objects/hosts.md, cloud/monitoring/basic-objects/services-create.md, cloud/monitoring/basic-objects/services-templates.md, cloud/monitoring/basic-objects/services.md, i18n/fr/docusaurus-plugin-content-docs-cloud/current/monitoring/basic-objects/hosts-create.md, i18n/fr/docusaurus-plugin-content-docs-cloud/current/monitoring/basic-objects/hosts.md, i18n/fr/docusaurus-plugin-content-docs-cloud/current/monitoring/basic-objects/services-create.md, i18n/fr/docusaurus-plugin-content-docs-cloud/current/monitoring/basic-objects/services-templates.md, i18n/fr/docusaurus-plugin-content-docs-cloud/current/monitoring/basic-objects/services.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/monitoring/basic-objects/hosts.md
Update configuration forms (H, HTPL, S, STPL) - Cloud
=> Update configuration forms (H, HTPL, S, STPL) - Cloud

cloud/administration/media.md, cloud/sidebarsCloud.js, i18n/fr/docusaurus-plugin-content-docs-cloud/current/administration/media.md
Add media topic - cloud 24.04 (push 1)
=> Add media topic - cloud 24.04 (push 1)

i18n/fr/docusaurus-plugin-content-docs/version-23.04/upgrade/upgrade-from-22-10.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/upgrade/upgrade-from-22-10.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/upgrade/upgrade-from-23-04.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/upgrade/upgrade-from-22-10.md, versioned_docs/version-23.04/upgrade/upgrade-from-22-10.md, versioned_docs/version-23.10/upgrade/upgrade-from-22-10.md, versioned_docs/version-23.10/upgrade/upgrade-from-23-04.md, versioned_docs/version-24.04/upgrade/upgrade-from-22-10.md
=> Fix Debian upgrade procedure

cloud/monitoring/basic-objects/hosts.md, cloud/monitoring/basic-objects/timeperiods.md, cloud/service-mapping/ba-management.md, cloud/sidebarsCloud.js, i18n/fr/docusaurus-plugin-content-docs-cloud/current/monitoring/basic-objects/hosts.md, i18n/fr/docusaurus-plugin-content-docs-cloud/current/monitoring/basic-objects/timeperiods.md, i18n/fr/docusaurus-plugin-content-docs-cloud/current/service-mapping/ba-management.md
=> Add time periods to Cloud doc

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-ups-socomec-netvision-snmp.md, pp/integrations/plugin-packs/procedures/hardware-ups-socomec-netvision-snmp.md
=> enh(mc): refresh the procedure for Socomec Net Vision

.github/workflows/archive.yml, .github/workflows/documentation.yml
=> chore(ci): upgrade gha

cloud/installation/poller-secure.md, i18n/fr/docusaurus-plugin-content-docs-cloud/current/installation/poller-secure.md, i18n/fr/docusaurus-plugin-content-docs/version-22.04/administration/secure-platform.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/administration/secure-platform.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/administration/secure-platform.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/administration/secure-platform.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/administration/secure-platform.md, versioned_docs/version-22.04/administration/secure-platform.md, versioned_docs/version-22.10/administration/secure-platform.md, versioned_docs/version-23.04/administration/secure-platform.md, versioned_docs/version-23.10/administration/secure-platform.md, versioned_docs/version-24.04/administration/secure-platform.md
=> Update Gorgone whitelists (2)

i18n/fr/docusaurus-plugin-content-docs/version-24.04/upgrade/upgrade-from-23-04.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/upgrade/upgrade-from-23-10.md, versioned_docs/version-24.04/upgrade/upgrade-from-23-04.md, versioned_docs/version-24.04/upgrade/upgrade-from-23-10.md, versioned_sidebars/version-24.04-sidebars.json
=> Add upgrade pages for 24.04

i18n/fr/docusaurus-plugin-content-docs/version-22.04/installation/installation-of-centreon-ha/installation-4-nodes.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/installation/installation-of-centreon-ha/installation-4-nodes.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/installation/installation-of-centreon-ha/installation-4-nodes.md, versioned_docs/version-22.04/installation/installation-of-centreon-ha/installation-4-nodes.md, versioned_docs/version-22.10/installation/installation-of-centreon-ha/installation-4-nodes.md, versioned_docs/version-23.04/installation/installation-of-centreon-ha/installation-4-nodes.md
=> Incorrect command fo Debian (HA 4-node install)

versioned_docs/version-23.04/installation/installation-of-centreon-ha/installation-4-nodes.md
=> Broken code block: add missing blank line within tab

versioned_docs/version-23.04/installation/installation-of-centreon-ha/installation-4-nodes.md
=> Fix broken code block

i18n/fr/docusaurus-plugin-content-docs/version-23.04/installation/installation-of-centreon-ha-manual/installation-2-nodes.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/installation/installation-of-centreon-ha-manual/installation-4-nodes.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/installation/installation-of-centreon-ha/installation-2-nodes.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/installation/installation-of-centreon-ha/installation-4-nodes.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/installation/installation-of-centreon-ha-manual/installation-2-nodes.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/installation/installation-of-centreon-ha-manual/installation-4-nodes.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/installation/installation-of-centreon-ha/installation-2-nodes.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/installation/installation-of-centreon-ha/installation-4-nodes.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/installation/installation-of-centreon-ha-manual/installation-2-nodes.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/installation/installation-of-centreon-ha-manual/installation-4-nodes.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/installation/installation-of-centreon-ha/installation-2-nodes.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/installation/installation-of-centreon-ha/installation-4-nodes.md, versioned_docs/version-23.04/installation/installation-of-centreon-ha-manual/installation-2-nodes.md, versioned_docs/version-23.04/installation/installation-of-centreon-ha-manual/installation-4-nodes.md, versioned_docs/version-23.04/installation/installation-of-centreon-ha/installation-2-nodes.md, versioned_docs/version-23.04/installation/installation-of-centreon-ha/installation-4-nodes.md, versioned_docs/version-23.10/installation/installation-of-centreon-ha-manual/installation-2-nodes.md, versioned_docs/version-23.10/installation/installation-of-centreon-ha-manual/installation-4-nodes.md, versioned_docs/version-23.10/installation/installation-of-centreon-ha/installation-2-nodes.md, versioned_docs/version-23.10/installation/installation-of-centreon-ha/installation-4-nodes.md, versioned_docs/version-24.04/installation/installation-of-centreon-ha-manual/installation-2-nodes.md, versioned_docs/version-24.04/installation/installation-of-centreon-ha-manual/installation-4-nodes.md, versioned_docs/version-24.04/installation/installation-of-centreon-ha/installation-2-nodes.md, versioned_docs/version-24.04/installation/installation-of-centreon-ha/installation-4-nodes.md
=> [HA] Remove unnecessary parameters

src/theme/DocBreadcrumbs/index.js, versioned_docs/version-22.04/upgrade/upgrade-from-21-04.md, versioned_docs/version-22.04/upgrade/upgrade-from-21-10.md
Replace #3090 because it's not building.
=> Fix upgrade procedures (mariaDB repo)

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-monitoring-centreon-sql-metrics.md, pp/integrations/plugin-packs/procedures/applications-monitoring-centreon-sql-metrics.md
=> Refresh the centreon-sql-metrics documentation

i18n/fr/docusaurus-plugin-content-docs/version-22.04/graph-views/install.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/graph-views/install.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/graph-views/install.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/graph-views/install.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/graph-views/install.md, versioned_docs/version-22.04/graph-views/install.md, versioned_docs/version-22.04/upgrade/upgrade-from-21-04.md, versioned_docs/version-22.04/upgrade/upgrade-from-21-10.md, versioned_docs/version-22.10/graph-views/install.md, versioned_docs/version-23.04/graph-views/install.md, versioned_docs/version-23.10/graph-views/install.md, versioned_docs/version-24.04/graph-views/install.md
Update contact for MAP legacy high volumetry
=> Update contact for MAP legacy high volumetry

cloud/graph-views/map-web-create-geoview.md, i18n/fr/docusaurus-plugin-content-docs-cloud/current/graph-views/map-web-create-geoview.md, i18n/fr/docusaurus-plugin-content-docs/version-22.04/graph-views/map-web-create-geoview.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/graph-views/map-web-create-geoview.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/graph-views/map-web-create-geoview.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/graph-views/map-web-create-geoview.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/graph-views/map-web-create-geoview.md, versioned_docs/version-22.04/graph-views/map-web-create-geoview.md, versioned_docs/version-22.10/graph-views/map-web-create-geoview.md, versioned_docs/version-23.04/graph-views/map-web-create-geoview.md, versioned_docs/version-23.10/graph-views/map-web-create-geoview.md, versioned_docs/version-24.04/graph-views/map-web-create-geoview.md
=> Update Map Web geoview topic

i18n/fr/docusaurus-plugin-content-docs/version-22.04/update/update-centreon-ha.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/update/update-centreon-ha.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/update/update-centreon-ha.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/update/update-centreon-ha.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/update/update-centreon-ha.md, versioned_docs/version-22.04/update/update-centreon-ha.md, versioned_docs/version-22.10/update/update-centreon-ha.md, versioned_docs/version-23.04/update/update-centreon-ha.md, versioned_docs/version-23.10/update/update-centreon-ha.md, versioned_docs/version-24.04/update/update-centreon-ha.md
Fix technical and gramatical from last publication
=> Fix(doc) update doc update centreon ha.md

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/releases/release-notes.md, pp/integrations/plugin-packs/releases/release-notes.md
=> enh(rn): release notes for MCR 24.03

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-watchguard-snmp.md, pp/integrations/plugin-packs/procedures/network-watchguard-snmp.md
=> enh(mc): automatic commit for network-watchguard-snmp

i18n/fr/docusaurus-plugin-content-docs/version-22.04/graph-views/map-web-install.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/graph-views/map-web-install.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/graph-views/map-web-install.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/graph-views/map-web-install.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/graph-views/map-web-install.md, versioned_docs/version-22.04/graph-views/map-web-install.md, versioned_docs/version-22.10/graph-views/map-web-install.md, versioned_docs/version-23.04/graph-views/map-web-install.md, versioned_docs/version-23.10/graph-views/map-web-install.md, versioned_docs/version-24.04/graph-views/map-web-install.md
Update MAP install procedure by deactivating SELinux and firewall
=> Update MAP install procedure by deactivating SELinux and firewall

i18n/fr/docusaurus-plugin-content-docs/version-23.04/installation/installation-of-centreon-ha/installation-2-nodes.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/installation/installation-of-centreon-ha/installation-4-nodes.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/installation/installation-of-centreon-ha/installation-2-nodes.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/installation/installation-of-centreon-ha/installation-4-nodes.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/installation/installation-of-centreon-ha/installation-2-nodes.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/installation/installation-of-centreon-ha/installation-4-nodes.md, versioned_docs/version-23.04/installation/installation-of-centreon-ha/installation-2-nodes.md, versioned_docs/version-23.04/installation/installation-of-centreon-ha/installation-4-nodes.md, versioned_docs/version-23.10/installation/installation-of-centreon-ha/installation-2-nodes.md, versioned_docs/version-23.10/installation/installation-of-centreon-ha/installation-4-nodes.md, versioned_docs/version-24.04/installation/installation-of-centreon-ha/installation-2-nodes.md, versioned_docs/version-24.04/installation/installation-of-centreon-ha/installation-4-nodes.md
=> [HA] Make commands consistent

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-datacore-api.md, pp/integrations/plugin-packs/procedures/hardware-storage-datacore-api.md
REF:CTOR-423
fix Datacore pluginpack documentation
=> CTOR-423-datacore-documentation-various-fixes

i18n/fr/docusaurus-plugin-content-docs/version-23.04/installation/installation-of-centreon-ha/installation-2-nodes.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/installation/installation-of-centreon-ha/installation-4-nodes.md, versioned_docs/version-23.04/installation/installation-of-centreon-ha/installation-2-nodes.md, versioned_docs/version-23.04/installation/installation-of-centreon-ha/installation-4-nodes.md
=> Add message about EL9 (HA 23.04)

versioned_docs/version-22.04/releases/centreon-core.md
added version pour gorgone 22.04.6
=> doc(release): fix for RN OSS 22.04

i18n/fr/docusaurus-plugin-content-docs/version-24.04/installation/installation-of-centreon-ha/installation-2-nodes.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/installation/installation-of-centreon-ha/installation-4-nodes.md, versioned_docs/version-24.04/installation/installation-of-centreon-ha/installation-2-nodes.md, versioned_docs/version-24.04/installation/installation-of-centreon-ha/installation-4-nodes.md
=> Warning that Debian 12 is not yet supported for version 24.04

i18n/fr/docusaurus-plugin-content-docs/version-23.10/installation/installation-of-a-central-server/using-virtual-machines.md, versioned_docs/version-23.10/installation/installation-of-a-central-server/using-virtual-machines.md
=> Improve "install from VM" page

i18n/fr/docusaurus-plugin-content-docs/version-22.04/installation/installation-of-a-central-server/using-virtual-machines.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/installation/installation-of-a-central-server/using-virtual-machines.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/installation/installation-of-a-central-server/using-virtual-machines.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/installation/installation-of-a-central-server/using-virtual-machines.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/installation/installation-of-a-central-server/using-virtual-machines.md, versioned_docs/version-22.04/installation/installation-of-a-central-server/using-virtual-machines.md, versioned_docs/version-22.10/installation/installation-of-a-central-server/using-virtual-machines.md, versioned_docs/version-23.04/installation/installation-of-a-central-server/using-virtual-machines.md, versioned_docs/version-23.10/installation/installation-of-a-central-server/using-virtual-machines.md, versioned_docs/version-24.04/installation/installation-of-a-central-server/using-virtual-machines.md
Complements https://github.com/centreon/centreon-documentation/pull/3150.
=> Improve "install from VM" page (other versions)

cloud/alerts-notifications/dashboards.md, i18n/fr/docusaurus-plugin-content-docs-cloud/current/alerts-notifications/dashboards.md
Update list of widgets - cloud push 2
=> Update list of widgets - cloud push 2

cloud/alerts-notifications/dashboards.md, i18n/fr/docusaurus-plugin-content-docs-cloud/current/alerts-notifications/dashboards.md
Remove temporary "update list of widgets"
=> Remove temporary "update list of widgets"

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-ruckus-snmp.md, pp/integrations/plugin-packs/procedures/network-ruckus-snmp.md
=> enh(mc): automatic commit for network-ruckus-snmp

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-ubiquiti-unifi-snmp.md, pp/integrations/plugin-packs/procedures/network-ubiquiti-unifi-snmp.md
=> enh(mc): automatic commit for network-ubiquiti-unifi-snmp

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-switchs-juniper-ex-snmp.md, pp/integrations/plugin-packs/procedures/network-switchs-juniper-ex-snmp.md
=> enh(mc): automatic commit for network-switchs-juniper-ex-snmp

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-firewalls-sonicwall-snmp.md, pp/integrations/plugin-packs/procedures/network-firewalls-sonicwall-snmp.md
=> enh(mc): automatic commit for network-firewalls-sonicwall-snmp

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-3com-snmp.md, pp/integrations/plugin-packs/procedures/network-3com-snmp.md
=> enh(mc): automatic commit for network-3com-snmp

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-hp-vc-snmp.md, pp/integrations/plugin-packs/procedures/network-hp-vc-snmp.md
=> enh(mc): automatic commit for network-hp-vc-snmp

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-routers-juniper-mseries-snmp.md, pp/integrations/plugin-packs/procedures/network-routers-juniper-mseries-snmp.md
=> enh(mc): automatic commit for network-routers-juniper-mseries-snmp

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-fortinet-fortiweb-snmp.md, pp/integrations/plugin-packs/procedures/network-fortinet-fortiweb-snmp.md
=> enh(mc): automatic commit for network-fortinet-fortiweb-snmp

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-dlink-standard-snmp.md, pp/integrations/plugin-packs/procedures/network-dlink-standard-snmp.md
=> enh(mc): automatic commit for network-dlink-standard-snmp

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-fortinet-fortiswitch-snmp.md, pp/integrations/plugin-packs/procedures/network-fortinet-fortiswitch-snmp.md
=> enh(mc): automatic commit for network-fortinet-fortiswitch-snmp

i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx, versioned_docs/version-23.04/releases/centreon-os.mdx
#REF MON-38180
Add release notes for
* COLLECT 23.04.10
=> doc(release): add release notes for collect 23.04.10

i18n/fr/docusaurus-plugin-content-docs/version-23.10/releases/centreon-os.mdx, versioned_docs/version-23.10/releases/centreon-os.mdx
#REF MON-38178
Add release notes for
* COLLECT 23.10.5
=> doc(release): add release notes for collect 23.10.5

i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx, versioned_docs/version-23.04/releases/centreon-os.mdx
=> doc(release): Fix collect 23.04.10 release notes.

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-digi-anywhereusb-snmp.md, pp/integrations/plugin-packs/procedures/network-digi-anywhereusb-snmp.md
=> enh(mc): automatic commit for network-digi-anywhereusb-snmp

versioned_docs/version-23.10/integrations/data-analytics/sc-elastic-events.md
=> Refresh Elastic Events page

i18n/fr/docusaurus-plugin-content-docs/version-23.10/integrations/data-analytics/sc-logstash-events.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/integrations/data-analytics/sc-splunk-metrics.md, versioned_docs/version-23.10/integrations/data-analytics/sc-logstash-events.md
=> Refresh Logstash stream connector doc

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/releases/release-notes.md, pp/integrations/plugin-packs/releases/release-notes.md
=> fix(rn): an item was missing from february release notes

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-openldap-ldap.md, pp/integrations/plugin-packs/procedures/applications-openldap-ldap.md
=> enh(mc): automatic commit - Open LDAP

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-cisco-ssms-restapi.md, pp/integrations/plugin-packs/procedures/applications-cisco-ssms-restapi.md
=> enh(mc): automatic commit - Cisco SSMS REST API

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-cisco-wap-snmp.md, pp/integrations/plugin-packs/procedures/network-cisco-wap-snmp.md
=> enh(mc): automatic commit for network-cisco-wap-snmp

i18n/fr/docusaurus-plugin-content-docs/version-23.10/integrations/data-analytics/sc-elastic-events.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/integrations/data-analytics/sc-elasticsearch-metrics.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/integrations/data-analytics/sc-elastic-events.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/integrations/data-analytics/sc-elasticsearch-metrics.md, versioned_docs/version-24.04/integrations/data-analytics/sc-elastic-events.md, versioned_docs/version-24.04/integrations/data-analytics/sc-elasticsearch-metrics.md
=> Refresh Elasticsearch events - FR + 24.04

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-ups-cyberpower-snmp.md, pp/integrations/plugin-packs/procedures/hardware-ups-cyberpower-snmp.md, pp/sidebarsPp.js
=> Refresh the hardware-ups-cyberpower-snmp doc

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-pdu-eaton-snmp.md, pp/integrations/plugin-packs/procedures/hardware-pdu-eaton-snmp.md
=> Refresh the Eaton PDU SNMP documentation

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-database-postgresql.md, pp/integrations/plugin-packs/procedures/cloud-azure-database-postgresql.md, pp/sidebarsPp.js
=> add(mc): new cloud-azure-database-postgresql MC

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-pdu-apc-snmp.md, pp/integrations/plugin-packs/procedures/hardware-pdu-apc-snmp.md
=> Refresh the APC PDU doc

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-ups-powerware-snmp.md, pp/integrations/plugin-packs/procedures/hardware-ups-powerware-snmp.md
=> Refresh the ups-powerware-snmp doc

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-sensors-netbotz-snmp.md, pp/integrations/plugin-packs/procedures/hardware-sensors-netbotz-snmp.md
=> Refresh the Netbotz Sensor documentation

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-sensors-hwgste-snmp.md, pp/integrations/plugin-packs/procedures/hardware-sensors-hwgste-snmp.md
=> Refresh the HWg-STE Sensor documentation

i18n/fr/docusaurus-plugin-content-docs/version-23.04/health/centreon-agent.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/health/centreon-agent.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/health/centreon-agent.md, versioned_docs/version-23.04/health/centreon-agent.md, versioned_docs/version-23.10/health/centreon-agent.md, versioned_docs/version-24.04/health/centreon-agent.md
=> Fix Helios procedure

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-hashicorp-vault-restapi.md, pp/integrations/plugin-packs/procedures/applications-hashicorp-vault-restapi.md
REF:CTOR-383
add new argument in plugin, updating doc format while at it.
=> update documentation of hashicorp plugin pack

i18n/fr/docusaurus-plugin-content-docs/version-22.04/monitoring/passive-monitoring/debug-snmp-traps-management.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/monitoring/passive-monitoring/debug-snmp-traps-management.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/monitoring/passive-monitoring/debug-snmp-traps-management.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/monitoring/passive-monitoring/debug-snmp-traps-management.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/monitoring/passive-monitoring/debug-snmp-traps-management.md
=> Fix typo in debug-snmp-traps-management.md

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/releases/release-notes.md, pp/integrations/plugin-packs/releases/release-notes.md
=> enh(rn): MCR 24.04

cloud/alerts-notifications/dashboards.md, i18n/fr/docusaurus-plugin-content-docs-cloud/current/alerts-notifications/dashboards.md
Document Playlists feature - Cloud
=> Document Playlists feature - Cloud

cloud/users/users.md, i18n/fr/docusaurus-plugin-content-docs-cloud/current/users/users.md
Add fullscreen feature - Cloud
=> Add fullscreen feature - Cloud

i18n/fr/docusaurus-plugin-content-docs/version-22.04/security/key-rotation.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/security/key-rotation.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/security/key-rotation.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/security/key-rotation.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/security/key-rotation.md, versioned_docs/version-22.04/security/key-rotation.md, versioned_docs/version-22.10/security/key-rotation.md, versioned_docs/version-23.04/security/key-rotation.md, versioned_docs/version-23.10/security/key-rotation.md, versioned_docs/version-24.04/security/key-rotation.md
=> New Debian keys

i18n/fr/docusaurus-plugin-content-docs/version-23.10/releases/centreon-os.mdx, versioned_docs/version-23.10/releases/centreon-os.mdx
added: - [Update] Fixed chmod warning on configuration export after a system update.
=> doc(release): add release note for web 23.10.11

i18n/fr/docusaurus-plugin-content-docs/version-22.04/security/key-rotation.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/security/key-rotation.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/security/key-rotation.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/security/key-rotation.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/security/key-rotation.md, versioned_docs/version-22.04/security/key-rotation.md, versioned_docs/version-22.10/security/key-rotation.md, versioned_docs/version-23.04/security/key-rotation.md, versioned_docs/version-23.10/security/key-rotation.md, versioned_docs/version-24.04/security/key-rotation.md
=> Fix GPG key

i18n/fr/docusaurus-plugin-content-docs/version-24.04/alerts-notifications/dashboards.md, versioned_docs/version-24.04/alerts-notifications/dashboards.md
Dashboards - Update list of widgets On-prem 24.04
=> Dashboards - Update list of widgets On-prem 24.04

i18n/fr/docusaurus-plugin-content-docs/version-24.04/monitoring/basic-objects/contacts.md, versioned_docs/version-24.04/monitoring/basic-objects/contacts.md
Add fullscreen feature - 24.04 On-prem
=> Add fullscreen feature - 24.04 On-prem

i18n/fr/docusaurus-plugin-content-docs/version-24.04/alerts-notifications/dashboards.md, versioned_docs/version-24.04/alerts-notifications/dashboards.md
Document Playlists feature - On-prem 24.04
=> Document Playlists feature - On-prem 24.04

i18n/fr/docusaurus-plugin-content-docs/version-24.04/api/api-tokens.md, versioned_docs/version-24.04/api/api-tokens.md, versioned_sidebars/version-24.04-sidebars.json
Document API tokens on-prem 24.04
=> Document API tokens on-prem 24.04

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-ats-eaton-snmp.md, pp/integrations/plugin-packs/procedures/hardware-ats-eaton-snmp.md
=> [CTOR-492] Update Eaton ATS SNMP page

i18n/fr/docusaurus-plugin-content-docs/version-24.04/releases/centreon-commercial-extensions.mdx, versioned_docs/version-24.04/releases/centreon-commercial-extensions.mdx
map 
anomaly detection
bam
mbi
IT Edition Extensions
=> doc(release) Release notes for modules 24.04 on prem

i18n/fr/docusaurus-plugin-content-docs/version-22.04/installation/installation-of-a-central-server/using-packages.md, i18n/fr/docusaurus-plugin-content-docs/version-22.04/installation/installation-of-a-remote-server/using-packages.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/installation/installation-of-a-central-server/using-packages.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/installation/installation-of-a-remote-server/using-packages.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/installation/installation-of-a-central-server/using-packages.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/installation/installation-of-a-remote-server/using-packages.md, versioned_docs/version-22.04/installation/installation-of-a-central-server/using-packages.md, versioned_docs/version-22.04/installation/installation-of-a-remote-server/using-packages.md, versioned_docs/version-22.10/installation/installation-of-a-central-server/using-packages.md, versioned_docs/version-22.10/installation/installation-of-a-remote-server/using-packages.md, versioned_docs/version-23.04/installation/installation-of-a-central-server/using-packages.md, versioned_docs/version-23.04/installation/installation-of-a-remote-server/using-packages.md, versioned_docs/version-23.10/installation/installation-of-a-central-server/using-packages.md, versioned_docs/version-23.10/installation/installation-of-a-remote-server/using-packages.md
=> Change packages for pre-24.04 versions

i18n/fr/docusaurus-plugin-content-pages/index.js, src/pages/index.js
=> Update banner 24 04

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-pdu-emerson-snmp.md, pp/integrations/plugin-packs/procedures/hardware-pdu-emerson-snmp.md
=> [CTOR-494] Update Emerson PDU page

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-pdu-clever-snmp.md, pp/integrations/plugin-packs/procedures/hardware-pdu-clever-snmp.md
=> [CTOR-493] [Doc-SC] Update Clever PDU

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-ups-nitram-snmp.md, pp/integrations/plugin-packs/procedures/hardware-ups-nitram-snmp.md
=> [CTOR-502] Update Nitram UPS SNMP page

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-sensors-akcp-snmp.md, pp/integrations/plugin-packs/procedures/hardware-sensors-akcp-snmp.md
=> [CTOR-505] Update the AKCP Sensor doc page

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/base-generic.md, pp/integrations/plugin-packs/procedures/base-generic.md
=> Refresh the base-generic documentation

i18n/fr/docusaurus-plugin-content-docs/version-24.04/api/api-tokens.md, i18n/fr/docusaurus-plugin-content-docs/version-24.10/api/api-tokens.md, versioned_docs/version-24.04/api/api-tokens.md, versioned_docs/version-24.10/api/api-tokens.md
=> Improve wording (API tokens)

i18n/fr/docusaurus-plugin-content-docs/version-24.04/api/rest-api-v2.md, i18n/fr/docusaurus-plugin-content-docs/version-24.10/api/rest-api-v2.md, versioned_docs/version-24.04/api/rest-api-v2.md, versioned_docs/version-24.10/api/rest-api-v2.md
=> Fix link to API in Postman doc

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-ups-alpha-snmp.md, pp/integrations/plugin-packs/procedures/hardware-ups-alpha-snmp.md
=> [CTOR-498] [Doc-SC] Update  Alpha UPS SNMP documentation

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-servers-dell-idrac-snmp.md, pp/integrations/plugin-packs/procedures/hardware-servers-dell-idrac-snmp.md
=> refresh the Dell iDRAC documentation

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-pdu-gude-epc-snmp.md, pp/integrations/plugin-packs/procedures/hardware-pdu-gude-epc-snmp.md
=> [CTOR-495] Update Gude EPC SNMP

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-ups-hp-snmp.md, pp/integrations/plugin-packs/procedures/hardware-ups-hp-snmp.md
=> [CTOR-500] Update HP UPS SNMP page

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-ups-phoenixtec-snmp.md, pp/integrations/plugin-packs/procedures/hardware-ups-phoenixtec-snmp.md
=> [CTOR-503] Update Phoenixtec UPS SNMP doc page

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-ups-mge-snmp.md, pp/integrations/plugin-packs/procedures/hardware-ups-mge-snmp.md
=> [CTOR-501] Update MGE UPS System doc page

i18n/fr/docusaurus-plugin-content-docs/version-24.04/upgrade/upgrade-mariadb.md, i18n/fr/docusaurus-plugin-content-docs/version-24.10/upgrade/upgrade-mariadb.md, versioned_docs/version-24.04/upgrade/upgrade-mariadb.md, versioned_docs/version-24.10/upgrade/upgrade-mariadb.md
=> Fix link in MariaDB upgrade topic

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-sensors-sensorip-snmp.md, pp/integrations/plugin-packs/procedures/hardware-sensors-sensorip-snmp.md
=> [CTOR-510] Update the Sensor Ip doc page

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-prometheus-kubernetes-api.md, pp/integrations/plugin-packs/procedures/cloud-prometheus-kubernetes-api.md
=> [CTOR-554] Update the Prometheus kubernetes doc page

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-devices-abb-cms700-snmp.md, pp/integrations/plugin-packs/procedures/hardware-devices-abb-cms700-snmp.md
=> [CTOR-504] Update the ABB CMS-700 doc page

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-monitoring-quanta-restapi.md, pp/integrations/plugin-packs/procedures/applications-monitoring-quanta-restapi.md, pp/sidebarsPp.js
Initial release for this pack.
=> [CTOR-566][Doc] New pack Quanta Restapi

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-rrdcached.md, pp/integrations/plugin-packs/procedures/applications-rrdcached.md, pp/sidebarsPp.js
Initial pack release for this plugin already existing.
=> [CTOR-514] [Doc] New Pack RRDCached

i18n/fr/docusaurus-plugin-content-docs/version-22.04/graph-views/map-web-upgrade.md, i18n/fr/docusaurus-plugin-content-docs/version-22.04/graph-views/upgrade.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/graph-views/map-web-upgrade.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/graph-views/upgrade.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/graph-views/map-web-upgrade.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/graph-views/upgrade.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/graph-views/map-web-upgrade.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/graph-views/upgrade.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/graph-views/map-web-upgrade.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/graph-views/upgrade.md, versioned_docs/version-22.04/graph-views/map-web-upgrade.md, versioned_docs/version-22.04/graph-views/upgrade.md, versioned_docs/version-22.10/graph-views/map-web-upgrade.md, versioned_docs/version-22.10/graph-views/upgrade.md, versioned_docs/version-23.04/graph-views/map-web-upgrade.md, versioned_docs/version-23.04/graph-views/upgrade.md, versioned_docs/version-23.10/graph-views/map-web-upgrade.md, versioned_docs/version-23.10/graph-views/upgrade.md, versioned_docs/version-24.04/graph-views/map-web-upgrade.md, versioned_docs/version-24.04/graph-views/upgrade.md
=> Fix MariaDB 10.11 mentions

i18n/fr/docusaurus-plugin-content-docs/version-24.04/releases/centreon-os.mdx, versioned_docs/version-24.04/releases/centreon-os.mdx
=> doc(release): Release notes for hotfix web 24.04.1, dsm 24.04.1

i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md, versioned_docs/version-22.10/releases/centreon-os.md
…one 22.10.7)
web 22.10.22
gorgone 22.10.7
=> doc(release): Prepare release notes for web 22.10.22, gorgone 22.10.7

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/releases/release-notes.md, pp/integrations/plugin-packs/releases/release-notes.md
=> May release note for monitoring connectors

i18n/fr/docusaurus-plugin-content-docs/version-24.04/releases/centreon-os.mdx, versioned_docs/version-24.04/releases/centreon-os.mdx
=> doc(release): Prepare release notes for hotfix web 24.04.1, dsm 24.04.1

i18n/fr/docusaurus-plugin-content-docs/version-22.10/installation/installation-of-a-central-server/using-packages.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/installation/installation-of-a-poller/using-packages.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/installation/installation-of-a-remote-server/using-packages.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/installation/installation-of-a-central-server/using-packages.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/installation/installation-of-a-poller/using-packages.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/installation/installation-of-a-remote-server/using-packages.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/installation/installation-of-a-central-server/using-packages.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/installation/installation-of-a-poller/using-packages.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/installation/installation-of-a-remote-server/using-packages.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/installation/installation-of-a-central-server/using-packages.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/installation/installation-of-a-poller/using-packages.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/installation/installation-of-a-remote-server/using-packages.md, i18n/fr/docusaurus-plugin-content-docs/version-24.10/installation/installation-of-a-central-server/using-packages.md, i18n/fr/docusaurus-plugin-content-docs/version-24.10/installation/installation-of-a-poller/using-packages.md, i18n/fr/docusaurus-plugin-content-docs/version-24.10/installation/installation-of-a-remote-server/using-packages.md, versioned_docs/version-22.10/installation/installation-of-a-central-server/using-packages.md, versioned_docs/version-22.10/installation/installation-of-a-poller/using-packages.md, versioned_docs/version-22.10/installation/installation-of-a-remote-server/using-packages.md, versioned_docs/version-23.04/installation/installation-of-a-central-server/using-packages.md, versioned_docs/version-23.04/installation/installation-of-a-poller/using-packages.md, versioned_docs/version-23.04/installation/installation-of-a-remote-server/using-packages.md, versioned_docs/version-23.10/installation/installation-of-a-central-server/using-packages.md, versioned_docs/version-23.10/installation/installation-of-a-poller/using-packages.md, versioned_docs/version-23.10/installation/installation-of-a-remote-server/using-packages.md, versioned_docs/version-24.04/installation/installation-of-a-central-server/using-packages.md, versioned_docs/version-24.04/installation/installation-of-a-poller/using-packages.md, versioned_docs/version-24.04/installation/installation-of-a-remote-server/using-packages.md, versioned_docs/version-24.10/installation/installation-of-a-central-server/using-packages.md, versioned_docs/version-24.10/installation/installation-of-a-poller/using-packages.md, versioned_docs/version-24.10/installation/installation-of-a-remote-server/using-packages.md
=> Specify that rhui repo is only for cloud RHEL instances

i18n/fr/docusaurus-plugin-content-docs/version-24.04/upgrade/upgrade-from-23-04.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/upgrade/upgrade-from-23-10.md, i18n/fr/docusaurus-plugin-content-docs/version-24.10/upgrade/upgrade-from-23-04.md, i18n/fr/docusaurus-plugin-content-docs/version-24.10/upgrade/upgrade-from-23-10.md, versioned_docs/version-24.04/upgrade/upgrade-from-23-04.md, versioned_docs/version-24.04/upgrade/upgrade-from-23-10.md, versioned_docs/version-24.10/upgrade/upgrade-from-23-04.md, versioned_docs/version-24.10/upgrade/upgrade-from-23-10.md
=> Fix command to remove repo when upgrading

cloud/monitoring/basic-objects/commands.md, i18n/fr/docusaurus-plugin-content-docs-cloud/current/monitoring/basic-objects/commands.md
=> Update example for centengine whitelist

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-ups-himoinsa-snmp.md, pp/integrations/plugin-packs/procedures/hardware-ups-himoinsa-snmp.md
=> [CTOR-499] Update Himoinsa UPS page

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-sensors-jacarta-snmp.md, pp/integrations/plugin-packs/procedures/hardware-sensors-jacarta-snmp.md
=> [CTOR-509] Update Jacarta Sensor page

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-sensors-comet-p8000-snmp.md, pp/integrations/plugin-packs/procedures/hardware-sensors-comet-p8000-snmp.md
=> [CTOR-507] Update Geist p8000 sensor SNMP page

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-sensors-geist-snmp.md, pp/integrations/plugin-packs/procedures/hardware-sensors-geist-snmp.md
=> [CTOR-508] Update Geist Sensor SNMP doc page

pp/integrations/plugin-packs/dev-resources/develop-with-centreon-plugins.md
=> enh(plugins-dev): updated the repos to add to the dev platform

i18n/fr/docusaurus-plugin-content-docs/version-24.04/graph-views/map-web-install.md, i18n/fr/docusaurus-plugin-content-docs/version-24.10/graph-views/map-web-install.md, versioned_docs/version-24.04/graph-views/map-web-install.md, versioned_docs/version-24.10/graph-views/map-web-install.md
=> Add missing Debian12 MAP

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-sensors-sensormetrix-em01-web.md, pp/integrations/plugin-packs/procedures/hardware-sensors-sensormetrix-em01-web.md
=> [CTOR-511] Update Sensormetrix doc page

i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx, versioned_docs/version-23.04/releases/centreon-os.mdx
=> doc(release): Prepare release notes for collect 23.04.12

i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx, versioned_docs/version-23.04/releases/centreon-os.mdx
=> doc(release): Release notes for web 23.04.18 / gorgone 23.04.14

i18n/fr/docusaurus-plugin-content-docs/version-24.04/releases/centreon-os.mdx, versioned_docs/version-24.04/releases/centreon-os.mdx
=> doc(release): Release notes for collect 24.04.1

i18n/fr/docusaurus-plugin-content-docs/version-23.10/releases/centreon-os.mdx, versioned_docs/version-23.10/releases/centreon-os.mdx
=> doc(release): Release notes for collect 23.10.7

i18n/fr/docusaurus-plugin-content-docs/version-23.10/releases/centreon-os.mdx, versioned_docs/version-23.10/releases/centreon-os.mdx
=> doc(release): Release notes for web 23.10.12, gorgone 23.10.7

i18n/fr/docusaurus-plugin-content-docs/version-24.04/releases/centreon-os.mdx, versioned_docs/version-24.04/releases/centreon-os.mdx
=> doc(release): Release notes for web 24.04.2 / dsm 24.04.2

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-dynamics-ax-mssql.md, pp/integrations/plugin-packs/procedures/applications-dynamics-ax-mssql.md, pp/sidebarsPp.js
=> [CTOR-567] Create Dynamics AX Database doc page

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-databases-redis.md, pp/integrations/plugin-packs/procedures/applications-databases-redis.md
=> [CTOR-485] Update Redis Database page

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/operatingsystems-aix-snmp.md, pp/integrations/plugin-packs/procedures/operatingsystems-aix-snmp.md
- updated the procedure by generating it
- added a notice about the known AIX issue
=> enh(mc): refreshed the doc and added a notice about a known AIX bug

i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx, versioned_docs/version-23.04/releases/centreon-os.mdx
=> Fix 23.04 RN wording

cloud/installation/prerequisites.md, i18n/fr/docusaurus-plugin-content-docs-cloud/current/installation/prerequisites.md
=> [Cloud] Debian 12 supported for pollers

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-grafana-api.md, pp/integrations/plugin-packs/procedures/applications-grafana-api.md, pp/sidebarsPp.js
=> [CTOR-568] Create Grafana doc page

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-veeam-nrpe.md, pp/integrations/plugin-packs/procedures/applications-veeam-nrpe.md
=> [CTOR-610] Refresh Veeam doc page

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-dns.md, pp/integrations/plugin-packs/procedures/applications-protocol-dns.md
=> [CTOR-487] Update the DNS Service doc page

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-trendmicro-iwsva-snmp.md, pp/integrations/plugin-packs/procedures/applications-trendmicro-iwsva-snmp.md
Fix packaging and add discovery rule
=> enhance(documentation) CTOR-591 Trendmicro IWSVA packaging 

cloud/integrations/stream-connectors-cloud.md, cloud/sidebarsCloud.js, i18n/fr/docusaurus-plugin-content-docs-cloud/current/integrations/stream-connectors-cloud.md
=> [Cloud] Stream connectors

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-monitoring-loggly-restapi.md, pp/integrations/plugin-packs/procedures/applications-monitoring-loggly-restapi.md
Add time-periode default value
=> CTOR-586 - Loggly Restapi initial release - little fix

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-dell-compellent-api.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/graph-views/create-standard-view.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/graph-views/create-standard-view.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/graph-views/create-standard-view.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/graph-views/create-standard-view.md, i18n/fr/docusaurus-plugin-content-docs/version-24.10/graph-views/create-standard-view.md, pp/integrations/plugin-packs/procedures/hardware-storage-dell-compellent-api.md, versioned_docs/version-22.10/graph-views/create-standard-view.md, versioned_docs/version-23.04/graph-views/create-standard-view.md, versioned_docs/version-23.10/graph-views/create-standard-view.md, versioned_docs/version-24.04/graph-views/create-standard-view.md, versioned_docs/version-24.10/graph-views/create-standard-view.md
=> Remove links to old doc site

i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-commercial-extensions.mdx, versioned_docs/version-23.04/releases/centreon-commercial-extensions.mdx
Autodisco 23.04.6
LM 23.04.3
it editions 23.04.4
map 23.04.16 
mbi 23.04.8
=> doc(release): Release notes for modules 23.04

pp/integrations/plugin-packs/procedures/cloud-prometheus-kubernetes-api.md
=> CTOR-651 - Fix Cloud-Prometheus-Kubernetes

i18n/fr/docusaurus-plugin-content-docs/version-24.04/api/api-tokens.md, i18n/fr/docusaurus-plugin-content-docs/version-24.10/api/api-tokens.md, versioned_docs/version-24.04/api/api-tokens.md, versioned_docs/version-24.10/api/api-tokens.md
=> Update API tokens topic

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/operatingsystems-windows-telegraf-agent.md, pp/integrations/plugin-packs/procedures/operatingsystems-windows-telegraf-agent.md, pp/sidebarsPp.js
=> new(mc): added new telegraf connector

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-smtp.md, pp/integrations/plugin-packs/procedures/applications-protocol-smtp.md
=> [CTOR-608] refresh SMTP Server doc page

i18n/fr/docusaurus-plugin-content-docs/version-22.10/upgrade/upgrade-mariadb.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/upgrade/upgrade-mariadb.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/upgrade/upgrade-mariadb.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/upgrade/upgrade-mariadb.md, i18n/fr/docusaurus-plugin-content-docs/version-24.10/upgrade/upgrade-mariadb.md, versioned_docs/version-22.10/upgrade/upgrade-mariadb.md, versioned_docs/version-23.04/upgrade/upgrade-mariadb.md, versioned_docs/version-23.10/upgrade/upgrade-mariadb.md, versioned_docs/version-24.04/upgrade/upgrade-mariadb.md, versioned_docs/version-24.10/upgrade/upgrade-mariadb.md
=> Fix command in MariaDB upgrade procedure

i18n/fr/docusaurus-plugin-content-docs/version-24.04/releases/centreon-commercial-extensions.mdx, versioned_docs/version-24.04/releases/centreon-commercial-extensions.mdx
LM 24.04.1
map 24.04.1
bam 24.04.1
IT editions 24.04.1
mbi 24.04.1
=> doc(release): Release notes for modules 24.04

pp/sidebarsPp.js
Add mysteriously removed Loggly entry.
=> Add loggly entry in sidebar

i18n/fr/docusaurus-plugin-content-docs/version-24.04/upgrade/upgrade-from-23-04.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/upgrade/upgrade-from-23-10.md, i18n/fr/docusaurus-plugin-content-docs/version-24.10/upgrade/upgrade-from-23-04.md, i18n/fr/docusaurus-plugin-content-docs/version-24.10/upgrade/upgrade-from-23-10.md, versioned_docs/version-24.04/upgrade/upgrade-from-23-04.md, versioned_docs/version-24.04/upgrade/upgrade-from-23-10.md, versioned_docs/version-24.10/upgrade/upgrade-from-23-04.md, versioned_docs/version-24.10/upgrade/upgrade-from-23-10.md
=> Fix command in upgrade procedure

i18n/fr/docusaurus-plugin-content-docs/version-24.04/releases/centreon-os.mdx, versioned_docs/version-24.04/releases/centreon-os.mdx
=> doc(release): prepare release notes for collect 24.04.2

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/releases/release-notes.md, pp/integrations/plugin-packs/releases/release-notes.md
=> June Connectors Release note

i18n/fr/docusaurus-plugin-content-docs/version-24.04/installation/installation-of-a-central-server/using-virtual-machines.md, i18n/fr/docusaurus-plugin-content-docs/version-24.10/installation/installation-of-a-central-server/using-virtual-machines.md, versioned_docs/version-24.04/installation/installation-of-a-central-server/using-virtual-machines.md, versioned_docs/version-24.10/installation/installation-of-a-central-server/using-virtual-machines.md
=> Add info for Debian OVAs

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-tcp.md, pp/integrations/plugin-packs/procedures/applications-protocol-tcp.md
=> [CTOR-609] refresh Protocol TCP doc page

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-pfsense-fauxapi.md, pp/integrations/plugin-packs/procedures/applications-pfsense-fauxapi.md
=> Ctor 619 refresh applications pfsense fauxapi

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-oracle-ovm-api.md, pp/integrations/plugin-packs/procedures/applications-oracle-ovm-api.md
=> [CTOR-618] refresh Oracle VM Manager API doc page

i18n/fr/docusaurus-plugin-content-docs/version-24.04/installation/installation-of-a-central-server/using-virtual-machines.md, i18n/fr/docusaurus-plugin-content-docs/version-24.10/installation/installation-of-a-central-server/using-virtual-machines.md, versioned_docs/version-24.04/installation/installation-of-a-central-server/using-virtual-machines.md, versioned_docs/version-24.10/installation/installation-of-a-central-server/using-virtual-machines.md
=> Fix formatting

i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx, versioned_docs/version-23.04/releases/centreon-os.mdx
=> doc(release): Release notes for collect 23.04.13

i18n/fr/docusaurus-plugin-content-docs/version-24.04/releases/centreon-commercial-extensions.mdx, versioned_docs/version-24.04/releases/centreon-commercial-extensions.mdx
=> doc(release): Prepare release notes for hotfix map 24.04.2

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-gorgone-restapi.md, pp/integrations/plugin-packs/procedures/applications-gorgone-restapi.md
=> [CTOR-613] refresh Gorgone Rest API doc page

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/operatingsystems-windows-telegraf-agent.md, pp/integrations/plugin-packs/procedures/operatingsystems-windows-telegraf-agent.md
Added some missing information.
=> enh(mc): updated windows telegraf mc procedure

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-monitoring-node-exporter-linux.md, pp/integrations/plugin-packs/procedures/applications-monitoring-node-exporter-linux.md
=> [CTOR-615] refresh Node Exporter linux Metrics doc page

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-databases-informix-snmp.md, pp/integrations/plugin-packs/procedures/applications-databases-informix-snmp.md
=> [CTOR-612] refresh Informix DB SNMP doc page

cloud/resources/known-issues.md, cloud/sidebarsCloud.js, i18n/fr/docusaurus-plugin-content-docs-cloud/current/resources/known-issues.md
=> Cloud known issues

cloud/monitoring/anomaly-detection.md, i18n/fr/docusaurus-plugin-content-docs-cloud/current/monitoring/anomaly-detection.md
=> [Cloud] Remove comment about AD notification interface

cloud/releases/cloud-release-notes.md, i18n/fr/docusaurus-plugin-content-docs-cloud/current/releases/cloud-release-notes.md
=> doc(release): Release notes for cloud 24.05

cloud/administration/resource_access.md, cloud/sidebarsCloud.js, cloud/users/users.md, i18n/fr/docusaurus-plugin-content-docs-cloud/current/administration/resource_access.md, i18n/fr/docusaurus-plugin-content-docs-cloud/current/users/users.md
=> RAM (Cloud)

i18n/fr/docusaurus-plugin-content-docs/version-23.10/releases/centreon-os.mdx, versioned_docs/version-23.10/releases/centreon-os.mdx
=> doc(release): Release notes for web 23.10.13 / gorgone 23.10.8

i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx, versioned_docs/version-23.04/releases/centreon-os.mdx
=> doc(release): Release notes for web 23.04.19 / gorgone 23.04.15

i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md, versioned_docs/version-22.10/releases/centreon-os.md
=> doc(release): Release notes for web 22.10.23 / gorgone 22.10.8

i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md, versioned_docs/version-22.10/releases/centreon-os.md
=> doc(release): Release notes for collect 22.10.10

.github/workflows/documentation.yml
=> "Last updated" date should not be the last publication date for every topic

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-database-cosmosdb.md, pp/integrations/plugin-packs/procedures/cloud-azure-database-cosmosdb.md
=> [CTOR-653] refresh Azure Cosmos DB doc page

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-database-sqlserver.md, pp/integrations/plugin-packs/procedures/cloud-azure-database-sqlserver.md
=> [CTOR-659] refresh Azure SQL Server doc page

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-database-mariadb.md, pp/integrations/plugin-packs/procedures/cloud-azure-database-mariadb.md
=> [CTOR-655] refresh Azure Database for MariaDB doc page

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-protocol-ldap.md, pp/integrations/plugin-packs/procedures/applications-protocol-ldap.md
=> [CTOR-606] refresh LDAP Server doc page

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-microsoft-dhcp-snmp.md, pp/integrations/plugin-packs/procedures/applications-microsoft-dhcp-snmp.md
=> [CTOR-602] refresh Microsoft DHCP SNMP doc page

i18n/fr/docusaurus-plugin-content-docs/version-24.04/releases/centreon-os.mdx, versioned_docs/version-24.04/releases/centreon-os.mdx
=> doc(release): Prepare release notes for web 24.04.4

.github/workflows/actionlint.yml, .github/workflows/archive.yml, .github/workflows/documentation.yml
=> chore(deps): absorb 24.07 dependabot GitHub Actions updates

i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-commercial-extensions.md, versioned_docs/version-22.10/releases/centreon-commercial-extensions.md
Anomaly D 22.10.6
Mbi 22.10.10
=> doc(release): Release notes for modules 22.10

i18n/fr/docusaurus-plugin-content-docs/version-24.04/releases/centreon-commercial-extensions.mdx, versioned_docs/version-24.04/releases/centreon-commercial-extensions.mdx
=> doc(release): Release notes map 24.04.3

src/theme/DocItem/Footer/styles.module.css
=> Reduce-space-between-buttons

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-database-sqlmanagedinstance.md, pp/integrations/plugin-packs/procedures/cloud-azure-database-sqlmanagedinstance.md
=> [CTOR-658] refresh Azure SQL Managed Instance doc page

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-database-elasticpool.md, pp/integrations/plugin-packs/procedures/cloud-azure-database-elasticpool.md
=> [CTOR-654] refresh Azure Elastic Pool doc page

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/releases/release-notes.md, pp/integrations/plugin-packs/releases/release-notes.md
=> CTOR-682 : July release note

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-database-redis.md, pp/integrations/plugin-packs/procedures/cloud-azure-database-redis.md
=> [CTOR-657] refresh Azure Cache for Redis doc page

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-servers-cisco-ucs-snmp.md, pp/integrations/plugin-packs/procedures/hardware-servers-cisco-ucs-snmp.md
=> [CTOR-646] refresh Cisco UCS doc page

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/getting-started/how-to-guides/telegraf.md, i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/operatingsystems-linux-telegraf-agent.md, pp/integrations/plugin-packs/getting-started/how-to-guides/telegraf.md, pp/integrations/plugin-packs/procedures/operatingsystems-linux-telegraf-agent.md, pp/integrations/plugin-packs/procedures/operatingsystems-windows-telegraf-agent.md
=> enh(mc): add linux to telegraf +fixes

i18n/fr/docusaurus-plugin-content-docs/version-22.10/assets/reporting/installation/centreon.cnf, i18n/fr/docusaurus-plugin-content-docs/version-23.04/assets/reporting/installation/centreon.cnf, i18n/fr/docusaurus-plugin-content-docs/version-23.10/assets/reporting/installation/centreon.cnf, i18n/fr/docusaurus-plugin-content-docs/version-24.04/assets/reporting/installation/centreon.cnf, i18n/fr/docusaurus-plugin-content-docs/version-24.10/assets/reporting/installation/centreon.cnf, versioned_docs/version-22.10/assets/reporting/installation/centreon.cnf, versioned_docs/version-23.04/assets/reporting/installation/centreon.cnf, versioned_docs/version-23.10/assets/reporting/installation/centreon.cnf, versioned_docs/version-24.04/assets/reporting/installation/centreon.cnf, versioned_docs/version-24.10/assets/reporting/installation/centreon.cnf
=> MBI: Fix default value for wait_timeout

i18n/fr/docusaurus-plugin-content-docs/version-22.10/developer/about-developer-resources.md, versioned_docs/version-22.10/developer/about-developer-resources.md, versioned_sidebars/version-22.10-sidebars.json, versioned_sidebars/version-23.04-sidebars.json, versioned_sidebars/version-23.10-sidebars.json, versioned_sidebars/version-24.04-sidebars.json, versioned_sidebars/version-24.10-sidebars.json
=> Remove how to write a module topic

i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx, versioned_docs/version-23.04/releases/centreon-os.mdx
=> doc(release): Release notes for collect 23.04

i18n/fr/docusaurus-plugin-content-docs/version-23.10/releases/centreon-os.mdx, versioned_docs/version-23.10/releases/centreon-os.mdx
=> doc(release): Release notes for collect 23.10

i18n/fr/docusaurus-plugin-content-docs/version-24.04/releases/centreon-os.mdx, versioned_docs/version-24.04/releases/centreon-os.mdx
=> doc(release): Release notes for collect 24.04

i18n/fr/docusaurus-plugin-content-docs/version-23.10/reporting/installation.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/reporting/installation.md, i18n/fr/docusaurus-plugin-content-docs/version-24.10/reporting/installation.md, versioned_docs/version-23.10/reporting/installation.md, versioned_docs/version-24.04/reporting/installation.md, versioned_docs/version-24.10/reporting/installation.md
=> Remove OBJ

i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx, versioned_docs/version-23.04/releases/centreon-os.mdx
=> doc(release): Release notes for OSS 23.04

i18n/fr/docusaurus-plugin-content-docs/version-23.10/releases/centreon-os.mdx, versioned_docs/version-23.10/releases/centreon-os.mdx
=> doc(release): Release notes for OSS 23.10

i18n/fr/docusaurus-plugin-content-docs/version-24.04/releases/centreon-os.mdx, versioned_docs/version-24.04/releases/centreon-os.mdx
=> doc(release): Release notes for OSS 24.04

i18n/fr/docusaurus-plugin-content-docs/version-22.10/graph-views/map-web-update.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/graph-views/map-web-upgrade.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/graph-views/map-web-update.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/graph-views/map-web-upgrade.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/graph-views/map-web-update.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/graph-views/map-web-upgrade.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/graph-views/map-web-update.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/graph-views/map-web-upgrade.md, i18n/fr/docusaurus-plugin-content-docs/version-24.10/graph-views/map-web-update.md, i18n/fr/docusaurus-plugin-content-docs/version-24.10/graph-views/map-web-upgrade.md, versioned_docs/version-22.10/graph-views/map-web-update.md, versioned_docs/version-22.10/graph-views/map-web-upgrade.md, versioned_docs/version-23.04/graph-views/map-web-update.md, versioned_docs/version-23.04/graph-views/map-web-upgrade.md, versioned_docs/version-23.10/graph-views/map-web-update.md, versioned_docs/version-23.10/graph-views/map-web-upgrade.md, versioned_docs/version-24.04/graph-views/map-web-update.md, versioned_docs/version-24.04/graph-views/map-web-upgrade.md, versioned_docs/version-24.10/graph-views/map-web-update.md, versioned_docs/version-24.10/graph-views/map-web-upgrade.md
Improve MAP update topic - 22.10 only (for a first check)
MON-139127
MON-38640
MON-88905
=> Improve MAP update topic

i18n/fr/docusaurus-plugin-content-docs/version-22.10/update/update-centreon-platform.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/update/update-centreon-platform.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/update/update-centreon-platform.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/update/update-centreon-platform.md, i18n/fr/docusaurus-plugin-content-docs/version-24.10/update/update-centreon-platform.md, versioned_docs/version-22.10/update/update-centreon-platform.md, versioned_docs/version-23.04/update/update-centreon-platform.md, versioned_docs/version-23.10/update/update-centreon-platform.md, versioned_docs/version-24.04/update/update-centreon-platform.md, versioned_docs/version-24.10/update/update-centreon-platform.md
=> Fix Debian update command (mark hold instead of exclude)

i18n/fr/docusaurus-plugin-content-docs/version-22.10/administration/licenses.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/administration/licenses.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/administration/licenses.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/administration/licenses.md, i18n/fr/docusaurus-plugin-content-docs/version-24.10/administration/licenses.md, versioned_docs/version-22.10/administration/licenses.md, versioned_docs/version-23.04/administration/licenses.md, versioned_docs/version-23.10/administration/licenses.md, versioned_docs/version-24.04/administration/licenses.md, versioned_docs/version-24.10/administration/licenses.md
=> Update link to MAP in licenses topic

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-sonus-sbc-snmp.md, pp/integrations/plugin-packs/procedures/network-sonus-sbc-snmp.md
=> CTOR-728 Plugin(network::sonus::sbc::snmp) - Mode(cpu) : Unknown option

i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-commercial-extensions.mdx, versioned_docs/version-23.04/releases/centreon-commercial-extensions.mdx
=> doc(release): Release notes for map 23.04.18 and mbi 23.04.10

i18n/fr/docusaurus-plugin-content-docs/version-22.10/security/security.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/security/security.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/security/security.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/security/security.md, i18n/fr/docusaurus-plugin-content-docs/version-24.10/security/security.md, versioned_docs/version-22.10/security/security.md, versioned_docs/version-23.04/security/security.md, versioned_docs/version-23.10/security/security.md, versioned_docs/version-24.04/security/security.md, versioned_docs/version-24.10/security/security.md
=> Additional info about reporting vulnerabilities

cloud/security/security.md, i18n/fr/docusaurus-plugin-content-docs-cloud/current/security/security.md
=> Additional info about reporting vulnerabilities - Cloud

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-hpe-primera-restapi.md, pp/integrations/plugin-packs/procedures/hardware-storage-hpe-primera-restapi.md
=> new(mc): added HPE Primera MC doc

i18n/fr/docusaurus-plugin-content-docs/version-22.10/update/update-centreon-platform.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/update/update-centreon-platform.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/update/update-centreon-platform.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/update/update-centreon-platform.md, i18n/fr/docusaurus-plugin-content-docs/version-24.10/update/update-centreon-platform.md, versioned_docs/version-22.10/update/update-centreon-platform.md, versioned_docs/version-23.04/update/update-centreon-platform.md, versioned_docs/version-23.10/update/update-centreon-platform.md, versioned_docs/version-24.04/update/update-centreon-platform.md, versioned_docs/version-24.10/update/update-centreon-platform.md
=> Fix update command

i18n/fr/docusaurus-plugin-content-docs/version-23.10/releases/centreon-os.mdx, versioned_docs/version-23.10/releases/centreon-os.mdx
=> doc(release): Release notes for collect 23.10.10

i18n/fr/docusaurus-plugin-content-docs/version-24.04/releases/centreon-os.mdx, versioned_docs/version-24.04/releases/centreon-os.mdx
=> doc(release): Release notes for collect 24.04.5

pp/sidebarsPp.js
Complement to the first (and already committed) PR.
=> fix(sidebars): added the missing entry for HPE Primera

i18n/fr/docusaurus-plugin-content-docs/version-23.10/releases/centreon-os.mdx, versioned_docs/version-23.10/releases/centreon-os.mdx
=> doc(release): Release notes for web 23.10.15

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-vmware-velocloud-restapi.md, pp/integrations/plugin-packs/procedures/cloud-vmware-velocloud-restapi.md
=> enh(mc): refreshed the doc page of VMware VeloCloud Orchestrator

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/releases/release-notes.md, pp/integrations/plugin-packs/releases/release-notes.md
=> enh(mc): 24.08 release notes

i18n/fr/docusaurus-plugin-content-docs/version-23.10/releases/centreon-commercial-extensions.mdx, versioned_docs/version-23.10/releases/centreon-commercial-extensions.mdx
=> doc(release): Release notes for map 231012 and mbi 23107

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/releases/release-notes.md, pp/integrations/plugin-packs/releases/release-notes.md
=> Minor fixes to connectors release notes

i18n/fr/docusaurus-plugin-content-docs/version-22.10/integrations/data-analytics/sc-splunk-events.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/integrations/data-analytics/sc-splunk-metrics.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/integrations/data-analytics/sc-splunk-events.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/integrations/data-analytics/sc-splunk-metrics.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/integrations/data-analytics/sc-splunk-events.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/integrations/data-analytics/sc-splunk-metrics.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/integrations/data-analytics/sc-splunk-events.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/integrations/data-analytics/sc-splunk-metrics.md, i18n/fr/docusaurus-plugin-content-docs/version-24.10/integrations/data-analytics/sc-splunk-events.md, i18n/fr/docusaurus-plugin-content-docs/version-24.10/integrations/data-analytics/sc-splunk-metrics.md, versioned_docs/version-22.10/integrations/data-analytics/sc-splunk-events.md, versioned_docs/version-22.10/integrations/data-analytics/sc-splunk-metrics.md, versioned_docs/version-23.04/integrations/data-analytics/sc-splunk-events.md, versioned_docs/version-23.04/integrations/data-analytics/sc-splunk-metrics.md, versioned_docs/version-23.10/integrations/data-analytics/sc-splunk-events.md, versioned_docs/version-23.10/integrations/data-analytics/sc-splunk-metrics.md, versioned_docs/version-24.04/integrations/data-analytics/sc-splunk-events.md, versioned_docs/version-24.04/integrations/data-analytics/sc-splunk-metrics.md, versioned_docs/version-24.10/integrations/data-analytics/sc-splunk-events.md, versioned_docs/version-24.10/integrations/data-analytics/sc-splunk-metrics.md
=> Refresh Splunk Events topic

cloud/alerts-notifications/dashboards.md, i18n/fr/docusaurus-plugin-content-docs-cloud/current/alerts-notifications/dashboards.md
Update Dashboards topic - Cloud 24.07
=> Update Dashboards topic - Cloud 24.07

cloud/releases/cloud-release-notes.md, i18n/fr/docusaurus-plugin-content-docs-cloud/current/releases/cloud-release-notes.md
=> doc(release): Release notes for Cloud 24.07

cloud/installation/deploy-poller.md, cloud/users/users.md, i18n/fr/docusaurus-plugin-content-docs-cloud/current/installation/deploy-poller.md, i18n/fr/docusaurus-plugin-content-docs-cloud/current/users/users.md
=> Only Editors and Administrators can see the poller installation command

cloud/security/security.md, i18n/fr/docusaurus-plugin-content-docs-cloud/current/security/security.md
=> Update description of services used by Centreon Cloud

i18n/fr/docusaurus-plugin-content-docs/version-22.10/graph-views/map-web-install.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/graph-views/map-web-install.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/graph-views/map-web-install.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/graph-views/map-web-install.md, i18n/fr/docusaurus-plugin-content-docs/version-24.10/graph-views/map-web-install.md, versioned_docs/version-22.10/graph-views/map-web-install.md, versioned_docs/version-23.04/graph-views/map-web-install.md, versioned_docs/version-23.10/graph-views/map-web-install.md, versioned_docs/version-24.04/graph-views/map-web-install.md, versioned_docs/version-24.10/graph-views/map-web-install.md
=> Clarify MAP install procedure

i18n/fr/docusaurus-plugin-content-docs/version-23.04/upgrade/upgrade-mariadb.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/upgrade/upgrade-mariadb.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/upgrade/upgrade-mariadb.md, i18n/fr/docusaurus-plugin-content-docs/version-24.10/upgrade/upgrade-mariadb.md, versioned_docs/version-23.04/upgrade/upgrade-mariadb.md, versioned_docs/version-23.10/upgrade/upgrade-mariadb.md, versioned_docs/version-24.04/upgrade/upgrade-mariadb.md, versioned_docs/version-24.10/upgrade/upgrade-mariadb.md
=> Add info to MariaDB upgrade procedure on Debian

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-bdt-multistak-snmp.md, pp/integrations/plugin-packs/procedures/hardware-storage-bdt-multistak-snmp.md, pp/sidebarsPp.js
Refresh hardware-storage-bdt-multistak-snmp
=> CTOR-823 : Refresh hardware-storage-bdt-multistak-snmp

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-dell-compellent-snmp.md, pp/integrations/plugin-packs/procedures/hardware-storage-dell-compellent-snmp.md, pp/sidebarsPp.js
Refresh hardware-storage-dell-compellent-snmp
=> CTOR-824 : Refresh hardware-storage-dell-compellent-snmp

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-emc-clariion-navisphere.md, pp/integrations/plugin-packs/procedures/hardware-storage-emc-clariion-navisphere.md, pp/sidebarsPp.js
Refresh hardware-storage-emc-clariion-navisphere
=> CTOR-825 : Refresh hardware-storage-emc-clariion-navisphere

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-hp-lefthand-snmp.md, pp/integrations/plugin-packs/procedures/hardware-storage-hp-lefthand-snmp.md, pp/sidebarsPp.js
Refresh hardware-storage-hp-lefthand-snmp
=> CTOR-827 : Refresh hardware-storage-hp-lefthand-snmp

i18n/fr/docusaurus-plugin-content-docs-cloud/current/installation/prerequisites.md
Typo "tafic"
Updated Cloud prerequisites typo
=> Update Cloud prerequisites typo

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-hp-msa2000-snmp.md, pp/integrations/plugin-packs/procedures/hardware-storage-hp-msa2000-snmp.md, pp/sidebarsPp.js
Refresh hardware-storage-hp-msa2000-snmp
=> CTOR-828 :  Refresh hardware-storage-hp-msa2000-snmp

i18n/fr/docusaurus-plugin-content-docs/version-22.10/graph-views/troubleshooter.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/graph-views/upgrade.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/graph-views/troubleshooter.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/graph-views/upgrade.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/graph-views/troubleshooter.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/graph-views/upgrade.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/graph-views/troubleshooter.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/graph-views/upgrade.md, i18n/fr/docusaurus-plugin-content-docs/version-24.10/graph-views/troubleshooter.md, i18n/fr/docusaurus-plugin-content-docs/version-24.10/graph-views/upgrade.md, versioned_docs/version-22.10/graph-views/troubleshooter.md, versioned_docs/version-22.10/graph-views/upgrade.md, versioned_docs/version-23.04/graph-views/troubleshooter.md, versioned_docs/version-23.04/graph-views/upgrade.md, versioned_docs/version-23.10/graph-views/troubleshooter.md, versioned_docs/version-23.10/graph-views/upgrade.md, versioned_docs/version-24.04/graph-views/troubleshooter.md, versioned_docs/version-24.04/graph-views/upgrade.md, versioned_docs/version-24.10/graph-views/troubleshooter.md, versioned_docs/version-24.10/graph-views/upgrade.md
Add troubleshooting info for MAP Legacy upgrade
=> Add troubleshooting info for MAP Legacy upgrade

cloud/alerts-notifications/dashboards.md, i18n/fr/docusaurus-plugin-content-docs-cloud/current/alerts-notifications/dashboards.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/alerts-notifications/dashboards.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/alerts-notifications/dashboards.md, i18n/fr/docusaurus-plugin-content-docs/version-24.10/alerts-notifications/dashboards.md, versioned_docs/version-22.10/releases/centreon-commercial-extensions.md, versioned_docs/version-23.04/releases/centreon-commercial-extensions.mdx, versioned_docs/version-23.10/alerts-notifications/dashboards.md, versioned_docs/version-24.04/alerts-notifications/dashboards.md, versioned_docs/version-24.04/releases/centreon-os.mdx, versioned_docs/version-24.10/alerts-notifications/dashboards.md, versioned_docs/version-24.10/releases/centreon-os.mdx
Replace "modal" with "window"
Remplacer "modale" par "fenêtre"
=> Replace "modal" with "window"

cloud/installation/prerequisites.md, i18n/fr/docusaurus-plugin-content-docs-cloud/current/installation/prerequisites.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/installation/compatibility.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/installation/compatibility.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/installation/compatibility.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/installation/compatibility.md, i18n/fr/docusaurus-plugin-content-docs/version-24.10/installation/compatibility.md, versioned_docs/version-22.10/installation/compatibility.md, versioned_docs/version-23.04/installation/compatibility.md, versioned_docs/version-23.10/installation/compatibility.md, versioned_docs/version-24.04/installation/compatibility.md, versioned_docs/version-24.10/installation/compatibility.md
=> Add link to article about installing Linux

cloud/getting-started/about-centreon-cloud.md, cloud/sidebarsCloud.js, i18n/fr/docusaurus-plugin-content-docs-cloud/current/getting-started/about-centreon-cloud.md
=> General info about Centreon Cloud

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-microsoft-office365-onedrive.md, pp/integrations/plugin-packs/procedures/cloud-microsoft-office365-onedrive.md, pp/sidebarsPp.js
Refresh cloud-microsoft-office365-onedrive
=> CTOR-847 : Refresh cloud-microsoft-office365-onedrive

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-microsoft-office365-exchange.md, pp/integrations/plugin-packs/procedures/cloud-microsoft-office365-exchange.md, pp/sidebarsPp.js
Refresh cloud-microsoft-office365-exchange
=> CTOR-846 : Refresh cloud-microsoft-office365-exchange

i18n/fr/docusaurus-plugin-content-docs/version-22.10/graph-views/map-web-troubleshooting.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/graph-views/troubleshooter.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/graph-views/map-web-troubleshooting.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/graph-views/troubleshooter.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/graph-views/map-web-troubleshooting.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/graph-views/troubleshooter.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/graph-views/map-web-troubleshooting.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/graph-views/troubleshooter.md, i18n/fr/docusaurus-plugin-content-docs/version-24.10/graph-views/map-web-troubleshooting.md, i18n/fr/docusaurus-plugin-content-docs/version-24.10/graph-views/troubleshooter.md, versioned_docs/version-22.10/graph-views/map-web-troubleshooting.md, versioned_docs/version-22.10/graph-views/troubleshooter.md, versioned_docs/version-23.04/graph-views/map-web-troubleshooting.md, versioned_docs/version-23.04/graph-views/troubleshooter.md, versioned_docs/version-23.10/graph-views/map-web-troubleshooting.md, versioned_docs/version-23.10/graph-views/troubleshooter.md, versioned_docs/version-24.04/graph-views/map-web-troubleshooting.md, versioned_docs/version-24.04/graph-views/troubleshooter.md, versioned_docs/version-24.10/graph-views/map-web-troubleshooting.md, versioned_docs/version-24.10/graph-views/troubleshooter.md
Add troubleshooting item for MAP credentials issue
=> Add info MAP credentials

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/getting-started/how-to-guides/telegraf.md, pp/integrations/plugin-packs/getting-started/how-to-guides/telegraf.md
=> Add procedure to Telegraf topic

i18n/fr/docusaurus-plugin-content-docs/version-22.10/reporting/update.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/resources/known-issues.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/reporting/update.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/resources/known-issues.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/reporting/update.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/resources/known-issues.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/reporting/update.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/resources/known-issues.md, i18n/fr/docusaurus-plugin-content-docs/version-24.10/reporting/update.md, i18n/fr/docusaurus-plugin-content-docs/version-24.10/resources/known-issues.md, versioned_docs/version-22.10/graph-views/known-issues.md, versioned_docs/version-22.10/reporting/update.md, versioned_docs/version-22.10/resources/known-issues.md, versioned_docs/version-23.04/graph-views/known-issues.md, versioned_docs/version-23.04/reporting/update.md, versioned_docs/version-23.04/resources/known-issues.md, versioned_docs/version-23.10/reporting/update.md, versioned_docs/version-23.10/resources/known-issues.md, versioned_docs/version-24.04/reporting/update.md, versioned_docs/version-24.04/resources/known-issues.md, versioned_docs/version-24.10/reporting/update.md, versioned_docs/version-24.10/resources/known-issues.md
Add known issue procedure after MBI update
=> Add known issue procedure after MBI update

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/infrastructure-active-directory-nsclient-05-restapi.md, pp/integrations/plugin-packs/procedures/infrastructure-active-directory-nsclient-05-restapi.md, pp/sidebarsPp.js
Refresh infrastructure-active-directory-nsclient-05-restapi
=> CTOR-732 : Refresh infrastructure-active-directory-nsclient-05-restapi

i18n/fr/docusaurus-plugin-content-docs/version-23.10/connect/autologin.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/connect/autologin.md, i18n/fr/docusaurus-plugin-content-docs/version-24.10/connect/autologin.md, versioned_docs/version-23.10/connect/autologin.md, versioned_docs/version-24.04/connect/autologin.md, versioned_docs/version-24.10/connect/autologin.md
=> &min=1 is obsolete

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/releases/release-notes.md, pp/integrations/plugin-packs/releases/release-notes.md
=> Add release note for september

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-backbox-restapi.md, i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/releases/release-notes.md, pp/integrations/plugin-packs/procedures/network-backbox-restapi.md, pp/integrations/plugin-packs/releases/release-notes.md
=> Backbox quick fix

cloud/releases/cloud-release-notes.md, i18n/fr/docusaurus-plugin-content-docs-cloud/current/releases/cloud-release-notes.md
=> Update cloud 24.07 RN

i18n/fr/docusaurus-plugin-content-docs/version-22.10/health/helios.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/health/helios.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/health/helios.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/health/helios.md, i18n/fr/docusaurus-plugin-content-docs/version-24.10/health/helios.md, versioned_docs/version-22.10/health/helios.md, versioned_docs/version-23.04/health/helios.md, versioned_docs/version-23.10/health/helios.md, versioned_docs/version-24.04/health/helios.md, versioned_docs/version-24.10/health/helios.md
=> update url for logrotate man

i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md, versioned_docs/version-22.10/releases/centreon-os.md
=> doc(release) Release notes for web 22.10.24

i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx, versioned_docs/version-23.04/releases/centreon-os.mdx
=> doc(release) Release notes for web 23.04.21

i18n/fr/docusaurus-plugin-content-docs/version-23.10/releases/centreon-os.mdx, versioned_docs/version-23.10/releases/centreon-os.mdx
=> doc(release) Release notes for web 23.10.16

i18n/fr/docusaurus-plugin-content-docs/version-24.04/releases/centreon-os.mdx, versioned_docs/version-24.04/releases/centreon-os.mdx
=> doc(release) Release notes for web 24.04.6

i18n/fr/docusaurus-plugin-content-docs/version-24.04/monitoring/monitoring-servers/advanced-configuration.md, versioned_docs/version-24.04/monitoring/monitoring-servers/advanced-configuration.md
Here is a first quick improvement of the broker configuration documentation. I know it is not perfect, but even if I work a lot on it, it won't be perfect... :sob: 
REFS: MON-123352
=> Add info about BBDO client/server

i18n/fr/docusaurus-plugin-content-docs/version-24.10/monitoring/monitoring-servers/advanced-configuration.md, versioned_docs/version-24.10/monitoring/monitoring-servers/advanced-configuration.md
=> BBDO client/server (24.10)

i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md, versioned_docs/version-22.10/releases/centreon-os.md
=> doc(release) Release notes collect 22.10.11 gorgone 22.10.9

i18n/fr/docusaurus-plugin-content-docs/version-22.10/integrations/stream-connectors.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/integrations/stream-connectors.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/integrations/stream-connectors.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/integrations/stream-connectors.md, i18n/fr/docusaurus-plugin-content-docs/version-24.10/integrations/stream-connectors.md, versioned_docs/version-22.10/integrations/stream-connectors.md, versioned_docs/version-23.04/integrations/stream-connectors.md, versioned_docs/version-23.10/integrations/stream-connectors.md, versioned_docs/version-24.04/integrations/stream-connectors.md, versioned_docs/version-24.10/integrations/stream-connectors.md
=> Stream connectors 24.09 Release Note

i18n/fr/docusaurus-plugin-content-docs/version-22.10/integrations/data-analytics/sc-influxdb2-metrics.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/integrations/stream-connectors.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/integrations/data-analytics/sc-influxdb2-metrics.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/integrations/stream-connectors.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/integrations/data-analytics/sc-influxdb2-metrics.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/integrations/stream-connectors.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/integrations/stream-connectors.md, i18n/fr/docusaurus-plugin-content-docs/version-24.10/integrations/data-analytics/sc-influxdb2-metrics.md, i18n/fr/docusaurus-plugin-content-docs/version-24.10/integrations/stream-connectors.md, versioned_docs/version-22.10/integrations/data-analytics/sc-influxdb2-metrics.md, versioned_docs/version-22.10/integrations/stream-connectors.md, versioned_docs/version-23.04/integrations/data-analytics/sc-influxdb2-metrics.md, versioned_docs/version-23.04/integrations/stream-connectors.md, versioned_docs/version-23.10/integrations/data-analytics/sc-influxdb2-metrics.md, versioned_docs/version-23.10/integrations/stream-connectors.md, versioned_docs/version-24.04/integrations/stream-connectors.md, versioned_docs/version-24.10/integrations/data-analytics/sc-influxdb2-metrics.md, versioned_docs/version-24.10/integrations/stream-connectors.md, versioned_sidebars/version-22.10-sidebars.json, versioned_sidebars/version-23.04-sidebars.json, versioned_sidebars/version-23.10-sidebars.json, versioned_sidebars/version-24.10-sidebars.json
Document InfluxDB SC in all Centreon version + release note links
=> CTOR-445 : Document InfluxDB SC

i18n/fr/docusaurus-plugin-content-docs/version-23.04/integrations/event-management/sc-service-now-em-events.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/integrations/event-management/sc-service-now-em-events.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/integrations/event-management/sc-service-now-em-events.md, i18n/fr/docusaurus-plugin-content-docs/version-24.10/integrations/event-management/sc-service-now-em-events.md, versioned_docs/version-23.04/integrations/event-management/sc-service-now-em-events.md, versioned_docs/version-23.10/integrations/event-management/sc-service-now-em-events.md, versioned_docs/version-24.04/integrations/event-management/sc-service-now-em-events.md, versioned_docs/version-24.10/integrations/event-management/sc-service-now-em-events.md
=> Fix typo in sc-service-now-em-events.md

i18n/fr/docusaurus-plugin-content-docs/version-22.10/update/update-centreon-platform.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/update/update-centreon-platform.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/update/update-centreon-platform.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/update/update-centreon-platform.md, i18n/fr/docusaurus-plugin-content-docs/version-24.10/update/update-centreon-platform.md, versioned_docs/version-22.10/update/update-centreon-platform.md, versioned_docs/version-23.04/update/update-centreon-platform.md, versioned_docs/version-23.10/update/update-centreon-platform.md, versioned_docs/version-24.04/update/update-centreon-platform.md, versioned_docs/version-24.10/update/update-centreon-platform.md
=> Update Debian update command

cloud/administration/api_tokens.md, i18n/fr/docusaurus-plugin-content-docs-cloud/current/administration/api_tokens.md
=> Remove Editor from API tokens permission information

i18n/fr/docusaurus-plugin-content-docs/version-24.04/graph-views/map-web-upgrade.md, i18n/fr/docusaurus-plugin-content-docs/version-24.10/graph-views/map-web-upgrade.md, versioned_docs/version-24.04/graph-views/map-web-upgrade.md, versioned_docs/version-24.10/graph-views/map-web-upgrade.md
=> Add missing Debian 12

i18n/fr/docusaurus-plugin-content-docs/version-22.10/monitoring/passive-monitoring/debug-snmp-traps-management.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/monitoring/passive-monitoring/debug-snmp-traps-management.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/monitoring/passive-monitoring/debug-snmp-traps-management.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/monitoring/passive-monitoring/debug-snmp-traps-management.md, i18n/fr/docusaurus-plugin-content-docs/version-24.10/monitoring/passive-monitoring/debug-snmp-traps-management.md, versioned_docs/version-23.04/service-mapping/remote-server.md
=> Fixed typo

i18n/fr/docusaurus-plugin-content-docs/version-24.04/api/api-tokens.md, i18n/fr/docusaurus-plugin-content-docs/version-24.10/api/api-tokens.md, versioned_docs/version-24.04/api/api-tokens.md, versioned_docs/version-24.10/api/api-tokens.md
=> Update labels in api tokens topic

i18n/fr/docusaurus-plugin-content-docs/version-23.10/connect/autologin.md, versioned_docs/version-23.10/connect/autologin.md
=> Update autologin.md 23.10

i18n/fr/docusaurus-plugin-content-docs/version-24.04/monitoring/basic-objects/timeperiods.md, i18n/fr/docusaurus-plugin-content-docs/version-24.10/monitoring/basic-objects/timeperiods.md, versioned_docs/version-24.04/monitoring/basic-objects/timeperiods.md, versioned_docs/version-24.10/monitoring/basic-objects/timeperiods.md
=> Update example of time period

i18n/fr/docusaurus-plugin-content-docs/version-23.10/monitoring/basic-objects/timeperiods.md, versioned_docs/version-23.10/monitoring/basic-objects/timeperiods.md
=> Add info to time periods topic (23.10)

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/operatingsystems-as400-connector.md, pp/integrations/plugin-packs/procedures/operatingsystems-as400-connector.md
Refresh operatingsystems-as400-connector
=> CTOR-910 : Refresh operatingsystems-as400-connector

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-antivirus-clamav-ssh.md, pp/integrations/plugin-packs/procedures/applications-antivirus-clamav-ssh.md
Refresh applications-antivirus-clamav-ssh
=> CTOR-731 : Refresh applications-antivirus-clamav-ssh

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-servers-hp-snmp.md, pp/integrations/plugin-packs/procedures/hardware-servers-hp-snmp.md
Refresh hardware-servers-hp-snmp
=> CTOR-736 : Refresh hardware-servers-hp-snmp

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-microsoft-office365-teams.md, pp/integrations/plugin-packs/procedures/cloud-microsoft-office365-teams.md
Refresh cloud-microsoft-office365-teams
=> CTOR-850 : Refresh cloud-microsoft-office365-teams

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-microsoft-office365-sharepoint.md, pp/integrations/plugin-packs/procedures/cloud-microsoft-office365-sharepoint.md
Refresh cloud-microsoft-office365-sharepoint
=> CTOR-848 : Refresh cloud-microsoft-office365-sharepoint

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-aws-health.md, pp/integrations/plugin-packs/procedures/cloud-aws-health.md
Missing permission in cloud-aws-health
=> CTOR-867 : Missing permission in cloud-aws-health

i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx, versioned_docs/version-23.04/releases/centreon-os.mdx
=> doc(release) Release notes collect 23.04.15 / gorgone 23.04.16

i18n/fr/docusaurus-plugin-content-docs/version-23.10/releases/centreon-os.mdx, versioned_docs/version-23.10/releases/centreon-os.mdx
=> doc(release) release notes for collect 23.10.11 / gorgone 23.10.10

i18n/fr/docusaurus-plugin-content-docs/version-24.04/releases/centreon-os.mdx, versioned_docs/version-24.04/releases/centreon-os.mdx
=> doc(release): Release notes collect 24.04.6 / gorgone 24.04.2

i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx, versioned_docs/version-23.04/releases/centreon-os.mdx
=> doc(release): Release notes for web 23.04.22

i18n/fr/docusaurus-plugin-content-docs/version-24.04/releases/centreon-os.mdx, versioned_docs/version-24.04/releases/centreon-os.mdx
=> doc(release) Release notes for web 24.04.7 / open tickets 24.04.1

i18n/fr/docusaurus-plugin-content-docs/version-24.04/releases/centreon-os.mdx, versioned_docs/version-24.04/releases/centreon-os.mdx
added Centreon monitoring agent
=> doc(release) Release notes collect 24.04.6

i18n/fr/docusaurus-plugin-content-docs/version-22.10/service-mapping/ba-monitoring.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/service-mapping/ba-monitoring.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/service-mapping/ba-monitoring.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/service-mapping/ba-monitoring.md, i18n/fr/docusaurus-plugin-content-docs/version-24.10/service-mapping/ba-monitoring.md
=> Fix typos in ba-monitoring.md

i18n/fr/docusaurus-plugin-content-docs/version-23.04/alerts-notifications/resources-status.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/alerts-notifications/resources-status.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/alerts-notifications/resources-status.md, i18n/fr/docusaurus-plugin-content-docs/version-24.10/alerts-notifications/resources-status.md, versioned_docs/version-23.04/alerts-notifications/resources-status.md, versioned_docs/version-23.10/alerts-notifications/resources-status.md, versioned_docs/version-24.04/alerts-notifications/resources-status.md, versioned_docs/version-24.10/alerts-notifications/resources-status.md
=> updated names of filter buttons in resources status

i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-commercial-extensions.mdx, versioned_docs/version-23.04/releases/centreon-commercial-extensions.mdx
=> doc(release) Release notes map 23.04.19 / mbi 23.04.11

i18n/fr/docusaurus-plugin-content-docs/version-22.10/administration/parameters/debug.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/resources/troubleshooting.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/administration/parameters/debug.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/resources/troubleshooting.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/administration/parameters/debug.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/resources/troubleshooting.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/administration/parameters/debug.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/resources/troubleshooting.md, i18n/fr/docusaurus-plugin-content-docs/version-24.10/administration/parameters/debug.md, i18n/fr/docusaurus-plugin-content-docs/version-24.10/resources/troubleshooting.md, versioned_docs/version-22.10/resources/troubleshooting.md, versioned_docs/version-23.04/resources/troubleshooting.md, versioned_docs/version-23.10/resources/troubleshooting.md, versioned_docs/version-24.04/resources/troubleshooting.md, versioned_docs/version-24.10/resources/troubleshooting.md
=> Added debugging link to troubleshooting page

i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-commercial-extensions.mdx, i18n/fr/docusaurus-plugin-content-docs/version-23.10/releases/centreon-commercial-extensions.mdx, versioned_docs/version-23.04/releases/centreon-commercial-extensions.mdx, versioned_docs/version-23.10/releases/centreon-commercial-extensions.mdx
Add CVE number to security fix
=> Add CVE number to security fix

i18n/fr/docusaurus-plugin-content-docs/version-23.04/resources/glossary.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/resources/glossary.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/resources/glossary.md, i18n/fr/docusaurus-plugin-content-docs/version-24.10/resources/glossary.md, versioned_docs/version-23.04/resources/glossary.md, versioned_docs/version-23.10/resources/glossary.md, versioned_docs/version-24.04/resources/glossary.md, versioned_docs/version-24.10/resources/glossary.md
=> Update glossary connectors entry

i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-commercial-extensions.md, versioned_docs/version-22.10/releases/centreon-commercial-extensions.md
=> doc(release) Release notes for map 22.10.17 / mbi 22.10.11

i18n/fr/docusaurus-plugin-content-docs/version-24.04/releases/centreon-commercial-extensions.mdx, versioned_docs/version-24.04/releases/centreon-commercial-extensions.mdx
=> doc(release) Release notes for map 24.04.5 / mbi 24.04.3 / ppm 24.04.1

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-rubrik-restapi.md, pp/integrations/plugin-packs/procedures/applications-rubrik-restapi.md
Added hostmacro to show more login ways on the API.
=> CTOR-752 : Former mandatory option in applications-rubrik-restapi 

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-rapidrecovery-snmp.md, pp/integrations/plugin-packs/procedures/applications-rapidrecovery-snmp.md
Refresh Doc page for the occasion
=> CTOR-950 : Pack(Applications-rapidrecovery-snmp) : Fix commands typo for both modes

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-pdu-cyberpower-snmp.md, pp/integrations/plugin-packs/procedures/hardware-pdu-cyberpower-snmp.md
Fix power unit and add Voltage metric
=> CTOR-887 : Plugin(hardware::pdu::cyberpower::snmp) - Mode(load) : StatusPower should not be multiplied by 10

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-wd-nas-snmp.md, pp/integrations/plugin-packs/procedures/hardware-storage-wd-nas-snmp.md
Add support for ex4100 model in Modes: volumes, listvolumes and hardware
=> CTOR-397 : [Plugin(storage::wd::nas::snmp) - Modes(volumes, listvolumes, hardware) : add support for ex4100 model

cloud/alerts-notifications/notif-configuration.md, cloud/monitoring/basic-objects/timeperiods.md, i18n/fr/docusaurus-plugin-content-docs-cloud/current/alerts-notifications/notif-configuration.md, i18n/fr/docusaurus-plugin-content-docs-cloud/current/monitoring/basic-objects/timeperiods.md
=> [Cloud] Time periods in notifications

cloud/alerts-notifications/dashboards.md, i18n/fr/docusaurus-plugin-content-docs-cloud/current/alerts-notifications/dashboards.md
Update list of widgets for Cloud 24.09 (clock/timer)
=> Update list of widgets for Cloud 24.09 (clock/timer)

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/operatingsystems-linux-centreon-monitoring-agent.md, pp/integrations/plugin-packs/procedures/operatingsystems-linux-centreon-monitoring-agent.md, pp/sidebarsPp.js
=> feat(mc-cma-linux): new monitoring connector - Linux with Centreon Monitoring Agent

.github/workflows/actionlint.yml, .github/workflows/archive.yml, .github/workflows/documentation.yml
=> chore(deps): absorb 24.10 dependabot GitHub Actions updates

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/releases/release-notes.md, pp/integrations/plugin-packs/releases/release-notes.md
Replace fix sectiond with bug fixes
=> Fix on connectors release note : Replace fix sectiond with bug fixes

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/getting-started/how-to-guides/cma.md, pp/integrations/plugin-packs/getting-started/how-to-guides/cma.md
=> CMA: Fix typo and add links

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/operatingsystems-linux-centreon-monitoring-agent.md, i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/operatingsystems-windows-centreon-monitoring-agent.md, pp/integrations/plugin-packs/procedures/operatingsystems-linux-centreon-monitoring-agent.md, pp/integrations/plugin-packs/procedures/operatingsystems-windows-centreon-monitoring-agent.md
fast-update-on-windows-linux-cma-connectors
=> fast-update-on-windows-linux-cma-connectors

.github/workflows/documentation.yml, i18n/fr/docusaurus-plugin-content-docs/version-24.10/upgrade/upgrade-from-22-10.md, i18n/fr/docusaurus-plugin-content-docs/version-24.10/upgrade/upgrade-from-23-04.md, i18n/fr/docusaurus-plugin-content-docs/version-24.10/upgrade/upgrade-from-23-10.md, i18n/fr/docusaurus-plugin-content-docs/version-24.10/upgrade/upgrade-from-24-04.md, package.json, versioned_docs/version-24.10/upgrade/upgrade-from-22-10.md, versioned_docs/version-24.10/upgrade/upgrade-from-23-04.md, versioned_docs/version-24.10/upgrade/upgrade-from-23-10.md, versioned_docs/version-24.10/upgrade/upgrade-from-24-04.md, versioned_docs/version-24.10/upgrade/upgrade-from-24.04.md, yarn.lock
fix(doc): enable php 8.2 streams on upgrade
=> fix(doc): enable php 8.2 streams on upgrade

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-beeware-snmp.md, pp/integrations/plugin-packs/procedures/network-beeware-snmp.md
=> Refresh network-beeware-snmp

i18n/fr/docusaurus-plugin-content-docs/version-24.04/installation/compatibility.md, versioned_docs/version-24.04/installation/compatibility.md
=> MySQL 8.0 (24.04)

i18n/fr/docusaurus-plugin-content-docs/version-22.10/update/update-centreon-platform.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/update/update-centreon-platform.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/update/update-centreon-platform.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/update/update-centreon-platform.md, i18n/fr/docusaurus-plugin-content-docs/version-24.10/update/update-centreon-platform.md, versioned_docs/version-22.10/update/update-centreon-platform.md, versioned_docs/version-23.04/update/update-centreon-platform.md, versioned_docs/version-23.10/update/update-centreon-platform.md, versioned_docs/version-24.04/update/update-centreon-platform.md, versioned_docs/version-24.10/update/update-centreon-platform.md
=> MON-146706 adding update links for MBI and MAP

i18n/fr/docusaurus-plugin-content-docs/version-22.10/security/security.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/security/security.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/security/security.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/security/security.md, i18n/fr/docusaurus-plugin-content-docs/version-24.10/security/security.md, versioned_docs/version-22.10/security/security.md, versioned_docs/version-23.04/security/security.md, versioned_docs/version-23.10/security/security.md, versioned_docs/version-24.04/security/security.md, versioned_docs/version-24.10/security/security.md
=> added link to the watch security bulletins

i18n/fr/docusaurus-plugin-content-docs/version-22.10/reporting/generate-reports.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/reporting/generate-reports.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/reporting/generate-reports.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/reporting/generate-reports.md, i18n/fr/docusaurus-plugin-content-docs/version-24.10/reporting/generate-reports.md, versioned_docs/version-22.10/reporting/generate-reports.md, versioned_docs/version-23.04/reporting/generate-reports.md, versioned_docs/version-23.10/reporting/generate-reports.md, versioned_docs/version-24.04/reporting/generate-reports.md, versioned_docs/version-24.10/reporting/generate-reports.md
=> Update generated-reports access path.md

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-databases-sap-hana.md, pp/integrations/plugin-packs/procedures/applications-databases-sap-hana.md
=> [CTOR-886]- refresh SAP HANA doc page

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-purestorage-snmp.md, pp/integrations/plugin-packs/procedures/hardware-storage-purestorage-snmp.md, pp/sidebarsPp.js
Refresh hardware-storage-purestorage-snmp
=> CTOR-833 : Refresh hardware-storage-purestorage-snmp

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-cisco-apic-restapi.md, pp/integrations/plugin-packs/procedures/network-cisco-apic-restapi.md
=> [CTOR-891] - Refresh Cisco APIC doc page

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-cisco-callmanager-snmp.md, pp/integrations/plugin-packs/procedures/network-cisco-callmanager-snmp.md
=> [CTOR-892] - Refresh Cisco Call Manager SNMP doc page

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-cisco-vcs-restapi.md, pp/integrations/plugin-packs/procedures/network-cisco-vcs-restapi.md
Refresh network-cisco-vcs-restapi
=> CTOR-901 : Refresh network-cisco-vcs-restapi

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-acmepacket-snmp.md, pp/integrations/plugin-packs/procedures/network-acmepacket-snmp.md
Refresh network-acmepacket-snmp
=> CTOR-915 : Refresh network-acmepacket-snmp

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-adva-fsp150-snmp.md, pp/integrations/plugin-packs/procedures/network-adva-fsp150-snmp.md
Refresh network-adva-fsp150-snmp
=> CTOR-916 : Refresh network-adva-fsp150-snmp

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-aerohive-snmp.md, pp/integrations/plugin-packs/procedures/network-aerohive-snmp.md
=> CTOR-917 : Refresh network-aerohive-snmp

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-switchs-arista-snmp.md, pp/integrations/plugin-packs/procedures/network-switchs-arista-snmp.md
Refresh network-switchs-arista-snmp
=> CTOR-920 : Refresh network-switchs-arista-snmp

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-allied-snmp.md, pp/integrations/plugin-packs/procedures/network-allied-snmp.md
=> CTOR-918 : Refresh network-allied-snmp

cloud/alerts-notifications/dashboards.md, i18n/fr/docusaurus-plugin-content-docs-cloud/current/alerts-notifications/dashboards.md
Warn user about language used in public playlist
(Handled in the jira MON-147382 for the On-prem 24.10 version)
=> Warn user about language used in public playlist

i18n/fr/docusaurus-plugin-content-docs/version-24.10/alerts-notifications/dashboards.md, i18n/fr/docusaurus-plugin-content-docs/version-24.10/resources/known-issues.md, versioned_docs/version-24.10/alerts-notifications/dashboards.md, versioned_docs/version-24.10/resources/known-issues.md
[OnPrem 24.10] Add public playlist + known issue for MAP widget
=> [OnPrem 24.10] Add public playlist + known issue for MAP widget

i18n/fr/docusaurus-plugin-content-docs/version-24.10/alerts-notifications/dashboards.md, i18n/fr/docusaurus-plugin-content-docs/version-24.10/alerts-notifications/ticketing.md, versioned_docs/version-24.10/alerts-notifications/dashboards.md, versioned_docs/version-24.10/alerts-notifications/ticketing.md
Add Open ticket to Dashboards - 24.10
=> Add Open ticket to Dashboards - 24.10

i18n/fr/docusaurus-plugin-content-docs/version-24.10/alerts-notifications/dashboards.md, versioned_docs/version-24.10/alerts-notifications/dashboards.md
=> Update list of widgets 24.10

i18n/fr/docusaurus-plugin-content-docs/version-24.10/installation/installation-of-a-central-server/using-virtual-machines.md, versioned_docs/version-24.10/installation/installation-of-a-central-server/using-virtual-machines.md
=> Update OVA install topic for 24.10

i18n/fr/docusaurus-plugin-content-docs/version-24.04/releases/centreon-commercial-extensions.mdx, versioned_docs/version-24.04/releases/centreon-commercial-extensions.mdx
=> doc(release) Release notes map 24.04.6

i18n/fr/docusaurus-plugin-content-docs/version-23.10/administration/platform-statistics.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/administration/platform-statistics.md, i18n/fr/docusaurus-plugin-content-docs/version-24.10/administration/platform-statistics.md, versioned_docs/version-23.04/administration/platform-statistics.md, versioned_docs/version-23.10/administration/platform-statistics.md, versioned_docs/version-24.04/administration/platform-statistics.md, versioned_docs/version-24.10/administration/platform-statistics.md
* Fix fr pages visualization
* Change menu titles in bold for en pages
=> Fix platform statistics pages

i18n/fr/docusaurus-plugin-content-docs/version-23.10/releases/centreon-commercial-extensions.mdx, versioned_docs/version-23.10/releases/centreon-commercial-extensions.mdx
=> doc(release) release notes map 23.10.14

i18n/fr/docusaurus-plugin-content-docs/version-24.04/installation/_database-local-install.mdx, i18n/fr/docusaurus-plugin-content-docs/version-24.04/installation/_database-remote-install.mdx, versioned_docs/version-24.04/installation/_database-local-install.mdx, versioned_docs/version-24.04/installation/_database-remote-install.mdx
=> Replace variable by service name (mysqld, 24.04)

i18n/fr/docusaurus-plugin-content-docs/version-23.04/upgrade/upgrade-from-22-04.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/upgrade/upgrade-from-22-10.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/upgrade/upgrade-from-22-04.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/upgrade/upgrade-from-22-10.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/upgrade/upgrade-from-23-04.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/upgrade/upgrade-from-22-04.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/upgrade/upgrade-from-22-10.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/upgrade/upgrade-from-23-04.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/upgrade/upgrade-from-23-10.md, versioned_docs/version-23.04/upgrade/upgrade-from-22-04.md, versioned_docs/version-23.04/upgrade/upgrade-from-22-10.md, versioned_docs/version-23.10/upgrade/upgrade-from-22-04.md, versioned_docs/version-23.10/upgrade/upgrade-from-22-10.md, versioned_docs/version-23.10/upgrade/upgrade-from-23-04.md, versioned_docs/version-24.04/upgrade/upgrade-from-22-04.md, versioned_docs/version-24.04/upgrade/upgrade-from-22-10.md, versioned_docs/version-24.04/upgrade/upgrade-from-23-04.md, versioned_docs/version-24.04/upgrade/upgrade-from-23-10.md
=> Debian: update before upgrading (23.04 to 24.04)

i18n/fr/docusaurus-plugin-content-docs/version-24.04/releases/centreon-commercial-extensions.mdx, versioned_docs/version-24.04/releases/centreon-commercial-extensions.mdx
=> Improve RN entry

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-cisco-umbrella-snmp.md, pp/integrations/plugin-packs/procedures/network-cisco-umbrella-snmp.md
Refresh network-cisco-umbrella-snmp
=> CTOR-900 : Refresh network-cisco-umbrella-snmp

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-cisco-callmanager-sxml.md, pp/integrations/plugin-packs/procedures/network-cisco-callmanager-sxml.md
=> [CTOR-893] - Refresh the cisco-callmanager-sxml doc page

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-aruba-orchestrator-restapi.md, pp/integrations/plugin-packs/procedures/network-aruba-orchestrator-restapi.md
Refresh network-aruba-orchestrator-restapi
=> CTOR-922 : Refresh network-aruba-orchestrator-restapi

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-athonet-epc-snmp.md, pp/integrations/plugin-packs/procedures/network-athonet-epc-snmp.md
Refresh network-athonet-epc-snmp
=> CTOR-923 : Refresh network-athonet-epc-snmp

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-atto-fibrebridge-snmp.md, pp/integrations/plugin-packs/procedures/network-atto-fibrebridge-snmp.md
Refresh network-atto-fibrebridge-snmp
=> Refresh network-atto-fibrebridge-snmp

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-barracuda-cloudgen-snmp.md, pp/integrations/plugin-packs/procedures/network-barracuda-cloudgen-snmp.md
Refresh network-barracuda-cloudgen-snmp
=> Refresh network-barracuda-cloudgen-snmp

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-barracuda-bma-snmp.md, pp/integrations/plugin-packs/procedures/network-barracuda-bma-snmp.md
Refresh network-barracuda-bma-snmp
=> Refresh network-barracuda-bma-snmp

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-generic-bluecoat-snmp.md, pp/integrations/plugin-packs/procedures/network-generic-bluecoat-snmp.md
Refresh network-generic-bluecoat-snmp
=> Refresh network-generic-bluecoat-snmp

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-citrix-sdx-snmp.md, pp/integrations/plugin-packs/procedures/network-citrix-sdx-snmp.md
Refresh network-citrix-sdx-snmp
=> Refresh network-citrix-sdx-snmp

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-colubris-snmp.md, pp/integrations/plugin-packs/procedures/network-colubris-snmp.md
=> Refresh network-colubris-snmp

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/virtualization-hpe-simplivity-restapi.md, pp/integrations/plugin-packs/procedures/virtualization-hpe-simplivity-restapi.md
Refresh virtualization-hpe-simplivity-restapi
=> Refresh virtualization-hpe-simplivity-restapi

i18n/fr/docusaurus-plugin-content-docs/version-24.10/releases/centreon-os.mdx, versioned_docs/version-24.10/releases/centreon-os.mdx
=> doc(release) Release notes for OSS and Collect 24.10.0

i18n/fr/docusaurus-plugin-content-docs/version-24.10/releases/centreon-commercial-extensions.mdx, versioned_docs/version-24.10/releases/centreon-commercial-extensions.mdx
=> doc(release) Release notes 24.10.0 Modules

docusaurus.config.js, i18n/fr/docusaurus-plugin-content-docs/version-22.10/installation/installation-of-a-central-server/unattended.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/installation/installation-of-a-central-server/using-packages.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/installation/installation-of-a-central-server/using-virtual-machines.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/installation/installation-of-a-poller/unattended.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/installation/installation-of-a-poller/using-packages.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/installation/installation-of-a-remote-server/unattended.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/installation/installation-of-a-remote-server/using-packages.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/installation/introduction.md, i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/lifecycle.md, versioned_docs/version-22.10/installation/installation-of-a-central-server/unattended.md, versioned_docs/version-22.10/installation/installation-of-a-central-server/using-packages.md, versioned_docs/version-22.10/installation/installation-of-a-central-server/using-virtual-machines.md, versioned_docs/version-22.10/installation/installation-of-a-poller/unattended.md, versioned_docs/version-22.10/installation/installation-of-a-poller/using-packages.md, versioned_docs/version-22.10/installation/installation-of-a-remote-server/unattended.md, versioned_docs/version-22.10/installation/installation-of-a-remote-server/using-packages.md, versioned_docs/version-22.10/installation/introduction.md, versioned_docs/version-22.10/releases/lifecycle.md
Remove obsolete information so that the files are ready to be archived.
=> 22.10 EOL: prepare files

i18n/fr/docusaurus-plugin-content-docs/version-24.10/releases/centreon-commercial-extensions.mdx, i18n/fr/docusaurus-plugin-content-docs/version-24.10/releases/centreon-os.mdx, versioned_docs/version-24.10/releases/centreon-commercial-extensions.mdx, versioned_docs/version-24.10/releases/centreon-os.mdx
=> Update release date

i18n/fr/docusaurus-plugin-content-docs/version-24.10/installation/installation-of-a-central-server/using-virtual-machines.md, i18n/fr/docusaurus-plugin-content-docs/version-24.10/migrate/introduction.md, versioned_docs/version-24.10/installation/installation-of-a-central-server/using-virtual-machines.md, versioned_docs/version-24.10/migrate/introduction.md
=> Fix ova versions + add link to Debian migration topic

versioned_docs/version-24.10/installation/installation-of-a-central-server/using-virtual-machines.md
=> Run another build

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-digi-portserverts-snmp.md, pp/integrations/plugin-packs/procedures/network-digi-portserverts-snmp.md
=> [CTOR-975] Refresh network-digi-portservets-snmp doc page

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-dell-6200-snmp.md, pp/integrations/plugin-packs/procedures/network-dell-6200-snmp.md
=> [CTOR-971] Refresh network-dell-6200-snmp doc page

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-dlink-dgs3100-snmp.md, pp/integrations/plugin-packs/procedures/network-dlink-dgs3100-snmp.md
=> [CTOR-970] Refresh network-dlink-dgs-3100-snmp doc page

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-dell-nseries-snmp.md, pp/integrations/plugin-packs/procedures/network-dell-nseries-snmp.md
Refresh network-dell-nseries-snmp
=> Refresh network-dell-nseries-snmp

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-denyall-snmp.md, pp/integrations/plugin-packs/procedures/network-denyall-snmp.md
=> Refresh network-denyall-snmp

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-enterasys-snmp.md, pp/integrations/plugin-packs/procedures/network-enterasys-snmp.md
Refresh network-enterasys-snmp
=> Refresh network-enterasys-snmp

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-fortinet-fortiadc-snmp.md, pp/integrations/plugin-packs/procedures/network-fortinet-fortiadc-snmp.md
Refresh network-fortinet-fortiadc-snmp
=> Refresh network-fortinet-fortiadc-snmp

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-fiberstore-snmp.md, pp/integrations/plugin-packs/procedures/network-fiberstore-snmp.md
=> [CTOR-980] Refresh network-fiberstore-snmp doc page

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-fortinet-fortiauthenticator-snmp.md, pp/integrations/plugin-packs/procedures/network-fortinet-fortiauthenticator-snmp.md
Refresh network-fortinet-fortiauthenticator-snmp
=> Refresh network-fortinet-fortiauthenticator-snmp

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-fritzbox-upnp.md, pp/integrations/plugin-packs/procedures/network-fritzbox-upnp.md
=> Refresh network-fritzbox-upnp

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-freebox-restapi.md, pp/integrations/plugin-packs/procedures/network-freebox-restapi.md
=> [CTOR-983] - Refresh network-freebox-restapi doc page

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-azure-management-monitor.md, pp/integrations/plugin-packs/procedures/cloud-azure-management-monitor.md
Refresh cloud-azure-management-monitor
=> CTOR- 938 : Refresh cloud-azure-management-monitor

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-lenovo-flexsystem-snmp.md, pp/integrations/plugin-packs/procedures/network-lenovo-flexsystem-snmp.md
=> [CTOR-999] Refresh network-lenovo-flexsystem-snmp doc page

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-microsens-g6-snmp.md, pp/integrations/plugin-packs/procedures/network-microsens-g6-snmp.md
=> [CTOR-1003] Refresh network-microsens-g6-snmp doc page

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-firewalls-juniper-sa-snmp.md, pp/integrations/plugin-packs/procedures/network-firewalls-juniper-sa-snmp.md
=> [CTOR-995] Refresh network-firewalls-juniper-sa-snmp doc page

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-lenovo-rackswitch-snmp.md, pp/integrations/plugin-packs/procedures/network-lenovo-rackswitch-snmp.md
=> [CTOR-1000] Refresh network-lenovo-rackswitch-snmp doc page

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-hp-moonshot-snmp.md, pp/integrations/plugin-packs/procedures/network-hp-moonshot-snmp.md
=> [CTOR-991] Refresh network-hp-moonshot-snmp doc page

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-meru-snmp.md, pp/integrations/plugin-packs/procedures/network-meru-snmp.md
=> [CTOR-1002] Refresh network-meru-snmp doc page

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-infoblox-snmp.md, pp/integrations/plugin-packs/procedures/network-infoblox-snmp.md
=> [CTOR-993] Refresh network-infoblox-snmp doc page

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-ibm-bladecenter-snmp.md, pp/integrations/plugin-packs/procedures/network-ibm-bladecenter-snmp.md
=> [CTOR-992] Refresh network-ibm-bladecenter-snmp doc page

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-aws-apigateway.md, pp/integrations/plugin-packs/procedures/cloud-aws-apigateway.md
=> CTOR-1049 : Refresh cloud-aws-apigateway

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-aws-cloudfront.md, pp/integrations/plugin-packs/procedures/cloud-aws-cloudfront.md
=> CTOR-1051 : Refresh cloud-aws-cloudfront

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-aws-backup.md, pp/integrations/plugin-packs/procedures/cloud-aws-backup.md
=> CTOR-1050 : Refresh cloud-aws-backup

i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/lifecycle.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/releases/lifecycle.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/releases/lifecycle.md, versioned_docs/version-23.04/releases/lifecycle.md, versioned_docs/version-23.10/releases/lifecycle.md, versioned_docs/version-24.04/releases/lifecycle.md
=> Fix supported version

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/releases/release-notes.md, pp/integrations/plugin-packs/releases/release-notes.md
=> CTOR-967 : November release note

i18n/fr/docusaurus-plugin-content-docs/version-24.10/releases/centreon-os.mdx, versioned_docs/version-24.10/releases/centreon-os.mdx
=> doc(release) Release notes for collect 24.10.1

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-emc-datadomain-snmp.md, i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-routers-atrica-snmp.md, i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/releases/release-notes.md, pp/integrations/plugin-packs/procedures/hardware-storage-emc-datadomain-snmp.md, pp/integrations/plugin-packs/procedures/network-routers-atrica-snmp.md, pp/integrations/plugin-packs/releases/release-notes.md
=> Ctor 967 connectors 24 11 release

i18n/fr/docusaurus-plugin-content-docs/version-24.10/releases/centreon-os.mdx, versioned_docs/version-24.10/releases/centreon-os.mdx
=> doc(release) Release notes for web 24.10.1

i18n/fr/docusaurus-plugin-content-docs/version-24.10/releases/centreon-os.mdx, versioned_docs/version-24.10/releases/centreon-os.mdx
=> Update date for web 24.10.1 hotfix

i18n/fr/docusaurus-plugin-content-docs/version-24.04/releases/centreon-os.mdx
Fix "Centreon Collect" duplicate section name.
=> Fix duplicate Centreon Collect section name

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-cyberoam-snmp.md, pp/integrations/plugin-packs/procedures/network-cyberoam-snmp.md
=> Refresh network-cyberoam-snmp

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-digi-sarian-snmp.md, pp/integrations/plugin-packs/procedures/network-digi-sarian-snmp.md
Refresh network-digi-sarian-snmp
=> Refresh network-digi-sarian-snmp

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-aws-cloudwatch.md, pp/integrations/plugin-packs/procedures/cloud-aws-cloudwatch.md
=> CTOR-1052 : Refresh cloud-aws-cloudwatch

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-aws-cloudwatchlogs.md, pp/integrations/plugin-packs/procedures/cloud-aws-cloudwatchlogs.md
Refresh cloud-aws-cloudwatchlogs
=> CTOR-1053 : Refresh cloud-aws-cloudwatchlogs

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-aws-directconnect.md, pp/integrations/plugin-packs/procedures/cloud-aws-directconnect.md
Refresh cloud-aws-directconnect
=> CTOR-1054 : Refresh cloud-aws-directconnect

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-aws-ebs.md, pp/integrations/plugin-packs/procedures/cloud-aws-ebs.md
=> CTOR-1055 : Refresh cloud-aws-ebs

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-aws-efs.md, pp/integrations/plugin-packs/procedures/cloud-aws-efs.md
=> CTOR-1056 : Refresh cloud-aws-efs

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-monitoring-centreon-central.md, pp/integrations/plugin-packs/procedures/applications-monitoring-centreon-central.md
Rework the SSH key exchange section in applications-monitoring-centreon-central
=> CTOR-1020 : Rework the SSH key exchange section in applications-monitoring-centreon-central

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-veeam-nsclient-05-restapi.md, pp/integrations/plugin-packs/procedures/applications-veeam-nsclient-05-restapi.md
Refresh applications-veeam-nsclient-05-restapi
=> CTOR-1023 : Refresh applications-veeam-nsclient-05-restapi

i18n/fr/docusaurus-plugin-content-docs/version-23.04/integrations/event-management/sc-opsgenie.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/integrations/event-management/sc-opsgenie.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/integrations/event-management/sc-opsgenie.md, i18n/fr/docusaurus-plugin-content-docs/version-24.10/integrations/event-management/sc-opsgenie.md, i18n/fr/docusaurus-plugin-content-docs/version-25.10/integrations/event-management/sc-opsgenie.md
=> Fix typo in sc-opsgenie.md

i18n/fr/docusaurus-plugin-content-docs/version-24.10/migrate/migrate-from-debian-to-debian.md, versioned_docs/version-24.10/migrate/migrate-from-debian-to-debian.md, versioned_sidebars/version-24.10-sidebars.json
=> Migrate from Debian 11 to Debian 12 on another server

i18n/fr/docusaurus-plugin-content-docs/version-22.10/alerts-notifications/notif-advanced.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/alerts-notifications/notif-advanced.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/alerts-notifications/notif-advanced.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/alerts-notifications/notif-advanced.md, i18n/fr/docusaurus-plugin-content-docs/version-24.10/alerts-notifications/notif-advanced.md, i18n/fr/docusaurus-plugin-content-docs/version-25.10/alerts-notifications/notif-advanced.md, versioned_docs/version-22.10/alerts-notifications/notif-advanced.md, versioned_docs/version-23.04/alerts-notifications/notif-advanced.md, versioned_docs/version-23.10/alerts-notifications/notif-advanced.md, versioned_docs/version-24.04/alerts-notifications/notif-advanced.md, versioned_docs/version-24.10/alerts-notifications/notif-advanced.md, versioned_docs/version-25.10/alerts-notifications/notif-advanced.md
=> removed ChatOps section as the project no longer exists

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-juniper-trapeze-snmp.md, pp/integrations/plugin-packs/procedures/network-juniper-trapeze-snmp.md
=> [CTOR-997] Refresh network-juniper-trapeze-snmp doc page

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-aws-elasticache.md, pp/integrations/plugin-packs/procedures/cloud-aws-elasticache.md
=> CTOR-1057 : Refresh cloud-aws-elasticache

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-h3c-snmp.md, pp/integrations/plugin-packs/procedures/network-h3c-snmp.md
=> CTOR-989 : Refresh network-h3c-snmp

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-mitel-3300icp-snmp.md, pp/integrations/plugin-packs/procedures/network-mitel-3300icp-snmp.md
=> [CTOR-1024] Refresh network-mitel-3300icp-snmp doc page

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-moxa-switch-snmp.md, pp/integrations/plugin-packs/procedures/network-moxa-switch-snmp.md
=> [CTOR-1025] Refresh network-moxa-switch-snmp doc page

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-netgear-sseries-snmp.md, pp/integrations/plugin-packs/procedures/network-netgear-sseries-snmp.md
=> [CTOR-1027] Refresh network-netgear-sseries-snmp doc page

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-nokia-timos-snmp.md, pp/integrations/plugin-packs/procedures/network-nokia-timos-snmp.md
=> [CTOR-1029] Refresh network-nokia-timos-snmp doc page

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-aws-kinesis.md, pp/integrations/plugin-packs/procedures/cloud-aws-kinesis.md
=> CTOR-1058 Refresh cloud-aws-kinesis

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-nortel-standard-snmp.md, pp/integrations/plugin-packs/procedures/network-nortel-standard-snmp.md
=> [CTOR-1031] Refresh network-nortel-standard-snmp doc page

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-aws-s3.md, pp/integrations/plugin-packs/procedures/cloud-aws-s3.md
=> CTOR-1059 : Refresh cloud-aws-s3

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-netgear-mseries-snmp.md, pp/integrations/plugin-packs/procedures/network-netgear-mseries-snmp.md
=> [CTOR-1026] Refresh network-netgear-mseries-snmp doc page

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-oracle-infiniband-snmp.md, pp/integrations/plugin-packs/procedures/network-oracle-infiniband-snmp.md
=> [CTOR-1087] Refresh network-oracle-infiniband-snmp doc page

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-radware-alteon-snmp.md, pp/integrations/plugin-packs/procedures/network-radware-alteon-snmp.md
=> [CTOR-1094] Refresh network-radware-alteon-snmp doc page

cloud/installation/deploy-poller.md, i18n/fr/docusaurus-plugin-content-docs-cloud/current/installation/deploy-poller.md
=> updating order of steps in the deploy poller step

i18n/fr/docusaurus-plugin-content-docs/version-22.10/connect/loginpwd.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/connect/loginpwd.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/connect/loginpwd.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/connect/loginpwd.md, i18n/fr/docusaurus-plugin-content-docs/version-24.10/connect/loginpwd.md, i18n/fr/docusaurus-plugin-content-docs/version-25.10/connect/loginpwd.md, versioned_docs/version-22.10/connect/loginpwd.md, versioned_docs/version-23.04/connect/loginpwd.md, versioned_docs/version-23.10/connect/loginpwd.md, versioned_docs/version-24.04/connect/loginpwd.md, versioned_docs/version-24.10/connect/loginpwd.md, versioned_docs/version-25.10/connect/loginpwd.md
=> specified the password expiration feature cannot be disabled

i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md, versioned_docs/version-22.10/releases/centreon-os.md
=> doc(release) Release notes web 22.10.26 open tickets 22.10.4 dsm 22.10.2

i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx, versioned_docs/version-23.04/releases/centreon-os.mdx
=> doc(release) Release notes web 23.04.23 open tickets 23.04.4 dsm 23.04.3

i18n/fr/docusaurus-plugin-content-docs/version-24.10/upgrade/upgrade-from-24-04.md, versioned_docs/version-24.10/upgrade/upgrade-from-24-04.md
=> remove unnecessary instruction to upgrade MariaDB

i18n/fr/docusaurus-plugin-content-docs/version-22.10/administration/secure-platform.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/administration/secure-platform.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/administration/secure-platform.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/administration/secure-platform.md, i18n/fr/docusaurus-plugin-content-docs/version-24.10/administration/secure-platform.md, i18n/fr/docusaurus-plugin-content-docs/version-25.10/administration/secure-platform.md, versioned_docs/version-22.10/administration/secure-platform.md, versioned_docs/version-23.04/administration/secure-platform.md, versioned_docs/version-23.10/administration/secure-platform.md, versioned_docs/version-24.04/administration/secure-platform.md, versioned_docs/version-24.10/administration/secure-platform.md, versioned_docs/version-25.10/administration/secure-platform.md
=> activating HTTPS mode on web server example is outdated

i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md, versioned_docs/version-22.10/releases/centreon-os.md
=> doc(release) Release notes for collect 22.10.12

i18n/fr/docusaurus-plugin-content-docs/version-24.04/releases/centreon-os.mdx, versioned_docs/version-24.04/releases/centreon-os.mdx
=> doc(release) Release notes collect 24.04.7

i18n/fr/docusaurus-plugin-content-docs/version-23.10/releases/centreon-os.mdx, versioned_docs/version-23.10/releases/centreon-os.mdx
=> doc(release) Release notes collect 23.10.12

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-aws-elb.md, pp/integrations/plugin-packs/procedures/cloud-aws-elb.md
=> CTOR-1065 : Refresh cloud-aws-elb

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-firewalls-paloalto-standard-ssh.md, pp/integrations/plugin-packs/procedures/network-firewalls-paloalto-standard-ssh.md
=> [CTOR-1088] Refresh network-firewalls-paloalto-standard-ssh doc page

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-aws-lambda.md, pp/integrations/plugin-packs/procedures/cloud-aws-lambda.md
=> CTOR-1067 : Refresh cloud-aws-lambda

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-aws-transitgateway.md, pp/integrations/plugin-packs/procedures/cloud-aws-transitgateway.md
Refresh cloud-aws-transitgateway
=> CTOR-1068 : Refresh cloud-aws-transitgateway

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-ruckus-scg-snmp.md, pp/integrations/plugin-packs/procedures/network-ruckus-scg-snmp.md
=> [CTOR-1138] Refresh network-ruckus-scg-snmp doc page

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-stormshield-ssh.md, pp/integrations/plugin-packs/procedures/network-stormshield-ssh.md
Refresh network-stormshield-ssh
=> CTOR-1143 : Refresh network-stormshield-ssh

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-patton-smartnode-snmp.md, pp/integrations/plugin-packs/procedures/network-patton-smartnode-snmp.md
Refresh network-patton-smartnode-snmp
=> CTOR-1089 : Refresh network-patton-smartnode-snmp

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-raisecom-snmp.md, pp/integrations/plugin-packs/procedures/network-raisecom-snmp.md
=> CTOR-1134 : Refresh network-raisecom-snmp

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-sophos-es-snmp.md, pp/integrations/plugin-packs/procedures/network-sophos-es-snmp.md
=> [CTOR-1142]-Refresh network-sophos-es-snmp doc page

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-ruckus-smartzone-snmp.md, pp/integrations/plugin-packs/procedures/network-ruckus-smartzone-snmp.md
=> [CTOR-1139] Refresh network-ruckus-smartzone-snmp doc page

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/getting-started/how-to-guides/troubleshooting-plugins.md, pp/integrations/plugin-packs/getting-started/how-to-guides/troubleshooting-plugins.md
How-to-guides - Troubleshooting-plugins : Add a new section for Amazon plugins
=> CTOR-1111 : How-to-guides - Troubleshooting-plugins : Add a new section for Amazon plugins

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/operatingsystems-aix-ssh.md, pp/integrations/plugin-packs/procedures/operatingsystems-aix-ssh.md
Update the documentation and add new macros in
=> CTOR-555 : Pack(operatingsystems-aix-ssh-storage) : Add usage-prct thresholds

i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx, versioned_docs/version-23.04/releases/centreon-os.mdx
=> doc(release) Release notes collect 23.04.16

i18n/fr/docusaurus-plugin-content-docs/version-24.10/releases/centreon-os.mdx, versioned_docs/version-24.10/releases/centreon-os.mdx
=> doc(release) Release notes Collect 24.10.2

i18n/fr/docusaurus-plugin-content-docs/version-24.10/releases/centreon-os.mdx, versioned_docs/version-24.10/releases/centreon-os.mdx
=> doc(release) Release notes for gorgone 24.10.1

i18n/fr/docusaurus-plugin-content-docs/version-24.10/releases/centreon-os.mdx, versioned_docs/version-24.10/releases/centreon-os.mdx
=> doc(release) Release notes web 24.10.2

i18n/fr/docusaurus-plugin-content-docs/version-23.10/releases/centreon-commercial-extensions.mdx, versioned_docs/version-23.10/releases/centreon-commercial-extensions.mdx
=> doc(release) Release notes for modules 23.10

i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-commercial-extensions.mdx, versioned_docs/version-23.04/releases/centreon-commercial-extensions.mdx
=> doc(release) Release notes modules 23.04

i18n/fr/docusaurus-plugin-content-docs/version-23.10/releases/centreon-commercial-extensions.mdx
=> doc(release) correct map in i18n 23.10

i18n/fr/docusaurus-plugin-content-docs/version-24.04/releases/centreon-commercial-extensions.mdx, versioned_docs/version-24.04/releases/centreon-commercial-extensions.mdx
autodisco 24.04.1
BAM 24.04.4
it editions 24.04.2
LM 24.04.2
mbi 24.04.4 
map 24.04.7
ppm 24.04.2
=> doc(release) Release notes modules 24.04

i18n/fr/docusaurus-plugin-content-docs/version-24.04/releases/centreon-commercial-extensions.mdx, versioned_docs/version-24.04/releases/centreon-commercial-extensions.mdx
=> doc(release) fixed date in modules 24.04 release notes

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-ruckus-icx-snmp.md, pp/integrations/plugin-packs/procedures/network-ruckus-icx-snmp.md
Refresh network-ruckus-icx-snmp
=> CTOR-1137 : Refresh network-ruckus-icx-snmp

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-commvault-commserve-restapi.md, pp/integrations/plugin-packs/procedures/applications-commvault-commserve-restapi.md
=> CTOR-851 : Plugin(apps::backup::commvault::commserve::restapi) - Mode(storagepools) : If statement added when $total == 0

i18n/fr/docusaurus-plugin-content-docs/version-24.10/releases/centreon-commercial-extensions.mdx, versioned_docs/version-24.10/releases/centreon-commercial-extensions.mdx
=> doc(release) Release notes Modules 24.10

i18n/fr/docusaurus-plugin-content-docs/version-24.10/releases/centreon-os.mdx, versioned_docs/version-24.10/releases/centreon-os.mdx
=> doc(release): Release notes open tickets 24.10.2

i18n/fr/docusaurus-plugin-content-docs/version-24.04/releases/centreon-os.mdx, versioned_docs/version-24.04/releases/centreon-os.mdx
=> doc(release) Release notes open tickets 24.04.3

i18n/fr/docusaurus-plugin-content-docs/version-23.10/releases/centreon-os.mdx, versioned_docs/version-23.10/releases/centreon-os.mdx
=> doc(release) Release notes open tickets 23.10.2

i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx, versioned_docs/version-23.04/releases/centreon-os.mdx
=> doc(release) Release notes for open tickets 23.04.5

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/hardware-storage-dell-compellent-api.md, pp/integrations/plugin-packs/procedures/hardware-storage-dell-compellent-api.md
=> CTOR-1221 : Doc(hardware-storage-dell-compellent-api) : Dead link

i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-os.md, versioned_docs/version-22.10/releases/centreon-os.md
=> doc(release) Release notes open tickets 22.10.5

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/applications-jmeter.md, pp/integrations/plugin-packs/procedures/applications-jmeter.md, pp/sidebarsPp.js
Documentation for a new monitoring connector: JMeter
=> CTOR-811 - New JMeter monitoring connector

i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx, i18n/fr/docusaurus-plugin-content-docs/version-23.10/releases/centreon-os.mdx, i18n/fr/docusaurus-plugin-content-docs/version-24.04/releases/centreon-os.mdx, i18n/fr/docusaurus-plugin-content-docs/version-24.10/releases/centreon-os.mdx, versioned_docs/version-23.04/releases/centreon-os.mdx, versioned_docs/version-23.10/releases/centreon-os.mdx, versioned_docs/version-24.04/releases/centreon-os.mdx, versioned_docs/version-24.10/releases/centreon-os.mdx
=> Fix rn dates

i18n/fr/docusaurus-plugin-content-docs/version-24.10/releases/centreon-commercial-extensions.mdx, versioned_docs/version-24.10/releases/centreon-commercial-extensions.mdx
=> doc(release) Release notes for itee 24.10.2

i18n/fr/docusaurus-plugin-content-docs/version-23.04/graph-views/introduction-map.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/graph-views/introduction-map.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/graph-views/introduction-map.md, i18n/fr/docusaurus-plugin-content-docs/version-24.10/graph-views/introduction-map.md, i18n/fr/docusaurus-plugin-content-docs/version-25.10/graph-views/introduction-map.md, versioned_docs/version-23.04/graph-views/introduction-map.md, versioned_docs/version-23.10/graph-views/introduction-map.md, versioned_docs/version-24.04/graph-views/introduction-map.md, versioned_docs/version-24.10/graph-views/introduction-map.md, versioned_docs/version-25.10/graph-views/introduction-map.md
=> Add standard license warning to MAP introduction

cloud/alerts-notifications/dashboards.md, i18n/fr/docusaurus-plugin-content-docs-cloud/current/alerts-notifications/dashboards.md
=> Remove web page widget

i18n/fr/docusaurus-plugin-content-docs/version-24.10/upgrade/upgrade-from-22-10.md, i18n/fr/docusaurus-plugin-content-docs/version-24.10/upgrade/upgrade-from-23-04.md, i18n/fr/docusaurus-plugin-content-docs/version-24.10/upgrade/upgrade-from-23-10.md, i18n/fr/docusaurus-plugin-content-docs/version-24.10/upgrade/upgrade-from-24-04.md, i18n/fr/docusaurus-plugin-content-docs/version-25.10/upgrade/upgrade-from-22-10.md, i18n/fr/docusaurus-plugin-content-docs/version-25.10/upgrade/upgrade-from-23-04.md, i18n/fr/docusaurus-plugin-content-docs/version-25.10/upgrade/upgrade-from-23-10.md, i18n/fr/docusaurus-plugin-content-docs/version-25.10/upgrade/upgrade-from-24-04.md, versioned_docs/version-24.10/upgrade/upgrade-from-22-10.md, versioned_docs/version-24.10/upgrade/upgrade-from-23-04.md, versioned_docs/version-24.10/upgrade/upgrade-from-23-10.md, versioned_docs/version-24.10/upgrade/upgrade-from-24-04.md, versioned_docs/version-25.10/upgrade/upgrade-from-22-10.md, versioned_docs/version-25.10/upgrade/upgrade-from-23-04.md, versioned_docs/version-25.10/upgrade/upgrade-from-23-10.md, versioned_docs/version-25.10/upgrade/upgrade-from-24-04.md
=> Remove unnecessary commands in Debian upgrade procedure

i18n/fr/docusaurus-plugin-content-docs/version-22.10/update/update-centreon-platform.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/update/update-centreon-platform.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/update/update-centreon-platform.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/update/update-centreon-platform.md, i18n/fr/docusaurus-plugin-content-docs/version-24.10/update/update-centreon-platform.md, i18n/fr/docusaurus-plugin-content-docs/version-25.10/update/update-centreon-platform.md, versioned_docs/version-22.10/update/update-centreon-platform.md, versioned_docs/version-23.04/update/update-centreon-platform.md, versioned_docs/version-23.10/update/update-centreon-platform.md, versioned_docs/version-24.04/update/update-centreon-platform.md, versioned_docs/version-24.10/update/update-centreon-platform.md, versioned_docs/version-25.10/update/update-centreon-platform.md
=> Fix Debian update procedure

.github/workflows/documentation.yml
fix(ci): update cache key to deploy staging/next doc
=> fix(ci): update cache key to deploy staging/next doc

i18n/fr/docusaurus-plugin-content-docs/version-22.10/releases/centreon-commercial-extensions.md, versioned_docs/version-22.10/releases/centreon-commercial-extensions.md
=> doc(release) Release notes modules 22.10

cloud/resources/known-issues.md, i18n/fr/docusaurus-plugin-content-docs-cloud/current/resources/known-issues.md
=> Known issues Cloud 24.11

cloud/releases/cloud-release-notes.md, i18n/fr/docusaurus-plugin-content-docs-cloud/current/releases/cloud-release-notes.md
=> Doc(release) Release notes cloud 24.11

versioned_docs/version-23.10/administration/knowledge-base.md, versioned_docs/version-24.04/administration/knowledge-base.md, versioned_docs/version-24.10/administration/knowledge-base.md, versioned_docs/version-25.10/administration/knowledge-base.md
=> Fix text split into blocks

i18n/fr/docusaurus-plugin-content-docs/version-22.10/integrations/data-analytics/sc-splunk-events.md, i18n/fr/docusaurus-plugin-content-docs/version-23.04/integrations/data-analytics/sc-splunk-events.md, i18n/fr/docusaurus-plugin-content-docs/version-23.10/integrations/data-analytics/sc-splunk-events.md, i18n/fr/docusaurus-plugin-content-docs/version-24.04/integrations/data-analytics/sc-splunk-events.md, i18n/fr/docusaurus-plugin-content-docs/version-24.10/integrations/data-analytics/sc-splunk-events.md, i18n/fr/docusaurus-plugin-content-docs/version-25.10/integrations/data-analytics/sc-splunk-events.md
Fix custom events format in FR
=> CTOR-1187 : Doc(sc-splunk-events) : Fix custom events format in FR

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-ubiquiti-edge-snmp.md, pp/integrations/plugin-packs/procedures/network-ubiquiti-edge-snmp.md
Refresh network-ubiquiti-edge-snmp
=> CTOR-1146 : Refresh network-ubiquiti-edge-snmp

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-vectra-restapi.md, pp/integrations/plugin-packs/procedures/network-vectra-restapi.md
Refresh network-vectra-restapi
=> CTOR-1147 : Refresh network-vectra-restapi

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/network-viptela-snmp.md, pp/integrations/plugin-packs/procedures/network-viptela-snmp.md
=> CTOR-1150 : Refresh network-viptela-snmp

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-cloudfoundry-api.md, pp/integrations/plugin-packs/procedures/cloud-cloudfoundry-api.md
Refresh cloud-cloudfoundry-api
=> CTOR-1153 : Refresh cloud-cloudfoundry-api

i18n/fr/docusaurus-plugin-content-docs-pp/current/integrations/plugin-packs/procedures/cloud-ibm-softlayer-api.md, pp/integrations/plugin-packs/procedures/cloud-ibm-softlayer-api.md
Refresh cloud-ibm-softlayer-api
=> CTOR-1154 : Refresh cloud-ibm-softlayer-api

i18n/fr/docusaurus-plugin-content-docs/version-23.10/releases/centreon-os.mdx, versioned_docs/version-23.10/releases/centreon-os.mdx
=> doc(release) Release notes collect 23.10.13

i18n/fr/docusaurus-plugin-content-docs/version-23.04/releases/centreon-os.mdx, versioned_docs/version-23.04/releases/centreon-os.mdx
=> doc(release) Release notes collect 23.04.17

i18n/fr/docusaurus-plugin-content-docs/version-24.10/releases/centreon-os.mdx
=> doc(release) correction titre centreon web
